### ISSUE TITLE
Response normalization

### ISSUE THREAD

**Issue by run2** [Lasagne/Lasagne#121]
Hi
Any idea of how we can do response normalization in Lasagne ? (before pooling) as mentioned in "ImageNet Classification with Deep Convolutional Neural Networks by Alex Krizhevsky, Ilya Sutskever, Geoffrey E. Hinton) ?
Thanks

**Comment by benanne** [comment]
You could implement it yourself from the formulas from the paper, or add a wrapper for the cuda-convnet implementation ( http://deeplearning.net/software/pylearn2/library/alex.html#module-pylearn2.sandbox.cuda_convnet.response_norm ).

For future reference, please post support questions on the mailing list from now on: https://groups.google.com/forum/#!forum/lasagne-users

Feature requests should still be on GitHub. This one is a bit of both I guess :)

**Comment by run2** [comment]
Ok - thanks. Please close this if you do not intend to add it to Lasagne.

**Comment by benanne** [comment]
I personally have no use for this so I probably won't be spending time implementing it. I did implement this in my Kaggle Galaxy Challenge code base though, and since Lasagne is largely based on this, it should be easy to port it: https://github.com/benanne/kaggle-galaxies/blob/master/cc_layers.py#L187

If you end up porting this a pull request would be awesome!

**Comment by run2** [comment]
Sure - I will work on this.

**Comment by dimatura** [comment]
Hi. I actually already have a working `lasagne` layer for this, but similarly to the Kaggle code it is a thin wrapper around the `pylearn2` functionality. Is there any part of `lasagne` currently depending on `pylearn2`? On the other hand it's pretty simple functionality and it would be fairly easy to port.

**Comment by benanne** [comment]
Yes, the entire `lasagne.layers.cuda_convnet` module is basically a bunch of wrappers of the pylearn2 ops. So it would definitely fit there.

**Comment by dimatura** [comment]
Oh true, somehow forgot about that. I'm not using the `cuda_convnet` code though, but the pure theano one for `bc01` data. `pylearn2` has expressions for both cases, which are pretty easily swappable.

**Comment by dimatura** [comment]
The non cuda-convnet version is actually pretty simple. (At some point I inspected it because I thought it had a bug... turns out it was me ;)). So it would be easy to port to `pylearn2`. Would there be any copyright issues?

**Comment by f0k** [comment]
> Would there be any copyright issues?

Hmm, pylearn2 has [this three-clause BSD license](https://github.com/lisa-lab/pylearn2/blob/master/LICENSE.txt). Lasagne has [this MIT license](https://github.com/benanne/Lasagne/blob/master/LICENSE). IANAL, but I guess if we include pylearn2's license with anything we copy over (and state that the copied part is covered by pylearn2's license rather than Lasagne's), we should be fine.

**Comment by dimatura** [comment]
Got it. It's on my queue -- a bit overloaded right now but shouldn't be too much work.

**Comment by run2** [comment]
Hi dimatura
Thanks a lot for that. I never found time to get around to this.
I need one help - can any one create a wiki somewhere on how to create a pull request and go about submitting such changes in future.

**Comment by benanne** [comment]
I missed this comment before! GitHub has extensive documentation on how to create a PR: https://help.github.com/articles/using-pull-requests/

I'll close this issue since @dimatura's work was merged a while ago.

**Comment by f0k** [comment]
> I need one help - can any one create a wiki somewhere on how to create a pull request and go about submitting such changes in future.

In addition to Sander's documentation hint, I wrote a short guide for another project on what to do before you can send a PR (namely, get your changes into a branch in your fork of the project on github): https://github.com/cudamat/cudamat/blob/master/CONTRIBUTE.md
