### ISSUE TITLE
Add support for striding and padding to pooling layers

### ISSUE THREAD

**Issue by benanne** [Lasagne/Lasagne#186]
Theano's `max_pool_2d` now supports striding and padding: http://deeplearning.net/software/theano/library/tensor/signal/downsample.html

We should modify `lasagne.layers.pool.MaxPool*DLayer` to support these new features. I might work on this myself later this week, just creating the issue as a reminder. But if anyone else wants to do it, go ahead. Just post a comment here so we don't do any double work.

**Comment by ebenolson** [comment]
I can work on this today if you haven't done it already.

**Comment by benanne** [comment]
Go for it :)
