### ISSUE TITLE
Rename MultipleInputsLayer

### ISSUE THREAD

**Issue by f0k** [Lasagne/Lasagne#200]
It has been noted a [few](https://github.com/benanne/Lasagne/issues/104#issuecomment-73141174) [times](https://groups.google.com/d/topic/lasagne-users/P_OakWeHwj0/discussion) that `MultipleInputsLayer` is easily mistaken to be related to `InputLayer`.

One possibility would be renaming it to `MultipleIncomingLayer`, since that reflects the keyword used to link layers to their incoming layers. This is not a whole lot better, though. `MultiLayer` could work, but might be a bit unspecific.

Another possibility is to focus on the aspect of taking multiple inputs and merging them in some way, as the class docstring acknowledges:
```python
class MultipleInputsLayer(Layer):
    """
    This class represents a layer that aggregates input from multiple layers.
    It should be subclassed when implementing new types of layers that
    obtain their input from multiple layers.
    """
```
After all, it allows multiple incoming layers, but always produces a single output, so it must do some kind of aggregation. Some ideas on this theme: `MergeLayer`, `MergingLayer`, `AggregateLayer`, `AggregationLayer`, `JoinLayer`, `JoiningLayer`, `CombinationLayer`, ...

This should be discussed and/or addressed before the first release.

**Comment by benanne** [comment]
Agreed, added it to the milestone.

I'm wondering if there are any use cases where a layer would have multiple input layers, but would not really 'aggregate' them. I'm having a hard time thinking of any concrete ones. Maybe something that does multiplication between two inputs or so? Or a layer that computes distances beween feature representations, to be used in a siamese architecture?

I would be okay with `MultiLayer` at any rate. It's not the most descriptive of names, but it's concise and it makes enough sense.

**Comment by f0k** [comment]
> I'm wondering if there are any use cases where a layer would have multiple input layers, but would not really 'aggregate' them. I'm having a hard time thinking of any concrete ones. Maybe something that does multiplication between two inputs or so?

Aggregation may not be a good fit for that, but I'd say that would still count as merging. Whatever operation it does, it is "take multiple inputs -> produce single output" -- even for the `ConcatLayer`, which preserves all inputs in its output. Instead of thinking of the data or the operation, one could also think of the graph: it's a node with indegree > 1 (usually), but outdegree 1. There's no special name for that, as far as I know, but it's joining two paths in the graph.

> I would be okay with `MultiLayer` at any rate.

I'd be okay with that, too. My only concern is that it sounds as if it was composed of multiple layers or has multiple outputs. My favorite is `MergeLayer`.

**Comment by benanne** [comment]
You could imagine a network where at some point per-feature distances are computed between pairs of examples and more layers are stacked on top of that. In that case incorporating the distance computation into the cost function would not be an option. Although to be honest I don't know if this kind of architecture would be useful at all in practice.

What about `JoinLayer` instead of `JointLayer`, using a verb instead of an adjective seems more consistent with some of the other layer names :)

I'm fine with `MergeLayer` too though. Maybe `MultiLayer` is a bit too vague as you pointed out.

**Comment by ebenolson** [comment]
I'm a fan of `MergeLayer`,  `JoinLayer`, or `CombineLayer`. 

For me, `MultiLayer` brings to mind something formed by a stack of layers, not a merging operation.

**Comment by benanne** [comment]
Let's try to wrap this up within 24 hours to avoid another lengthy discussion about names. Names of things are important but I feel we've been overemphasizing this aspect a little ;)

I think `MergeLayer` has the most support, so let's go with that unless anyone comes up with a good reason not to.

**Comment by f0k** [comment]
> Names of things are important but I feel we've been overemphasizing this aspect a little ;)

I think base class names are pretty important, but we've found a few names that would probably do equally well. I'm fine with any of `MergeLayer`, `JoinLayer` and `CombineLayer`.

I just noticed that we have `lasagne/layers/merge.py` for `ConcatLayer` and `ElemwiseSumLayer`, so we already figured out before that it was a good abstraction for those.
If we want to plan for a possible `lasagne/layers/compare.py` that does differences or something, we should go for `JoinLayer`. Otherwise we should go for `MergeLayer` to keep it consistent with `merge.py`.

**Comment by f0k** [comment]
Has been addressed in #245.

**Comment by craffel** [comment]
We may allow layers to produce multiple outputs #337, so this isn't necessarily true anymore:

> Whatever operation it does, it is "take multiple inputs -> produce single output"

And, awkwardly, the recurrent layers are now going to be subclasses of `MergeLayer` https://github.com/Lasagne/Lasagne/issues/337#issuecomment-124475829 .

Sorry to start a naming convention discussion; I don't think it's too big of a deal, just a big awkward.  Sadly, I think `MultipleInputsLayer` is the name that makes the most sense, but it's problematic for other reasons.  I think `MultiLayer` is ok, but maybe too vague.

I'm also wondering why we can't just have the `Layer` class gracefully accept any number of inputs, and get rid of the distinction altogether.  One simple way to do this would be to always use lists for `self.input_shapes` and `self.input_layers`; when only a single `incomings` is passed, we'd create lists for `self.input_shapes` and `self.input_layers`, and then when they are singletons, just retrieve the first value whenever it's asked for.

**Comment by benanne** [comment]
I feel like that would severely degrade the readability of the code though. And the most common use cases actually do not require it. It goes against 'Pragmatism' and 'Don't get in the way' a bit, imo.

Personally I don't understand the issue with the name `MergeLayer`. It merges inputs from multiple layers. We could technically call it `MergeInputsFromMultipleLayersLayer` but there is something to be said for conciseness :)

Would `MultipleInputsLayer` not be even more confusing? It still only accepts inputs from *multiple layers*, which is something different than accepting multiple inputs.

**Comment by craffel** [comment]
> I feel like that would severely degrade the readability of the code though. And the most common use cases actually do not require it. It goes against 'Pragmatism' and 'Don't get in the way' a bit, imo.

Well, I think we could do it only adding about 5 or 10 lines of code to the `Layer` class.

> Personally I don't understand the issue with the name MergeLayer.

The `RecurrentLayer` isn't merging its input with the mask; it's using the mask to decide which entires in its input to use.  Purely semantically, "merge" makes it sound like it is consuming both inputs.   The `InputLayer` which supplies the mask would be re-used multiple times throughout the network's graph.  See @f0k's usage: https://github.com/Lasagne/Lasagne/issues/337#issuecomment-124475829

> Would MultipleInputsLayer not be even more confusing? It still only accepts inputs from multiple layers, which is something different than accepting multiple inputs.

How is that different?

All this being said, if it's something you don't like, I don't think it's important enough for me to try to convince you to change your mind.  It's just awkward semantically for recurrent layers to be subclasses of a `MergeLayer` when they don't merge anything.

**Comment by f0k** [comment]
> Well, I think we could do it only adding about 5 or 10 lines of code to the `Layer` class.

It would affect all subclasses though, wouldn't it? They'd all need to use `self.input_layers[0]` instead of `self.input_layer` and `self.input_shapes[0]` instead of `self.input_shape` then.

> The `RecurrentLayer` isn't merging its input with the mask; it's using the mask to decide which entires in its input to use.

Agreed, "merging" is not really fitting here.

> How is that different?

Accepting multiple inputs could mean accepting multiple inputs from a single layer, while here we're specifically dealing with layers that have multiple incoming layers.

> All this being said, if it's something you don't like, I don't think it's important enough for me to try to convince you to change your mind.

I'd be fine with renaming if we find a better name than what we currently have. I don't think any name suggested in this thread is better than `MergeLayer`, though, it would have to be something new.

**Comment by craffel** [comment]
> It would affect all subclasses though, wouldn't it? They'd all need to use self.input_layers[0] instead of self.input_layer and self.input_shapes[0] instead of self.input_shape then. Given that only few layers need that functionality, it would degrade readability too much.

The idea was that `Layer` would check when `input_layers` and `input_shapes` were singletons, and retrieve the zeroth element in those cases.

> /edit: We could make self.input_layer a property returning self.input_layers[0], and similarly for self.input_shape, but that would make the first incoming layer somewhat special (even for ConcatLayer and the like). Hmm.

Yes, I think we could avoid that.

> /edit /edit: There's still get_output_for() and get_output_shape_for(). Either they would have inputs and input_shapes (requiring changes to all existing layer subclasses), or they would have lists only when there actually are multiple incoming layers (requiring changes to all existing MergeLayer subclasses, because they couldn't rely on being provided with lists any longer).

I was envisioning existing `MergeLayer` subclasses having to be modified.

> Accepting multiple inputs could mean accepting multiple inputs from a single layer, while here we're specifically dealing with layers that have multiple incoming layers. So MultipleInputsLayer is not specific enough either.

True.

> I'd be fine with renaming if we find a better name than what we currently have. I don't think any name suggested in this thread is better than MergeLayer, though, it would have to be something new.

I'm not sure there's a good name for it, because we want to say that the layer has multiple input connections, but not that it will merge or combine said input connections, and I don't know of a concise way to summarize that.

**Comment by benanne** [comment]
I think the confusion about `MultipleInputsLayer` and `MergeLayer` stems from people giving different interpretations to what it means for a layer to have multiple inputs (i.e. does it get input from multiple layers, or is it just a layer that accepts multiple tensors as input), and what the semantics of 'merging' are.  a `MergeLayer` combines inputs from multiple layers, so maybe `CombineLayer` is a name that is less prone to misinterpretation? It sounds a bit silly though.

**Comment by craffel** [comment]
Yeah, I don't really see the recurrent layers as merging or combining anything.  I will just live with `MergeLayer`, sorry for bringing it up.

**Comment by f0k** [comment]
> and what the semantics of 'merging' are

I think that's the main trouble here. We'd need a verb (or any word, actually) that encompasses both the current meaning of combining some inputs, and the new use case's meaning of interpreting an input in light of a second input.

> sorry for bringing it up.

I love name discussions!
