### ISSUE TITLE
RNN language model

### ISSUE THREAD

**Issue by kadarakos** [Lasagne/Lasagne#205]
I like the Lasange API (and the name obviously) and I was wondering if there are any plans to include RNNs and its variants (LSTMs or Gated units) in the library?

**Comment by craffel** [comment]
RNNs are being added in my fork:
https://github.com/craffel/nntools
Currently on pause until #104 is completely resolved.

**Comment by benanne** [comment]
According to my colleague the code in @craffel's fork is very much usable :) Hopefully we can merge it soon!

**Comment by kadarakos** [comment]
Ah cool I will check it out. Thanks!
