### ISSUE TITLE
Missing stride argument in lasagne/layers/pool/FeaturePoolLayer

### ISSUE THREAD

**Issue by neilsummers** [Lasagne/Lasagne#208]
Commit a0961b1cf451255ea3372787d6ee4c78cee700a8 modified lasagne/layers/pool.py
method ```pool_output_length``` to include a stride argument, but ```FeaturePoolLayer``` makes a call to this method without this argument, raising an exception.

More details:

```class FeaturePoolLayer(Layer)```
defines the method
```
def get_output_shape_for(self, input_shape):
        output_shape = list(input_shape)  # make a mutable copy
        output_shape[self.axis] = pool_output_length(input_shape[self.axis],
                                                     self.ds)
        return tuple(output_shape)
```

which makes a call to pool_output_length, but is missing the stride argument
```def pool_output_length(input_length, ds, st, ignore_border=True, pad=0):```

Should stride be set to ds if None like with ```MaxPool2DLayer```?

**Comment by ebenolson** [comment]
Oops... I'm not sure there's a reason to support stride in `FeaturePoolLayer`, so just hardcoding it to use `st=ds` in that call is probably enough.

Feel free to make a PR, otherwise I'll do it later today. 

Even better would be a test case for `FeaturePoolLayer`

**Comment by f0k** [comment]
> Should stride be set to ds if None like with `MaxPool2DLayer`?

Yes, it would be good to have `st=None` as a default in `pool_output_length()`, and there should be a test case for `FeaturePoolLayer.get_output_shape_for()`. A PR would be welcome!

**Comment by neilsummers** [comment]
I can hopefully do a PR later today.

**Comment by neilsummers** [comment]
From your comments above, I guess there are two different ways of doing this.
Would you rather that
a) ```pool_output_length()``` had the default argument of ```st=None```, and then set to ```st=ds``` in ```pool_output_length()```,
or
b) call ```pool_output_length()``` is called from ```FeaturePoolLayer.get_output_shape_for()``` with the argument ```st=None```?

**Comment by f0k** [comment]
The second solution probably should have read "with the argument `st=ds`". In any case, I prefer the first solution: Have a default value `st=None`, and a `if st is None: st = ds` in `pool_output_length()`, but keep `FeaturePoolLayer.get_output_shape_for()` unchanged.

**Comment by neilsummers** [comment]
Yes it should.
Will take me a bit longer to put a PR together with a test for ```FeaturePoolLayer```. If you can do it quickly then feel free.

**Comment by ebenolson** [comment]
@neilsummers I'll do this today unless you've been working on it.

**Comment by neilsummers** [comment]
Go ahead. Sorry, not had time yet. Thanks.
