### ISSUE TITLE
leaky_rectify shortcut not working

### ISSUE THREAD

**Issue by skaae** [Lasagne/Lasagne#209]
The leaky_rectify shortcut is not working:

https://github.com/Lasagne/Lasagne/blob/master/lasagne/nonlinearities.py#L125

I guess it should be 

`leaky_rectify = LeakyRectify` 
instead of
`leaky_rectify = LeakyRectify()`

**Comment by f0k** [comment]
As the comment says, it's a shortcut for the leaky rectifier with default leakiness, not an alias. The following should be equivalent:
```python
DenseLayer(foo, num_units=bar, nonlinearity=leaky_rectify)
DenseLayer(foo, num_units=bar, nonlinearity=LeakyRectify())
DenseLayer(foo, num_units=bar, nonlinearity=LeakyRectify(0.01))
```
It's provided to be compatible with:
```python
DenseLayer(foo, num_units=bar, nonlinearity=rectify)
```
Does that solve the issue or is there still something wrong?

**Comment by skaae** [comment]
Ok, I  tried to replace LeakyRectify(leakiness=LEAKYNESS) with leaky_rectify(eakiness=LEAKYNESS), which didnt work. 

I guess i misunderstood the purpose of the leaky_rectify shortcut. 
Tts not a big deal, but i couldn't get the leaky_rectify to work because my IDE suggested leaky_rectify which i assumed was the correct function.

I think it would be easier if the short_cut was removed or had similar interface as LeakyRectify

**Comment by f0k** [comment]
> I think it would be easier if the short_cut was removed or had similar interface as LeakyRectify

The idea of the shortcut was to have a similar interface as `sigmoid`, `softmax`, `tanh`, and `rectify` -- i.e., all the nonlinearities we have apart from the leaky rectifier -- and leave `LeakyRectify` as the odd exception with a different spelling and usage. Any other parameterized nonlinearities would probably follow suit.

> my IDE suggested leaky_rectify

Did it also suggest `leaky_rectify(leakiness=VALUE)`, i.e., is it confused by the way it's defined?

We could turn the shortcut into a function such as:
```python
def leaky_rectify(x):
    return LeakyRectify()(x)
```
That would be inelegant, but allow to attach a separate docstring.

**Comment by skaae** [comment]
No, the IDE did not suggest any parameters. I thought it was a bug, but I see now that it isn't :) 

Thanks for the help. 
I'll close this issue
