### ISSUE TITLE
hessian free solver

### ISSUE THREAD

**Issue by shaih82** [Lasagne/Lasagne#216]
does anyone knows if lasagne will have an approximated hessian (2nd order diff) descent solver?
for example
https://github.com/boulanni/theano-hf
or 
http://riejohnson.com/svrg_download.html

or even simply newton method (which is applicable for very small networks)
but still very helpful

**Comment by benanne** [comment]
This is outside of the scope of Lasagne for now I think. But all Lasagne does is generate some Theano expressions, so it should be compatible with https://github.com/boulanni/theano-hf .
