### ISSUE TITLE
Cannot execute nolearn.lasagne.NeuralNet fit method in python3.4.0

### ISSUE THREAD

**Issue by stephane-rolland** [Lasagne/Lasagne#230]
run-time error is located in lasagne.py  (the full stack is at the bottom of my message):

/usr/local/lib/python3.4/dist-packages/nolearn/lasagne.py in _print_layer_info(self, layers)
    378                 layer.__class__.__name__,
    379                 output_shape,
--> 380                 reduce(operator.mul, output_shape[1:]),
    381                 ))
    382 

NameError: name 'reduce' is not defined

---------------------------------------------------------------------------
I retrieved the lasagne code today from git-hub download on master branch.
And installed according the documentation.

However, at first I had to modify inside lasagne.py  the `import cPickle`   into `import pickle` so as I can import lasagne stuffs. That passed ok.

But this run-time error happens when executing the code that can be found here: http://nbviewer.ipython.org/github/ottogroup/kaggle/blob/master/Otto_Group_Competition.ipynb

when executing the ipython3 block:
`net0.fit(X, y)`

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-19-767460c55f9b> in <module>()
----> 1 net0.fit(X, y)

/usr/local/lib/python3.4/dist-packages/nolearn/lasagne.py in fit(self, X, y)
    138             out = self._output_layer = self.initialize_layers()
    139         if self.verbose:
--> 140             self._print_layer_info(self.get_all_layers())
    141 
    142         iter_funcs = self._create_iter_funcs(

/usr/local/lib/python3.4/dist-packages/nolearn/lasagne.py in _print_layer_info(self, layers)
    378                 layer.__class__.__name__,
    379                 output_shape,
--> 380                 reduce(operator.mul, output_shape[1:]),
    381                 ))
    382 

NameError: name 'reduce' is not defined

**Comment by ebenolson** [comment]
Couple things:

1. This is an issue with nolearn, not Lasagne, and should be reported to https://github.com/dnouri/nolearn

2. `lasagne.py` no longer exists in nolearn, so I don't think you're using the latest code. Try updating to the latest github version, I think this has been fixed.

**Comment by stephane-rolland** [comment]
okay. i'm gonna look there.
thx.

**Comment by stephane-rolland** [comment]
I confirm it's fixed with the latest sources.
