### ISSUE TITLE
binary_crossentropy

### ISSUE THREAD

**Issue by abhisheksimhadri** [Lasagne/Lasagne#234]
Any idea why this is happening:

>>> from lasagne.objectives import binary_crossentropy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name binary_crossentropy

********************************************************************************************************************

Other modules work fine ... 
from lasagne.layers import InputLayer, DropoutLayer, DenseLayer
from lasagne.updates import nesterov_momentum etc...

**Comment by ebenolson** [comment]
what versions of Lasagne and Theano are you using?

**Comment by benanne** [comment]
This function no longer exists because it became redundant, you should use `theano.tensor.nnet.binary_crossentropy` instead :)

**Comment by benanne** [comment]
I'll close this, feel free to let us know if you run into any other issues. For support questions make sure to post to the mailing list instead: https://groups.google.com/forum/#!forum/lasagne-users

Thanks!
