### ISSUE TITLE
ImportError: dnn not available

### ISSUE THREAD

**Issue by andyyuan78** [Lasagne/Lasagne#242]
ubgpu@ubgpu:~/github/Lasagne/examples$ python mnist_conv_dnn.py
Using gpu device 0: GeForce GTX 970
Traceback (most recent call last):
  File "mnist_conv_dnn.py", line 4, in <module>
    from lasagne.layers import dnn  # fails early if not available
  File "/usr/local/lib/python2.7/dist-packages/Lasagne-0.1dev-py2.7.egg/lasagne/layers/dnn.py", line 12, in <module>
    raise ImportError("dnn not available")
ImportError: dnn not available
ubgpu@ubgpu:~/github/Lasagne/examples$ sudo python mnist_conv_dnn.py
[sudo] password for ubgpu: 
ERROR (theano.sandbox.cuda): nvcc compiler not found on $PATH. Check your nvcc installation and try again.
Traceback (most recent call last):
  File "mnist_conv_dnn.py", line 4, in <module>
    from lasagne.layers import dnn  # fails early if not available
  File "/usr/local/lib/python2.7/dist-packages/Lasagne-0.1dev-py2.7.egg/lasagne/layers/dnn.py", line 12, in <module>
    raise ImportError("dnn not available")
ImportError: dnn not available

**Comment by ebenolson** [comment]
Have you installed the CUDA toolkit and cuDNN library?

Theano has installation instructions here: 
http://deeplearning.net/software/theano/install.html#gpu-linux
http://deeplearning.net/software/theano/library/sandbox/cuda/dnn.html

**Comment by f0k** [comment]
All right, the second one (with `sudo`) just fails because, as it says, `nvcc` is not on the PATH any more. One way of solving it would be `sudo PATH="$PATH" ...`, but just ignore that case, it's not relevant here. 

The first one indicates that cuDNN is not installed. To get more details, run the following:
```bash
python -c 'from theano.sandbox.cuda.dnn import dnn_available; print dnn_available(); print dnn_available.msg'
```

cuDNN installation instructions: http://deeplearning.net/software/theano/library/sandbox/cuda/dnn.html (at the top)

**Comment by benanne** [comment]
I'll close this, feel free to post on the mailing list if you need more help!

**Comment by HadXu** [comment]
If I do not have a device supported bu cuDnn,but I also want to use lasagne.layers.dnn,how to do?

**Comment by ebenolson** [comment]
You can use the default `MaxPool2DLayer` and `Conv2DLayer`, or the alternative implementations in `cormm` and `cuda_convnet`.

**Comment by f0k** [comment]
Note that if you're changing an existing model that uses `Conv2DDNNLayer` to use `Conv2DLayer` instead, you will need to flip the filter weights (`W = W[:, :, ::-1, ::-1]`), otherwise the outputs will not be identical.

**Comment by lbiemans** [comment]
What worked for me was running "export THEANO_FLAGS=floatX=float32,device=gpu0,force_device=True,nvcc.fastmath=True,nvcc.flags=-arch=sm_30,cuda.root=/usr/local/cuda-7.5/" before running python and lasagne. If this works add it to your environment to make it automatically load on login (Linux).
