### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by benanne** [Lasagne/Lasagne#26]
There is no documentation at the moment - we should probably get started with this as soon as possible. We talked about this previously and I believe we were thinking of using [Sphinx](http://sphinx-doc.org/). Are there any alternatives we should consider? Does anybody have any experience setting up Sphinx?

EDIT: relevant reading: http://www.jeffknupp.com/blog/2013/08/16/open-sourcing-a-python-project-the-right-way/

**Comment by benanne** [comment]
I just added some more docs (input layer and dense layer) and changed the documentation theme because I thought the previous one looked very messy. I stole the one that librosa uses (sphinx-bootstrap-theme).

I actually meant to do this on a branch + pull request, because I believe the theme is an additional dependency. But apparently I forgot to check out the branch or something... so if you can't build the docs right now, that would be my fault. Sorry!

**Comment by f0k** [comment]
`<offtopic>`
> I actually meant to do this on a branch + pull request, because I believe the theme is an additional dependency. But apparently I forgot to check out the branch or something...

It's too late now, but if stuff like that happens, you can always do something like
```bash
git checkout -b wrong-commit  # just to have a backup
git checkout master
git reset --hard HEAD^  # or the SHA of the commit you want to revert to
git push --force origin master
```
to undo what you pushed to the server. If nobody pulled in between, nobody will notice. Maybe you know this anyway, but don't be too shy about force-pushing.
`</offtopic>`

**Comment by benanne** [comment]
I did not know that :) Thanks for the hint!

**Comment by benanne** [comment]
The current layout on http://lasagne.readthedocs.org/ looks a little messy, so we should probably experiment with this a bit (maybe reduce the number of levels of indentation by making the subtitles like "usage" and "parameters" be headers instead.

As a side note it looks like Brian McFee is actually converting the librosa docs to the numpy format: https://github.com/bmcfee/librosa/issues/145

**Comment by JackKelly** [comment]
Really excited about Lasagne!

One small tweak: it might be worth linking to http://lasagne.readthedocs.org from Lasagne's front page on github.  For example, link to http://lasagne.readthedocs.org from the "Website" attribute on the project's github front page.

**Comment by benanne** [comment]
Good call. Done :)

**Comment by JackKelly** [comment]
perfect, thank you ;)

**Comment by benanne** [comment]
I just had another look at the docs. I switched back to the sphinx bootstrap theme, because imo the readthedocs one looked pretty messy. It's a bit better now, still not very aesthetically pleasing though...

I've also added "autoclass" lines for all layer classes. It would actually be much nicer if we were able to use "automodule" on all of the layer submodules, so they could have separate pages as well. Unfortunately then the layers will be reported as `lasagne.layers.dense.DenseLayer` for example, and we want it to say `lasagne.layers.DenseLayer` instead.

Is there a workaround for this? The current approach of manually enumerating all the members of `lasagne.layers` by name in the documentation is error-prone and redundant. It would be great to get rid of that.

Another problem is that the specialized convolution layer modules cannot be imported by readthedocs (we make these imports fail if the dependencies are not present, this includes a GPU). So they cannot be documented. I don't suppose there is a workaround for this as well?

We should also figure out how to clean up some of the signatures. For example, we get:

```
class lasagne.layers.DenseLayer(incoming, num_units, W=<lasagne.init.Uniform object at 0x756c4d0>, b=<lasagne.init.Constant object at 0x756c510>, nonlinearity=<function rectify at 0x756f9b0>, **kwargs)
```

which should really read:

```
class lasagne.layers.DenseLayer(incoming, num_units, W=lasagne.init.Uniform(), b=lasagne.init.Constant(0.0), nonlinearity=lasagne.nonlinearities.rectify, **kwargs)
```

I think the only solution there is to manually specify this signature. Supposedly you can specify this as the first line in the docstring. Not sure if that's the cleanest approach though.

**Comment by f0k** [comment]
> It's a bit better now, still not very aesthetically pleasing though...

Much better!

> I think the only solution there is to manually specify this signature.

Or to default to `W=None` and have a `if W is None: W = lasagne.init.Uniform()` in the constructor. That's the common scheme for mutable objects, but we could use it here as well.

**Comment by craffel** [comment]
> It would actually be much nicer if we were able to use "automodule" on all of the layer submodules, so they could have separate pages as well. Unfortunately then the layers will be reported as lasagne.layers.dense.DenseLayer for example, and we want it to say lasagne.layers.DenseLayer instead.

I remember there being a similar problem with `mir_eval`'s docs but I can't find any reference to it. I feel like this is something @bmcfee would know.

**Comment by benanne** [comment]
> Or to default to `W=None` and have a `if W is None: W = lasagne.init.Uniform()` in the constructor. That's the common scheme for mutable objects, but we could use it here as well.

True. The idea of changing the actual code just so the docs will look a bit nicer doesn't sit well with me though!

**Comment by bmcfee** [comment]
> I've also added "autoclass" lines for all layer classes. It would actually be much nicer if we were able to use "automodule" on all of the layer submodules, so they could have separate pages as well. Unfortunately then the layers will be reported as lasagne.layers.dense.DenseLayer for example, and we want it to say lasagne.layers.DenseLayer instead.
> 
> Is there a workaround for this? The current approach of manually enumerating all the members of lasagne.layers by name in the documentation is error-prone and redundant. It would be great to get rid of that.

Jumping in, due to the @caffel summons...

I've been basing the upcoming librosa release's doc style on scipy, which IMO has the cleanest layout to crib from.

Your `layers.dense.DenseLayer` vs `layers.DenseLayer` issue should be easy enough to fix. If an example helps, check out https://github.com/bmcfee/librosa/blob/develop/librosa/core/__init__.py (which import*'s from submodules) and https://raw.githubusercontent.com/bmcfee/librosa/develop/docs/core.rst .

FWIW, adding submodule docstrings to index the contents, while inelegant, actually does give you the best control over layout.

**Comment by benanne** [comment]
I will close this issue. Documentation is never finished, but it's in a pretty good state right now and I don't think we have to add too much for it to be ready for the first release (except for the modules for which the API isn't finalized yet, i.e. `objectives` and `regularization`).
