### ISSUE TITLE
Conv3DLayer implementation

### ISSUE THREAD

**Issue by benanne** [Lasagne/Lasagne#27]
I'd like to have `Conv1DLayer`, `Conv2DLayer` and `Conv3DLayer` available. Unfortunately Theano's support for 3D convolutions is a bit of a mess imho, there are some different implementations (see [documentation](http://deeplearning.net/software/theano/library/tensor/nnet/conv.html) for details):
- `theano.tensor.nnet.Conv3D.conv3D`, which I guess is the default. Its expected input shape configuration is `b01tc` (b = batch, 0 = width, 1 = height, t = time, c = channels, note that 0, 1 and t are basically interchangeable), which is sort of unusual because the channel dimension is last. In practice this is apparently CPU only because the GPU implementation is slow (the docs even encourage using `conv3d2d` on GPU instead).
- `theano.tensor.nnet.conv3d2d.conv3d` has `btc01` as its input shape configuration. Also kind of weird to have the channel dimension in the middle there. This works by turning the 3D convolution into a 2D convolution, and given the recent improvements for the 2D convolution, this is probably the most useful implementation.
- `theano.sandbox.cuda.fftconv.conv3d_fft` has `bct01` as its input shape configuration, which is the most natural way to do things imho (since `conv2d` uses `bc01`). This is a 3D version of `conv2d_fft`. I don't know how practical this is because FFT convolutions use a lot of memory. There is no gradient implemented
- There is an optimization that swaps `theano.tensor.nnet.Conv3D.conv3D` for `theano.sandbox.cuda.fftconv.conv3d_fft`. It must be enabled manually.

Since `conv3d_fft` has no gradient implemented, there is no point in supporting it directly. Instead we should support `Conv3D.conv3D`.

I think we should also support `conv3d2d.conv3d`. Afaik there is no optimization to replace  `Conv3D.conv3D` by `conv3d2d.conv3d`. So that means the `Conv3DLayer` class needs a switch to choose the implementation. This can just be an `implementation` keyword argument on the constructor (which is how I've tackled this issue in the past in layers.py).

In general I think having an `implementation` keyword for all of the `Conv*DLayers` is a good idea, there are a lot of different ways to do things and although there are sometimes optimizations that can be enabled manually, those aren't always available. And for the 1D convolution there is currently no implementation at all (but I have a bunch of code for that already).

What should be the default implementation to use? I think having `conv3d2d.conv3d` as the default makes the most sense since it is probably the most practically usable implementation these days. But we should definitely support `Conv3D.conv3D` as well.

Regardless of this, I think `Conv3DLayer` should use `bct01` input order by default. This means some reshapes may be necessary. We could also add a keyword argument to disable this reshaping, as a performance optimization. In that case the user would be expected to ensure that the input to the layer already has the right order.

**Comment by MartinThoma** [comment]
@benanne Just to make sure I understand what 3D convolutions are: When I have a 3 channel image (e.g. RGB) I do not need 3D convolution, but the results might be better. Correct?

**Comment by f0k** [comment]
> I could also use 2D convolutions without having to convert the image to greyscale before I feed it to Lasagne. But the results with 3D convolutions might be better than with 2D convolutions. Correct?

No. If you have a three-channel image of shape `(3, h, w)`, there are three options for a 3D convolutional layer:
* kernel shape `(3, kh, kw)`: this convolves the three channels with three separate kernels and adds up the results, which is exactly the same as using a 2D convolution
* kernel shape `(1, kh, kw)`: this convolves each channel separately with the same kernel and leaves the results separated, which is exactly the same as reshaping the input to three times the batchsize and a single input channel, applying a 2D convolution and reshaping back
* kernel shape `(2, kh, kw)`: this convolves and merges the red and green channel, then convolves and merges the green and blue channel using the same kernels as for the first operation, which doesn't make sense

**Comment by benanne** [comment]
That, or 3D imagery (depth, height, width), which is common in medical applications for example.

**Comment by MerlinBlume** [comment]
'That, or 3D imagery (depth, height, width), which is common in medical applications for example.'

> Can someone tell me how I can build a 3D convolutional autoencoder for voxelgrid data?
> Maybe using Theano, Pylearn2 and Lasagne?
> THX Merlin

**Comment by benanne** [comment]
Please use the mailing list ( https://groups.google.com/forum/#!forum/lasagne-users ) for this type of requests, this GitHub issue is not the appropriate venue for that. Thanks!

**Comment by bmcfee** [comment]
As @f0k mentioned above, there are three possibilities for `(k, h, w)` convolutions, depending on the shape `(p, q, r)` of the filter (assuming `mode='valid'` semantics):

* If `p==1`, you get a stack of 2d convolutions, which are already supported/can be mimicked by 2d + reshape.
* If `p==k`, you can sum out a stack of 2d convolutions to achieve the volumetric convolution.
* If `1<p<k`, then weird stuff can happen unless there's a meaningful topology to the third dimension.  (Red->Green->Blue maybe isn't that meaningful, but a time dimension might be.)

So in light of the above, what do folks think about providing a class that fakes the first two options (or just the second one, since it's the most interesting)?  It seems to me that this should still compile down to reasonably efficient code (compared to theano's existing 3d conv support), and cover the interesting use cases.

**Comment by nouiz** [comment]
Just to be sure you know theano have a conv3d2d that use cond2d for
computation. But this cause some extra computation in corners. I don't know
if this is useful.

That 2nd option would cause extra memory usage.

GpuCorr3dMM is pretty efficient and I think would use less tmp memory that
what you suggest. GpuCorr3dMM is faster then cudnn v3 3d conv I think. But
that probably won't last :)

**Comment by benanne** [comment]
When was `GpuCorr3dMM` added? It sounds like we should create a `Conv3DLayer` class that calls this directly and be done with it? At least while we wait for the Theano convolution interface to be revamped ( https://github.com/Theano/Theano/issues/2505 ).

**Comment by nouiz** [comment]
That PR cover only 2d conv.

https://github.com/Theano/Theano/pull/2114/ added this.

**Comment by benanne** [comment]
It does? That is unfortunate. I was hoping that the plan was to have a unified convolution interface regardless of the dimensionality of the input. This shouldn't be that hard to do.

**Comment by dimatura** [comment]
I've implemented a couple of 3D conv layers for my research. I was planning on releasing on something as a third party layer - not sure if there's any licensing issues.

**Comment by benanne** [comment]
Sweet! If you're unsure, you're always welcome to send a PR to https://github.com/Lasagne/Recipes - the requirements in terms of docs / tests are not as strict there. We can always move the bits that seem useful over to the main library later.

**Comment by nouiz** [comment]
The goal is to support other (1d/3d) convolution too. But as this is taking
more time, we will finish and merge the 2d case first.

**Comment by WanyiLi** [comment]
@dimatura  Could you share your 3D conv layer implementation to me? My Email is :wanyi.li@ia.ac.cn. Thank you very much!

**Comment by stablum** [comment]
is the 3D convolution something typically used for videos too? (for example action recognition) That would be sweet!

**Comment by nouiz** [comment]
The only case I think of 3d conv is video. But I'm sure other people can
find other use of this.
Le 17 oct. 2015 10:49, "stablum@gmail.com" <notifications@github.com> a
écrit :

**Comment by WanyiLi** [comment]
In my opinion, except video, 3D can be also used for volumetric data, i.e., voxel data.

**Comment by gyglim** [comment]
Hi

I'd like to revive this issue. I agree with @benanne that the Theano implementation is a bit messy. 
Thus far, Lasagne has 3D convs and 3D pooling for cuDNN, but I also need it on CPU. Therefore I implemented the 3D Conv using theano.tensor.nnet.conv3d2d.conv3d and 3D pooling using dimshuffle and 2D pooling.

I tried it for the C3D network
 (https://github.com/Lasagne/Recipes/blob/master/examples/Video%20features%20with%20C3D.ipynb) and get, up to rounding errors, identical results.

Is there still interest to add this to the main library?
Positive:
- More complete library

Negative:
- Theano's 3D conv is limited. It doesn't support stride or padding, as far as I understand. Padding is easy to add in Lasagne, though.
- Speed: Running C3D using theano.tensor.nnet.conv3d2d.conv3d on GPU takes 2x the time of the cuDNN implementation, which is still ok I guess. But on CPU it is >100x. However I am sure my implementation can be somewhat improved.

What do you think, is it worth adding 3D convs and pooling? 
My Implementation uses dimshuffle to put the data into the right format (btc01) and back and to do the 3D pooling. Is this ok to use in terms of speed or should it be avoided?

If there is interest I can make a pull request.

**Comment by f0k** [comment]
> What do you think, is it worth adding 3D convs and pooling?

Yes, definitely! Over the long term, Theano should get an `abstract_conv3d` interface similar to the one for 2D convolution, so it can use the fastest implementation depending on what's available for the device. For now, we'll have to choose one and mention in the docs that the cuDNN version should be preferred. The same holds for pooling. I don't know if the situation is any better in Theano's new backend.

> Running C3D using theano.tensor.nnet.conv3d2d.conv3d on GPU takes 2x the time of the cuDNN implementation, which is still ok I guess. But on CPU it is >100x.

Note that there is also theano.sandbox.cuda.blas.GpuCorr3dMM, which might be faster (would be curious to know). If you're looking for performance, it may be worth porting this to CPU (in Theano), just like GpuCorrMM was ported to CPU as theano.tensor.nnet.corr.CorrMM.

**Comment by nouiz** [comment]
Just a few note. Cudnn v5 got good speed up for 3d conv. If you want a CPU
corrmm3d, I think it would be faster to start from the CPU corrmm 2d then
the GPU 3d corrmm.

**Comment by hmeine** [comment]
I just tried @gyglim 's branch and found two issues:
* lasagne.layers.Conv3DLayer should be a valid forward from the conv submodule
* lasagne.layers.Conv3DLayer does not seem to support arbitrary-size dimensions

What led me to believe the latter: When I use Conv3DLayer on top of  `lasagne.layers.InputLayer(shape = (None, input_channels, None, None, None), input_var = ftensor5())`, I am getting an exception like this:

```
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/theano/tensor/nnet/conv3d2d.pyc in conv3d(signals, filters, signals_shape, filters_shape, border_mode)
    222
    223     _signals_shape_4d = (
--> 224         _signals_shape_5d[0] * _signals_shape_5d[1],
    225         _signals_shape_5d[2],
    226         _signals_shape_5d[3],

TypeError: unsupported operand type(s) for *: 'NoneType' and 'NoneType'
```

**Comment by nouiz** [comment]
I htink I fixed this error in Theano some times ago. Can you update to
Theano dev version? Maybe the code you use need a newer Theano.

**Comment by hmeine** [comment]
Indeed, thanks. I did not even notice the error came from theano and not from lasagne.
However, after fixing the above Lasagne branch to work with an up-to-date theano dev version, I got a very similar error from here: https://github.com/Theano/Theano/blob/master/theano/tensor/nnet/conv3d2d.py#L227

**Comment by f0k** [comment]
Seems conv3d2d does not handle partly-specified shapes. You can change
```python
if signals_shape is None:
```
to
```python
if signals_shape is None or any(s is None for s in signals_shape):
```
Same for the filter shape.

Not sure if we would win anything by using constants whenever possible. This would require something like:
```
if signals_shape is None:
    _signals_shape_5d = (None,) * 5
_signals_shape_5d = tuple(s if c is None else c
                          for c, s in zip(signals_shape, signals.shape))
```
Same for the filter shape.

**Comment by f0k** [comment]
https://github.com/Theano/Theano/pull/4862 paved the way for a generic `Conv3DLayer`.
