### ISSUE TITLE
Programs slow down when they run on the same GPU card

### ISSUE THREAD

**Issue by lim0606** [Lasagne/Lasagne#291]
Hi, everyone 

I'm doing some experiments using with Lasagne. 

During the experiments, I encountered an issue that programs slow down when they run on the same GPU card. For example, when I run two `mnist_conv.py`s on gpu0, each took more time than the program running solely (longer than twice).    

Is this phenomenon natural for theano with gpu? or natural for all gpu programming?
 
I'm using Ubuntu 14.04.2, Titan Z

Thank you 

Jaehyun

**Comment by benanne** [comment]
If it was possible to run multiple experiments on a single GPU at full speed, you would only ever need a single one :) Running multiple experiments on a single GPU will always lead to slowdowns if your experiments use it efficiently. You can only get away with it if the experiments are small enough that they only utilize the GPU for less than 50%, but that will rarely be the case.

**Comment by nouiz** [comment]
One point in the original email is that the slow down is more then 2x. This
can happen with CPU only program and GPU program. There is context switch
and shared ressource (like the memory cache) that if shared between
different jobs can cause a slow down bigger then the number of jobs.

Quick example. If the cache size is 16MB and the working set of a jobs is
12MB(the sizes of the memory region it need to work on at one point). If
you launch 2 jobs, then the working set get to 24M, bigger then the 16M
available. So the each jobs need to read data from the main memory more
frequently then in the past, so it get slow down.
