### ISSUE TITLE
Layer shortcuts are repeated in docs

### ISSUE THREAD

**Issue by skaae** [Lasagne/Lasagne#303]
In some of the docs (all?) the layer shortcuts are inserted in the docst with full descriptions. 

e.g. in ReshapeLayer and reshape but also in other places. 

I think we need to remove the `.. autofunction::` lines for the shortcuts in `layers.rst`,

```
.. autoclass:: ReshapeLayer
    :members:

.. autofunction:: reshape
```

and then add `See also` with reference to the shortcut. Should i create a PR that removes autofunction for all shortcuts and adds references to the shortcuts if they are missing? 

I also noticed that [R5]_ is not working in the dropout layer. Should i create a separate PR for that?

**Comment by benanne** [comment]
PRs are always welcome :) Are you sure this is the correct way to fix it? I think the problem may be that we use some tricks to make all the layer classes appear in the top level `lasagne.layers` module, which means sphinx is unable to figure out they are shortcuts. But feel free to try and fix it :)

Separate PRs are good, a single one is good as well, I guess neither are urgent.

**Comment by skaae** [comment]
They disappear if you remove the autofunction line. As long as they appear in See also I guess its fine?

**Comment by benanne** [comment]
Only if there is something there to "also see" :) If they are not listed at all, listing them under 'see also' for another function/class doesn't make sense.

**Comment by benanne** [comment]
Here's a working shortcut (alias) listing that Sphinx detected and added automatically: http://lasagne.readthedocs.org/en/latest/modules/layers.html#lasagne.layers.cuda_convnet.bc01_to_c01b

For any of the layer classes that are imported into the `lasagne.layers` namespace, this feature does not seem to work correctly.

**Comment by skaae** [comment]
After a little trail and error it seems that alias works if you use `autoclass` for Real name and shortcut.

**Comment by skaae** [comment]
I'll create a PR that fixes it.

**Comment by skaae** [comment]
PR: https://github.com/Lasagne/Lasagne/pull/304
