### ISSUE TITLE
Add a test for conv_output_length(..., border_mode='pad')

### ISSUE THREAD

**Issue by benanne** [Lasagne/Lasagne#305]
According to coveralls, there is exactly one line of code that currently isn't covered by our tests. It's this one: https://github.com/Lasagne/Lasagne/blob/e19ea3655d31cbd3803a6cb37253b8a9504bdd35/lasagne/layers/conv.py#L80

This is just a reminder to add a test for this. The coveralls badge does show 100% coverage now, but that is apparently a lie! And I just can't live with that. I can do it myself, but if someone else wants to do it, feel free.

**Comment by f0k** [comment]
This is bugging me as well.

**Comment by benanne** [comment]
There is already one test that tests it directly, I think we decided then that this was enough for now. So I'd be content just having one extra test to cover that line. But of course more tests is better :)
