### ISSUE TITLE
cuDNN installation / configuration

### ISSUE THREAD

**Issue by MartinThoma** [Lasagne/Lasagne#316]
I've recently seen that a lot of tests get skipped for me (see https://gist.github.com/MartinThoma/68e5e78101a3fbaed334). The / one reason is that I don't have CuDNN:

```bash
$ python mnist_conv_dnn.py
Using gpu device 0: GeForce GTX TITAN Black
Traceback (most recent call last):
  File "mnist_conv_dnn.py", line 4, in <module>
    from lasagne.layers import dnn  # fails early if not available
  File "/usr/local/lib/python2.7/dist-packages/Lasagne-0.1.dev-py2.7.egg/lasagne/layers/dnn.py", line 12, in <module>
    raise ImportError("dnn not available")  # pragma: no cover
ImportError: dnn not available
```

It should be made clear in the docs (e.g. on http://lasagne.readthedocs.org/en/latest/user/development.html) that you need to install it manually. Eventually we could also add some help how to install / configure it. Or simply link to http://deeplearning.net/software/theano/library/sandbox/cuda/dnn.html

**Comment by MartinThoma** [comment]
(by the way: I registered as a developer via https://developer.nvidia.com/cuDNN - do you know how long it takes until I can download cuDNN?

**Comment by benanne** [comment]
I think it might take a few days before they "approve" your account. Also I'm not sure that we "should" mention this since it's an indirect dependency through Theano, but I guess it can't hurt :)

**Comment by f0k** [comment]
We could copy over the "To install it" part from the Theano docs (I wrote that part anyway), but I guess we should rather link to it and name cuDNN as an optional dependency somewhere.

**Comment by MartinThoma** [comment]
@f0k Ok. I'll add the link with https://github.com/Lasagne/Lasagne/pull/311

I just got acceptes as a Nvidia developer. The cuDNN installtion was really simple. And now I get LOTS of failing tests for https://github.com/Lasagne/Lasagne/pull/311 

I'll add a comment as soon as I have fixed them.

**Comment by MartinThoma** [comment]
Damn, too early. When I try to execute `mnist_conv_dnn.py` I get: https://gist.github.com/MartinThoma/791187d5935ba88e8089

Does anybody have an idea what is going wrong?

**Comment by benanne** [comment]
What GPU are you running this on? Also it might be related to setting up the correct paths so Theano can find everything. Here's what I have in my .bashrc file:

```
export PATH=$PATH:/usr/local/cuda/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64:/mnt/storage/users/sedielem/lib/cudnn-R2
export LIBRARY_PATH=$LIBRARY_PATH:/mnt/storage/users/sedielem/lib/cudnn-R2
export CPATH=/mnt/storage/users/sedielem/lib/cudnn-R2
```

Not sure if all of these are necessary, but it works.

**Comment by MartinThoma** [comment]
> What GPU are you running this on?

nVidia GeForce GTX Titan Black

**Comment by benanne** [comment]
Hmm, okay, that should be fine.

**Comment by f0k** [comment]
I'd first try:
```bash
python -c 'from theano.sandbox.cuda.dnn import dnn_available; print dnn_available(), dnn_available.msg'
```
It will either say `True None` (everything's okay), or `False` followed by the reason.

**Comment by kinginsky** [comment]
I have install CuDnn successfully,but when I use the Lasagne wich is based on theano to train, I get the same error? What am I wrong?

**Comment by f0k** [comment]
> What am I wrong?

Please do what I suggested [in the post directly above yours](https://github.com/Lasagne/Lasagne/issues/316#issuecomment-118072158) and report back.

**Comment by f0k** [comment]
Installing CUDA is not enough, you also need to configure Theano to use it. Please see http://lasagne.readthedocs.io/en/latest/user/installation.html#gpu-support for a short guide and https://github.com/Lasagne/Lasagne/wiki/From-Zero-to-Lasagne for a more extensive one.

**Comment by kinginsky** [comment]
thanks,after I configure Theano,I can use Lasagne successfully.
