### ISSUE TITLE
ImportError: dnn not available

### ISSUE THREAD

**Issue by andyyuan78** [Lasagne/Lasagne#325]
ubgpu@ubgpu:~/github/Lasagne$ sudo python  examples/mnist_conv_dnn.py 
Using gpu device 0: GeForce GTX 970
Traceback (most recent call last):
  File "examples/mnist_conv_dnn.py", line 4, in <module>
    from lasagne.layers import dnn  # fails early if not available
  File "/usr/local/lib/python2.7/dist-packages/Lasagne-0.1.dev-py2.7.egg/lasagne/layers/dnn.py", line 12, in <module>
    raise ImportError("dnn not available")  # pragma: no cover
ImportError: dnn not available
ubgpu@ubgpu:~/github/Lasagne$

**Comment by benanne** [comment]
Please use the mailing list for support requests, we would like to stick to development-related discussion on GitHub. Thanks! You can find it here: https://groups.google.com/forum/#!forum/lasagne-users

Also it would be helpful to get some more information about the issue and what you
