### ISSUE TITLE
Running out of memory on EC2 GPU when allocating variables

### ISSUE THREAD

**Issue by coltsfan** [Lasagne/Lasagne#326]
Hello: 

I am creating a very shallow CNN with 3 x 256 x 256, but at the stage of building a theano graph. I receive the following error: I am not sure what's going on here. 

Here is my code: 
    
    l_in = lasagne.layers.InputLayer(shape = (None, 3, 256, 256),)

    l_conv1 = Conv2DCCLayer(l_in,
                        num_filters=16,
                        filter_size= (3, 3),
                        nonlinearity=lasagne.nonlinearities.rectify,
                        W=lasagne.init.Orthogonal(gain='relu'))

    l_conv2 = Conv2DCCLayer(l_conv1,
                        num_filters=16,
                        filter_size=(3, 3),
                        nonlinearity=lasagne.nonlinearities.rectify,
                        W=lasagne.init.Orthogonal(gain='relu'))

    l_pool1 = MaxPool2DCCLayer(l_conv2,
                           pool_size=(2, 2))
    l_hidden1 = lasagne.layers.DenseLayer(l_pool1,
                                      num_units=500,
                                      nonlinearity=lasagne.nonlinearities.rectify,
                                      W=lasagne.init.Orthogonal(gain='relu'))

    l_hidden1_dropout = lasagne.layers.DropoutLayer(l_hidden1, p=0.5)

    l_hidden2 = lasagne.layers.DenseLayer(l_hidden1_dropout,
                                      num_units=500,
                                      nonlinearity=lasagne.nonlinearities.rectify,
                                      W=lasagne.init.Orthogonal(gain='relu'))

    #l_hidden2_dropout = lasagne.layers.DropoutLayer(l_hidden2, p=0.5)
    l_out = lasagne.layers.DenseLayer(l_hidden2,
                                  num_units=5,
                                  nonlinearity=lasagne.nonlinearities.softmax,
                                  W=lasagne.init.GlorotUniform())

Here is the error:

    MemoryError: ('Error allocating 508032000 bytes of device memory (out of memory).', "you might consider using 'theano.shared(..., borrow=True)'")

Any advice would be appreciated -- thanks!

**Comment by ebenolson** [comment]
Your `l_hidden1` layer is connecting an output of (16, 126, 126) into 500 hidden units - that's about 127M connections, which is quite large. You should introduce more layers of convolution/pooling, or otherwise reduce your image size. 

If you have further questions, please use the [mailing list](https://groups.google.com/forum/#!forum/lasagne-users) for support.

**Comment by coltsfan** [comment]
Ah I see -- thanks; really appreciate it. Will do.
