### ISSUE TITLE
Make NonlinearityLayer a base class?

### ISSUE THREAD

**Issue by f0k** [Lasagne/Lasagne#334]
While splitting up the layer class documentation, I wondered whether we should move `NonlinearityLayer` to `lasagne.layers.base` and then have all layers that sport a nonlinearity derive from it? This way we wouldn't need to replicate (and test) the `nonlinearity is None` case for every subclass. A minor annoyance is that we can't have a `DNNLayer` base class for both `Pool2DDNNLayer` and `Conv2DDNNLayer` any more then. Any opinions?

**Comment by ebenolson** [comment]
I think `NonlinearityLayer` makes more sense in `base` than `dense`. But since placement of nonlinearities is somewhat a matter of preference and convention (hence the need for `nonlinearity=None`), I'm not sure the distinction should be a part of the inheritance tree. What about moving that stuff into `Layer` itself, so every layer can have a possible nonlinearity?

What is the purpose of `DNNLayer`? Would multiple inheritance work?

**Comment by f0k** [comment]
> What about moving that stuff into `Layer` itself, so every layer can have a possible nonlinearity?

**Comment by ebenolson** [comment]
> Do you mean the placement of the keyword arg in the constructor, or where the nonlinearity is inserted into the expression created in get_output_for()?

I just meant sometimes you want e.g. a linear `DenseLayer`, and sometimes you want a nonlinearity following a `PoolLayer`. So codifying that distinction into the inheritance doesn't really make sense to me.

**Comment by ebenolson** [comment]
> I think we disagreed on this somewhere, but I don't recall exactly. From what I remember, only deriving those layers from NonlinearityLayer that need one would counter the argument that was given in that discussion.

Are you thinking of #225? Looks like [you had this idea already](https://github.com/Lasagne/Lasagne/pull/225#issuecomment-97873650), but the current default of `nonlinearity=rectify` was a blocker?

**Comment by f0k** [comment]
> Are you thinking of [...]

Yes, that's what I meant, thank you!

> So codifying that distinction into the inheritance doesn't really make sense to me.

I'd only codify the difference between "accepts a `nonlinearity` kwarg (with the default we agreed on)" and "does not accept a `nonlinearity` kwarg ever". So `DenseLayer` and `Conv2DLayer` would be derived from `NonlinearityLayer`, but `MaxPool2DLayer` or `MergeLayer` wouldn't. That's the difference to my previous suggestion of having the base class handle it. The advantage would be that we could remove all of the `if nonlinearity is None: nonlinearity = lasagne.nonlinearities.identity` checks in constructors. Code would change from:

```python
def DenseLayer(Layer):
    def __init__(self, num_units, W=..., b=..., nonlinearity=lasagne.nonlinearities.rectify, **kwargs):
        if nonlinearity is None:
            nonlinearity = lasagne.nonlinearities.identity
        self.nonlinearity = nonlinearity
        ...
    def get_output_for(self, input, **kwargs):
        act = T.dot(input, self.W) + b
        return self.nonlinearity(act)
```
to:
```python
def DenseLayer(NonlinearityLayer):
    def __init__(self, num_units, W=..., b=..., nonlinearity=lasagne.nonlinearities.rectify, **kwargs):
        super(DenseLayer, self).__init__(nonlinearity, **kwargs)
        ...
    def get_output_for(self, input, **kwargs):
        act = T.dot(input, self.W) + b
        return super(DenseLayer, self).get_output_for(act, **kwargs)
```

It wouldn't make it easier to follow, but code would be decoupled a lot better. I.e., if we ever decide to introduce a default nonlinearity, this would reduce required changes to a single class (safe for the docstrings). Plus we wouldn't need to test the `nonlinearity=None` case for every class that has a nonlinearity just to have 100% test coverage.

**Comment by f0k** [comment]
This was before the first release. We can't change this without breaking backwards compatibility. Closing.
