### ISSUE TITLE
max_pool_2d() got an unexpected keyword argument 'mode'

### ISSUE THREAD

**Issue by anuragsingh31** [Lasagne/Lasagne#339]
getting this error while trying to run mnist.py cnn

**Comment by ebenolson** [comment]
Make sure you are running an up to date version of Theano. 

You can upgrade by typing `pip install -r https://raw.githubusercontent.com/Lasagne/Lasagne/master/requirements.txt`

**Comment by anuragsingh31** [comment]
Thanks it's working now, foolish me ! is there anyway  i can contribute ?

**Comment by ebenolson** [comment]
We should probably raise a warning on import if the Theano version is 0.7.0, or at least add a section about this to https://github.com/Lasagne/Lasagne/blob/master/docs/user/installation.rst

**Comment by anuragsingh31** [comment]
It would be better to add both, in installation section a Prerequisites section with warning rather than just a link to install the requirements, and a import warning as well.

**Comment by f0k** [comment]
I guess it would help to just explain what exactly `pip install -r .../requirements.txt` is for: installing a version of Theano that is recent enough to work with Lasagne (i.e., usually more recent than the current Theano release). An import warning might help as well, it's just a bit annoying for users installing Theano in developer mode (`python setup.py develop`) / editable mode (`pip install . -e`) because then `theano.__version__` doesn't update when updating Theano.

**Comment by ebenolson** [comment]
I was think we could just give a warning `if theano__version__ == '0.7.0'` - wouldn't help people running old git versions, but it would catch the common problematic case of people doing `pip install Theano`.

**Comment by ebenolson** [comment]
> I guess it would help to just explain what exactly pip install -r .../requirements.txt is for: installing a version of Theano that is recent enough to work with Lasagne (i.e., usually more recent than the current Theano release). 

I think this should be done for sure though. [Example from Blocks](http://blocks.readthedocs.org/en/latest/setup.html)

**Comment by f0k** [comment]
Wow, Blocks really does a good job with its documentation (not only the installation instructions). That's the level we should strive for.

**Comment by pratik18v** [comment]
Is there any alternative way to download latest version of theano? 
I tried pip install -r https://raw.githubusercontent.com/Lasagne/Lasagne/master/requirements.txt but it is installing theano 0.7.0 for me.

**Comment by ebenolson** [comment]
Are you sure? You may see a line like this:

    Requested Theano==0.8.git [...] but installing version 0.7.0

But it can be ignored. 
What is the output from `python -c "import theano; print(theano.__version__)"`?

**Comment by pratik18v** [comment]
The output I get is:
0.7.0.dev-36d1eca8ff1b1fb965896bd30e1952338e7e51c5
There was also a error prompt regarding '36d1eca8'.

**Comment by ebenolson** [comment]
The `dev-36d1eca...` suffix indicates you've got the correct git version, you should be all set. 
What do you mean by an error prompt?

**Comment by pratik18v** [comment]
Could not find a tag or branch '36d1eca8', assuming commit.
Requested Thean==0.0.git from git+https://github.com/Theano/Theano.git@36d1eca8#egg=Theano==0.8.git (from -r https://raw.githubusercontent.com/Lasagne/Lasagne/master/requirements.txt (line1)), but installing version None.
This is what it shows.

**Comment by pratik18v** [comment]
It's running now. I don't know what changed though. Thanx for your attention.
