### ISSUE TITLE
Citation for Lasagne

### ISSUE THREAD

**Issue by dimatura** [Lasagne/Lasagne#340]
Hello, I have a camera ready coming up and I'd like to cite Lasagne in it. I know you'll be getting a DOI with the first release, but I can't wait till then :/. Any preferences in this regard?

**Comment by dimatura** [comment]
Never mind, I see this is a duplicate.

**Comment by MartinThoma** [comment]
Duplicate of https://github.com/Lasagne/Lasagne/issues/73
