### ISSUE TITLE
Softmax of 4D Tensor (for fully-convolutional nets)

### ISSUE THREAD

**Issue by HapeMask** [Lasagne/Lasagne#346]
I just finished playing with fully-convolutional nets with Lasagne and ran into one small issue. Theano's `theano.tensor.nnet.softmax` op doesn't support 4D tensors. This is an issue when setting the nonlinearity of a Conv2DLayer to `lasagne.nonlinearities.softmax`.

It's possible to just replace the use of Theano's softmax with the equivalent code like this:
```python
e_x = theano.tensor.exp(x - x.max(axis=1, keepdims=True))
return e_x / e_x.sum(axis=1, keepdims=True)
```

and everything works fine. This might miss out on extra speed/stability optimizations done by the actual Theano softmax op though. I don't know if this issue is better raised here or with Theano.

**Comment by benanne** [comment]
I guess it would be useful to report this to the Theano people as well, perhaps they are interested in including a helper function for this or something. If not, then maybe we could consider having it in Lasagne instead.

**Comment by f0k** [comment]
Discussion continued in #626. Closing this.

**Comment by Alinadi23** [comment]
I've got problem with theano package. I installed it but when i'm gonna use it in programs, I encounter with this error:
Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\site-packages\theano\gof\lazylinker_c.py", line 75, in <module>
    raise ImportError()
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\site-packages\theano\gof\lazylinker_c.py", line 92, in <module>
    raise ImportError()
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    import theano
  File "C:\Program Files\Python35\lib\site-packages\theano\__init__.py", line 110, in <module>
    from theano.compile import (
  File "C:\Program Files\Python35\lib\site-packages\theano\compile\__init__.py", line 12, in <module>
    from theano.compile.mode import *
  File "C:\Program Files\Python35\lib\site-packages\theano\compile\mode.py", line 11, in <module>
    import theano.gof.vm
  File "C:\Program Files\Python35\lib\site-packages\theano\gof\vm.py", line 673, in <module>
    from . import lazylinker_c
  File "C:\Program Files\Python35\lib\site-packages\theano\gof\lazylinker_c.py", line 127, in <module>
    preargs=args)
  File "C:\Program Files\Python35\lib\site-packages\theano\gof\cmodule.py", line 2359, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: Compilation failed (return status=1): C:\Users\asus\AppData\Local\Theano\compiledir_Windows-10-10.0.10586-SP0-Intel64_Family_6_Model_78_Stepping_3_GenuineIntel-3.5.4-64\lazylinker_ext\mod.cpp:1:0: sorry, unimplemented: 64-bit mode not compiled in
.

**Comment by rafaelvalle** [comment]
Do you have libraries compiled in 32 and 64 bits? Look at the last lines of
the error you posted:

Exception: Compilation failed (return status=1):
C:\Users\asus\AppData\Local\Theano\compiledir_Windows-10-
10.0.10586-SP0-Intel64_Family_6_Model_78_Stepping_3_GenuineIntel-3.5.4-64\lazylinker_ext\mod.cpp:1:0:
sorry, unimplemented: 64-bit mode not compiled in
.

**Comment by Alinadi23** [comment]
Yes, i installed by pip install theano. is that correct??
when i do it again i received this message:
C:\Windows\system32>pip install theano
Requirement already satisfied: theano in c:\program files\python35\lib\site-packages
Requirement already satisfied: six>=1.9.0 in c:\program files\python35\lib\site-packages (from theano)
Requirement already satisfied: scipy>=0.14 in c:\program files\python35\lib\site-packages (from theano)
Requirement already satisfied: numpy>=1.9.1 in c:\program files\python35\lib\site-packages (from theano)

**Comment by Alinadi23** [comment]
sorry, i did'nt get you exactly.
I'm glad if you can help me with this problem.
thank you

**Comment by rafaelvalle** [comment]
Try re-installing theano for 32 bits.

**Comment by Alinadi23** [comment]
Reinstall by pip install theano???
or there is another to that?

**Comment by rafaelvalle** [comment]
Check Google if there's a way to install a 32 bit version of theano with pip
