### ISSUE TITLE
unable to install Lasagne

### ISSUE THREAD

**Issue by aparnamhnty** [Lasagne/Lasagne#347]
Pip install -r https://raw.githubusercontent.com/Lasagne/Lasagne/master/requirements.txt

showing error

**Comment by benanne** [comment]
Please use the mailing list for support requests, this github issue queue is for development of the library and bug reports only. You can find it here: https://groups.google.com/forum/#!forum/lasagne-users

Also, it would be helpful to at least include the error message. Right now we have nothing to go on so we cannot help you.

**Comment by aparnamhnty** [comment]
![capture](https://cloud.githubusercontent.com/assets/9334941/8949661/aa28ff74-35d3-11e5-851f-10e22c3b994a.PNG)
This is a snapshot of the error i am getting.
As i am new to it can you please help me come out of this bug?

**Comment by f0k** [comment]
> As i am new to it can you please help me come out of this bug?

The last line says **Cannot find command "git"**. It means that git is not installed. The download link for Windows seems to be: https://git-scm.com/download/win. Install it and possibly adjust your path, such that `git --version` does not throw an error. Then try again.

Alternatively, install the bleeding-edge version of Lasagne as described in the [installation instructions](http://lasagne.readthedocs.org/en/latest/user/installation.html#bleeding-edge-version); it does not require git. It may be incompatible with Daniel's code, though (that's exactly why he's giving a particular git commit in his `requirements.txt`).

**Comment by aparnamhnty** [comment]
I now have this as the error:
![capture](https://cloud.githubusercontent.com/assets/9334941/8987339/42df6c46-36fe-11e5-9157-b4f0540eb509.PNG)

**Comment by f0k** [comment]
> **Failed to connect to github.com port 443: Connection refused**

Seems you are behind a proxy; this is outside our responsibility. You can try googling for a solution: https://www.google.at/search?q=Failed+to+connect+to+github.com+port+443%3A+Connection+refused

Otherwise I'd suggest you to try [installing the bleeding-edge version](http://lasagne.readthedocs.org/en/latest/user/installation.html#bleeding-edge-versions) of Theano and Lasagne. If it doesn't work, try switching `https` for `http`.

**Comment by aparnamhnty** [comment]
Thank you.......
could do it.........
