### ISSUE TITLE
Warning about use of Uniform appears even when GlorotUniform is being used.

### ISSUE THREAD

**Issue by peterderivaz** [Lasagne/Lasagne#352]
In lasagne/init.py line 86 there is a warnings.warn to ask the user to use GlorotUniform instead of Uniform.

However, if I do use GlorotUniform, then the warning still appears because GlorotUniform makes use of Uniform to prepare the weights.  Could the warning message be disabled somehow if Uniform is not being called directly perhaps?

**Comment by benanne** [comment]
I'm sure it could - not sure if it's worth the effort at this point as all those warnings will be removed before the final release, which has been imminent for a long time but should really be coming soon now :)
