### ISSUE TITLE
spatial transformer network layer

### ISSUE THREAD

**Issue by skaae** [Lasagne/Lasagne#355]
I wrote a spatial transformer network: https://github.com/skaae/transformer_network

Do you want it added to Lasagne? In that case i can clean it up a bit and try to come up with some tests?

**Comment by ebenolson** [comment]
I think it would be great. 

If you also felt like coding up a script/notebook for replication of the paper experiments, that would be an excellent start for https://github.com/Lasagne/Recipes/tree/master/papers

**Comment by f0k** [comment]
Cool! Just had a look at it -- I'd replace the `incomings` constructor argument by two arguments and then pass them as a list to the super constructor. That's easier than asking people to pass a list of two layers. Something like:
```python
class MyLayer(MergeLayer):
    def __init__(self, layerX, layerY, ..., **kwargs):
        super(MyLayer, self).__init__([layerX, layerY], **kwargs)
```

> Do you want it added to Lasagne?

Either that, or as a Recipe!

**Comment by benanne** [comment]
We should definitely add it as a Recipe at the very least. I'm okay with having it in the main library as well, lots of people probably want to experiment with this stuff.

What's the performance like? Seems to me like the `_transform` part would be an ideal candidate for a dramatic speedup with a custom CUDA kernel :) In fact, a fast differentiable affine transform is a primitive that would be useful to have in Theano itself.

**Comment by JeffreyDF** [comment]
@skaae Did you test your implementation on bigger input images as well? I have my own quick implementation and I remember that speeding it up for bigger images/grids was different from small images like MNIST (which makes sense). I haven't had time yet to test yours and compare it with my quick and dirty implementation.

**Comment by skaae** [comment]
@ebenolson: I think i did reproduce the results. The image on the repos frontpage is a spatial transformer layer coupled with a GRU. You can do that in "unmodified" lasagne as well. 

@f0k: Thats a good idea. 

@benanne: I think the speed is alright. I think the main slowdown is having to evaluate the extra localization conv net. Deepmind just released their implementation, I think they have cuda code?
The main work is in _interpolate(), but most of it is just indexing. 

@JeffreyDF: I tested in on sequences of cluttered mnist images which where 100x100. You get a fair speedup if you set the downsampling factor > 1. I tried to downsample with a factor 4. The output is then 25x25. It did not detoriate performance but seems to encourage the model to zoom in on the correct digit.

**Comment by JeffreyDF** [comment]
In my use case I used it with 512x512 images to zoom to 256x256. I think it was about 25% slower than just downsampling some 512x512 image to 256x256. For the released code, do you mean [this](https://github.com/qassemoquab/stnbhwd)?

**Comment by skaae** [comment]
25% is fine? 
Yes it's the correct code.

**Comment by benanne** [comment]
I don't think that code is from deepmind, it's just someone else's reimplementation. But it looks like they have CUDA code for the transformation operation, so if someone decides to do an optimised implementation for Theano this could be used as a basis.

**Comment by skaae** [comment]
PR: https://github.com/Lasagne/Lasagne/pull/361

**Comment by kshmelkov** [comment]
The corresponding PR was merged. The issue can be closed I guess?

**Comment by f0k** [comment]
Ah, thanks! I've been meaning to close it in the merge commit.

**Comment by zaizhongche** [comment]
Hello,I am a fresh man of torch. When I used the stn demo_minst, I have encountered a problem in torch, that is "/home/zczhou/stnbhwd/demo/Optim.lua:95: attempt to call method 'for_each' (a nil value) ; stack traceback: /home/zczhou/stnbhwd/demo/Optim.lua:95: in function '__init' "; Could you help me solve this problem ? Thank you very much!

**Comment by zaizhongche** [comment]
I have solved this problem,https://github.com/facebook/fbnn/issues/4
  thanks.
