### ISSUE TITLE
Allow (custom) recurrent layers to accept more than one feature dimension

### ISSUE THREAD

**Issue by craffel** [Lasagne/Lasagne#358]
As noted by @f0k here https://github.com/Lasagne/Lasagne/pull/294/files#r35102212, currently all the recurrent layers, including the `CustomRecurrentLayer`, squash the input past the third dimension.  The `CustomRecurrentLayer` doesn't need to do that; it should be able to accept N-D inputs and have, e.g., convolutional layers for its input-to-hidden and hidden-to-hidden connections.  I addressed that here: https://github.com/craffel/nntools/commit/1b55bbe9d910b7bc117040286ae0e6bc22053262 but it needs to be updated.  If and when there are more custom recurrent layer types #357, those should also be able to handle more-than-one-feature-dimension input.

**Comment by f0k** [comment]
:+1:
