### ISSUE TITLE
Suggestion for biases of forget gate in LSTM to be equal to 1 by default.

### ISSUE THREAD

**Issue by avostryakov** [Lasagne/Lasagne#368]
Reading "An Empirical Exploration of Recurrent Network Architectures"  (https://drive.google.com/file/d/0B9lktJxL9h23emRhcmFNYzAxUHc/view) I noticed one recommendation about Forget Gates Bias: "Importantly, adding a bias of size 1 significantly improved the performance of the LSTM on tasks where it fell behind the GRU and MUT1. Thus we recommend adding a bias of 1 to the forget gate of every LSTM in every application"

May it is a good idea do be a default setting for LSTM in Lasagne?

**Comment by skaae** [comment]
I'm fairly sure we discussed that somewhere and aggreed to keep the biases at 0. I can't remember in which issue/PR though. 

We have an example in the docs on how to initialize the bias to non-zero values: http://lasagne.readthedocs.org/en/latest/modules/layers/recurrent.html#lasagne.layers.Gate

**Comment by craffel** [comment]
We also have an example which demonstrates how to do this:
https://github.com/Lasagne/Lasagne/blob/master/lasagne/layers/recurrent.py#L534

Although it does seem to help in general, it's not standard practice, so I'd rather keep it default to 0 and joint point people in the right direction (as we are hopefully doing).

**Comment by avostryakov** [comment]
I see. Ok, feel free to close this issue.

**Comment by skaae** [comment]
@benanne: Can you close this issue?
