### ISSUE TITLE
is it possible to use a dense layer's output to initialize the hidden state and cell state of recurrent layer?

### ISSUE THREAD

**Issue by stephenjia** [Lasagne/Lasagne#370]
Hi, everyone
I am new to Lasagne. I want to train an RNN but want to initialize the hidden state and cell state of the recurrent layer with an MLP.
Is it possible to use a separate dense layer's output to initialize the hidden state and cell state of a recurrent layer in Lasagne? And parameters of this separate dense layer's parameter and other layers should be learned during training. Can you give me some tips?

Thanks a lot.
Xu

**Comment by f0k** [comment]
`hid_init` and `cell_init` can be Theano expressions, so you can set them to anything you want, including the output of an MLP. Note that the output shape of that MLP must be `(batch_size, num_rnn_units)`. You will need to build the MLP's output expressions before constructing the RNN:

```python
from lasagne.layers import InputLayer, DenseLayer, LSTMLayer
mlp = InputLayer(...)
mlp = DenseLayer(mlp, num_units=100)
mlp = DenseLayer(mlp, num_units=N)
mlp_out = lasagne.layers.get_output(mlp)
rnn = InputLayer(...)
rnn = LSTMLayer(rnn, num_units=N, hid_init=mlp_out, ...)
```

And for training, you will need to obtain the parameters of both networks:
```python
params = lasagne.layers.get_all_params(mlp, trainable=True) + lasagne.layers.get_all_params(rnn, trainable=True)
updates = lasagne.updates.nesterov_momentum(loss, params, ...)
```

----

In future, please post such questions on our mailing list instead: https://groups.google.com/forum/#!forum/lasagne-users
The github issue tracker is reserved for bug reports, feature requests and contributions.

**Comment by stephenjia** [comment]
Hi Jan,

Thanks a lot for your reply. It is very helpful. I will remember to post
such questions on google group.

Best,
Xu
