### ISSUE TITLE
Add bias to NonlinearityLayer

### ISSUE THREAD

**Issue by f0k** [Lasagne/Lasagne#378]
For building an auto-encoder via #373, it would be useful to be able to drag out not only the nonlinearity, but also the bias from a layer into a separate layer (so the `UnLayer`/`InverseLayer` can be built to not invert the nonlinearity and bias, but be followed by its own bias and nonlinearity).

We could either add a `BiasLayer` for that, or regard it as part of the `NonlinearityLayer`. I think it wouldn't hurt to add it to the latter.

To be useful for different purposes, the bias should broadcast over all but the second dimension by default (that would be reasonable for dense and convolutional layers), but also be customizable to broadcast over a set of given axes (as in my [`BatchNormLayer` implementation](https://gist.github.com/f0k/f1a6bd3c8585c400c190)). This would also partly address the use case mentioned in #249.

**Comment by benanne** [comment]
If we want that level of functionality wouldn't it be better to have a separate layer for it? Maybe just have a `BiasLayer` that also supports having a nonlinearity? That seems more natural to me than to complicate the `NonlinearityLayer` code for this.

**Comment by skaae** [comment]
I agree with Sander. I think its easier for the users to find the functionality if we have a separate `BiasLayer`. In either case i don't think it makes sense to have the nonlinearity in there.

**Comment by f0k** [comment]
Okay, maybe you're (both) right. Having a separate `BiasLayer` also allows you to move the bias past the nonlinearity, if you ever wanted to. I wouldn't give it a nonlinearity then, just a bias.

It's still a bit unclear where to put them. `dense.py` is not a good place, probably. Should it be moved to the upcoming `special.py` or is it not special-purpose enough for that?
