### ISSUE TITLE
Change theano.config.device.startswith("gpu") check

### ISSUE THREAD

**Issue by f0k** [Lasagne/Lasagne#379]
As discussed in https://groups.google.com/forum/#!topic/lasagne-users/AWbQ0vvJjrQ, the existing `theano.config.device.startswith("gpu")` checks are too strict -- Theano provides a second way to use a GPU, via `theano.sandbox.cuda.use`, and Lasagne wrongly prevents `lasagne.layers.dnn` to be imported in that case.

From https://groups.google.com/d/msg/lasagne-users/AWbQ0vvJjrQ/neQZc-vLBgAJ, it seems the most universal solution for now would be replacing it with `theano.sandbox.cuda.use.device_number >= 0`. We might want to check if there's a solution that also works in the new GPU backend, though.

In any case, this would require changes in the mocks for readthedocs as well.

**Comment by nouiz** [comment]
I think it would be better to use "theano.sandbox.cuda.cuda_enabled".

If we have initialized a GPU, but not enabled it, it should not be used by
default.

**Comment by f0k** [comment]
Nice, that seems to work fine as well, and looks less hackish than checking the device number.

```bash
$ THEANO_FLAGS=device=cpu python -c 'import theano.sandbox.cuda; print theano.sandbox.cuda.cuda_enabled'
False
$ THEANO_FLAGS=device=cpu python -c 'import theano.sandbox.cuda; theano.sandbox.cuda.use("gpu0"); print theano.sandbox.cuda.cuda_enabled'
Using gpu device 0: GeForce GT 640 (CNMeM is disabled)
True
$ THEANO_FLAGS=device=gpu python -c 'import theano.sandbox.cuda; print theano.sandbox.cuda.cuda_enabled'
Using gpu device 0: GeForce GT 640 (CNMeM is disabled)
True
```

Thanks for the hint!
