### ISSUE TITLE
Move this repository to an organization?

### ISSUE THREAD

**Issue by benanne** [Lasagne/Lasagne#38]
I created this repository on my personal GitHub account, but since this is a joint project, maybe it's better to create an organization and move this repository to it. Added benefits would be more granular access control (commit rights etc.).

Also I would just be able to submit pull requests like everyone else, instead of committing to the repo directly. Currently this is convenient because a lot of the 'base' library is still missing, but I probably don't want to make a habit out of this in the long term.

What do you guys think?

If we decide to do this, it would be a good time to change the name as well (if we're going to do that, see #3), so we only have to update configurations once.

**Comment by benanne** [comment]
I'm reopening this, as @avdnoord mentioned in #74 it might be a good idea to move this repository to an organization before we put out the first release. What are everyone's current thoughts on this?

**Comment by craffel** [comment]
I think either is fine; making an organization makes it seem slightly more official in a superficial way.

**Comment by f0k** [comment]
> What are everyone's current thoughts on this?

My thoughts are the same as before:
> It's mainly a question of how you want to present it to the outside: as a project of yours with a couple of contributions from others (= personal account), or as a joint project with you being one of the core maintainers (= organization account)?

**Comment by benanne** [comment]
The latter is a bit more accurate :) Even if it doesn't make much of a difference in practice, it does look a bit more "professional" I suppose.

If nobody has any objections to this, I'll look into it.

**Comment by benanne** [comment]
So, let's do this. I know @f0k was joking about the organization name vote earlier, but it turns out 'Lasagne' is already taken :p So what should we use instead?

**Comment by craffel** [comment]
lasagne_chefs? pasta_chefs?

**Comment by avdnoord** [comment]
Deep_Learning_Jedis_from_Napoli

**Comment by ebattenberg** [comment]
"Layered" is available.  As is "nntools".  I like "Layered" as a kind of abstract name.

Layered/Lasagne
nntools/Lasagne

@benanne Are there other projects that could eventually fit under this organization?  If so, what sort of common theme would be good to express in the organization name?

**Comment by benanne** [comment]
No idea. I guess we can go with something generic to take that into account. I like 'pasta_chefs', or something similarly clever :p

**Comment by bmcfee** [comment]
ChefBoyardeep?

I'll show myself out.

**Comment by f0k** [comment]
I like "Layered", or some other adjective. "Greasy". "Tasty". "Delicious". Ah, they're all taken. Maybe a generic Italian restaurant name? "Ristorante", "Milano", "Pizzeria", "Pastaria", all taken. The alleged origin of Lasagne? "Naples", "Napoli", taken.
"Moms/Lasagne" is free, but would limit side projects to food items. "Hot/Lasagne" would have been free a month ago. "Zazastyle/Lasagne" is free, but only two others know that reference ;)

> Are there other projects that could eventually fit under this organization? If so, what sort of common theme would be good to express in the organization name?

I'm thinking about publishing my dataset iteration library under the name "spoon", and my neural network experiment framework under the name "pastaria". But that will probably stay in my personal account unless there's sufficient interest.

Given how active that lasagne account is, we can also try convincing that user to choose another name to help a promising open source project :)

> ChefBoyardeep?

It has deep in it! (I was completely unaware of that brand, though.)

**Comment by f0k** [comment]
> we can also try convincing that user to choose another name to help a promising open source project :)

Unfortunately, there is no way to email a github user.

@lasagne, if you read this, we're developing a deep neural network library called "Lasagne" (because it has many layers, just like an artificial neural network). It's currently hosted under a personal github account and we want to move it to an organization account. Unfortunately, github.com/lasagne is already taken. Would you be willing to change your github user name so that we can use it for our project? We'd be eternally grateful, and I'd invite you for a beer and lasagne!

**Comment by bmcfee** [comment]
It's worth noting that github will occasionally forfeit inactive accounts, if they haven't touched the site in too long.  If that user's really inactive, you might just ask for the name and see what happens.

**Comment by craffel** [comment]
> "Zazastyle/Lasagne" 

:grinning:

**Comment by f0k** [comment]
"[Trattoria](http://en.wikipedia.org/wiki/Trattoria)" is free, as is "[Osteria](http://en.wikipedia.org/wiki/Osteria)".

**Comment by benanne** [comment]
Trattoria is great, it has my vote :+1:

**Comment by avdnoord** [comment]
+1 for Trattoria :)

**Comment by craffel** [comment]
> Trattoria is great, it has my vote :+1: 

In this case, we would have to name all of our projects after pasta dishes.  Maybe "spaghetti" would be a reservoir network library?  I'm down.

**Comment by f0k** [comment]
> In this case, we would have to name all of our projects after pasta dishes.

It actually still leaves a lot of freedom!

> Maybe "spaghetti" would be a reservoir network library? I'm down.

:) You could also have "decanter" for liquid state networks, and "tablecloth" or "menu" for a point-and-click network design GUI. My dataset iteration library "spoon" would fit as well.

The only downside is that it's a little more difficult to remember than "Layered/Lasagne" or just "Lasagne/Lasagne". Let's give @lasagne a little time to reply, then ask github directly, and then decide.

**Comment by ebattenberg** [comment]
> 'm thinking about publishing my dataset iteration library under the name "spoon", and my neural network experiment framework under the name "pastaria". But that will probably stay in my personal account unless there's sufficient interest.

Nice.  My tools that run on top of Lasagne are currently called "parmesan".  :)

I like Trattoria.  And ChefBoyardeep is excellent.  As would be zazastyle.  :P

**Comment by f0k** [comment]
> My tools that run on top of Lasagne are currently called "parmesan". :)

Nice one. We have some creative minds here, I see :)

By the way, Zà Zà calls itself a Trattoria, that's a free extra reference. If we go for that, I need to come up with a project called "custard".

**Comment by MartinThoma** [comment]
Although I like many of the ideas (such as parmesan, @ebattenberg :-) ), I think using the organization name "Lasagne" would be the best option. This way people know what the organization is about and new developers find the organization.

It seems as if it got free. I cached it and invited @benanne. I will transfer admin rights / ownership to you, if this is possible. As a first step I invited you to https://github.com/Lasagne

**Comment by benanne** [comment]
Awesome, Thanks! Looks like it shouldn't be a problem to transfer it: https://help.github.com/articles/transferring-organization-ownership/

**Comment by MartinThoma** [comment]
Ok, it looks as if you are already an owner. If it is ok for you, I would like to stay in the organization.

**Comment by MartinThoma** [comment]
The next step would be to transfer the Lasagne repository to the Lasagne organization:
https://help.github.com/articles/transferring-a-repository/
and to invite people to the organization.

**Comment by benanne** [comment]
To be honest I'm not really comfortable with giving any kind of administration rights to anyone outside the core development team at this time. Why would you like to stay in the organisation?

**Comment by MartinThoma** [comment]
Ok, I kicked myself out of the "owners" group, but I am still in the "developers" group.

I would like to stay in the organization, because I want to contribute to the project (at first mainly with examples and documentation, later with tests and then, eventually with code). I think making a pull request for simple changes in examples / docstrings / documentation texts where nothing can break is overhead which can be removed.

Also, I like to stay in the organization group because I really like the project. I used a toolkit which was developed at KIT for my bachelors thesis. I am not allowed to make the source code of this internally developed tool (which is also based on Theano) public, so I wanted to to write my own (https://github.com/MartinThoma/nntoolkit - only evaluation works, when you already have a neural network, which makes it pretty much useless. I stopped the development quite early at my toolkit, because I had a matrix shape problem and I didn't figure out where that came from.). I think I can use Lasagne and make my `nntoolkit` a (bash)-wrapper for it, which is pretty cool :-)

So, I don't have any important reason to stay in the developer team in the organization. If you don't feel comfortable with me being there I will quit from it, too, and continue making pull requests.

**Comment by benanne** [comment]
I appreciate your enthusiasm and your contributions so far, but I don't think it makes sense to give some contributors more rights than others. I think the pull request is an excellent 'interface' by which people can contribute code, and it doesn't really make sense to allow certain people to bypass that. It does add a little overhead for smaller changes, but it's not excessive (I usually merge PRs with bugfixes / typo fixes within 24 hours). No disrespect to you, but I'm also uncomfortable with the idea of other people that I don't know very well being able to commit code to the project or administer it without any form of supervision.

In the long term it is probably a good idea to expand the core development team with some of the main contributors, but I think it's a little too early for that :)

**Comment by MartinThoma** [comment]
Ok, no problem. I am not not a member of the organization any more.

**Comment by MartinThoma** [comment]
And thanks for being so kind not to kick me, but to discuss this, explaining me the reasons and letting me do it myself. I appreciate that :-)

**Comment by benanne** [comment]
Thanks, I appreciate your understanding!

**Comment by benanne** [comment]
Looks like everyone will have to change the remote URL of their clones when the repository is transfered, else you can no longer open PRs: https://help.github.com/articles/transferring-a-repository/

So I think I'll hold off for another day or so, until we have fewer pending PRs (there are 6 right now).

**Comment by f0k** [comment]
OK great, thanks for catching that name, Martin! Seems that user reacted on being mentioned, but turned down my offer for beer and lasagna. Anyway, thanks a lot, dear former github user :)

> Looks like everyone will have to change the remote URL of their clones when the repository is transfered

There's another catch: When you fork back the repository to your own account, the redirects from benanne/Lasagne to Lasagne/Lasagne will stop working. Maybe you should hold off with forking for some time after the transfer as well.

**Comment by benanne** [comment]
Good point. I probably don't need to fork it anytime soon though, I can just keep creating my PR branches on the main repo for now. But in the long term forking it is probably cleaner.

**Comment by MartinThoma** [comment]
Eventually it would be a good idea to transfer the repository when Lasagne reaches 1.0?

**Comment by f0k** [comment]
> I can just keep creating my PR branches on the main repo for now

Exactly. That would be good.

> Eventually it would be a good idea to transfer the repository when Lasagne reaches 1.0?

No, we need to transfer it before we release 0.1. URLs shouldn't change afterwards (especially as the benanne/Lasagne URLs will end up pointing to Sander's development fork after a while).

**Comment by ebenolson** [comment]
When this happens I'd suggest renaming the repo to `lasagne` (lowercase). Obviously not very important but it is a minor annoyance when trying to tab complete.

**Comment by craffel** [comment]
> When this happens I'd suggest renaming the repo to lasagne (lowercase). Obviously not very important but it is a minor annoyance when trying to tab complete.

:+1:

**Comment by bmcfee** [comment]
:+1: :heavy_multiplication_x:  :100:

**Comment by benanne** [comment]
The reason we went with a capital for the repository name is basically to follow the Theano convention of having the name of the library be capitalized, but not the Python module. I'm not sure if there's a huge advantage to that though.

Moving the repository to an organisation and renaming it will be two separate operations though. I hope everything stays "linked" so the old URLs still work if we do that.

**Comment by craffel** [comment]
> The reason we went with a capital for the repository name is basically to follow the Theano convention

Yeah, the thing is that Theano is the only python module I can think off the top of my head which does it this way.  Virtually every other one I know uses the module name (i.e., what you import) as the repo name.  Sort of nitpicky and offtopic but it would def be cool to have the repo name "lasagne".

**Comment by benanne** [comment]
Sure, I don't care either way so I'm okay with changing it. Just a little worried that it might affect "backwards compatibility" with the current repo URLs, because of the chained redirects.

**Comment by craffel** [comment]
>Just a little worried that it might affect "backwards compatibility" with the current repo URLs, because of the chained redirects.

If it does we can complain to github and they'll fix it, or we'll take our (non-revenue-generating) business elsewhere, damnit!

**Comment by MartinThoma** [comment]
:+1: for the idea of moving to an `lasagne` repository.

> If it does we can complain to github and they'll fix it, or we'll take our (non-revenue-generating) business elsewhere, damnit!

Wooo... hold your horses! I guess moving to another site will cause more issues.

**Comment by craffel** [comment]
> Wooo... hold your horses! I guess moving to another site will cause more issues.

Kidding there.  No reason to leave Github.

**Comment by f0k** [comment]
So we're finally voting on the capitalization. [Quoting @dnouri](https://github.com/benanne/Lasagne/issues/56#issuecomment-66832480):
> I like project names that start with capital letters, so Lasagne. Package name definitely lower-case. I have a feeling we don't need another vote there. ;-)

Well, it had to come to this :) I prefer Lasagne, and I don't understand the tab completion issue (@ebenolson?), but I don't feel strongly about the capital L. Maybe it's just the language I grew up with.

**Comment by ebenolson** [comment]
Wait a minute, is this the same dnouri, author of https://github.com/dnouri/nolearn? :)

It sounds silly but that little effort of moving my pinky from shift to tab when typing the path gets annoying. I also seem to mess it up on the first try half the time, possibly because I think a capitalized repo is unusual, at least for python projects.

**Comment by benanne** [comment]
As I said I don't really care either way, and I guess now is a good time to change it if we do want to change it, but I do feel that we're giving a little too much thought to a minor issue like this when we have bigger fish to fry.

I've noticed this tendency to focus on and extensively discuss the small things that are 'easy' to tackle in the GitHub issues. If we're still aiming for a late April release, we have a lot of work to do in the next few weeks and we should shift our focus to the big stuff (i.e. documentation).

So far most people either seem to be in favour of losing the capital or don't care either way, so let's wrap this up with a decision ASAP. If anyone has objections to getting rid of the capital, please voice them in the next 24 hours, otherwise we're getting rid of it.

**Comment by dnouri** [comment]
FWIW, the repo name is case insensitive, so you can type lasagne with a lower 'l' and it'll already work.

**Comment by benanne** [comment]
The original issue was that tab completion doesn't work properly right? In what context is that? I'm trying to understand what problem this solves exactly because I think I haven't fully understood yet. If it's fairly minor it's probably not worth the risk of breaking redirects of old URLs. The original issue was tab completion which seems like a minor inconvenience. Broken URLs will affect a lot more people.

**Comment by ebenolson** [comment]
Like dnouri said, github URLs are case insensitive so I don't see why that would be a problem.

I'm talking about tab completion when working on the project from the command line. e.g.

    nano ~/projects/Lasagne/lasagne/layers/pool.py

With the capital, I need to move my finger off of tab and there's a good chance I will forget and need multiple tries to type it.

It is absolutely a minor thing, but I think there's a reason most stuff in linux sticks to lowercase.

**Comment by f0k** [comment]
> The original issue was that tab completion doesn't work properly right? In what context is that? I'm trying to understand what problem this solves exactly because I think I haven't fully understood yet.

Me neither. I asked @ebenolson, and he said:
> It sounds silly but that little effort of moving my pinky from shift to tab when typing the path gets annoying.

In case the discussion isn't absurd enough by now, I'll just add that a) you can use your ring finger to do tab completion so your pinky can stay on shift nevertheless, b) there's a second shift key on the right that's much closer to the L key and c) there's no practical reason to name your clone directory `Lasagne` if that's impractical for your pinky, this is fully independent of the repository name on github.

I don't know if @craffel and @bmcfee voted for the same reason as @ebenolson, though.

> I've noticed this tendency to focus on and extensively discuss the small things that are 'easy' to tackle in the GitHub issues.

:exclamation:

**Comment by ebenolson** [comment]
I sparked this discussion with a two sentence comment suggesting a 5 second change to fix a minor usability issue.

I don't suggest things here for my personal convenience (I renamed my clone long ago), but because I think they will improve the project for others, in however minor a way. 

You may find it absurd, but there is a reason every linux command is lowercase, and the vast majority of Python projects use a lowercase name.

>>I've noticed this tendency to focus on and extensively discuss the small things that are 'easy' to tackle in the GitHub issues.
>:exclamation:

:+1:

**Comment by f0k** [comment]
> You may find it absurd, but there is a reason every linux command is lowercase, and the vast majority of Python projects use a lowercase name.

I don't think this is the reason. And sorry if I was a bit harsh, I like your work and didn't mean to offend you. It's just that I like the uppercase `L` and found that there should be a better argument for changing it... after all, you can just rename your directory locally!

**Comment by ebenolson** [comment]
Sorry if I got a bit upset, just trying to clarify that making a big deal out of this was never my intention.

 A strong preference for the `L` is a completely valid reason to keep it.

**Comment by ebattenberg** [comment]
Just came here to vote for lowercase "lasagne" as the organization and repo name.  Just personal preference.

**Comment by benanne** [comment]
I'm not convinced that it's worth changing. Theano has done fine with a capital and I personally think it looks better for the name of the library to be capitalized as well (even though my native language does not have noun capitalization).

I guess I'll just make this decision official at this point so we can put an end to this discussion and start focusing on more useful stuff. I'll move the repo to the Lasagne organisation tomorrow.

**Comment by ebattenberg** [comment]
There's nothing inherently wrong with the capitalization (maybe just the extra shift key as mentioned above).  It's just an eyesore to me since all github projects and organizations and usernames (except Theano) are lowercase.  However, everyone still capitalizes the project name in the README.md and formatted header/title.

**Comment by benanne** [comment]
I have moved this repository to the Lasagne organisation. It looks like all redirects are working correctly, even from benanne/nntools, which is nice. Travis and readthedocs may act up a little (I think there was a small issue when we went from nntools to Lasagne) but I'll keep an eye on them.

I have also given @f0k full admin rights for the organisation, since he is actively reviewing PRs and contributing a lot of code. This should further streamline things a bit :)

**Comment by f0k** [comment]
> I have moved this repository to the Lasagne organisation.

Cool, I haven't even noticed, but yes, my address bar displays a new URL :)

Thank you for the admin rights, but I guess I'll still leave most merging to you. Let's see how things develop!
