### ISSUE TITLE
Nonlinearities as arbitrary Theano expressions

### ISSUE THREAD

**Issue by craffel** [Lasagne/Lasagne#384]
Hi, perhaps this is already widely known, but it recently occurred to me that nonlinearities are a somewhat hackish way to introduce arbitrary Theano expressions into your network graph.  In particular, the NonlinearityLayer can be used to compute any sort of theano expression you want between two layers; e.g. in this questionable use-case:

```Python
l_in = lasagne.layers.InputLayer((2, 3))
l_print = lasagne.layers.NonlinearityLayer(
    l_in, nonlinearity=lambda x: theano.printing.Print('x: ')(x))
out = lasagne.layers.get_output(l_print)
compute_out = theano.function([l_in.input_var], out)
compute_out(np.array([[1, 2, 3], [4, 5, 6]], dtype=theano.config.floatX))
```

will result in this being printed out:

```
x:  __str__ = [[ 1.  2.  3.]
 [ 4.  5.  6.]]
```

This is true for any layer with a nonlinearity; here we are printing and using a Tanh nonlinearity both:

```Python
l_in = lasagne.layers.InputLayer((2, 3))
l_out = lasagne.layers.DenseLayer(
    l_in, 4, nonlinearity=lambda x: theano.printing.Print('x: ')(T.tanh(x)))
out = lasagne.layers.get_output(l_out)
compute_out = theano.function([l_in.input_var], out)
compute_out(np.array([[1, 2, 3], [4, 5, 6]], dtype=theano.config.floatX))
```

If this is something we'd like to encourage, I'd suggest putting it in an FAQ list #298 somewhere under "How can I include arbitrary calculations in Lasagne networks?" and maybe even making an alias for NonlinearityLayer called ExpressionLayer (or something) with self.nonlinearity renamed self.expression.  Note that you can also do this in a maybe less hacky but a bit more cumbersome way by calling `lasagne.layers.get_output`, modifying the resulting Theano expression, and using it as the input variable to a new `InputLayer` that then feeds the rest of your network.

**Comment by f0k** [comment]
Could be something for the (still-not-existing) FAQ, yes! Note that this technique has two shortcomings:

1. It only works for expressions that return a same-shaped output
2. If you use lambda expressions, the resulting network isn't pickable any more

This being said, it may still be useful to quickly try something without having to define a layer (which isn't a big deal either, but takes three lines more):
```python
class PrintTanhLayer(Layer):
    def get_output_for(self, input, **kwargs):
        return theano.printing.Print('x :')(T.tanh(input))
```

**Comment by craffel** [comment]
> It only works for expressions that result in a same-shaped output

True, true.

> If you use lambda expressions, the resulting network isn't pickable any more

Of course.

> This being said, it may still be useful to quickly try something without having to define a layer (which isn't a big deal either, but takes three lines more):

Yes, less of a hack, probably more recommendable.  How about in one (horrifyingly ugly) line more?

```Python
l_in = lasagne.layers.InputLayer((2, 3))
l_print = lasagne.layers.Layer(l_in)
l_print.get_output_for = lambda x, **kwargs: theano.printing.Print('x :')(T.tanh(x))
out = lasagne.layers.get_output(l_print)
...
```

**Comment by craffel** [comment]
(Oops, somehow my comment got deleted)

> It only works for expressions that result in a same-shaped output

True, true.

> If you use lambda expressions, the resulting network isn't pickable any more

Of course.

> This being said, it may still be useful to quickly try something without having to define a layer (which isn't a big deal either, but takes three lines more):

Yes, this is probably more recommendable.  But, how about doing it in one (horrifyingly ugly) line more?

```Python
l_print = lasagne.layers.Layer(l_in)
l_print.get_output_for = lambda x, **kwargs: theano.printing.Print('x :')(T.tanh(x))
out = lasagne.layers.get_output(l_print)
compute_out = theano.function([l_in.input_var], out)
compute_out(np.array([[1, 2, 3], [4, 5, 6]], dtype=theano.config.floatX))
```

**Comment by f0k** [comment]
> How about in one (horrifyingly ugly) line more?

Yes, but that doesn't help anything, does it? The only addition we could make to support such kind of rapid prototyping would be a layer that takes a `get_output_for()` and a `get_output_shape_for()` function in its constructor (with the second being optional). While that functionality would be very similar to `NonlinearityLayer` (plus supporting to change the shape), we can't really merge it with that one because `NonlinearityLayer` must have a `nonlinearity` member.

**Comment by craffel** [comment]
> Yes, but that doesn't help anything, does it?

What do you mean? It works with Lasagne as it currently is, and is valid (ugly) Python code.

**Comment by f0k** [comment]
> What do you mean?

I mean that it doesn't solve any of the problems that `NonlinearityLayer(..., nonlinearity=lambda ...: ...)` has; it's virtually the same (except that it shows a way to also override the shape propagation).

**Comment by craffel** [comment]
> I mean that it doesn't solve any of the problems that NonlinearityLayer(..., nonlinearity=lambda ...: ...) has; it's virtually the same (except that it shows a way to also override the shape propagation).

Sorry, yes, the point (in jest) was that it was a shorter way to do this:
```Python
class PrintTanhLayer(Layer):
    def get_output_for(self, input, **kwargs):
        return theano.printing.Print('x :')(T.tanh(input))
```
