### ISSUE TITLE
Inverse Layer update problem with Conv1DLayer stride > 1

### ISSUE THREAD

**Issue by fmder** [Lasagne/Lasagne#398]
I advice that I might have overlooked something, but the following error comes out when using a stride greater than 1 in a 1D ConvolutionLayer followed by an inverse layer (I haven't tried 2D).

    ValueError: ('You cannot drop a non-broadcastable dimension.', ((False, False, False, False, False), (0, 4, 1, 2)))

The minimal code to reproduce the error is available in the following gist: https://gist.github.com/fmder/de72992071a12ddf4c68

**Comment by f0k** [comment]
Thanks for reporting! I don't have the time to look into this right now, but in case this is a bug in Theano, you might be able to get rid of it by using a `Conv2DDNNLayer` instead, on input data of shape `(batch_size, 1, 32, 32)`, using a filter size of `(1, 3)` and a stride of `(1, 2)`. For strided convolution, Theano will currently use a legacy implementation for the gradient* (and thus the forward pass of the `InverseLayer`), and maybe that implementation has a broken gradient (for the backward pass of the `InverseLayer`).

* That was supposed to be fixed a long time ago in https://github.com/Theano/Theano/pull/2665, but it seems nobody's working on that any more -- ah wait, the original author seems to just have started on it again.

**Comment by akshay13ml** [comment]
I get the same error with Conv2D:

```
File "/usr/local/lib/python2.7/dist-packages/theano/tensor/elemwise.py", line 163, in __init__
    (input_broadcastable, new_order))

ValueError: ('You cannot drop a non-broadcastable dimension.', ((False, False, False, False, False), (0, 4, 1, 2)))
```

The line generating the error is:
```
lasagne.layers.Conv2DLayer(netC_0,num_filters=32,filter_size=(8,8),pad="valid",stride=(2,2),nonlinearity=None, name="conv1")
``` 

This error only appears with stride > 1

**Comment by f0k** [comment]
Did you try using `lasagne.layers.dnn.Conv2DDNNLayer` or `lasagne.layers.corrmm.Conv2DMMLayer` instead? I still think the error will disappear with https://github.com/Theano/Theano/pull/2665, and until then enforcing one of the other convolution implementations will be the best workaround. If it doesn't solve the problem, and you're using the bleeding-edge version of Lasagne and Theano, then we can investigate and file a Theano issue.

**Comment by akshay13ml** [comment]
I saw that https://github.com/Theano/Theano/pull/2665 has been merged - I updated to the latest Theano and Lasagne code but the error with InverseLayer for strided convolutions still persist.

With  lasagne.layers.Conv2DLayer :
('You cannot drop a non-broadcastable dimension.', ((False, False, False, False, False), (0, 4, 1, 2)))

Works fine with Conv2DDNNLayer and  Conv2DMMLayer as you suggested.

**Comment by f0k** [comment]
> I updated to the latest Theano and Lasagne code but the error with InverseLayer for strided convolutions still persist.

Thanks for reporting! #2665 didn't replace `theano.tensor.nnet.conv2d` as I had expected, but added the new interface under a different name. They're planning to transition to using the new interface later (https://github.com/Theano/Theano/issues/3557) -- only then the issue will magically disappear.

> Works fine with Conv2DDNNLayer and Conv2DMMLayer as you suggested.

That's good! I'll close the issue as it's going to be solved upstream (in Theano) and we can't really do anything about it in Lasagne.
