### ISSUE TITLE
Rename floatX to as_floatX

### ISSUE THREAD

**Issue by superbobry** [Lasagne/Lasagne#403]
The latter allows to distinguish it from the actual type in `theano.config`. What do you think?

**Comment by dnouri** [comment]
Namespaces allow `theano.config.floatX` and `lasagne.utils.floatX` to be different things.  I wonder how confusing it is really.

**Comment by superbobry** [comment]
Indeed they do. I wonder how often do people use fully qualified names for both of the `floatX`?

**Comment by dnouri** [comment]
FWIW, the Theano tutorial seems to be using `config.floatX` or `theano.config.floatX` throughout: http://deeplearning.net/software/theano/tutorial/using_gpu.html

**Comment by f0k** [comment]
It's too late to rename because people might rely on it, we could just add an alias. I usually use fully-qualified names for both, or do something like `floatX = theano.config.floatX` if I need it a lot in a particular function.

**Comment by superbobry** [comment]
I see, thank you. It does seem a bit too late for renaming and if one really wants it, there's always `import floatX as as_floatX` :)

Closing the issue.
