### ISSUE TITLE
"pip search lasagne" gives no results

### ISSUE THREAD

**Issue by MartinThoma** [Lasagne/Lasagne#406]
I thought it would now be possible to install Lasagne with pip. But `pip search lasagne`, `pip3 search lasagne`, `pip search Lasagne`, `pip3 search Lasagne` all give no result.

I have `pip 7.1.2`.

Does anybody know the reason?

**Comment by ebenolson** [comment]
I think it is a PyPi issue: https://bitbucket.org/pypa/pypi/issues/326/some-packages-not-showing-up-when

`pip install lasagne` works for me.

**Comment by Jenzzz** [comment]
$ pip install lasagne works for me too :)

**Comment by bmckown** [comment]
Using pip version 7.1.2 and python 2.7.10, `pip search lasagne` returns correct results for me as well.

**Comment by benanne** [comment]
Sweet! works for me as well, so I'll close this.

**Comment by MartinThoma** [comment]
Just for the record: It seems to work for me, too

```bash
$ pip search lasagne
Lasagne                   - A lightweight library to build and train neural networks in Theano
  INSTALLED: 0.1.dev0
  LATEST:    0.1
$ pip --version
pip 1.5.6 from /usr/lib/python2.7/dist-packages (python 2.7)
$ pip3 search lasagne
Lasagne     - A lightweight library to build and train neural networks in Theano
  INSTALLED: 0.1.dev0
  LATEST:    0.1
$ pip3 --version
pip 7.1.2 from /usr/local/lib/python3.4/dist-packages (python 3.4)
```
