### ISSUE TITLE
Latest update GPU compilation errors (No valid section marker was found in file error)

### ISSUE THREAD

**Issue by JesseBuesking** [Lasagne/Lasagne#413]
I updated Lasagne (and in turn Theano) in order to get access to ``lasagne.random`` but in doing so it appears there's an issue, which may or may not be with Theano.

I followed the [installation instructions](http://lasagne.readthedocs.org/en/latest/user/installation.html#stable-lasagne-release), but now when running the Mnist example I receive a bunch of compilation errors, like the following:

```
Using gpu device 0: GeForce GTX 750 Ti (CNMeM is disabled)
Loading data...
Building model and compiling functions...
ERROR (theano.gof.opt): Optimization failure due to: LocalOptGroup(local_conv_dnn,local_conv_gemm)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/opt.py", line 1484, in process_node
    replacements = lopt.transform(node)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/opt.py", line 994, in transform
    repl = opt.transform(node)
  File "/usr/local/lib/python2.7/dist-packages/theano/sandbox/cuda/dnn.py", line 2035, in local_conv_dnn
    direction_hint=direction_hint)
  File "/usr/local/lib/python2.7/dist-packages/theano/sandbox/cuda/dnn.py", line 1197, in dnn_conv
    return GpuDnnConv(algo=algo)(img, kerns, out, desc)
ERROR (theano.gof.opt): Optimization failure due to: LocalOptGroup(local_conv_dnn,local_conv_gemm)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/opt.py", line 1484, in process_node
    replacements = lopt.transform(node)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/opt.py", line 994, in transform
    repl = opt.transform(node)
  File "/usr/local/lib/python2.7/dist-packages/theano/sandbox/cuda/dnn.py", line 2035, in local_conv_dnn
    direction_hint=direction_hint)
  File "/usr/local/lib/python2.7/dist-packages/theano/sandbox/cuda/dnn.py", line 1197, in dnn_conv
    return GpuDnnConv(algo=algo)(img, kerns, out, desc)
  File "/usr/local/lib/python2.7/dist-packages/theano/sandbox/cuda/dnn.py", line 431, in __init__
    "APPLY_SPECIFIC(conv_fwd)")
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 1099, in __init__
    self.load_c_code()
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 1174, in load_c_code
    "%s" % self.func_files[i])
ValueError: No valid section marker was found in file /usr/local/lib/python2.7/dist-packages/theano/sandbox/cuda/dnn_base.c
...
```

The errors continue, each of which appears to result in the same ```ValueError: No valid section marker was found in file``` error.

I've tried reverting the Theano version, but then I see a previous issue (https://github.com/Lasagne/Lasagne/issues/339).

I also attempted to update cuda itself from 7.0 to 7.5, but the issue persists.

GPU code does continue to work, however the Mnist network I was running before which took ~8s per epoch now takes ~30s per epoch, so it appears that GPU optimizations are failing (as noted by the error above ```ERROR (theano.gof.opt): Optimization failure due to...```).

Additional info:
```
>> nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Tue_Aug_11_14:27:32_CDT_2015
Cuda compilation tools, release 7.5, V7.5.17
>> python -c "import theano; print(theano.__version__)"
Using gpu device 0: GeForce GTX 750 Ti (CNMeM is disabled)
0.7.0.dev-15c90dd36c95ea2989a2c0085399147d15a6a477
>> python -c "import lasagne; print(lasagne.__version__)"
Using gpu device 0: GeForce GTX 750 Ti (CNMeM is disabled)
0.1
>> python -c "import theano; print theano.sandbox.cuda.dnn.dnn_available() or theano.sandbox.cuda.dnn.dnn_available.msg"
Using gpu device 0: GeForce GTX 750 Ti (CNMeM is disabled)
True
```

Please let me know if there's any additional information needed.

**Comment by benanne** [comment]
Please use the mailing list for support requests: https://groups.google.com/forum/#!forum/lasagne-users
We would like to keep the github issues focused on development.

It sounds like there might be a cudnn-related version conflict. Have you treid clearing your Theano cache? You can do this by running `theano-cache purge`.

**Comment by JesseBuesking** [comment]
Sorry for posting in the wrong location. If you want we can move this over to google groups or just keep this here.

I tried purging like you suggested, but the error persists.

Previously I was copying the cudnn files into my cuda install directory, but I just removed the files and put them in a separate directory so that I can control whether the cudnn files are included using my ``.bashrc`` file. By temporarily removing them from all the required paths and disabling the ``optimizer_including=cudnn`` I was able to see if the error was caused by cudnn, and it is indeed.  I'm still at a loss for why it's happening now when it wasn't on my previous Theano install, but I can at least get optimizations compiling again.

If you have any other ideas of things to try, please let me know.

**Comment by benanne** [comment]
Are you sure you moved/removed everything? This sounds like a classic cudnn version mixing error. Maybe it's still using header files from a previous version and the library files from the new version, or vice versa.

**Comment by JesseBuesking** [comment]
Here's a rough outline of what I did:
  1. Uninstalled cuda.
  2. Removed the lingering ``/usr/local/cuda-7.0`` directory from before the upgrade.
  3. Removed the remaining ``/usr/local/cuda-7.5`` directory and it's contents which included the copied cudnn files. I did this since doing an uninstall left the directory behind which still contained the cudnn files.
  4. Reinstalled cuda which recreated the ``/usr/local/cuda-7.5`` directory.
  5. Copied the cudnn files to ``/usr/local/cudnn-7.0`` (where I'm choosing to keep them).
  6. Updated my ``.bashrc`` file to pull from both ``/usr/local/cuda-7.5`` and ``/usr/local/cudnn-7.0``.

How could I go about confirming the filepath to the header files and library files being used? Determining this would rule out the issue you're mentioning, but I'm unsure of how to other than confirming the paths being appended in my ``.bashrc`` by echoing the environment variables. My environment variables for ``PATH``, ``LD_LIBRARY_PATH``, ``LIBRARY_PATH`` all point to ``/usr/local/cuda`` (soft link to ``/usr/local/cuda-7.5``) and ``/usr/local/cudnn-7.0``.

**Comment by f0k** [comment]
Some other things to try:

1. `rm -r ~/.theano/compiledir*`
2. `sudo ldconfig`
3. Make sure that `PATH=/usr/local/cuda/bin`, `LD_LIBRARY_PATH=/usr/local/cuda/lib64:/usr/local/cudnn-7.0/lib64`, `CPATH=/usr/local/cudnn-7.0/include`
4. `locate */cudnn.h` to check if you don't have a second copy somewhere (or `find / -name cudnn.h`)

**Comment by JesseBuesking** [comment]
@f0k I tried / verified the things you mentioned, but still no luck.

One thing to note, using the cuda_convnet ``Conv2DCCLayer`` instead of the ``Conv2DLayer`` results in no errors. I believe that's because it's copying a pre-optimized layer in place of generating the code and optimizing itself via Theano, but correct me if I'm wrong.

**Comment by nouiz** [comment]
I recall an error that could be this one that got fixed already some times
ago in Theano. Are you sure you have that with the development version of
Theano? Can you uninstall THeano multiple time to be sure there is only one
installed and reinstall the dev version of Theano?

**Comment by f0k** [comment]
> One thing to note, using the cuda_convnet Conv2DCCLayer instead of the Conv2DLayer results in no errors.

Sure, because cuda_convnet is not cuDNN. You'll probably see the same error with `Conv2DDNNLayer`.

**Comment by JesseBuesking** [comment]
@nouiz I will attempt to uninstall and reinstall the dev version of Theano in a few days when I get some time and report back.

Also, thank you everyone who is helping me try to fix this issue!

**Comment by JesseBuesking** [comment]
@nouiz I just gave it a go, but still no luck.

```
>> sudo pip uninstall theano
>> sudo find / -iname *theano*
/usr/local/lib/python2.7/dist-packages/lasagne/theano_extensions
/home/jbuesking/repositories/python/pylearn2/doc/theano_to_pylearn2_tutorial.txt
/home/jbuesking/repositories/python/pylearn2/pylearn2/tests/test_theano.py
/home/jbuesking/repositories/python/pylearn2/pylearn2/utils/theano_graph.py
/home/jbuesking/repositories/python/pylearn2/pylearn2/packaged_dependencies/theano_linear
/home/jbuesking/repositories/python/Lasagne/build/lib.linux-x86_64-2.7/lasagne/theano_extensions
/home/jbuesking/repositories/python/Lasagne/lasagne/tests/test_theano_extensions.py
/home/jbuesking/repositories/python/Lasagne/lasagne/theano_extensions
/home/jbuesking/.theanorc
>> sudo pip install -r https://raw.githubusercontent.com/Lasagne/Lasagne/v0.1/requirements.txt
>> rm -r ~/.theano
... running mnist example ...
```

**Comment by f0k** [comment]
Can you try installing the bleeding-edge Theano version, not just the one from Lasagne's requirements.txt? `sudo pip uninstall theano`, then `pip install https://github.com/Theano/Theano/archive/master.zip`.

**Comment by JesseBuesking** [comment]
@f0k I just installed the bleeding-edge version, and it works! Thank you guys for helping me to troubleshoot this!

Semi-depressingly, I was hoping that cudnn would help reduce memory pressure but it appears that it actually increases it even if I pass [theano flags](http://deeplearning.net/software/theano/library/sandbox/cuda/dnn.html) to try and reduce it. So it looks like cudaconv is the best option for me.

```
                 mem      sec
base:            16.9%    3:00
cudaconv:        17.2%    1:07
cudnn(none):     18.6%    1:50
cudnn(small):    18.6%    1:40
cudnn(fft):      20.2%    1:51
```

*For these numbers I'm running [this network](http://nbviewer.ipython.org/github/dnouri/nolearn/blob/master/docs/notebooks/CNN_tutorial.ipynb#Even-more-information), replacing the 64 node dense layers with 1024 node to increase memory pressure.*

**Comment by benanne** [comment]
Note that you can tune the cuda-convnet performance/memory trade-off further using the `partial_sum` argument. More details here: http://lasagne.readthedocs.org/en/latest/modules/layers/cuda_convnet.html#lasagne.layers.cuda_convnet.Conv2DCCLayer

**Comment by JesseBuesking** [comment]
@benanne good to know, thanks for the tip!

```
partial_sum   mem      min
0             15.8%    1:25
1             17.2%    1:06
```
