### ISSUE TITLE
Docs failing to build

### ISSUE THREAD

**Issue by Kaixhin** [Lasagne/Lasagne#417]
Was just checking on the documentation and realised it hasn't been building properly [for weeks](https://readthedocs.org/projects/lasagne/builds/). [This](https://readthedocs.org/projects/lasagne/builds/3263592/) is the last build to have passed, and [this](https://readthedocs.org/projects/lasagne/builds/3268724/) is the first build to have failed.

**Comment by benanne** [comment]
The badge is still green for whatever reason. What happened 3 weeks ago? Seems like `lasagne` fails to import.

**Comment by f0k** [comment]
> Was just checking on the documentation and realised it hasn't been building properly for weeks.

Oh!

> The badge is still green for whatever reason.

Not surprising, the image is static: http://img.shields.io/badge/docs-latest-brightgreen.svg
Is there a dynamic version somewhere?

> What happened 3 weeks ago?

The first build that failed is the one that merged #393. That one only changed a single word in a docstring, this can't be the reason. Did readthedocs change anything?

**Comment by f0k** [comment]
> Did readthedocs change anything?

I diffed the two log files, and there are some changes.

Completed build:
```
Successfully installed Jinja2-2.7.2 Markdown-2.6.2 MarkupSafe-0.18 PyYAML-3.10 Pygments-2.0.2 alabaster-0.7.6 babel-2.0 backports.ssl-match-hostname-3.4.0.2 certifi-2015.4.28 click-5.1 commonmark-0.5.4 docutils-0.11 livereload-2.4.0 mkdocs-0.14.0 mock-1.0.1 nilsimsa-0.3.7 pillow-2.3.0 pytz-2012rc0 readthedocs-sphinx-ext-0.5.4 recommonmark-0.1.1 requests-2.2.1 setuptools-3.3 six-1.5.2 snowballstemmer-1.2.0 sphinx-1.3.1 sphinx-rtd-theme-0.1.8 tornado-4.2.1 virtualenv-13.1.0
```
Failed build:
```
Successfully installed Jinja2-2.8 Markdown-2.6.2 MarkupSafe-0.23 PyYAML-3.11 Pygments-2.0.2 alabaster-0.7.6 babel-2.0 backports.ssl-match-hostname-3.4.0.2 certifi-2015.4.28 click-5.1 commonmark-0.5.4 docutils-0.11 livereload-2.4.0 mkdocs-0.14.0 mock-1.0.1 nilsimsa-0.3.7 pillow-2.6.1 pytz-2015.4 readthedocs-sphinx-ext-0.5.4 recommonmark-0.1.1 requests-2.7.0 setuptools-18.0.1 six-1.9.0 snowballstemmer-1.2.0 sphinx-1.3.1 sphinx-rtd-theme-0.1.8 tornado-4.2.1 virtualenv-13.1.0
```

Completed build:
```
Collecting Theano==0.8.git from git+https://github.com/Theano/Theano.git@15c90dd3#egg=Theano==0.8.git (from -r requirements.txt (line 1))
  Cloning https://github.com/Theano/Theano.git (to 15c90dd3) to /tmp/pip-build-GOZ5UR/Theano
  Could not find a tag or branch '15c90dd3', assuming commit.
  Requested Theano==0.8.git from git+https://github.com/Theano/Theano.git@15c90dd3#egg=Theano==0.8.git (from -r requirements.txt (line 1)), but installing version **0.7.0**
```
Failed build:
```
Collecting Theano==0.8.git from git+https://github.com/Theano/Theano.git@15c90dd3#egg=Theano==0.8.git (from -r requirements.txt (line 1))
  Cloning https://github.com/Theano/Theano.git (to 15c90dd3) to /tmp/pip-build-MUt9C5/Theano
  Could not find a tag or branch '15c90dd3', assuming commit.
  Requested Theano==0.8.git from git+https://github.com/Theano/Theano.git@15c90dd3#egg=Theano==0.8.git (from -r requirements.txt (line 1)), but installing version **None**
```

Completed build:
```
Requirement already satisfied (use --upgrade to upgrade): numpydoc in ...
(same for pep8, pytest, pytest-cov, pytest-pep8)
...
Collecting six>=1.9.0
...
Successfully installed Jinja2-2.7.2 Sphinx-1.2.3 Theano-0.7.0 six-1.5.2
```
Failed build:
```
Collecting numpydoc from ...
(same for pep8, pytest, pytest-cov, pytest-pep8)
...
Requirement already satisfied (use --upgrade to upgrade): six>=1.9.0
...
Successfully installed Jinja2-2.7.3 Sphinx-1.2.3 Theano-0.7.0 apipkg-1.4 coverage-3.7.1 execnet-1.4.0 numpydoc-0.5 pep8-1.6.2 py-1.4.30 pytest-2.7.2 pytest-cache-1.0 pytest-cov-2.1.0 pytest-pep8-1.0.6
```

So the configuration of preinstalled packages has changed somewhat, but I don't see anything that should make a difference. Maybe it's running things from a different directory than before, so `lasagne` is not in the current directory to be imported. We'd need to check if readthedocs has anything to say about this. At least it seems it doesn't install `lasagne` in order to generate the docs.

**Comment by f0k** [comment]
From [the documentation](https://read-the-docs.readthedocs.org/en/latest/faq.html#where-do-i-need-to-put-my-docs-for-rtd-to-find-it), sphinx-build is run from within the directory it finds the `conf.py` file. For us, that would be the `docs` directory. From there, it can only access `lasagne` if it has been installed or is on the Python path.
Another readthedocs FAQ is titled: [Can I document a python package that is not at the root of my repository?](https://read-the-docs.readthedocs.org/en/latest/faq.html#can-i-document-a-python-package-that-is-not-at-the-root-of-my-repository) This suggests that having `lasagne` at the repository root will magically make things work, but I don't see how.
The [Sphinx documentation](http://sphinx-doc.org/ext/autodoc.html) suggests to extend `sys.path` in `conf.py` such that the module is found. That would be easy to do (the documentation would then always be built for the version found in the source directory, not for the currently installed version, but that may be what you want anyway).

I guess I'll just try extending `conf.py` accordingly, although I wonder why the readthedocs build has ever worked at all...

**Comment by f0k** [comment]
Fixed by [Sander changing the readthedocs config](https://github.com/Lasagne/Lasagne/pull/419#issuecomment-141090432) to use virtualenv, so it installs Lasagne before running Sphinx.

**Comment by benanne** [comment]
I've added you as a maintainer.

**Comment by f0k** [comment]
Kiitos!
