### ISSUE TITLE
Inconsistent passing of **kwargs to CustomRecurrentLayer's child layers

### ISSUE THREAD

**Issue by craffel** [Lasagne/Lasagne#421]
`CustomRecurrentLayer` doesn't pass `kwargs` to `hidden_to_hidden` when calling `get_output`:
https://github.com/Lasagne/Lasagne/blob/master/lasagne/layers/recurrent.py#L387
It does for in_to_hid when `precompute_input` is `True`:
https://github.com/Lasagne/Lasagne/blob/master/lasagne/layers/recurrent.py#L370
but not when `precompute_input` is `False`:
https://github.com/Lasagne/Lasagne/blob/master/lasagne/layers/recurrent.py#L394

Intuitively, I'd think it should always pass `**kwargs` to its child layers, but I have a vague feeling there may be a case when the user wouldn't want it to.  Is there?  If not, I will fix this and make it pass them.

**Comment by f0k** [comment]
> Intuitively, I'd think it should always pass `**kwargs` to its child layers, but I have a vague feeling there may be a case when the user wouldn't want it to. Is there?

It must always be passed on, it's bad we overlooked this. If somebody uses the `CustomRecurrentLayer` with dropouts anywhere, they will never be disabled at test time. A fix would be welcome!

**Comment by craffel** [comment]
PR: #423
