### ISSUE TITLE
AttributeError: 'DenseLayer' object has no attribute 'get_output_shape'

### ISSUE THREAD

**Issue by lfwin** [Lasagne/Lasagne#426]
i try the first example from http://danielnouri.org/notes/2014/12/17/using-convolutional-neural-nets-to-detect-facial-keypoints-tutorial/ and get this error
# add to kfkd.py
from lasagne import layers
from lasagne.updates import nesterov_momentum
from nolearn.lasagne import NeuralNet

net1 = NeuralNet(
    layers=[  # three layers: one hidden layer
        ('input', layers.InputLayer),
        ('hidden', layers.DenseLayer),
        ('output', layers.DenseLayer),
        ],
    # layer parameters:
    input_shape=(None, 9216),  # 96x96 input pixels per batch
    hidden_num_units=100,  # number of units in hidden layer
    output_nonlinearity=None,  # output layer uses identity function
    output_num_units=30,  # 30 target values

    # optimization method:
    update=nesterov_momentum,
    update_learning_rate=0.01,
    update_momentum=0.9,

    regression=True,  # flag to indicate we're dealing with regression problem
    max_epochs=400,  # we want to train this many epochs
    verbose=1,
    )

X, y = load()
net1.fit(X, y)

**Comment by benanne** [comment]
You may be using an older version of nolearn with a newer version of Lasagne. This error is the result of an API change in Lasagne that happened before the first release. There is no longer a `get_output_shape()` method, only an `output_shape` attribute. The newest version of nolearn should use the correct API.

That said, please don't use our GitHub issue tracker for support requests. These should be sent to the mailing list instead: https://groups.google.com/forum/#!forum/lasagne-users
The issue tracker is for development-related stuff only. Thanks for your understanding.

**Comment by gitvicky** [comment]
I am using Theano 0.8.0, Lasagne 0.1 and nolearn 0.6. While trying to run my program this line:
the_layers = lasagne.layers.DenseLayer(the_layers, num_units=64, nonlinearity=lasagne.layers.nonlinearities.rectify)

 is showing this error:

    the_layers = lasagne.layers.DenseLayer(the_layers, num_units=64, nonlinearity=lasagne.layers.nonlinearities.rectify)

AttributeError: 'module' object has no attribute 'nonlinearities'

**Comment by f0k** [comment]
@gitvicky: It should be `lasagne.nonlinearities`, not `lasagne.layers.nonlinearities`.
