### ISSUE TITLE
Theano 0.8

### ISSUE THREAD

**Issue by DeanChan** [Lasagne/Lasagne#427]
It seems that Theano 0.8 has not been established?

<code>Could not find a tag or branch '15c90dd3', assuming commit.
  Requested Theano==0.8.git from git+https://github.com/Theano/Theano.git@15c90dd3#egg=Theano==0.8.git (from -r https://raw.githubusercontent.com/Lasagne/Lasagne/v0.1/requirements.txt (line 1)), but installing version 0.7.0<code>

![image](https://cloud.githubusercontent.com/assets/10941346/10014473/035f7494-614c-11e5-9588-a9be17889b46.png)

**Comment by benanne** [comment]
Indeed it isn't. `0.8.git` is just a trick to make it install a development version of the library :)

**Comment by f0k** [comment]
We should document that, it's been asked on the mailing list before and it's a bit confusing!

**Comment by DeanChan** [comment]
Thanks for the answer.

**Comment by f0k** [comment]
The same question came up on the mailing list again: https://groups.google.com/forum/#!topic/lasagne-users/nQpautjd_gU
We should do something. Shall we just add a sentence to the installation instructions saying: "Don't be surprised if it tries to install 0.8, but finds 0.7 instead, this is a trick to make pip upgrade any existing installation." ? Or is there any other way of achieving what we want? What problem are we actually trying to solve -- is it that pip refuses to upgrade an existing Theano release with the development version? For what reason?

**Comment by ebenolson** [comment]
As I understand it, the root issue is that Theano calls `setup` with `version='0.7.0'` even in the development version, so pip cannot distinguish between a git version and a previously installed release.

I think the real solution would be for Theano to adopt something like [Versioneer](https://github.com/warner/python-versioneer). But we could also switch to telling people to do

`pip install --upgrade git+https://github.com/Theano/Theano.git@15c90dd3`

This will still display the warning `Could not find a tag or branch '15c90dd3', assuming commit.`, but that's a bit less disconcerting than the version mismatch warning.

**Comment by f0k** [comment]
> But we could also switch to telling people to do
>
> `pip install --upgrade git+https://github.com/Theano/Theano.git@15c90dd3`

Would `pip install --upgrade -r requirements.txt` work?

> As I understand it, the root issue is that Theano calls setup with version='0.7.0' even in the development version, so pip cannot distinguish between a git version and a previously installed release.

Wouldn't it be enough if Theano switched to `0.7.1.dev1` right after the release? They probably wouldn't mind if it helped downstream projects to better manage dependencies.

**Comment by ebenolson** [comment]
> Would pip install --upgrade -r requirements.txt work?

I think we'd need to do something like
`pip install --upgrade -r https://raw.githubusercontent.com/Lasagne/Lasagne/requirements.txt`

which is longer and more opaque. But it should work as well.

> Wouldn't it be enough if Theano switched to 0.7.1.dev1 right after the release? They probably wouldn't mind if it helped downstream projects to better manage dependencies.

That would help somewhat - but I think we'd have the same issue if someone installed shortly after release, then tried to upgrade some time in the future (when Lasagne's requirements had changed).

**Comment by f0k** [comment]
> That would help somewhat - but I think we'd have the same issue if someone installed shortly after release, then tried to upgrade some time in the future (when Lasagne's requirements had changed).

Yes, right. We'd need to bug Theano to bump their development version whenever we need to update our dependency. That's impractical.

> I think we'd need to do something like `pip install --upgrade -r https://raw.githubusercontent.com/Lasagne/Lasagne/requirements.txt`

That's what we have now, except for `--upgrade` (and the explicit reference to version 0.1 because for bleeding-edge we recommend a bleeding-edge Theano anyway): http://lasagne.readthedocs.org/en/latest/user/installation.html#stable-lasagne-release
It even says to add `--upgrade` to upgrade existing installations.

@dnouri, do you have any insights on the consequences of dropping `#egg=Theano==0.8.git` from `requirements.txt`? What exactly would break?

**Comment by ebenolson** [comment]
Yes, that was assuming we'd drop the #egg from requirements.txt to
eliminate the warning.

**Comment by nouiz** [comment]
I'm not expert in the detail of versioning development version. If you have
suggestion to Theano, don't hesitate.

I know there is a recent pep on versioning, could we add a sufix like
0.7.0.devN, where we increment N when we add new interface?

This would be useful to more then just lasagne and wouldn't be too hard for
reviewers of Theano PR to check this.

But yes, as it is manual, we could miss it a few times, but the fix would
be very easy.

**Comment by f0k** [comment]
> I know there is a recent pep on versioning, could we add a sufix like 0.7.0.devN, where we increment N when we add new interface?

Yes, except that you'd use `0.7.1.devN` (all the `.dev` come before the release, i.e., `0.7.0.dev1` would be older than `0.7.0` according to [PEP 440](https://www.python.org/dev/peps/pep-0440/#examples-of-compliant-version-schemes)).

If you did that, we could append `#egg=Theano==0.7.1.devN` with the correct version number to the git reference in our `requirements.txt`, and we could check for the correct version by the version string rather than by a feature test.

**Comment by nouiz** [comment]
Would this request a tag in the github repo? Do this need an update to
pypi? The tag isn't a problem, asking us to update to pypi is more
complicated and time consumming.

**Comment by f0k** [comment]
> Would this request a tag in the github repo? Do this need an update to pypi?

No, neither of those. For our purposes, it would be enough if Theano updated its `setup.py` with the new version number. Tagging the version would allow us to reference the tag instead of the commit, but I think that would also create a github release? That might be overkill.

**Comment by nouiz** [comment]
I launched the discussion on theano-dev about our versioning:

https://groups.google.com/forum/#!topic/theano-dev/UZSgNkQZ8wc

**Comment by f0k** [comment]
Theano now uses `.devX` version numbers between releases we can depend on.
