### ISSUE TITLE
Scan: float64 warnings when non_sequences contains  "()"

### ISSUE THREAD

**Issue by lpigou** [Lasagne/Lasagne#443]
For example:

```
theano.scan(..., non_sequences=[..., ()], ...)
```
This gives float64 warnings.

This is used [here](https://github.com/Lasagne/Lasagne/blob/master/lasagne/layers/recurrent.py#L1037) for example.

See https://github.com/Theano/Theano/issues/3345

**Comment by skaae** [comment]
Nice catch. I'll look into this.
