### ISSUE TITLE
Issue with LSTM output

### ISSUE THREAD

**Issue by eralmansouri** [Lasagne/Lasagne#448]
I noticed LSTM layer output is a little bit off. 

Even with sigmoid activation I would sometimes get 1 < output or output < 0. 

The value of the cell to output gate was being added after the activation function when peepholes are enabled.

At line 970~ in recurrent.py
```python
            outgate = self.nonlinearity_outgate(outgate)

            # Compute new cell value
            cell = forgetgate*cell_previous + ingate*cell_input

            if self.peepholes:
                outgate += cell*self.W_cell_to_outgate
```

should be changed to:
```python
            # Compute new cell value
            cell = forgetgate*cell_previous + ingate*cell_input

            if self.peepholes:
                outgate += cell*self.W_cell_to_outgate
	
            outgate = self.nonlinearity_outgate(outgate)
```

I'm pretty sure there's a way to pull or push or something but I don't know how. No real experience with Github. I hope I helped anyway.

**Comment by skaae** [comment]
Thanks. I'll fix that right away.
