### ISSUE TITLE
Docs of the CustomRecurrentLayer

### ISSUE THREAD

**Issue by Botev** [Lasagne/Lasagne#452]
In the docs the examples for the `CustomRecurrentLayer` and the docs don't match. Particularly - ``
```
input_to_hidden : :class:`lasagne.layers.Layer`
        :class:`lasagne.layers.Layer` instance which connects input to the
        hidden state (:math:`f_i`).  This layer may be connected to a chain of
        layers, which must end in a :class:`lasagne.layers.InputLayer` with the
        same input shape as `incoming`. 
```
However, in the examples to `incoming` has shape `(n_batch, n_steps, n_in)` while the bottom `InputLayer` of the `input_to_hidden` has shape `(None, n_in)`. The same applies an the example of convolutional recurrence where the `incoming` has shape `(n_batch, n_steps, n_channels, width, height)`, while the bottom of the `input_to_hidden` has shape `(None, n_channels, width, height)`. From this it seems that the `InputLayer` of the `input_to_hidden` must have shape `incoming.shape[1:]`.

Or is it intentional that it takes `None` at the start so that you flat out the batch and the input length?

**Comment by craffel** [comment]
When `precompute_input == True` (the default), `input_to_hidden.input_shape[0]` should be `incoming.output_shape[0]*incoming.output_shape[1]` or `None`.  When `precompute_input == False`, `input_to_hidden.input_shape[0]` should be `incoming.output_shape[0]` or `None`.  I will make the docs more verbose.

**Comment by craffel** [comment]
PR: #455
