### ISSUE TITLE
rectify use theano.tensor.nnet.relu which is not exist

### ISSUE THREAD

**Issue by citihome** [Lasagne/Lasagne#454]
Hi, When I execute the code layers.get_output_for (In line 185, lasagne.layers.helper.py ), the procedure will execute the function rectify, here it encapsulate theano.tensor.nnet.relu which is not exist.
 How should I fix this problem?
We see that in the lasagne.layers.Conv2DCCLayer.__init__, there is default setting nonlinearity = nonlinearities.rectify, also in the function, there is branch depends on if the nonliearity is None
which seems inconsistence

**Comment by ebenolson** [comment]
You need a more recent version of Theano, see the [installation instructions](http://lasagne.readthedocs.org/en/latest/user/installation.html#theano).

**Comment by citihome** [comment]
It is the newest version

Python 2.7.10 |Anaconda 2.3.0 (64-bit)| (default, Sep 15 2015, 14:50:01) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import theano
Using gpu device 0: GeForce GTX 460
>>> theano.__version__
'0.7.0'

**Comment by ebenolson** [comment]
please read the linked instructions.

**Comment by f0k** [comment]
> please read the linked instructions.

:+1:

We could extend the check in [`__init__.py`](https://github.com/Lasagne/Lasagne/blob/master/lasagne/__init__.py) to test for required features. We've established in some other discussion that testing `theano.__version__` won't work, but testing for `hasattr(theano.tensor.nnet, 'relu')` would. We'd just need to take care to modify this whenever we advance the Theano version in `requirements.txt`.

**Comment by ebenolson** [comment]
It might also be good to explicitly state that `0.7.0` is too old - although we can't easily test if a commit has is new enough, the `dev` suffix will always be present, right?

**Comment by f0k** [comment]
> although we can't easily test if a commit hash is new enough, the -dev suffix is a necessary condition, right?

Yes, but in this case it still doesn't tell whether the version is recent enough. It would just catch people installing Theano 0.7.0. Checking for some specific feature would be the most robust option, and also catch people who originally installed Theano from github as they should, but forgot to update it along with Lasagne later on.
