### ISSUE TITLE
build badge shows 'failing' because a PR does not build

### ISSUE THREAD

**Issue by benanne** [Lasagne/Lasagne#458]
For some reason the build badge in the README file is showing that the build is failing. Clicking it leads to a failed build of a PR #456. The badge should only show the build status for the master branch. I'm pretty sure that's what it did before, no? If so, what has changed, and how can we fix it?

**Comment by ebenolson** [comment]
Seems to be a Travis issue: https://github.com/travis-ci/travis-ci/issues/4024
