### ISSUE TITLE
installation from master fails in ipython3 with UnicodeDecodeError

### ISSUE THREAD

**Issue by matthias-k** [Lasagne/Lasagne#463]
I try to install Lasange in python3 (in a docker container running `jupyter/scipy-notebook`) from master, but the installation fails with a UnicodeDecodeError when trying to read `CHANGES.rst`. To reproduce:

```
% docker run -t -i jupyter/scipy-notebook /bin/bash                        
root@80f2ce016b94:/home/jovyan/work# pip install --upgrade https://github.com/Lasagne/Lasagne/archive/master.zip
Collecting https://github.com/Lasagne/Lasagne/archive/master.zip
  Downloading https://github.com/Lasagne/Lasagne/archive/master.zip (176kB)
    100% |################################| 180kB 1.9MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-m2x57j8q-build/setup.py", line 10, in <module>
        CHANGES = open(os.path.join(here, 'CHANGES.rst')).read()
      File "/opt/conda/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 243: ordinal not in range(128)
    
    ----------------------------------------
```

**Comment by daikazoku** [comment]
I had the same problem yesterday (but not 2-3 days ago). I fixed it by setting an UTF-8 locale on my system.

**Comment by f0k** [comment]
Hmm, that actually doesn't look very good anyway, we don't open the files for reading only and we don't close them:
```python
here = os.path.abspath(os.path.dirname(__file__))
try:
    README = open(os.path.join(here, 'README.rst')).read()
    CHANGES = open(os.path.join(here, 'CHANGES.rst')).read()
except IOError:
    README = CHANGES = ''
```

A possible fix for your case might be:
```python
here = os.path.abspath(os.path.dirname(__file__))
try:
    with open(os.path.join(here, 'README.rst'), 'rb') as f:
        README = f.read()
    with open(os.path.join(here, 'CHANGES.rst'), 'rb') as f:
        CHANGES = f.read()
except IOError:
    README = CHANGES = ''
```

This will read the files in binary mode and thus won't try to decode anything, but the `long_description` will be of type `bytes` instead of `str` then -- is that a problem? Can you try?

The alternative would be:
```python
here = os.path.abspath(os.path.dirname(__file__))
try:
    with open(os.path.join(here, 'README.rst'), 'r', encoding='utf8') as f:
        README = f.read()
    with open(os.path.join(here, 'CHANGES.rst'), 'r', encoding='utf8') as f:
        CHANGES = f.read()
except IOError:
    README = CHANGES = ''
```

This would be incompatible with Python 2 and need some case distinction, but if it's the only way to get it to work independently of the platform's locale settings, that's the way we should go.

**Comment by matthias-k** [comment]
what about using the `codecs` module to read the files with correct encoding? That should work with python2 and python3

**Comment by dnouri** [comment]
Should use `io.open`, which works just like Python 3's `open`.

> Hmm, that actually doesn't look very good anyway, we don't open the files for reading only and we don't close them:

FWIW, calling `open` without a second argument will open a file for reading only; the default mode is 'r'.  And in the case of `setup.py`, not closing the file is probably fine.

**Comment by f0k** [comment]
> Should use `io.open`, which works just like Python 3's `open`.

But then the Python 2 `setup` dictionary has `unicode` values instead of `str` -- would that cause any problem?

> FWIW, calling open without a second argument will open a file for reading only; the default mode is 'r'.

Ah, all right, sorry. `h5py.File` has `'a'` by default, so I got into a habit of specifying the mode everywhere.

**Comment by bamartin-ua** [comment]
Did anyone ever fix this? If not, is there a work-around? This is interfering with the development of my project.

**Comment by ebenolson** [comment]
As a workaround, try `export LANG=C.UTF-8` before installing.
