### ISSUE TITLE
Add softplus nonlinearity

### ISSUE THREAD

**Issue by wuaalb** [Lasagne/Lasagne#464]
Can make a PR for this wrapper around `theano.tensor.nnet.softplus()`, just wanted to make sure it wasn't excluded intentionally (all the other functions seem wrapped).

**Comment by benanne** [comment]
They are wrapped mostly for documentation purposes :) You can pass `nonlinearity=theano.tensor.nnet.softplus` to a `Layer` and it will work just fine! I guess we could wrap it also but I'm not sure if that's necessary. All in all it's not that commonly used.

**Comment by wuaalb** [comment]
Yes, just so users don't have to remember/look up which non-linearities are in Theano and which are in Lasagne.. But if it is too rarely used to warrant inclusion, that's OK.

**Comment by f0k** [comment]
I'm fine with wrapping it, as it's one of the few things from http://deeplearning.net/software/theano/library/tensor/nnet/nnet.html we don't have wrapped in Lasagne.
