### ISSUE TITLE
Glorot gains for Leaky_rectify and very_leaky_rectify

### ISSUE THREAD

**Issue by skaae** [Lasagne/Lasagne#468]
Should we add the correct Glorot gains for `leaky_rectify` and `very_leaky_rectify`. That would be

```Python
if gain == 'rectify':
    gain = np.sqrt(2)
elif nonlin == 'leaky_rectify':
    gain = np.sqrt(2/(1+0.01**2))
elif nonlin == 'very_leaky_rectify':
    gain = np.sqrt(2/(1+(1/3)**2))
```

Maybe also add a note to the doc that the correct  init for `leaky_rectify` with `alpha` leakiness is `np.sqrt(2/(1+alpha**2))`

**Comment by benanne** [comment]
I don't think we should add an if statement like that. That could get messy in the long run. But we could document them at least.

In practice though, getting this gain right matters very little unless you go beyond 20 or so layers, in my experience. I guess for RNNs it could be more significant as well.

**Comment by skaae** [comment]
I'm fine with adding the formula to the docs

Den 16/10/2015 22.09 skrev "Sander Dieleman" <notifications@github.com>:
>
> I don't think we should add an if statement like that. That could get
messy in the long run. But we could document them at least.
>
> In practice though, getting this gain right matters very little unless
you go beyond 20 or so layers, in my experience. I guess for RNNs it could
be more significant as well.

**Comment by f0k** [comment]
> I'm fine with adding the formula to the docs

Sounds good to me as well. Will you do it? It would be nice to not require people to enter the full formula, but I don't see a good way either. We probably don't want to have a string shortcut for every nonlinearity. Maybe a helper function in `lasagne.init` or `lasagne.nonlinearities` that takes a nonlinearity *instance* and returns the correct gain factor if known, or derives / estimates it if not?

**Comment by skaae** [comment]
yes. We can also mention it in the nonlinearities docs?

**Comment by f0k** [comment]
> We can also mention it in the nonlinearities docs?

I think it just belongs in the `init` docs (to every initializer that has a `gain` argument). Adding a helper function would avoid the need of duplicating the recommendations in every docstring (1.0 for linear and sigmoid, 2.0 for tanh (if I remember correctly), sqrt(2) for relu, sqrt(2 / (1 + leakiness**2)) for leaky relu), but it's not so bad repeating the docstring for now.

How did you derive the `sqrt(2 / (1 + leakiness**2))` -- does it hold for both `Glorot` and `He`? `He` only takes into account the forward pass, `Glorot` takes the average of the forward and backward pass. Ah, wait, it's Eq. (15) in "Delving Deep into Rectifiers", and they already show it's the same for forward and backward. Good then. Please go ahead :)

**Comment by skaae** [comment]
Can you assign me to this issue?

**Comment by f0k** [comment]
> Can you assign me to this issue? 

I thought to do so, but then I didn't because this issue is closed. Assigned you and reopened it :)

**Comment by Botev** [comment]
I think that instead of documenting for `leaky_rectify` and `very_leaky_rectify` you should just document it for any slope `alpha` as in the PReLU paper. You can also and just add another `init` class which takes as argument the slope of the relu and calls the correct initializer with the correct gain.

**Comment by f0k** [comment]
> I think that instead of documenting for leaky_rectify and very_leaky_rectify you should just document it for any slope alpha as in the PReLU paper.

Yes, that's what I suggested: https://github.com/Lasagne/Lasagne/issues/468#issuecomment-149212511

> You can also and just add another `init` class which takes as argument the slope of the relu and calls the correct initializer with the correct gain.

That's complicated, there are several initializers (six in total) with a `gain` argument, so we'd either need six subclasses or a single class that takes an initializer class as an argument, which would be weird to use. Instead, we could just add a helper function that gives the gain factor for a nonlinearity, as I suggested: https://github.com/Lasagne/Lasagne/issues/468#issuecomment-149190199
But documenting it is a good first step.
