### ISSUE TITLE
ImportError for dnn while using deep_q_rl

### ISSUE THREAD

**Issue by ssampang** [Lasagne/Lasagne#469]
I'm trying to train a network on pong using a variant of [Nathan Sprague's deep_q_rl implementation](https://github.com/jcatw/deep_q_rl/tree/multiplayer). I should have cuda toolkit and cudnn installed correctly  according to [this link.](http://stackoverflow.com/questions/31326015/how-to-verify-cudnn-installation) However, when I try to start training, I get the following output:

```
~/Projects/deep_q_rl/deep_q_rl$ ./run_nips.py --rom pong
A.L.E: Arcade Learning Environment (version 0.5.0)
[Powered by Stella]
Use -help for help screen.
Warning: couldn't load settings file: ./ale.cfg
Game console created:
  ROM file:  ../roms/pong.bin
  Cart Name: Video Olympics (1978) (Atari)
  Cart MD5:  60e0ea3cbe0913d39803477945e9e5ec
  Display Format:  AUTO-DETECT ==> NTSC
  ROM Size:        2048
  Bankswitch Type: AUTO-DETECT ==> 2K

Running ROM file...
Random seed is 65
Traceback (most recent call last):
  File "./run_nips.py", line 60, in <module>
    launcher.launch(sys.argv[1:], Defaults, __doc__)
  File "/home/sid/Projects/deep_q_rl/deep_q_rl/launcher.py", line 225, in launch
    rng)
  File "/home/sid/Projects/deep_q_rl/deep_q_rl/q_network.py", line 53, in __init__
    num_actions, num_frames, batch_size)
  File "/home/sid/Projects/deep_q_rl/deep_q_rl/q_network.py", line 168, in build_network
    batch_size)
  File "/home/sid/Projects/deep_q_rl/deep_q_rl/q_network.py", line 407, in build_nips_network_dnn
    from lasagne.layers import dnn
  File "/home/sid/.local/lib/python2.7/site-packages/lasagne/layers/dnn.py", line 13, in <module>
    raise ImportError("dnn not available")  # pragma: no cover
ImportError: dnn not available
```

I'm running this on Ubuntu 14.04 with a titan gpu. `LD_LIBRARY_PATH`, `CPATH`, and `PATH` all include the appropriate directories. Any ideas?

Thanks,
Sid

**Comment by moscow25** [comment]
Hey Sid,

I remember something vaguely similar when running Nathan's Deep-Q-RL
with Lasagne. Forgot how I fixed it, but there's what I remember...

I'd look at two things:

1. do check $LD_LIBRARY_PATH, if you're sure that everything is
installed correctly

2. I think that Nathan's code includes two options for Deep-Q-RL with
Lasagne. You can comment out the import statement for the one that you
don't need. Nathan didn't write the Lasagne hook, and the gentleman
who did, may have things installed that you don't need to run the
code, but which will throw an error if explicitly imported. For
example, I was able to run Nathan's Deep-Q-RL, without "from
lasagne.layers import dnn"

In other words, there's nothing wrong with Lasagne here, at least in
the similar error which I had. Either you need CUDA DNN and it's not
linked to Theano/Python, in which case you can test that separately,
and update your path as needed. Or you don't need the include file, or
can swap code in three places, and use the CNN or DNN class from
Lasagne that you need. In Lasagne, there are several ways to create
DNN and CNN layers, but if you #import a package, you will get an
error... even if your code never declares that object.

I hope that's helpful. Maybe your error is different, but I remember
something similar, and with a small fix, was able to run Nathan's code
via Lasagne CNN, no problem :-)

If you're able to fix this, I'd love to hear what it was. But we
should probably discuss this on the Deep-Q-RL list.

Best,
Nikolai

**Comment by ssampang** [comment]
Hey Nikolai,

Thanks for the suggestions. 

1. Here's my LD_LIBRARY_PATH: `/opt/ros/indigo/lib:/opt/ros/indigo/lib/x86_64-linux-gnu:/usr/local/cuda-7.0/lib64:/home/sid/OpenBLAS/build/lib
` Please let me know if I'm missing anything.
2. I had a look inside the source, and they do seem to be using the dnn code, so it looks like I do need it. I'll keep trying to find a fix and report back when I do.

I'll post on the Deep-Q-RL list if I have any further problems. I didn't know about it until now.

Thanks,
Sid

**Comment by moscow25** [comment]
Yeah, that list should be more helpful. Your path looks good. Lasagne dnn
object is called, I think... but you can use a different DNN layer
declaration that works fine. But yeah, good one to post on the Deep-Q-RL
list.

Good luck!

Best,
N

On Sun, Oct 18, 2015 at 4:43 PM, Siddarth Sampangi <notifications@github.com

**Comment by ssampang** [comment]
Ok, I've narrowed down the problem I think, and it seems to be an issue with Lasagne specifically, so I'm going to go ahead and close this issue but open another one on this project which details the issue further.

Thanks for the help Nikolai.

-Sid
