### ISSUE TITLE
Theano can find my cudnn library files, but Lasagne can't

### ISSUE THREAD

**Issue by ssampang** [Lasagne/Lasagne#470]
I've created a previous issue #469 regarding my overall problem, but after spending the past couple days on this, I believe I can offer a more focused view of where I think the problem is. I have cuda-toolkit-7.0 installed (deviceQuery works) and I've moved my cudnn library files to `${CUDA_HOME}/lib64` and `cudnn.h` to `${CUDA_HOME}/include`. 

Theano seems to be able to integrate with cudnn, because `python -c "import theano; print theano.sandbox.cuda.dnn.dnn_available() or theano.sandbox.cuda.dnn.dnn_available.msg"` (obtained from this [installation guide](http://lasagne.readthedocs.org/en/latest/user/installation.html#prerequisites)) prints `True`, as it should. 

The problem seems to lie with my install of Lasagne:
```
~/Projects/deep_q_rl/deep_q_rl$ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import lasagne
Using gpu device 0: GeForce GTX TITAN X (CNMeM is disabled)
>>> lasagne.layers
<module 'lasagne.layers' from '/home/sid/.local/lib/python2.7/site-packages/lasagne/layers/__init__.pyc'>
>>> lasagne.layers.dnn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'dnn'
>>> quit()
```

Any suggestions would be appreciated!

Thanks,
Sid

**Comment by craffel** [comment]
I believe you need to import `lasagne.layers.dnn` explicitly, it's not included in the submodules automatically imported: https://github.com/Lasagne/Lasagne/blob/master/lasagne/layers/__init__.py

**Comment by ssampang** [comment]
Oh wow you're right. The deep_q_rl code did attempt to explicitly import it, but it wasn't working earlier and I hadn't tried to rerun that code until now. Everything works now. Thanks!

**Comment by DanielTakeshi** [comment]
Hate to bring up an old topic, but did you mean import as in

    import lasagne.layers.dnn

Because I can't do that:

```
Python 2.7.10 |Anaconda 2.2.0 (x86_64)| (default, Oct 19 2015, 18:31:17) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import lasagne
>>> lasagne.layers
<module 'lasagne.layers' from '/Users/danielseita/.local/lib/python2.7/site-packages/lasagne/layers/__init__.pyc'>
>>> lasagne.layers.dnn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'dnn'
>>> import lasagne.layers.dnn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/danielseita/.local/lib/python2.7/site-packages/lasagne/layers/dnn.py", line 13, in <module>
    raise ImportError("dnn not available")  # pragma: no cover
ImportError: dnn not available
```

Theano can find my cuDNN, so I was hoping this could be the solution.

**Comment by benanne** [comment]
This error is raised by this piece of code: https://github.com/Lasagne/Lasagne/blob/master/lasagne/layers/dnn.py#L12-L13

so if you get that, either Theano is not configured to use the GPU (or it cannot find it), or it did not detect cuDNN correctly. What steps did you take to ensure that Theano is finding cuDNN and using it?

**Comment by DanielTakeshi** [comment]
Thanks for the pointer in the code, benanne. The solution did indeed seem to be that I did not set up the configuration file correctly.

I'm posting some detailed instructions here in case these help anyone else.

First, check to make sure CUDA is installed. I have 7.5:

```
dhcp-46-165:~ danielseita$ /usr/local/cuda/bin/nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Thu_Sep_24_00:26:39_CDT_2015
Cuda compilation tools, release 7.5, V7.5.19
```

Then, copy over the DNN files:

```
dhcp-46-165:~ danielseita$ sudo cp ~/cuda_osx/include/cudnn.h /usr/local/cuda/include/
dhcp-46-165:~ danielseita$ sudo cp ~/cuda_osx/lib/libcudnn* /usr/local/cuda/lib/
```

Then I installed Theano from the master branch:
```
dhcp-46-165:~ danielseita$ pip install --user --upgrade --no-deps git+git://github.com/Theano/Theano.git
Collecting git+git://github.com/Theano/Theano.git
  Cloning git://github.com/Theano/Theano.git to /var/folders/zz/h65yg4xx5616jfxtcb61lb_r0000gn/T/pip-ojPPTj-build
Installing collected packages: Theano
  Running setup.py install for Theano
Successfully installed Theano-0.7.0
```

Now to check for the GPU, use the instructions here:
http://deeplearning.net/software/theano/tutorial/using_gpu.html
http://deeplearning.net/software/theano/library/sandbox/cuda/dnn.html
I created three scripts according to the GPU example, and they all seem to run. Here's one output, with the `optimizer_including=cudnn` option.

```
dhcp-46-165:~ danielseita$ THEANO_FLAGS=mode=FAST_RUN,device=gpu,floatX=float32,optimizer_including=cudnn python check1.py
Using gpu device 0: GeForce GT 750M (CNMeM is disabled)
[GpuElemwise{exp,no_inplace}(<CudaNdarrayType(float32, vector)>), HostFromGpu(GpuElemwise{exp,no_inplace}.0)]
Looping 1000 times took 0.634406 seconds
Result is [ 1.23178029  1.61879349  1.52278066 ...,  2.20771813  2.29967761
  1.62323296]
Used the gpu
```

Theano does not recognize the GPU, but DNN is available:

```
dhcp-46-165:~ danielseita$ python -c 'from theano.sandbox.cuda.dnn import dnn_available; print dnn_available(), dnn_available.msg'
Using gpu device 0: GeForce GT 750M (CNMeM is disabled)
True None
dhcp-46-165:~ danielseita$ python
Python 2.7.10 |Anaconda 2.2.0 (x86_64)| (default, Oct 19 2015, 18:31:17) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import theano
>>> from theano.sandbox.cuda import dnn
>>> theano.config.device.startswith("gpu") 
False
>>> dnn.dnn_available()
Using gpu device 0: GeForce GT 750M (CNMeM is disabled)
True
```

After creating an example configuration file according to:
http://deeplearning.net/software/theano/library/config.html
it works:

```
dhcp-46-165:~ danielseita$ python
Python 2.7.10 |Anaconda 2.2.0 (x86_64)| (default, Oct 19 2015, 18:31:17) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import theano
Using gpu device 0: GeForce GT 750M (CNMeM is disabled)
>>> from theano.sandbox.cuda import dnn
>>> theano.config.device.startswith("gpu")
True
>>> dnn.dnn_available()
True
```

(Note: I had to *create* it because I didn't have it there originally.)

**Comment by benanne** [comment]
Glad to hear you managed to sort it out :) Thanks for sharing the solution!

**Comment by clairelopt** [comment]
I'm getting the same error ("ImportError: dnn not available"). I followed DanielTakeshi's instructions, but am still having some issues. Theano seems to recognise the GPU, but dnn still isn't available:

    THEANO_FLAGS=mode=FAST_RUN,device=gpu,floatX=float32,optimizer_including=cudnn python check1.py
    Using gpu device 0: GeForce GT 750M (CNMeM is disabled)
    [GpuElemwise{exp,no_inplace}(<CudaNdarrayType(float32, vector)>),     HostFromGpu(GpuElemwise{exp,no_inplace}.0)]
    Looping 1000 times took 1.068189 seconds
    Result is [ 1.23178029  1.61879349  1.52278066 ...,  2.20771813  2.29967761
    1.62323296]
    Used the gpu

    Python 3.4.3 |Anaconda 2.2.0 (x86_64)| (default, Oct 20 2015, 14:27:51) 
    [GCC 4.2.1 (Apple Inc. build 5577)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import theano
    Using gpu device 0: GeForce GT 750M (CNMeM is disabled)
    >>> from theano.sandbox.cuda import dnn
    >>> theano.config.device.startswith("gpu") 
    True
    >>> dnn.dnn_available()
    False

Does anyone know why this is? Or how I might be able to figure it out myself? I'm relatively new to this, so it is possible I'm just doing something really stupid. Any help would be appreciated.

**Comment by benanne** [comment]
Theano being able to recognise the GPU, and being able to recognise your cuDNN installation are two entirely different things :) Although the latter of course requires the former. Make sure you have followed the instructions in the documentation correctly: http://deeplearning.net/software/theano/library/sandbox/cuda/dnn.html (i.e. set all the environment variables as instructed). Also make sure your CUDA installation is recent enough, as well as your Theano version.

If you need more help, please post on the Lasagne mailing list: https://groups.google.com/forum/#!forum/lasagne-users
Or the Theano mailing list: https://groups.google.com/forum/#!forum/theano-users

**Comment by f0k** [comment]
> Or how I might be able to figure it out myself?

In your last Python prompt, add the following:
```
>>> dnn.dnn_available.msg
```
This will print the reason for why `dnn_available()` is `False`. This is also suggested in [the installation docs](http://lasagne.readthedocs.org/en/latest/user/installation.html#cudnn). If you can't make sense of the error message, please check (or post to) the Theano mailing list, as Sander said. The only thing we could change in Lasagne is to give a more meaningful error message than "ImportError: dnn not available".
