### ISSUE TITLE
Recurrent layers: "Keep final time step" possibly suboptimal

### ISSUE THREAD

**Issue by f0k** [Lasagne/Lasagne#471]
Recurrent layers are frequently used in a way that only their final output for a time sequence needs to be propagated. There's an optimization for Theano's scan function that recognizes the case:
```python
outputs, updates = theano.scan(...)
keep = outputs[-1]
```
In Lasagne, this use case is currently supported by adding a SliceLayer on top of a RecurrentLayer:
```python
layer = RecurrentLayer(...)
layer = SliceLayer(layer, -1, axis=1)
```
However, the recurrent layers shuffle the scan output from (timesteps, batchsize, features) to (batchsize, timesteps, features), so Theano will never encounter a subtensor(scan(...)) sequence, but a subtensor(dimshuffle(scan(...))) sequence. We need to check if that case is optimized as well.

Lasagne's recurrent layers also accept an `unroll_scan` keyword argument, which unrolls the scan into a graph that ends in a `T.stack()` for stacking all the time steps. Again, if there's a SliceLayer on top to only keep the last output, Theano will see a subtensor(dimshuffle(stack(...))) sequence. We need to check if that case is optimized into keeping the last time step only, or whether it will actually stack all the time steps first.

Both is complicated by the fact that for layers processing the sequences in reverse order, there will also be a subtensor(::-1) between the recurrent layer's output and the SliceLayer. We also need to check whether those cases are optimized.

For the first case, Theano would need an optimization subtensor(dimshuffle(...)) -> dimshuffle(subtensor(...)), but maybe it has this. For the second case, it would need an optimization subtensor(dimshuffle(stack(...))) -> ..., but maybe it has this already. For reverse layers, Theano would need to be able to turn x[::-1][0] into x[-1] before applying the other optimizations.

Alternatively, Lasagne's recurrent layers could get a `final_state_only` keyword argument that tells them to keep the final state only and constructs the appropriate graph. That would solve all problems at once, but only for Lasagne.

**Comment by skaae** [comment]
@craffel: Didnt we discuss this at some point? I think the consensus was not to include the keyword. I'm fine with adding the keyword though.

**Comment by craffel** [comment]
@skaae  I think we probably did.

> For the first case, Theano would need an optimization subtensor(dimshuffle(...)) -> dimshuffle(subtensor(...)), but maybe it has this. For the second case, it would need an optimization subtensor(dimshuffle(stack(...))) -> ..., but maybe it has this already. For reverse layers, Theano would need to be able to turn x[::-1][0] into x[-1] before applying the other optimizations.

Wouldn't this be complicated by how the user actually does the slicing?  For example, if they place different things before the slice, or something.  I'm not familiar enough with Theano's optimizations to feel confident tackling this in any expedient way.

> Alternatively, Lasagne's recurrent layers could get a final_state_only keyword argument that tells them to keep the final state only and constructs the appropriate graph. That would solve all problems at once, but only for Lasagne.

Do you know if the scan optimization only applies to the final state?  Or, if you slice, say, the 10th-from-last output, is it also smart enough to only store that in memory, or something?  If it's the latter, it would probably be best to allow the user to pass time indices to slice after scanning, which I think would best be implemented as part of the RNN "containers".  If it's the former, I think a keyword argument is probably ok.

**Comment by f0k** [comment]
> Wouldn't this be complicated by how the user actually does the slicing? For example, if they place different things before the slice, or something.

Yes, it would get more complicated the more there is. It would seem like a useful general optimization to push subtensor() as close to the input as possible, but I don't know at all what Theano does and what it doesn't do.

> Do you know if the scan optimization only applies to the final state? Or, if you slice, say, the 10th-from-last output, is it also smart enough to only store that in memory, or something?

I don't know. In that case it could even short-cut the scan, except if there are side effects (updates). That doesn't seem like an important use case, though, you'd probably just shorten the input sequence if you don't need the scan to proceed up to the end. So I think a keyword argument would suffice -- unless Theano optimizes everthing in the correct way.

@nouiz, can you comment on that? Does Theano's "only keep the last output of scan" optimization pass through dimshuffling and things like that? This would be helpful to know. I don't really know how to search for that. From compiling two simple graphs, it seems the optimization is blocked by a dimshuffle, but I'm not sure what exactly to look out for -- it's just that the graphs look quite different.

**Comment by craffel** [comment]
> That doesn't seem like an important use case, though, you'd probably just shorten the input sequence if you don't need the scan to proceed up to the end. So I think a keyword argument would suffice -- unless Theano optimizes everthing in the correct way.

Yes, it's an esoteric use-case.  I was more thinking of cases where multiple timesteps near the end were sliced (maybe after a burn-in period).

**Comment by f0k** [comment]
Good question. Also I don't know if that would just affect memory usage or also performance (i.e., by allowing more in-place operations inside scan).

**Comment by craffel** [comment]
> Also I don't know if that would just affect memory usage or also performance (i.e., by allowing more in-place operations inside scan).

Yeah, the scan docs just mention memory usage.

**Comment by nouiz** [comment]
Le 19 oct. 2015 13:25, "Jan Schlüter" <notifications@github.com> a écrit :
>>
>> Wouldn't this be complicated by how the user actually does the slicing?
For example, if they place different things before the slice, or something.
>
> Yes, it would get more complicated the more there is. It would seem like
a useful general optimization to push subtensor() as close to the input as
possible, but I don't know at all what Theano does and what it doesn't do.

This is very hard to do. It would all to make an optimization for each op
that exist. We cover a few cases, but not many. It would be very hard to
maintain as all new op would need such optimization.

So the only save thing to do is to have the user put the subtensor the
earlier he can.

>>
>> Do you know if the scan optimization only applies to the final state?
Or, if you slice, say, the 10th-from-last output, is it also smart enough
to only store that in memory, or something?
>
> I don't know. In that case it could even short-cut the scan, except if
there are side effects (updates). That doesn't seem like an important use
case, though, you'd probably just shorten the input sequence if you don't
need the scan to proceed up to the end. So I think a keyword argument would
suffice -- unless Theano optimizes everthing in the correct way.
>
> @nouiz, can you comment on that? Does Theano's "only keep the last output
of scan" optimization pass through dimshuffling and things like that? This
would be helpful to know. I don't really know how to search for that. From
compiling two simple graphs, it seems the optimization is blocked by a
dimshuffle, but I'm not sure what exactly to look out for -- it's just that
the graphs look quite different.

**Comment by nouiz** [comment]
Scan save memory opt should cover the subtensor that keep only N last ouput
of scan to save memory. But this opt isn't always a applied. If there is
other op between the scan and the subtensor, there is big chance that the
save mem opt don't apply.

**Comment by craffel** [comment]
Hm, ok, so if I'm reading correctly that strengthens the argument for a keyword argument designating which sequence steps should be saved, so that the appropriate subtensor operation can occur immediately after `scan`.  I'd personally suggest this be rolled into the new RNN container effort, although we can add it to the current RNN layers too.

**Comment by f0k** [comment]
I think it wouldn't hurt to add it to the current RNN layers. We'd just have to decide about the interface:

1. A boolean flag telling to only keep the final output ([-1] of the scan, even if it was backwards), defaulting to `False`
2. An integer telling to only keep the final N outputs ([-N:] of the scan, even if it was backwards), defaulting to `'all'` or `None` or something like that
3. A slice telling which outputs to keep

The third option is a bit complicated to use, the most complex to implement (it would replicate some `SliceLayer.get_output_shape_for()` code), and difficult to document in combination with `backwards`.
The first option is the easiest to implement and to document, and would probably fit most use cases exactly (note that it would drop the time step dimension).
The second would be more flexible than the first, but it probably wouldn't drop the time step dimension for the common use case of setting it to `1`. Is there a use case for the second option?

**Comment by craffel** [comment]
I think 1. covers at least 95% of the use-cases.  In the probably uncommon use-case of using the last `-N` outputs, or an arbitrary slice, I think it's ok to let the user suffer the memory penalty (or, when the containers are done, write a new scan container).

**Comment by f0k** [comment]
> In the probably uncommon use-case of using the last -N outputs, or an arbitrary slice, I think it's ok to let the user suffer the memory penalty

We could even add that one later if we choose a name for the flag that works both with `flagname=False`, `flagname=True` and `flagname=123`. Keras has `return_sequences=False`, which must be set to `True` to return sequences and will only return the final output otherwise -- this wouldn't work for multiple states. Maybe something like `only_return_final`?

**Comment by craffel** [comment]
Well, we could always overload whatever keyword argument we use, and process things differently depending on whether it was a slice, or list of indices, or index, or `None`, etc.  But, I think as a first step, a simple "last n steps" argument, where `True` means "only the last step", is a good idea.

**Comment by f0k** [comment]
All right! I've assigned you to the issue -- if you don't want to do this, let me know and I'll assign myself.

**Comment by craffel** [comment]
PR: #501
