### ISSUE TITLE
Custom Validation Metric - AUC

### ISSUE THREAD

**Issue by binga** [Lasagne/Lasagne#473]
Hello!
Is there any way to monitor AUC while training the net using Lasagne? Currently, logloss and accuracy are dislayed by default. Spare my ignorance of not being able to figure this out myself. My theano knowledge is minimal!

Thank you.

**Comment by f0k** [comment]
> Currently, logloss and accuracy are dislayed by default.

I'm not sure what you mean with `by default` -- Lasagne does not have any training loop code. Do you refer to [the MNIST example](https://github.com/Lasagne/Lasagne/blob/master/examples/mnist.py), or do you actually use [nolearn](https://github.com/dnouri/nolearn]?

In any case, you'd either need to define a Theano expression for AUC, or you'd need to compile a function that gives you the predictions and compute the AUC in Python.

This is something to be discussed on [our mailing list](https://groups.google.com/forum/#!forum/lasagne-users), though -- please repost your question there. The github issue tracker is meant for bug reports and missing features!
