### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'op'

### ISSUE THREAD

**Issue by star013** [Lasagne/Lasagne#474]
Hello, I wrote a loss function (i.e. objective function), for example, 

```
myloss = myfunction(y,label)
```

where y is the output of neural network. I tested myfunction() by inputting y and label into myfunction(), and it could work.

However, when I tried to link my loss function to neural network, it failed and printed error like this:

```
WARNING (theano.tensor.opt): Failed to infer_shape from Op GpuDnnPool.
Input shapes: [(Shape_i{0}.0, <TensorType(int64, scalar)>, Elemwise{add,no_inplace}.0, Elemwise{add,no_inplace}.0), None]
Exception encountered during infer_shape: <type 'exceptions.AttributeError'>
Exception message: 'NoneType' object has no attribute 'op'
Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/opt.py", line 1075, in on_import
    [self.shape_of[r] for r in node.inputs])
  File "/usr/local/lib/python2.7/dist-packages/theano/sandbox/cuda/dnn.py", line 854, in infer_shape
    desc = node.inputs[1].owner.op
AttributeError: 'NoneType' object has no attribute 'op'
```

In my program, I use myfunction(y,label) like this:

```
y = lasagne.layers.get_output(network)
myloss = mycost(y, label)
params = lasagne.layers.get_all_params(network, trainable=True)
updates = lasagne.updates.nesterov_momentum(
            myloss, params, learning_rate=0.0001, momentum=0.9)
train_fn = theano.function([input_var, label], myloss, updates=updates)
```

where network is my neural network. I do not know where is wrong. Could anyone tell me how to fix it? Thank you.

**Comment by f0k** [comment]
Please re-post your question on our mailing list: https://groups.google.com/forum/#!forum/lasagne-users
The GitHub issue tracker is meant for bug reports or discussions of new features.
When re-posting your question, please include your loss function `mycost()`. Without it, it's hard to see what's wrong -- your code seems legit!
