### ISSUE TITLE
Print values of output layer

### ISSUE THREAD

**Issue by babaksaleh** [Lasagne/Lasagne#475]
Can anyone print the values outputted by a lasagne DenseLayer (or any layer for that matter).

 If I use the following for the lasagne layer l_decoder_out

```
print layers.get_output(l_decoder_out)
```

I get Subtensors
```
Elemwise{add,no_inplace}.0

```
However I actually need to get the numbers in this output layer. 

Thank you for your help in advance

**Comment by karstenBehrendt** [comment]
Hi, this is not an issue with Lasagne, but the way Theano works. What you created at the point of get_output() is pretty much a function graph of symbolic variables. At this point, it has not been evaluated (or even compiled). To get the output value, you either make it a function with theano.function() or use eval() on your output. 

This issue can be closed.

**Comment by f0k** [comment]
For more detailed explanations, follow the Theano tutorial: http://deeplearning.net/software/theano/tutorial/
We recommend to go up to (and including) "Graph Structures".
In future, please post such questions on our mailing list: https://groups.google.com/forum/#!forum/lasagne-users
The github issue tracker is meant for bug reports and feature discussions. Thanks!
