### ISSUE TITLE
get the __version__ differently

### ISSUE THREAD

**Issue by 317070** [Lasagne/Lasagne#477]
Right now, the `__version__` is retrieved by communicating with the packaging system. However, when using lasagne outside of the packaging system, this is quite annoying.
```
  File "/home/jdgrave/python_modules/lasagne/__init__.py", line 33, in <module>
    __version__ = pkg_resources.get_distribution("Lasagne").version
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 344, in get_distribution
    if isinstance(dist,Requirement): dist = get_provider(dist)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 223, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: Lasagne
```
Not only is it crash prone, if I am correct it is also unreliable (because the Lasange installed might not be the Lasagne I am accessing).
I am juggling with a ton of libraries in different versions, so I install these libraries in a python_modules folder. Most of the packages do this fine (numpy, scipy, theano), but lasange doesn't play nicely right now.

```python
import pkg_resources
__version__ = pkg_resources.get_distribution("Lasagne").version
del pkg_resources
```

**Comment by benanne** [comment]
You should be able to just run `pip install --editable .` though? See http://pip.readthedocs.org/en/stable/reference/pip_install/#editable-installs for more info. But I agree that this is maybe not intuitive, and it would be nice if it worked without having to do anything else.

**Comment by 317070** [comment]
The `pip install -e` won't work when you install on shared drives, for instance.

I went to get some references on how other projects do this:

* Theano catches import errors as well (and generates a version file on compilation)  https://github.com/Theano/Theano/blob/4814cd9973df83eb3b6ea3fbbd5744a0d1598dfb/theano/version.py
* Numpy has it hard coded https://github.com/numpy/numpy/blob/97c35365beda55c6dead8c50df785eb857f843f0/numpy/distutils/__version__.py
* Scipy generates a version file on compilation. This is then imported through __init__.py, but only when scipy is not running from the source code
https://github.com/scipy/scipy/blob/master/setup.py
https://github.com/scipy/scipy/blob/master/scipy/__init__.py

So, catching an error like this _is quite common_. The other projects have measures in place to run from source code.

And other than that, is the current approach not unreliable? Say I have the latest Lasagne installed, but have a lingering lasagne source in the lib directory of my project. If I ask for the `lasagne.__version__` in my project, won't I get the wrong __version__ reported?

**Comment by benanne** [comment]
Those are all good points -- I will let those who are more familiar with Python package versioning chime in, because I basically have no idea :)

**Comment by f0k** [comment]
I also bumped into that at some point, and I'd be totally fine with just hard-coding it. We're not changing the version that often, and changing it at two places instead of one wouldn't be that problematic.

**Comment by benanne** [comment]
I guess we should add a test that checks if they are equal then, or something like that? Seems like something that could be easily forgotting when creating a new release, because it happens so rarely.

**Comment by ebenolson** [comment]
I'm just going to put in another plug here for [versioneer](https://github.com/warner/python-versioneer).

**Comment by f0k** [comment]
> I guess we should add a test that checks if they are equal then, or something like that?

That's not easily possible. One of the version strings lives in `setup.py` (which cannot import `__init__.py` because that version of Lasagne isn't installed yet), and the other one lives in `__init__.py` (which cannot import `setup.py` because that's not installed along with Lasagne). We could move the version string into a data file that's read with `open()` and installed along with Lasagne, or we could have `setup.py` parse the `__init__.py` file instead of importing it (I think I've seen this technique being used somewhere, it would just have to find the `__version__ = ` assignment).

> Seems like something that could be easily forgotting when creating a new release, because it happens so rarely.

There are only two places. It would be very easy to put a comment at the first place to update the second place and vice versa!

> I'm just going to put in another plug here for versioneer.

I think using versioneer just to keep the two strings synced would be overkill, but it would give us version strings including the git commit.

**Comment by benanne** [comment]
> There are only two places. It would be very easy to put a comment at the first place to update the second place and vice versa!

Also true. I guess I can live with that :)

Re: versioneer I have no strong opinion either way at the moment. I recall there being a discussion about this before though, so I should probably re-read that.
