### ISSUE TITLE
Multidirectional MDRNN implementation

### ISSUE THREAD

**Issue by davidbuniat** [Lasagne/Lasagne#483]
Hi, I was wondering if anyone implemented Grave's Mutlidirectional MDRNN [1]. How can I tackle the problem given CustomRecurrentLayer class or the class itself should be modified for handling mutli-direction?

[1] Graves, Alex: "Generating sequences with recurrent neural networks." arXiv preprint arXiv:1308.0850 (2013).

**Comment by eralmansouri** [comment]
A bidirectional LSTM implementation is in the examples. Am I misunderstanding your question?

https://github.com/Lasagne/Lasagne/blob/master/examples/recurrent.py

**Comment by davidbuniat** [comment]
A bidirectional LSTM works on 1D sequential data (text, sound, etc. ). Alex Grave's in his PhD thesis expanded the concept to ND (multi-dimensional) sequential data which can work for images, videos etc. I am looking into the implementation of his proposed Multi-directional Multidimensional Recurrent Neural Network.

**Comment by f0k** [comment]
Do you mean Graves/Fernandez/Schmidhuber (2007): "Multi-Dimensional Recurrent Neural Network", http://arxiv.org/abs/0705.2011? That one cannot directly be implemented with the `CustomRecurrentLayer`. It requires a nested loop, while all the layers in `lasagne.layers.recurrent` only use a single Theano `scan()`. You will need to write your own layer for this, and I guess a nested loop in Theano will be very slow to compile and run. Sorry for the bad news!

If you still want to try and need any help with it, please post on our mailing list instead: https://groups.google.com/forum/#!forum/lasagne-users
Thanks!

**Comment by icemansina** [comment]
I am also seeking for the Multi-Dimensional RNN for image application. According to your description and corresponding papers, it is necessary to use a nested loop for two dimensional RNN. Is it possible for implementation based on Lasagne or Theano considering your experience. Thanks a lot.

**Comment by davidbuniat** [comment]
I posted the problem in the Google Group https://groups.google.com/forum/#!topic/lasagne-users/mOUbQh-RvIY Anyone interested in Multi-Dimensional RNN we can continue the conversation for implementation their.

**Comment by f0k** [comment]
> Is it possible for implementation based on Lasagne or Theano considering your experience.

As I said, it is possible with Lasagne and Theano, but it will require writing your own layer and it will probably be slow.

Before going that route, note that a multi-dimensional RNN will only help you if it learns to take into account a *lot* of context, otherwise you're better off with a CNN that takes into account a fixed amount of context (which can be exactly controlled via the filter sizes in your stack of convolutional layers). The original paper I linked above is from 2007, and a lot has changed in the past 8 years!
