### ISSUE TITLE
upgrade Theano commit requirement for Lasagne to pymc3 level of need

### ISSUE THREAD

**Issue by stonebig** [Lasagne/Lasagne#489]
Hi,

In order to have both pymc3 and Lasagne working, I have two conflicting requirements:
- pymc3: https://github.com/Theano/Theano/commit/bdcb752aa9abcaf8a7fb1e8e56d981e9bc151058 or better
- Lasagne: git+https://github.com/Theano/Theano.git@15c90dd3#egg=Theano==0.8.git

Would it be possible to find a common commit for both projects ?

**Comment by ebenolson** [comment]
The Theano requirement is pinned to the earliest version that works for Lasagne, but any later version should be fine.

**Comment by stonebig** [comment]
ok, will take the latest.
