### ISSUE TITLE
Add CONTRIBUTING file

### ISSUE THREAD

**Issue by f0k** [Lasagne/Lasagne#492]
If we add a `CONTRIBUTING` or `CONTRIBUTING.md` file, this will be linked from the "New Issue" or "New Pull Request" page. This might help us direct traffic away from the issue tracker to the mailing list.

https://help.github.com/articles/setting-guidelines-for-repository-contributors/

**Comment by ebenolson** [comment]
:+1:

**Comment by benanne** [comment]
Sounds like a plan! We should keep it as short as possible though (2 or 3 paragraphs at the most maybe), so people actually bother to read it.

**Comment by f0k** [comment]
Yes, I'd probably just go for three bullet points making clear where to get support, what goes in an issue and what's important for pull requests (mostly a single sentence with a link). There are some examples at the bottom of the github.com article I linked above.

**Comment by benanne** [comment]
Sounds great!

**Comment by benanne** [comment]
It looks like we are still getting a fair few support questions submitted as issues. The contribution guidelines are still too easy to miss, despite the link at the top of the issue submission form.

Maybe we should look into issue templates instead?
https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by f0k** [comment]
Cool, didn't know about that! Yes, this seems like a good way to let more people know about the mailing list. The blog post mentions the possibility of placing these files into a `.github` directory, this seems useful as well.
