### ISSUE TITLE
IndexError with current network architecture

### ISSUE THREAD

**Issue by ssampang** [Lasagne/Lasagne#494]
Hi all,

This might be an issue with me just not creating the network layer sizes correctly. I was trying to follow the [MNIST example](https://github.com/Lasagne/Lasagne/blob/master/examples/mnist.py), and change the layer sizes of that network to match my own input (a 2x361 feature vector). This is the relevant code:

```
def build_cnn(input_var=None):
	network = lasagne.layers.InputLayer(shape=(None,2,361), input_var = input_var)
	conv1 = lasagne.layers.Conv2DLayer(network,num_filters=10,filter_size=(1,50),nonlinearity=ReLU,W=lasagne.init.GlorotUniform())
	network = lasagne.layers.MaxPool2DLayer(conv1, (1,5))
	conv2 = lasagne.layers.Conv2DLayer(network,num_filters=10,filter_size=(1,50),nonlinearity=ReLU,W=lasagne.init.GlorotUniform())
	network = lasagne.layers.MaxPool2DLayer(conv2, pool_size=(1,5))
	network = lasagne.layers.DenseLayer(network, num_units=100,nonlinearity=ReLU)
	network = lasagne.layers.DenseLayer(network,num_units=2,nonlinearity = lasagne.nonlinearities.softmax)
	return network

input_var = T.tensor3('inputs')
target_var = T.ivector('targets')

network = build_cnn(input_var)
```

Unfortunately, I get the following error:
```
Traceback (most recent call last):
  File "CNN.py", line 51, in <module>
    network = build_cnn(input_var)
  File "CNN.py", line 41, in build_cnn
    network = lasagne.layers.MaxPool2DLayer(conv1, pool_size=(1,5))
  File "/home/sid/.local/lib/python2.7/site-packages/lasagne/layers/pool.py", line 362, in __init__
    **kwargs)
  File "/home/sid/.local/lib/python2.7/site-packages/lasagne/layers/pool.py", line 215, in __init__
    super(Pool2DLayer, self).__init__(incoming, **kwargs)
  File "/home/sid/.local/lib/python2.7/site-packages/lasagne/layers/base.py", line 35, in __init__
    self.input_shape = incoming.output_shape
  File "/home/sid/.local/lib/python2.7/site-packages/lasagne/layers/base.py", line 49, in output_shape
    return self.get_output_shape_for(self.input_shape)
  File "/home/sid/.local/lib/python2.7/site-packages/lasagne/layers/conv.py", line 452, in get_output_shape_for
    output_columns = conv_output_length(input_shape[3],
IndexError: tuple index out of range

```

I've tried multiple changes with the network including removing the pooling layers such that the conv layers are sequential, and switching out the pooling layers for a single dense layer between the conv layers, but the error remains. If I don't add in the pooling layers, I get the same error for the second conv layer (basically any layer directly after the first conv layer).

I'm sure I'm just doing something stupid - I just dont know what it is. Also, no similar results on google.

Any help appreciated,
Sid

**Comment by benanne** [comment]
Hi Sid,

if you want to use 2D convolutional layers in your network, your input will have to be 4D: (batch_size, num_features, height, width). As far as I can tell you are passing in 3D tensors, so Conv2DLayer doesn't know what to do with that. The error message is a bit hard to decipher though, maybe we could do something about that.

By the way, for questions like these the best venue is our mailing list: https://groups.google.com/forum/#!forum/lasagne-users
We prefer to keep the GitHub issues for development and bug reporting only. Thanks for your cooperation.

**Comment by ssampang** [comment]
@benanne Thanks! That did the trick. Also, will post on the google group henceforth.

-Sid
