### ISSUE TITLE
GRULayer - learn_init=True inconsistent with the rest

### ISSUE THREAD

**Issue by Botev** [Lasagne/Lasagne#496]
I guess it might be a typo, or there is some reason for this?

**Comment by benanne** [comment]
Good point, that is a bit inconsistent. All other recurrent layers have this set to `False` by default. Any reason for this discrepancy, @craffel, @skaae ?

**Comment by skaae** [comment]
no, i think its a typo.

**Comment by craffel** [comment]
PR: #497
