### ISSUE TITLE
Allow parameter sharing

### ISSUE THREAD

**Issue by Botev** [Lasagne/Lasagne#500]
So currently it is quite hard to nail parameter sharing or having a symbolic variable be the "weights" of the layer. I do not know how many people have thought about this, but I see a few usecases for this, ranging from autoencoders to rnns. I've hacked something, however I might be missing an important part so was wondering if someone can give an advice/thought or maybe its a very bad idea. Essentially I modified the `add_param()` in the `base.py` of layers to check for a `TensorVariable` or `SharedVariable` instance, and would look something like this. So far I did not see any obvious drawbacks, but I'm sort of thinking I'm missing something. Potentially, if it is a `SharedVariable` could be added to self.params, since usually for `updates` you call `unique`, however I'm personally not for this.
```
if not isinstance(spec, (T.TensorVariable, theano.compile.SharedVariable)):
    if name is not None:
        if self.name is not None:
            name = "%s.%s" % (self.name, name)
    # create shared variable, or pass through given variable/expression
    param = utils.create_param(spec, shape, name)
    # parameters should be trainable and regularizable by default
    tags['trainable'] = tags.get('trainable', True)
    tags['regularizable'] = tags.get('regularizable', True)
    self.params[param] = set(tag for tag, value in tags.items() if value)
    return param
```

**Comment by f0k** [comment]
> So currently it is quite hard to nail parameter sharing or having a symbolic variable be the "weights" of the layer.

No, it's fairly easy: http://benanne.github.io/2015/11/10/arbitrary-expressions-as-params.html

> I do not know how many people have thought about this

We did that a year ago (#11) and I finally implemented it a month ago (#404). Simple parameter sharing (using the same shared variables for two layers) was always possible, and using other expressions is possible since #404. If there's anything missing, feel free to reopen and elaborate!

**Comment by Botev** [comment]
Hmm, however I tried passing not an expression like `W.T`, but just the W and it gives me an error cause it tries to call it as an initializer.

**Comment by f0k** [comment]
That would be a bug then, can you post a minimal example along with the error?

**Comment by f0k** [comment]
For me, it works:
```python
In [1]: import lasagne
Using gpu device 0: GeForce GT 640 (CNMeM is disabled)

In [2]: l1 = lasagne.layers.DenseLayer((10,20), 30)

In [3]: l2 = lasagne.layers.DenseLayer((10,20), 30, W=l1.W)
```

**Comment by Botev** [comment]
Hmm that is strange now that I try it it works... sorry about that probably I did something fishy earlier might need to investigate what was I exactly doing.
