### ISSUE TITLE
EmbeddingLayer not work

### ISSUE THREAD

**Issue by VikingMew** [Lasagne/Lasagne#503]
lembed = lasagne.layers.EmbeddingLayer(linput,input_size=E.shape[0],output_size=config.embeddingSize, W=E)
lhidden = lasagne.layers.DenseLayer(lembed,num_units=config.hiddenSize,W=W1,b=b1)

  File "/home//anaconda3/lib/python3.4/site-packages/lasagne/layers/embedding.py", line 64, in get_output_shape_for
    return input_shape + (self.output_size, )
TypeError: can only concatenate list (not "tuple") to list

**Comment by benanne** [comment]
What is `linput`? Is it an unmodified Lasagne `InputLayer`?

By the way, questions like these are more appropriate for our mailing list: https://groups.google.com/forum/#!forum/lasagne-users
We would prefer to keep the GitHub issue queue focussed on development and bug reporting.
