### ISSUE TITLE
Transfer learning in lasagne

### ISSUE THREAD

**Issue by shashankg7** [Lasagne/Lasagne#507]
I used following architecture of CNN to train on cifar10 dataset:
```python
def build_cnn(input_var, input_shape=(3, 32, 32),
              num_crp=3, crp_num_filters=128, crp_filter_size=5,
              num_cr=1,
              num_fc=1, fc_num_units=256,
              output_type='softmax', num_classes=10,
              **junk):
    # input layer
    network = lasagne.layers.InputLayer(shape=(None,) + input_shape,
                                        input_var=input_var)
    # conv-relu-pool layers
    for i in range(num_crp):
        network = lasagne.layers.Conv2DLayer(
            network, num_filters=crp_num_filters,
            filter_size=(crp_filter_size, crp_filter_size),
            pad='same',
            nonlinearity=lasagne.nonlinearities.rectify,
            W=lasagne.init.GlorotUniform(gain='relu'))
        network = lasagne.layers.MaxPool2DLayer(network, pool_size=(2, 2))
    # conv-relu
    for i in range(num_cr):
        network = lasagne.layers.Conv2DLayer(
            network, num_filters=crp_num_filters,
            filter_size=(crp_filter_size, crp_filter_size),
            pad='same',
            nonlinearity=lasagne.nonlinearities.rectify,
            W=lasagne.init.GlorotUniform(gain='relu'))
    # fc-relu
    for i in range(num_fc - 1):
        network = lasagne.layers.DenseLayer(
            lasagne.layers.dropout(network, p=.5),
            num_units=fc_num_units,
            nonlinearity=lasagne.nonlinearities.rectify)
    # output layer
    assert output_type=='softmax'
    network = lasagne.layers.DenseLayer(
        lasagne.layers.dropout(network, p=.5),
        num_units=num_classes,
        nonlinearity=lasagne.nonlinearities.softmax)
    return network
```

I want to extract features from input once network is trained. Last two layers are fully connected NN for classification. I tried to extract from 3rd last layer using the following code:
```python
    net1 = lasagne.layers.get_all_layers(network)
    feat_layer = lasagne.layers.get_output(net1[len(net1)-3])
    input_variable = net1[0].input_var
    f_output = theano.function([input_variable],feat_layer)
    num_test = X_test.shape[0]
    X = X_test[0][None,:,:]
    instance = f_output(X)
    for i in range(num_test):
        instance = np.vstack((instance,f_output(X_test[i][None,:,:]).flatten()))
```

But I am getting tensor of dimension (1,128,4,4) as output everytime I change layer from 3rd last to 4th last and so on. Where I am getting wrong, can anyone help?

**Comment by f0k** [comment]
Please post such questions on our mailing list instead: https://groups.google.com/forum/#!forum/lasagne-users
The github issue tracker is meant for bug reports and feature discussions.

> But I am getting tensor of dimension (1,128,4,4) as output everytime I change layer from 3rd last to 4th last and so on. Where I am getting wrong, can anyone help?

You're using `pad='same'` and the same number of filters, so the output of the last two convolutional layers will be same size. When you go further backwards, you should get `(1, 128, 8, 8)`, `(1, 128, 16, 16)` and `(1, 128, 32, 32)` as well. The following will print all the expected shapes:
```python
print [(layer, layer.output_shape) for layer in net1[1:]]
```

I'm closing this issue, let's continue discussion on the mailing list if there are open questions!

PS: Note that you can use `net1[-3]` as a shortcut for `net1[len(net1) - 3]` almost everywhere in Python.
