### ISSUE TITLE
Error when importing into python

### ISSUE THREAD

**Issue by freundzi** [Lasagne/Lasagne#510]
Hi,
I recieved the following error when importing lasage.layers.dnn int python:
===============================
In file included from /usr/include/python2.7/Python.h:8:0,
                 from mod.cu:1:
/usr/include/python2.7/pyconfig.h:1161:0: warning: "_POSIX_C_SOURCE" redefined [enabled by default]
/usr/include/features.h:164:0: note: this is the location of the previous definition
/usr/include/python2.7/pyconfig.h:1183:0: warning: "_XOPEN_SOURCE" redefined [enabled by default]
/usr/include/features.h:166:0: note: this is the location of the previous definition
<built-in>:0:0: fatal error: when writing output to : No space left on device
compilation terminated

this is after a few days ago evertyhing worked fine.
Any help would be appreciated !
Ziv

**Comment by f0k** [comment]
> fatal error: when writing output to : No space left on device

How much space is left on your device then? What does `df -h` say?

**Comment by freundzi** [comment]
A lot, more than 100gb.
The tmp folder has only 1mb, ill try to increase it.
However, it is disturbing that the error does not specify the location.

**Comment by f0k** [comment]
> However, it is disturbing that the error does not specify the location.

That's right, but unfortunately we cannot do anything about this in Lasagne, this is in Theano. You could try asking at [theano-users](https://groups.google.com/forum/#!forum/theano-users) for help. There should be a way to get it to display the full command line it was trying to execute, which will include the path. Closing this!

**Comment by nouiz** [comment]
That isn't in Theano, probably in g++.

You can set the TMPDIR env variable to tell g++ to use another tmp
directory. This would also afect the creation of Python tmp directory and
so will help at other places too.
