### ISSUE TITLE
Official dump/load methods

### ISSUE THREAD

**Issue by petrbel** [Lasagne/Lasagne#516]
I read #161, #159 and #7 with a [solution](https://gist.github.com/senbon/70adf5410950c0dc882b) of saving and loading models. But it's unofficial and it requires implementing some external functions that are probably repeated in many projects.

I wonder why there isn't `save` and `load` functions directly in the model. The user could easily call `network.save('file.dat')`. The other question is (if we don't like save/load functions) why there isn't `pickle` support?

Is there some reason that is hidden to me? I'm no expert, of course, but I'd really like to have these methods and I'm willing to implement them if it is desirable.

Thanks for comments :)

**Comment by benanne** [comment]
It should be possible to pickle an entire model if you want to, but there are issues in Theano with loading GPU-trained models on CPU-only machines. So it's not recommended. The better way is just to grab the parameter values (with `get_all_param_values()`) and store those.

Implementing save/load directly on the layer class would require some assumptions on our part regarding how you want to store it exactly:
- the model itself, or just the parameters
- file format: pickle, numpy array file (npy / npz), HDF5, ...

I think these are choices we would rather leave to the user. Everyone has their own favourite data format these days.

Perhaps we should consider providing some general parameter storage functions as part of `lasagne.utils`. Definitely not as layer methods though, we want to keep the code size down in the interest of readability (and it would also be problematic for models with multiple output layers).

**Comment by petrbel** [comment]
I see. Thanks for explanation anyway :)
