### ISSUE TITLE
Relu weight init doc problem?

### ISSUE THREAD

**Issue by colinfang** [Lasagne/Lasagne#520]
From the [doc](http://lasagne.readthedocs.org/en/latest/modules/init.html#lasagne.init.Glorot) or [source](https://github.com/Lasagne/Lasagne/blob/master/lasagne/init.py#L103), it says:

```{python}
For a :class:`DenseLayer <lasagne.layers.DenseLayer>`, if ``gain='relu'``
    and ``initializer=Uniform``, the weights are initialized as
    .. math::
       a &= \\sqrt{\\frac{6}{fan_{in}+fan_{out}}}\\\\
       W &\sim U[-a, a]
```
But from what I read from the souce, the formula is true for a sigmoid activator. In case of Relu, it should be `U[-sqrt(2)a, sqrt(2)a]`, as the gain is `sqrt(2)`.

Am I right?

**Comment by ebenolson** [comment]
No, the gain is lumped in with the additional factor `sqrt(3)` from the conversion of standard deviation to bounds of the uniform distribution. I'd agree this may not be the most clear example though, since it depends on knowing the behavior of the `Uniform` class.

**Comment by colinfang** [comment]
But there exists an extra `sqrt(2)` from the fact that the `std` is `sqrt(2 / (in + out))` for the sigmoid case.

**Comment by ebenolson** [comment]
My mistake, yes I think you are correct.
