### ISSUE TITLE
Revamp Convolutional Layers

### ISSUE THREAD

**Issue by f0k** [Lasagne/Lasagne#524]
We should refactor/clean up the different convolutional layers in Lasagne:

* [x] Refactor the existing code to have a common base class for all convolution dimensionalities and all implementations (as discussed in #498)
* [x] Reconsider the interface(s) of the convolutional layers in light of the new `conv2d()` interface in Theano -- can `Conv2DLayer` support more than it does now, and should we drop some of the implementation-specific layers?
* [x] Add a `Deconv2DLayer`. Theano provides a placeholder Op for the gradient wrt. input now, so we can provide a more direct route than via the `InverseLayer`.
* [x] Document that the implementation-specific layers not only live outside the `lasagne.layers` namespace (I think this is probably clear from the way it's documented), but also that their modules are not imported by default. (#535)

(Side issue: At least the first step would be interesting for pooling as well.)

**Comment by ebenolson** [comment]
> should we drop some of the implementation-specific layers?

If this happens, I think it's important to make sure we don't have cases where tweaking a parameter causes a switch to a slow implementation, or provide prominent warnings. I really like being able to explicitly use cuDNN.

**Comment by f0k** [comment]
>> should we drop some of the implementation-specific layers?

> I really like being able to explicitly use cuDNN.

I also tend towards keeping them. When I refactor the code, the class won't be more than a long docstring and a single `convolve(self, inputs)` method that calls `dnn_conv()`, so it won't be as much of a burden to maintain.

**Comment by benanne** [comment]
That sounds like a good deal. We would have to keep them around with deprecation warnings for a long time anyway. I don't think they should necessarily be removed, it would just be nice that you can use `Conv2DLayer` in almost all cases and don't have to worry about slowdowns.

**Comment by benanne** [comment]
Now that #541 is merged we can check the first two boxes, if I'm not mistaken :)

**Comment by fvisin** [comment]
Regarding the `Deconv2DLayer`, we recently merged a PR in Theano that introduces a deconvolution interface (https://github.com/Theano/Theano/pull/3872) and we will add soon a "more user-friendly alias" (https://github.com/Theano/Theano/issues/3989). 

If I have time I'll wrap it into a Lasagne layer and submit a PR.

**Comment by benanne** [comment]
Sweet! :)

**Comment by f0k** [comment]
I posted an implementation [on our mailing list some time ago](https://groups.google.com/forum/#!msg/lasagne-users/KB4SmoODtkg/FKCaR5wlCwAJ):
```python
class Deconv2DLayer(lasagne.layers.Layer):

    def __init__(self, incoming, num_filters, filter_size, stride=1, pad=0,
            nonlinearity=lasagne.nonlinearities.rectify, **kwargs):
        super(Deconv2DLayer, self).__init__(incoming, **kwargs)
        self.num_filters = num_filters
        self.filter_size = lasagne.utils.as_tuple(filter_size, 2, int)
        self.stride = lasagne.utils.as_tuple(stride, 2, int)
        self.pad = lasagne.utils.as_tuple(pad, 2, int)
        self.W = self.add_param(lasagne.init.Orthogonal(),
                (self.input_shape[1], num_filters) + self.filter_size,
                name='W')
        self.b = self.add_param(lasagne.init.Constant(0),
                (num_filters,),
                name='b')
        if nonlinearity is None:
            nonlinearity = lasagne.nonlinearities.identity
        self.nonlinearity = nonlinearity

    def get_output_shape_for(self, input_shape):
        shape = tuple(i*s - 2*p + f - 1
                for i, s, p, f in zip(input_shape[2:],
                                      self.stride,
                                      self.pad,
                                      self.filter_size))
        return (input_shape[0], self.num_filters) + shape

    def get_output_for(self, input, **kwargs):
        op = T.nnet.abstract_conv.AbstractConv2d_gradInputs(
            imshp=self.output_shape,
            kshp=(self.input_shape[1], self.num_filters) + self.filter_size,
            subsample=self.stride, border_mode=self.pad)
        conved = op(self.W, input, self.output_shape[2:])
        if self.b is not None:
            conved += self.b.dimshuffle('x', 0, 'x', 'x')
        return self.nonlinearity(conved)
```
It doesn't support string shortcuts for the `pad` parameter yet and lacks docstrings and tests, but should provide a good basis.

**Comment by fvisin** [comment]
I am sorry it took me so long, but I finally did a PR to add the transposed convolution layer: #656
