### ISSUE TITLE
learning rate in nesterov_momentum

### ISSUE THREAD

**Issue by Medeah** [Lasagne/Lasagne#527]
Why is the learning rate not part of the formula presented in the documentation for  nesterov_momentum:
```
velocity := momentum * velocity + updates[param] - param
param := param + momentum * velocity + updates[param] - param
```
Looking at the code it looks like it is used in the same way as momentum.

**Comment by f0k** [comment]
Good catch, it seems this was just copied over from apply_nesterov_momentum(): http://lasagne.readthedocs.org/en/latest/modules/updates.html#lasagne.updates.apply_nesterov_momentum
I'll fix it.
