### ISSUE TITLE
Add RReLu nonlinearity

### ISSUE THREAD

**Issue by jonhoo** [Lasagne/Lasagne#530]
Some of you may have seen it, but the paper [Empirical Evaluation of Rectified Activations in Convolutional Network](http://arxiv.org/abs/1505.00853) compares several rectifier variants, and shows that Randomized ReLUs (uniform random a during training) can outperform PReLUs on CIFAR-10 & CIFAR-100 on the test set. RReLus have been [discussued](https://github.com/torch/nn/issues/380), [merged](https://github.com/torch/nn/pull/437), and [documented](https://github.com/torch/nn/blob/master/doc/transfer.md#rrelu) in Torch. That documentation link above also gives a fairly straightforward expression of what RReLus are.

I suspect it shouldn't be too hard to add support for RReLus in Lasagne, but I have little experience with the Lasagne internals. I believe it should simply be a matter of copying [`LeakyRectify`](https://github.com/Lasagne/Lasagne/blob/master/lasagne/nonlinearities.py#L160), replacing the leakiness with min+max, setting up a [Theano shared random stream](http://deeplearning.net/software/theano/tutorial/examples.html#brief-example), and using that to pick the leakiness. I'm not entirely sure how to make the leakiness be `(l+u)/2` during evaluation though...

**Comment by f0k** [comment]
> I believe it should simply be a matter of [...]

Sounds good, but:

> I'm not entirely sure how to make the leakiness be `(l+u)/2` during evaluation though...

This is a dealbreaker for implementing it as a simple nonlinearity. Only `Layer.get_output_for()` can see the `deterministic` keyword argument that's commonly used to replace probabilistic behavior by deterministic behavior. So the solution is to implement RReLUs as a `Layer`, similar to how it was done for the `PReLU`: http://lasagne.readthedocs.org/en/latest/modules/layers/special.html#lasagne.layers.ParametricRectifierLayer

Would you like to try that and send a PR? Do you need further hints on what to do? It will probably become a medley of the `DropoutLayer` and `ParametricRectifierLayer`, just use their source code for guidance and feel free to come back with any questions!

**Comment by jonhoo** [comment]
See #533.
