### ISSUE TITLE
How to save trained model?

### ISSUE THREAD

**Issue by HadXu** [Lasagne/Lasagne#536]
I had trained a model,but I want to save model,what to do?

**Comment by benanne** [comment]
This question is more appropriate for our mailing list: https://groups.google.com/forum/#!forum/lasagne-users
We try to keep the GitHub issue queue restricted to bug reports and development only. Thanks for your cooperation.

Have a look at these discussions on the topic:
https://groups.google.com/forum/#!searchin/lasagne-users/save$20model/lasagne-users/w8safJOJYvI/ofkMjr_EDQAJ
https://groups.google.com/forum/#!searchin/lasagne-users/save$20parameters/lasagne-users/DXxP9cavoj4/l-mMp-onCAAJ

If you have any more questions about this, feel free to post them on the mailing list!

**Comment by HadXu** [comment]
I am very sorry for that!Thank you!
