### ISSUE TITLE
Typos in the documentation

### ISSUE THREAD

**Issue by pedromnasc** [Lasagne/Lasagne#538]
Hi everyone,

i want to warn about some possible typos:

1) In the documentation of orthogonal initialization there is this equation: sqrt(2/(1+alpha**2)

, shouldn't it be: sqrt(2/(1+alpha**2))

2) In the documentation of Spatial Transform Layer:

>The layer applies an affine transformation on the input. The affine transformation is parameterized with six learned parameters [R40]. The output is interpolated with a bilinear transformation.

The number of parameters must be six? I think it is "only" the original use case.

Thanks for the excellent work with Lasagne!!!

**Comment by f0k** [comment]
> 1) In the documentation of orthogonal initialization there is this equation: sqrt(2/(1+alpha**2)

Thanks, good spot. Have submitted a PR fixing this.

> The number of parameters must be six?

Yes, the `TransformerLayer` requires six parameters. It currently doesn't support omitting some of them for a less expressive transformation.
