### ISSUE TITLE
CNN-LSTM

### ISSUE THREAD

**Issue by imochaz** [Lasagne/Lasagne#544]
Hi,

I am implementing a CNN-LSTM, but I was struggling when I was trying to reshape the output from CNN to be in the input shape required by LSTM. See below.

```
network = lasagne.layers.InputLayer(
    shape=(None, n_channels, height, width),
    input_var=input_var
)
network = lasagne.layers.dnn.Conv2DDNNLayer(
    network,
    num_filters=40,
    filter_size=(4, 4),
    stride=(2, 2),
    nonlinearity=lasagne.nonlinearities.rectify,
    W=lasagne.init.GlorotUniform()
)
network = lasagne.layers.dnn.MaxPool2DDNNLayer(
    network,
    pool_size=(2, 2)
)

### Reshape input into the shape (batch_size, sequence_length, num_inputs) ###

network = lasagne.layers.LSTMLayer(
    network, 
    n_hidden,
    nonlinearity=lasagne.nonlinearities.tanh
)
network = ReshapeLayer(
    network, 
    (-1, 250)
)
network = lasagne.layers.DenseLayer(
    lasagne.layers.dropout(network, p=.5),
    num_units=250,
    nonlinearity=lasagne.nonlinearities.rectify
)
network = lasagne.layers.DenseLayer(
    lasagne.layers.dropout(network, p=.5),
    num_units=2,
    nonlinearity=lasagne.nonlinearities.softmax
)
```

As CNN receive each input at a time, how can I design the ``network`` so that LSTM receives input with ``sequence_length=5``?

Thanks

**Comment by f0k** [comment]
You will want to form your input batches for the CNN such that the 5 time steps always follow one another. Then, at the place you indicated, just insert a `FlattenLayer(network)` to reshape the feature maps into a vector, and a `ReshapeLayer(network, (-1, 5, [1]))` to group together every 5 items of your minibatch into a single sequence. Have a look into the documentation for FlattenLayer and ReshapeLayer if you're unsure.

In future, please post such questions on our mailing list (https://groups.google.com/forum/#!forum/lasagne-users), the issue tracker is meant for bug reports and feature discussions. Thanks!
