### ISSUE TITLE
Use theano.tensor.switch in LSTM Layer in masked step

### ISSUE THREAD

**Issue by avostryakov** [Lasagne/Lasagne#550]
I'm curious why theano.tensor.switch isn't used in the following place: https://github.com/Lasagne/Lasagne/blob/master/lasagne/layers/recurrent.py#L1077

not_mask = 1 - mask_n
cell = cell*mask_n + cell_previous*not_mask
hid = hid*mask_n + hid_previous*not_mask

we can rewrite this code as following:

cell = T.switch(mask_n, cell, cell_previous)
hid = T.switch(mask_n, hid, hid_previous)

How I see it runs with the same speed but anyway why you don't use 'switch'?

**Comment by skaae** [comment]
Have you confired that it works? if so there is no particular reason that we do not use switch :) You are more than welcome to time it on cpu and gpu!

**Comment by avostryakov** [comment]
First of all, I created a simple example:

import numpy as np
import theano
import theano.tensor as T

x = T.fmatrix('x')
y = T.fmatrix('x')
m = T.imatrix('m')

output = T.switch(m, x, y)
output_fn = theano.function([x, y, m], output, mode='FAST_RUN')

x_n = np.ones((3, 10), dtype=np.float32)
y_n = np.zeros((3, 10), dtype=np.float32)
x_n[:, 0] = 2.0
y_n[:, 0] = 5.0
y_n[:, 8] = 3.0
y_n[:, 9] = 5.0
m_n = np.ones((3, 10), dtype=np.int32)
m_n[:, 9] = 0
m_n[:, 8] = 0

print output_fn(x_n, y_n, m_n)

Output:
[[ 2.  1.  1.  1.  1.  1.  1.  1.  3.  5.]
 [ 2.  1.  1.  1.  1.  1.  1.  1.  3.  5.]
 [ 2.  1.  1.  1.  1.  1.  1.  1.  3.  5.]]

All works how it is expected.

At second, I took lasagne recurrent example: https://github.com/Lasagne/Lasagne/blob/master/examples/recurrent.py

I tried the example without any modifications (only added time measurement). Results:
 - CPU:
Epoch 0 validation cost = 0.0688457875194
Epoch tooks 16.328s
Epoch 1 validation cost = 0.028865720423
Epoch tooks 16.567s
Epoch 2 validation cost = 0.0178229600844
Epoch tooks 16.546s
Epoch 3 validation cost = 0.016658732813
Epoch tooks 16.557s
Epoch 4 validation cost = 0.0141251974018
Epoch tooks 16.687s
Epoch 5 validation cost = 0.0143786395363
Epoch tooks 16.645s
Epoch 6 validation cost = 0.0139143127762
Epoch tooks 17.463s
Epoch 7 validation cost = 0.0120921117769
Epoch tooks 16.580s
Epoch 8 validation cost = 0.012654618122
Epoch tooks 16.603s
Epoch 9 validation cost = 0.00922488035047
Epoch tooks 16.611s

 - GPU
Epoch 0 validation cost = 0.0694505646825
Epoch tooks 2.243s
Epoch 1 validation cost = 0.0373803600669
Epoch tooks 2.234s
Epoch 2 validation cost = 0.0231883041561
Epoch tooks 2.231s
Epoch 3 validation cost = 0.0278937723488
Epoch tooks 2.229s
Epoch 4 validation cost = 0.0210238900036
Epoch tooks 2.229s
Epoch 5 validation cost = 0.0283807311207
Epoch tooks 2.230s
Epoch 6 validation cost = 0.0140059422702
Epoch tooks 2.232s
Epoch 7 validation cost = 0.0206452645361
Epoch tooks 2.230s
Epoch 8 validation cost = 0.0231954474002
Epoch tooks 2.237s
Epoch 9 validation cost = 0.0234997197986
Epoch tooks 2.229s

After it I replace the following line in https://github.com/Lasagne/Lasagne/blob/master/lasagne/layers/recurrent.py#L442

hid_out = hid*mask_n + hid_previous*(1 - mask_n)
on:
hid_out = T.switch(mask_n, hid, hid_previous)

Results for CPU:
Epoch 0 validation cost = 0.047338658931
Epoch tooks 15.947s
Epoch 1 validation cost = 0.0244674165043
Epoch tooks 15.740s
Epoch 2 validation cost = 0.0156295154771
Epoch tooks 15.665s
Epoch 3 validation cost = 0.0138679970066
Epoch tooks 15.983s
Epoch 4 validation cost = 0.0126286862563
Epoch tooks 15.837s
Epoch 5 validation cost = 0.0161567894884
Epoch tooks 16.163s
Epoch 6 validation cost = 0.0105125567767
Epoch tooks 16.498s
Epoch 7 validation cost = 0.00989797278958
Epoch tooks 16.248s
Epoch 8 validation cost = 0.0116344351554
Epoch tooks 16.021s
Epoch 9 validation cost = 0.0103609594182
Epoch tooks 15.997s

for GPU:
Epoch 0 validation cost = 0.066644847393
Epoch tooks 2.239s
Epoch 1 validation cost = 0.0250374842435
Epoch tooks 2.236s
Epoch 2 validation cost = 0.0186377726495
Epoch tooks 2.238s
Epoch 3 validation cost = 0.00966571550816
Epoch tooks 2.234s
Epoch 4 validation cost = 0.0116246994585
Epoch tooks 2.236s
Epoch 5 validation cost = 0.00955564435571
Epoch tooks 2.238s
Epoch 6 validation cost = 0.0122297005728
Epoch tooks 2.236s
Epoch 7 validation cost = 0.00811908580363
Epoch tooks 2.237s
Epoch 8 validation cost = 0.0071579432115
Epoch tooks 2.236s
Epoch 9 validation cost = 0.00821639504284
Epoch tooks 2.241s

So, the quality is the same, the speed on CPU is better, on GPU the speed is the same.

**Comment by benanne** [comment]
Cool! And the version with switch is more readable to boot. I'm all for changing it. Thanks for taking the time to benchmark both options :)

**Comment by skaae** [comment]
Nice work. I'm fine with changing this. Do you want to make a pr?

**Comment by skaae** [comment]
I'm too slow :)

**Comment by avostryakov** [comment]
yes, I did it!
