### ISSUE TITLE
Raise a warning when a keyword passed to `get_output()` is unused

### ISSUE THREAD

**Issue by benanne** [Lasagne/Lasagne#557]
`lasagne.layers.get_output()` can be called with keyword arguments, which are passed to all traversed layers. This makes it possible to control layers with multiple behaviours (e.g. dropout, which can be turned on or off, or batch normalization, which can use minibatch statistics or aggregated statistics).

The most common use case for this is the `deterministic` keyword, which is used to turn off any regularizing noise in the net at test time (i.e. dropout).

The handling of these keywords is implemented in the `get_output_for()` method of each `Layer` class, which is required to take a catchall `**kwargs` argument to absorb any keywords that the layer doesn't recognize.

One issue with this is that a `Layer` instance might unintentionally ignore a certain keyword, and this is basically a silent failure. If you misspell `deterministic` as `determinstic` for example, all layers will ignore it and no warning or exception will be raised.

This is not very user friendly. Recently I had a brief discussion about this issue on this reddit thread: https://www.reddit.com/r/MachineLearning/comments/3xom8a/discussion_what_would_you_like_to_see_in_a/cy6hqg8

One of the developers of climin ( https://github.com/BRML/climin ) chimed in and pointed me to their solution for this issue: https://github.com/BRML/climin/blob/master/climin/util.py#L140-L151

Basically, check the called function's argument specification through introspection, and see if any arguments were provided that aren't listed there. If so, raise a warning.

I think such a solution may be possible for Lasagne as well. We could have `get_output()` inspect the argument specification for all `get_output_for()` calls it makes, and keep track of the set of all accepted keyword arguments across all layers. Once the graph is traversed, we can check whether any of the provided keyword arguments are not in this set.

As far as I can tell this would only require modifications in `get_output()` itself. It would complicate the code somewhat, but not excessively so, and I think the usability benefit should not be underestimated.

There is one big caveat: not all `get_output_for()` implementations specify all keywords arguments they accept in the method signature. Some implementations work directly with the `kwargs` dictionary, most importantly the new batch normalization implementation (#467).

So we'd have to figure out a workaround for that. The simplest approach would be to always have all accepted keyword arguments in the method signature, but I don't know if that is desirable. Another solution would be to provide an alternative way for such methods to 'declare' which keyword arguments they understand, but I think that might get a little too complicated.

I might try whipping up a PR for this, but before I do that we should probably figure out what to do with accepted keyword arguments that are not explicitly declared in the method signature.

**Comment by ebenolson** [comment]
I think the simplest option would be a global kwarg whitelist, and a check in `get_output` to raise if something in `kwargs` is not in this list. 

It would only catch misspellings, not incorrect usage of existing kwargs, but I'm not sure you can really protect against that anyway.

**Comment by skaae** [comment]
Ebens idea seems really simple but you would get warnings with custom layers that uses new keywords. 
I don't know if that is a problem?

**Comment by benanne** [comment]
I'm not a huge fan of having a global whitelist. As @skaae points out it will raise warnings when people define new layers with custom keywords, which could be annoying and/or confusing. Also it creates an additional maintenance burden (we would have to remember to keep it up to date at all times). But it's definitely the least "magical" solution, which is also a valuable trait.

**Comment by dnouri** [comment]
I think Eben's idea implies to have custom layers update that global list.

**Comment by skaae** [comment]
Can init in each layer add accepted key words to a global list?
Den 29/12/2015 00.35 skrev "Daniel Nouri" <notifications@github.com>:

**Comment by benanne** [comment]
I guess that could work, seems a bit brittle though, but I can't quite put my finger on why I believe it is. @f0k's insight would probably be useful here :)

**Comment by f0k** [comment]
> @f0k's insight would probably be useful here :)

We already came up with the whitelist solution the last time we discussed it, but I can't find that thread again. The idea was to have a set of accepted keyword arguments that includes `deterministic` by default, and have layers add words to that list as they're constructed (or when their `get_output_for()` method is called). When `lasagne.layers.get_output()` encounters an unregistered keyword argument, it warns the user (and possibly suggests to use the closest match instead).

> seems a bit brittle though

Introspection of the method signatures is not necessarily better. Developers implementing their own layers would need to know that they must specify keyword arguments in the `get_output_for()` signature and are not allowed to get them out of `kwargs`. This may end up being more bewildering than having to register them with the global whitelist.
The brittleness of the global whitelist is that the whitelist can only reflect the accepted keyword arguments of all layers that were constructed (or `get_output_for()`'ed) within the lifetime of a process, it can not specifically check the layers that are involved in a particular `lasagne.layers.get_output()` call.
The real downside of introspection is that it will make it impossible to write a layer proxy that forwards any calls to an embedded layer instance and does something with the results. In this case, you simply cannot have the `get_output_for()` signature list the keyword arguments.

Third solution: Have an attribute that lists the accepted keyword arguments. This avoids the global whitelist and still allows to write a generic layer proxy. It would make the `Layer` base class a little more complex.

At any rate, `deterministic` should probably be an allowed keyword argument even if the network does not involve any indeterministic layers, so we can encourage the generic "`deterministic=True` for testing" pattern. (I think either @benanne or @craffel didn't like this idea the last time we discussed it.)

**Comment by benanne** [comment]
The third solution sounds pretty good. The main thing is that people who implement a layer class that does not respond to any kwargs, should not have to worry about it. I think I agree that having `deterministic` in there by default is a good idea.

**Comment by ebenolson** [comment]
I don't think it even needs to be as complicated as dynamically updating during initialization. Just keep a list in `helpers.py` and when someone defines a custom layer they can write

    lasagne.layers.helper._accepted_kwargs.append('some_new_kwarg')

to silence the warning (I would actually make it an Exception so it's not too easy to ignore). It shouldn't be confusing at all if we include text to that effect in the warning.

Travis should make sure we update the whitelist as long as tests are being written exercising the new kwarg. How often will this really be needed anyway? I think batch normalization is the first layer to use something beyond `deterministic`?

> At any rate, deterministic should probably be an allowed keyword argument even if the network does not involve any indeterministic layers, so we can encourage the generic "deterministic=True for testing" pattern.

Yes, I think a simple check to protect against typos is useful, but we shouldn't go overboard trying to determine if what the user is doing is logical.

**Comment by dnouri** [comment]
I agree it's arguably nicer to define a layer that takes additional
get_output kwargs like this:

class MyLayer(Layer):
    get_output_kwargs = ['some_new_kwarg']

rather than:

lasagne.layers.helper._accepted_kwargs.append('some_new_kwarg')
class MyLayer(Layer):
    pass

For the first variant, basic MRO class introspection will allow assembling
a final list of kwargs that are allowed for the derived class.  Thus, only
the base Layer class will need to have 'deterministic' in its
get_output_kwargs etc.

A minor nitpick about the second variant: '_accepted_kwargs' would be part
of a public API and therefore should not start with an underscore.

On Tue, Dec 29, 2015 at 3:35 PM, Eben Olson <notifications@github.com>
wrote:

> I don't think it even needs to be as complicated as dynamically updating
> during initialization. Just keep a list in helpers.py and when someone
> defines a custom layer they can write
>
> lasagne.layers.helper._accepted_kwargs.append('some_new_kwarg')
>
> to silence the warning (I would actually make it an Exception so it's not
> too easy to ignore). It shouldn't be confusing at all if we include text to
> that effect in the warning.
>
> Travis should make sure we update the whitelist as long as tests are being
> written exercising the new kwarg. How often will this really be needed
> anyway? I think batch normalization is the first layer to use something
> beyond deterministic?
>
> At any rate, deterministic should probably be an allowed keyword argument
> even if the network does not involve any indeterministic layers, so we can
> encourage the generic "deterministic=True for testing" pattern.
>
> Yes, I think a simple check to protect against typos is useful, but we
> shouldn't go overboard trying to determine if what the user is doing is
> logical.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Lasagne/Lasagne/issues/557#issuecomment-167873210>.
>



-- 
http://danielnouri.org

**Comment by dnouri** [comment]
Thinking about this a little more, I don't know how f0k intends to solve
the 'generic layer proxy' case if the check is happening in
'helpers.get_output'.  (Where else would it happen?)

Third solution: Have an attribute that lists the accepted keyword
arguments. This avoids the global whitelist and still allows to write a
generic layer proxy. *It would make the Layer base class a little more
complex.*

What do you have in mind here?

**Comment by f0k** [comment]
> Thinking about this a little more, I don't know how f0k intends to solve the 'generic layer proxy' case [...]
> What do you have in mind here?

For this, it can't be a class attribute, but an ordinary attribute of the instance. For example:
```python
class Layer(object):
    def __init__(...):
        self.get_output_for_kwargs = {'deterministic'}
        ...

class BatchNormLayer(Layer):
    def __init__(...):
        super(...)
        self.get_output_for_kwargs.update(['batch_norm_update_averages', 'batch_norm_use_averages'])
        ...

class SomeProxy(Layer):
     def __init__(self, wrapped, ...):
        super(...)
        self.get_output_for_kwargs.update(wrapped.get_output_for_kwargs)
        ...

def get_output(layer_or_layers, ..., **kwargs):
    # at some point, we call get_all_layers()
    # we can then create a union of all `get_output_for_kwargs`
    # and compare against kwargs.keys()
```
Although I think `get_output_for_kwargs` doesn't sound too nice.

> The third solution sounds pretty good. The main thing is that people who implement a layer class that does not respond to any kwargs, should not have to worry about it.

We could even use introspection to have the base class add all kwargs explicitly listed in `get_ouput_for()`. That way only classes that do not (or cannot) explicitly define them would need to care.

**Comment by dnouri** [comment]
```python
def get_output(layer_or_layers, ..., **kwargs):
    # at some point, we call get_all_layers()
    # we can then create a union of all `get_output_for_kwargs`
    # and compare against kwargs.keys()
```

Thanks for the explanation.

It appears that you could similarly use introspection of `get_output_for` kwargs here?  Call `get_all_layers()`, call some `get_kwargs(layer)` for each layer, and make a union of return values.  Or, in other words, wouldn't this suffer from the same problem you're describing here:

> The real downside of introspection is that it will make it impossible to write a layer proxy that forwards any calls to an embedded layer instance and does something with the results.

I'm sure you can enlighten me again.  :-)

**Comment by dnouri** [comment]
Duh, please ignore, I didn't read this example:

```python
class SomeProxy(Layer):
     def __init__(self, wrapped, ...):
        super(...)
        self.get_output_for_kwargs.update(wrapped.get_output_for_kwargs)
        ...
```

**Comment by f0k** [comment]
Feature has been added in the meantime, closing!
