### ISSUE TITLE
param "mode" is not supported by tensor.signal.downsample.max_pool_2d

### ISSUE THREAD

**Issue by citihome** [Lasagne/Lasagne#558]
the pool.py file shows that mean_pooling operation is implemented through max_pool_2d API when we using mode, but when I tried the function on my Anaconda environment, it fails, here is the testcase:

>>> import theano, numpy
Using gpu device 0: GeForce GTX 460
>>> from theano import tensor
>>> x = theano.shared(numpy.arange(256).reshape(4,4,4,4))
>>> tensor.signal.downsample.max_pool_2d(x, (2,2), mode="max")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: max_pool_2d() got an unexpected keyword argument 'mode'

the follow is the help information of max_pool_2d, which also shows there is no 'mode' parameter.
==========
Help on function max_pool_2d in module theano.tensor.signal.downsample:

max_pool_2d(input, ds, ignore_border=False, st=None, padding=(0, 0))
    Takes as input a N-D tensor, where N >= 2. It downscales the input image by
    the specified factor, by keeping only the maximum value of non-overlapping
    patches of size (ds[0],ds[1])
    
    :type input: N-D theano tensor of input images.
    :param input: input images. Max pooling will be done over the 2 last
        dimensions.
    :type ds: tuple of length 2
    :param ds: factor by which to downscale (vertical ds, horizontal ds).
        (2,2) will halve the image in each dimension.
    :type ignore_border: bool
    :param ignore_border: When True, (5,5) input with ds=(2,2)
        will generate a (2,2) output. (3,3) otherwise.
    :type st: tuple of lenght 2
    :param st: stride size, which is the number of shifts
        over rows/cols to get the the next pool region.
        if st is None, it is considered equal to ds
        (no overlap on pooling regions)
    :param padding: (pad_h, pad_w), pad zeros to extend beyond four borders
            of the images, pad_h is the size of the top and bottom margins,
=====
the theano version is 0.7.0, I tried down from pydy/asmeurer/jeprescottroy, but none of these support mode param.
https://anaconda.org/search?q=theano
My question is that how should I do to suport the mean-pooling operation?

**Comment by ebenolson** [comment]
Please see the [installation instructions](https://lasagne.readthedocs.org/en/latest/user/installation.html) - the 0.7.0 release of Theano is too old, you need to install from github.
