### ISSUE TITLE
dropout layers leak float64 into graph

### ISSUE THREAD

**Issue by n291hhJJA** [Lasagne/Lasagne#563]
When using a dropout layer, the output upcasts to float64, causing every layer after it to be upcast to float64. The problem seems to be caused by the way numpy treats operations that upcast integers. For example:

x = 1 - numpy.float32(0.5)

causes x to have type numpy.float64

This happens to me on numpy version 1.9.0, but I think it happens on other versions as well.

So, here is a code fix:

Line 73 of noise.py - which reads:
retain_prob = 1 - self.p

should be changed to something like this:
if theano.config.floatX == 'float64' :
   retain_prob = np.float64(1 - self.p)
else :
   retain_prob = np.float32(1 - self.p)

**Comment by benanne** [comment]
it's odd that this only comes up now, but maybe it is something that happens only with newer numpy versions? Anyone care doing some tests? At any rate we should avoid it. I think a more future-proof fix is probably `retain_prob = np.array(1 - self.p, dtype=theano.config.floatX)`.

**Comment by f0k** [comment]
> it's odd that this only comes up now

No, if you set `p` to a Python float instead of a numpy scalar, then everything's fine. We should allow both, though.

> I think a more future-proof fix is probably retain_prob = np.array(1 - self.p, dtype=theano.config.floatX).

Nope, `p` could be symbolic. It should be `retain_prob = lasagne.utils.floatX(1) - self.p`.

@n291hhJJA, would you like to send a PR or shall we?

**Comment by n291hhJJA** [comment]
I'd like to do the pull request if you don't mind waiting a day or two.

I agree on the symbolic issue- didn't think of that case originally.

**Comment by f0k** [comment]
> I'd like to do the pull request if you don't mind waiting a day or two.

That's okay! Check the [contribution guide](http://lasagne.readthedocs.org/en/latest/user/development.html#how-to-contribute), and let us know if you need any help.
