### ISSUE TITLE
Thin Spline Transform Transformer Layer

### ISSUE THREAD

**Issue by arimorcos** [Lasagne/Lasagne#579]
Are there any plans to implement the thin spline transform used in the Jaderberg paper?

**Comment by skaae** [comment]
I don't plan to do it but it would be a nice contribution :)

**Comment by arimorcos** [comment]
Ok, thanks for the quick response. I'm gonna see if I can get it working.

**Comment by skaae** [comment]
Feel free to ask questions.

**Comment by arimorcos** [comment]
Ok, I pretty much have the code written to do this. Do you think it would be better as it's own layer (resulting in a thin plate spline transformer layer and an affine transformer layer), or merged into the current transformer layer by adding a mode parameter?

**Comment by skaae** [comment]
I prefer mode parameter that's easier to extend. I'm Exited to see the code :)
