### ISSUE TITLE
Reproduce cifar10 results

### ISSUE THREAD

**Issue by wjb123** [Lasagne/Lasagne#580]
I want to reproduce the results of classification on cifar10 via lasagne , and I use the same structure as caffe(https://github.com/BVLC/caffe/blob/master/examples/cifar10/cifar10_full_train_test.prototxt),  but I can't get the same result. So i just wonder there is any example about cifar10 in lasagne, or how do i deal with it ?

**Comment by benanne** [comment]
Maybe this helps, it uses the weights from Caffe but you could also retrain the model from scratch: https://github.com/Lasagne/Recipes/blob/master/examples/Using%20a%20Caffe%20Pretrained%20Network%20-%20CIFAR10.ipynb

**Comment by wjb123** [comment]
But the network architecture is differrent from caffe, which is not Network in Network model. so is there any other demo?

**Comment by f0k** [comment]
Sorry for the lack of feedback, this is suited much better for our mailing list (https://groups.google.com/forum/#!forum/lasagne-users). There seem to be quite some demos for CIFAR-10 with Lasagne: https://www.google.com/search?q=cifar10+lasagne
