### ISSUE TITLE
Reshape Problem

### ISSUE THREAD

**Issue by KlaymenGC** [Lasagne/Lasagne#581]
Hello,

I'm quite new to this awesome library, I'm now having some trouble in the softmax layer:
```
network = ... # size: (batch_size, num_classes, img_col, img_row)
network = lasagne.layers.reshape(network, (img_row*img_col, nb_classes))
network = lasagne.nonlinearities.softmax(network)
```
```
raise AsTensorError("Cannot convert %s to TensorType" % str_x, type(x))
theano.tensor.var.AsTensorError: ('Cannot convert <lasagne.layers.shape.ReshapeLayer object at 0x151c0ea10> to TensorType', <class 'lasagne.layers.shape.ReshapeLayer'>)
```
the output of my network is of the same size of the input: ```(num_images, num_classes, img_col, img_row)```
I'm trying to do a softmax over the class dimension of my output after reshaping it to: ```(num_images, img_col*img_row, num_classes)```

Any ideas how may I do this in Lasagne? Thanks in advance!

**Comment by benanne** [comment]
For support requests please use the mailing list, as stated in the contribution guidelines: https://groups.google.com/forum/#!forum/lasagne-users

`lasagne.nonlinearities` contains nonlinearity functions, not `Layer` classes. You cannot simply apply a function to a layer (unfortunately). Have a look at: http://lasagne.readthedocs.org/en/latest/modules/layers/special.html#lasagne.layers.NonlinearityLayer

If you have more questions, please use the mailing list. Thanks for your cooperation!
