### ISSUE TITLE
When using standardize, scales doesn't get returned as a parameter

### ISSUE THREAD

**Issue by craffel** [Lasagne/Lasagne#583]
```Python
In [1]: net = lasagne.layers.standardize(
   ...:     lasagne.layers.InputLayer((10, 20)), np.zeros(20), np.ones(20), 0)

In [2]: lasagne.layers.get_all_params(net)
Out[2]: [b]

In [3]: net.params
Out[3]: OrderedDict([(Elemwise{inv,no_inplace}.0, set())])

In [4]: net.get_params()
Out[4]: []

In [5]: theano.printing.debugprint(net.scales)
Elemwise{inv,no_inplace} [id A] ''
 |TensorConstant{(20,) of 1.0} [id B]
```

Maybe because it's using [`T.inv` on a `np.ndarray`](https://github.com/Lasagne/Lasagne/blob/master/lasagne/layers/special.py#L232) (which gets converted to a `TensorConstant`, not a `SharedVariable`), so `collect_shared_vars` misses it?  I can't think of why someone would not want `scales` to be considered a parameter or to actually be a non-shared Theano variable, so I think requiring the user to pass in a shared variable or a `np.ndarray` is reasonable, and then just use `1./scale` instead of `T.inv(scale)`.

**Comment by f0k** [comment]
> so `collect_shared_vars` misses it

Oh yes, didn't think of that.

Make sure to use `utils.floatX(1) / scale`, though: https://github.com/Lasagne/Lasagne/pull/570#discussion_r49492821

**Comment by craffel** [comment]
PR: #588
