### ISSUE TITLE
Documentation of categorial cross-entropy

### ISSUE THREAD

**Issue by MartinThoma** [Lasagne/Lasagne#591]
It would be nice if the meaning of the indices i and j would be explained in http://lasagne.readthedocs.org/en/latest/modules/objectives.html#lasagne.objectives.categorical_crossentropy

**Comment by f0k** [comment]
It says in the text that "data points [are] in rows and class probabilities in columns", so `i` denotes the data points and `j` denotes the classes. What else would you add?

**Comment by MartinThoma** [comment]
I think I would write:

> Computes the categorical cross-entropy between predictions $p_{i,j}$ and targets $t_{i,j}$, where $i$ denotes the data point and $j$ denotes the class:
> \[L_i = ...\]

or something similar.

**Comment by Sentient07** [comment]
I'll take this one as no one seems to be working on. Also, I personally feel that we should include a word about the `one-hot` encoding that happens under-the-hood (inside theano's function).
