### ISSUE TITLE
Speed up thin plate spline transformer layer 

### ISSUE THREAD

**Issue by arimorcos** [Lasagne/Lasagne#601]
Currently, the thin plate spline transformer layer I just implemented is fairly slow for larger images. The main culprit is '_get_transformed_points_tps'. The way it works now is that `_get_transformed_points_tps` takes in all of the points in the grid (equivalent to the number of pixels if no downsampling is applied), and shifts them according the to calculated thin plate spline coefficients. The shifted grid is then run through the bilinear interpolation along with the input image to create the output. 

Unfortunately, while the computation for an affine transform is simply a dot product of the parameters and the source grid, the computation for the thin plate spline transform is more complicated. The main culprit for the slow down is that the computation requires taking the squared difference between each input point and each source point and then multiplying this squared difference by it's log. [This computation](https://github.com/Lasagne/Lasagne/blob/master/lasagne/layers/special.py#L734) is taking up over 80% of the run time. 

Thankfully, we don't actually need to compute it as part of the theano graph! Because this portion only relies on the source points and the original image size and downsample factor, we can compute it in numpy when the layer is constructed. I see that in the note for [`_meshgrid`](https://github.com/Lasagne/Lasagne/blob/master/lasagne/layers/special.py#L527) that grid construction was implemented in theano to allow for symbolic grid sizes because there wasn't a noticable effect on performance but there is clearly one here. 

It seems to me that for this layer it is clearly worth increasing the speed at the cost of having to prespecify the image size when the layer is constructed (likely defaulting to the shape of the incoming layer). What do you guys think?

**Comment by skaae** [comment]
> The main culprit for the slow down is that the computation requires taking the squared difference between each input point and each source point and then multiplying this squared difference by it's log. This computation is taking up over 80% of the run time.

So you could just precalculate this in the constructur for the class? I think that is a very good idea. One option is to have a flag that defaults to precalculate?



> . I see that in the note for _meshgrid that grid construction was implemented in theano to allow for symbolic grid sizes because there wasn't a noticable effect on performance but there is clearly one here.

Yes. We had a discussion at some point wether to precalculate the grid. It didn't really make a difference in speed to we used the dynamic calculation.

**Comment by skaae** [comment]
@arimorcos: Way ahead of me :)
