### ISSUE TITLE
Segmentation fault (core dumped) after Conv2D-Layer

### ISSUE THREAD

**Issue by PaulZhutovsky** [Lasagne/Lasagne#604]
Hey!

Recently, I encountered a weird problem when using `lasagne` and `theano`. The following minimal example reproduces the error for me:
```python
import numpy as np
import theano
import theano.tensor as T
import lasagne

batch_size = 1

data = np.random.rand(10, 3, 425, 620).astype(np.float32)
W = np.random.rand(3, 3, 65, 65).astype(np.float32)

input_var = T.tensor4(name='input', dtype='float32')

net = lasagne.layers.InputLayer(input_var=input_var, shape=(batch_size, ) + data.shape[1:])
net = lasagne.layers.Conv2DLayer(net, num_filters=W.shape[0], filter_size=W.shape[-2:], 
                                                    pad='valid', W=W, b=None,
                                                    nonlinearity=lasagne.nonlinearities.linear)

filtered_array = np.zeros(net.output_shape)
out_var = lasagne.layers.get_output(net)

conv_fun = theano.function([input_var], outputs=out_var)

for id_batch in xrange(0, data.shape[0], batch_size):
    print '{}'.format(id_batch)
    filtered_array[id_batch:id_batch + batch_size] = conv_fun(data[id_batch:id_batch + batch_size])
```
(The specific parameters are chosen in a way to mimic my actual problem)
Running this script results in a `Segmentation fault (core dumped)` for the first batch already.

What seems strange is that the whole routine was working before without any problems. 
I reproduced the error on my laptop with 16GB RAM, Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz on Ubuntu 14.04.3 LTS (64bit), on a PC with 16GB RAM, Intel(R) Core(TM) i3 CPU 530 @ 2.93GHz on Ubuntu 14.04.3 LTS (64bit) (running `theano` on CPU) and an Amazon EC2 GPU unit (using the GPU).

I'm using the newest `theano` version ('0.8.0.dev0.dev-RELEASE') and newest `lasagne` version ('0.2.dev1'). 

The error seems to me like the system runs out of memory but the whole thing **was** working for me without any problems with older versions of `theano` and `lasagne`. 

Do you have any suggestions how I can make it workable again?

**Comment by ebenolson** [comment]
I'm able to reproduce this, although on CPU only, not GPU. 

A segfault is almost certain to be a Theano bug, not Lasagne. I simplified your example to use Theano only:

    import numpy as np
    import theano
    import theano.tensor as T

    data = np.random.rand(1, 3, 425, 620).astype(np.float32)
    W = theano.shared(np.random.rand(3, 3, 65, 65).astype(np.float32))

    input_var = T.tensor4(name='input', dtype='float32')

    T.nnet.conv2d(input_var, W).eval({input_var: data})

The problem seems to have appeared with https://github.com/Theano/Theano/commit/51c6ef71d8b043cf72cad5e3e5a0ff7e4862fe1e, during the switch to abstract_conv. I'd suggest opening a Theano issue.

**Comment by PaulZhutovsky** [comment]
A fix was provided for Theano and the problem is solved for me.

**Comment by benanne** [comment]
Good to know, thanks for the heads up :)

**Comment by Ranjan13** [comment]
One of the major reasons for segmentation fault in Theano and Lasagne is at any layer "m" if number of dim of output is less than number of dim of input in layer "m+1" . This actually helped me in one of the fault. Hope this was helpful. :)
