### ISSUE TITLE
simple example from main web page gives error

### ISSUE THREAD

**Issue by Sandy4321** [Lasagne/Lasagne#607]
I installed it today on windows PC
theano.__version__
'0.7.0'
C:\Users\Sander>pip install Lasagne
Collecting Lasagne
  Downloading Lasagne-0.1.tar.gz (125kB)
    100% |################################| 126kB 772kB/s
Requirement already satisfied (use --upgrade to upgrade): numpy in c:\anaconda\l
ib\site-packages (from Lasagne)
Building wheels for collected packages: Lasagne
  Running setup.py bdist_wheel for Lasagne ... done
  Stored in directory: C:\Users\Sander\AppData\Local\pip\Cache\wheels\57\ec\18\8
500d722ff864dd917e3cd76b14eca8bc88fb0efa47547f449
Successfully built Lasagne
Installing collected packages: Lasagne
Successfully installed Lasagne-0.1

C:\Users\Sander>

but test case
import lasagne
import theano
import theano.tensor as T

# create Theano variables for input and target minibatch
input_var = T.tensor4('X')
target_var = T.ivector('y')

# create a small convolutional neural network
from lasagne.nonlinearities import leaky_rectify, softmax
network = lasagne.layers.InputLayer((None, 3, 32, 32), input_var)
network = lasagne.layers.Conv2DLayer(network, 64, (3, 3),
                                     nonlinearity=leaky_rectify)
network = lasagne.layers.Conv2DLayer(network, 32, (3, 3),
                                     nonlinearity=leaky_rectify)
network = lasagne.layers.Pool2DLayer(network, (3, 3), stride=2, mode='max')
network = lasagne.layers.DenseLayer(lasagne.layers.dropout(network, 0.5),
                                    128, nonlinearity=leaky_rectify,
                                    W=lasagne.init.Orthogonal())
network = lasagne.layers.DenseLayer(lasagne.layers.dropout(network, 0.5),
                                    10, nonlinearity=softmax)

# create loss function
prediction = lasagne.layers.get_output(network)
loss = lasagne.objectives.categorical_crossentropy(prediction, target_var)
loss = loss.mean() + 1e-4 * lasagne.regularization.regularize_network_params(
    network, lasagne.regularization.l2)

# create parameter update expressions
params = lasagne.layers.get_all_params(network, trainable=True)
updates = lasagne.updates.nesterov_momentum(loss, params, learning_rate=0.01,
                                            momentum=0.9)

# compile training function that updates parameters and returns training loss
train_fn = theano.function([input_var, target_var], loss, updates=updates)

# train network (assuming you've got some training data in numpy arrays)
for epoch in range(100):
    loss = 0
    for input_batch, target_batch in training_data:
        loss += train_fn(input_batch, target_batch)
    print("Epoch %d: Loss %g" % (epoch + 1, loss / len(training_data)))

# use trained network for predictions
test_prediction = lasagne.layers.get_output(network, deterministic=True)
predict_fn = theano.function([input_var], T.argmax(test_prediction, axis=1))
print("Predicted class for first test input: %r" % predict_fn(test_data[0]))

gives mistake

File "c:\Sander\my_code\S_Lasagne_simple_test_from_web_page_feb10.py", line 27, in <module>
  prediction = lasagne.layers.get_output(network)
File "C:\Anaconda\Lib\site-packages\lasagne\layers\helper.py", line 185, in get_output
  all_outputs[layer] = layer.get_output_for(layer_inputs, **kwargs)
File "C:\Anaconda\Lib\site-packages\lasagne\layers\pool.py", line 240, in get_output_for
  mode=self.mode,

TypeError: max_pool_2d() got an unexpected keyword argument 'mode'

by the way recurrent.py gives error

File "C:\Sander\Theano\Lasagne\Lasagne-master feb10\examples\recurrent.py", line 171, in <module>
  main()
File "C:\Sander\Theano\Lasagne\Lasagne-master feb10\examples\recurrent.py", line 122, in main
  nonlinearity=lasagne.nonlinearities.tanh, only_return_final=True)
File "C:\Anaconda\Lib\site-packages\lasagne\layers\recurrent.py", line 554, in __init__
  nonlinearity=None, **kwargs)
File "C:\Anaconda\Lib\site-packages\lasagne\layers\dense.py", line 64, in __init__
  super(DenseLayer, self).__init__(incoming, **kwargs)

TypeError: __init__() got an unexpected keyword argument 'only_return_final'

**Comment by ebenolson** [comment]
Your Theano version is too old, and unfortunately your Lasagne version is too old to tell you that directly. Follow the [installation instructions](https://github.com/Lasagne/Lasagne#installation) to get up-to-date versions.

Similarly, the `recurrent.py` in master is written to work with the current version of Lasagne - 0.1 is too old.

Perhaps it's time for a new pypi release?

**Comment by Sandy4321** [comment]
Eben
thanks for soon answer
1

installation

pip install https://github.com/Lasagne/Lasagne/archive/master.zip

was ok

but now the error is

File "C:\Sander\my_code\S_Lasagne_simple_test_from_web_page_feb10.py",
line 24, in <module>
  import lasagne
File "C:\Anaconda\Lib\site-packages\lasagne\__init__.py", line 17, in <module>
  raise ImportError("Your Theano version is too old." + install_instr)

ImportError: Your Theano version is too old.
Please make sure you install a recent enough version of Theano. Note that a
simple 'pip install theano' will usually give you a version that is too old
for Lasagne. See the installation docs for more
details:http://lasagne.readthedocs.org/en/latest/user/installation.html#theano

2

when I use recommended link

http://lasagne.readthedocs.org/en/latest/user/installation.html#theano




and run

pip install --upgrade https://github.com/Theano/Theano/archive/master.zip


installation fails with error:

******************************************************************************************************

c\umath -Inumpy\core\src\npysort -IC:\Anaconda\include -IC:\Anaconda\PC -c
_conf
igtest.c -o _configtest.o
    success!
    removing: _configtest.c _configtest.o
    C compiler: gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes

    compile options: '-DNPY_MINGW_USE_CUSTOM_MSVCR
-D__MSVCRT_VERSION__=0x0900 -
Inumpy\core\src\private -Inumpy\core\src -Inumpy\core
-Inumpy\core\src\npymath -
Inumpy\core\src\multiarray -Inumpy\core\src\umath -Inumpy\core\src\npysort
-IC:\
Anaconda\include -IC:\Anaconda\PC -c'
    gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes
-DNPY_MINGW_USE_CUST
OM_MSVCR -D__MSVCRT_VERSION__=0x0900 -Inumpy\core\src\private
-Inumpy\core\src -
Inumpy\core -Inumpy\core\src\npymath -Inumpy\core\src\multiarray
-Inumpy\core\sr
c\umath -Inumpy\core\src\npysort -IC:\Anaconda\include -IC:\Anaconda\PC -c
_conf
igtest.c -o _configtest.o
    success!
    removing: _configtest.c _configtest.o
    C compiler: gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes

    compile options: '-DNPY_MINGW_USE_CUSTOM_MSVCR
-D__MSVCRT_VERSION__=0x0900 -
Inumpy\core\src\private -Inumpy\core\src -Inumpy\core
-Inumpy\core\src\npymath -
Inumpy\core\src\multiarray -Inumpy\core\src\umath -Inumpy\core\src\npysort
-IC:\
Anaconda\include -IC:\Anaconda\PC -c'
    gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes
-DNPY_MINGW_USE_CUST
OM_MSVCR -D__MSVCRT_VERSION__=0x0900 -Inumpy\core\src\private
-Inumpy\core\src -
Inumpy\core -Inumpy\core\src\npymath -Inumpy\core\src\multiarray
-Inumpy\core\sr
c\umath -Inumpy\core\src\npysort -IC:\Anaconda\include -IC:\Anaconda\PC -c
_conf
igtest.c -o _configtest.o
    _configtest.c: In function 'main':
    _configtest.c:8:12: error: 'HAVE_DECL_SIGNBIT' undeclared (first use in
this
 function)
    _configtest.c:8:12: note: each undeclared identifier is reported only
once f
or each function it appears in
    failure.
    removing: _configtest.c _configtest.o
    C compiler: gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes

    compile options: '-DNPY_MINGW_USE_CUSTOM_MSVCR
-D__MSVCRT_VERSION__=0x0900 -
Inumpy\core\src\private -Inumpy\core\src -Inumpy\core
-Inumpy\core\src\npymath -
Inumpy\core\src\multiarray -Inumpy\core\src\umath -Inumpy\core\src\npysort
-IC:\
Anaconda\include -IC:\Anaconda\PC -c'
    gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes
-DNPY_MINGW_USE_CUST
OM_MSVCR -D__MSVCRT_VERSION__=0x0900 -Inumpy\core\src\private
-Inumpy\core\src -
Inumpy\core -Inumpy\core\src\npymath -Inumpy\core\src\multiarray
-Inumpy\core\sr
c\umath -Inumpy\core\src\npysort -IC:\Anaconda\include -IC:\Anaconda\PC -c
_conf
igtest.c -o _configtest.o
    _configtest.c: In function 'main':
    _configtest.c:8:12: error: 'HAVE_DECL_ISFINITE' undeclared (first use
in thi
s function)
    _configtest.c:8:12: note: each undeclared identifier is reported only
once f
or each function it appears in
    failure.
    removing: _configtest.c _configtest.o
    C compiler: gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes

    compile options: '-DNPY_MINGW_USE_CUSTOM_MSVCR
-D__MSVCRT_VERSION__=0x0900 -
Inumpy\core\src\private -Inumpy\core\src -Inumpy\core
-Inumpy\core\src\npymath -
Inumpy\core\src\multiarray -Inumpy\core\src\umath -Inumpy\core\src\npysort
-IC:\
Anaconda\include -IC:\Anaconda\PC -c'
    gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes
-DNPY_MINGW_USE_CUST
OM_MSVCR -D__MSVCRT_VERSION__=0x0900 -Inumpy\core\src\private
-Inumpy\core\src -
Inumpy\core -Inumpy\core\src\npymath -Inumpy\core\src\multiarray
-Inumpy\core\sr
c\umath -Inumpy\core\src\npysort -IC:\Anaconda\include -IC:\Anaconda\PC -c
_conf
igtest.c -o _configtest.o
    success!
    removing: _configtest.c _configtest.o
    C compiler: gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes

    compile options: '-DNPY_MINGW_USE_CUSTOM_MSVCR
-D__MSVCRT_VERSION__=0x0900 -
Inumpy\core\src\private -Inumpy\core\src -Inumpy\core
-Inumpy\core\src\npymath -
Inumpy\core\src\multiarray -Inumpy\core\src\umath -Inumpy\core\src\npysort
-IC:\
Anaconda\include -IC:\Anaconda\PC -c'
    gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes
-DNPY_MINGW_USE_CUST
OM_MSVCR -D__MSVCRT_VERSION__=0x0900 -Inumpy\core\src\private
-Inumpy\core\src -
Inumpy\core -Inumpy\core\src\npymath -Inumpy\core\src\multiarray
-Inumpy\core\sr
c\umath -Inumpy\core\src\npysort -IC:\Anaconda\include -IC:\Anaconda\PC -c
_conf
igtest.c -o _configtest.o
    success!
    removing: _configtest.c _configtest.o
    C compiler: gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes

    compile options: '-DNPY_MINGW_USE_CUSTOM_MSVCR
-D__MSVCRT_VERSION__=0x0900 -
Inumpy\core\src\private -Inumpy\core\src -Inumpy\core
-Inumpy\core\src\npymath -
Inumpy\core\src\multiarray -Inumpy\core\src\umath -Inumpy\core\src\npysort
-IC:\
Anaconda\include -IC:\Anaconda\PC -c'
    gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes
-DNPY_MINGW_USE_CUST
OM_MSVCR -D__MSVCRT_VERSION__=0x0900 -Inumpy\core\src\private
-Inumpy\core\src -
Inumpy\core -Inumpy\core\src\npymath -Inumpy\core\src\multiarray
-Inumpy\core\sr
c\umath -Inumpy\core\src\npysort -IC:\Anaconda\include -IC:\Anaconda\PC -c
_conf
igtest.c -o _configtest.o
    success!
    removing: _configtest.c _configtest.o
    C compiler: gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes

    compile options: '-DNPY_MINGW_USE_CUSTOM_MSVCR
-D__MSVCRT_VERSION__=0x0900 -
Inumpy\core\src\private -Inumpy\core\src -Inumpy\core
-Inumpy\core\src\npymath -
Inumpy\core\src\multiarray -Inumpy\core\src\umath -Inumpy\core\src\npysort
-IC:\
Anaconda\include -IC:\Anaconda\PC -c'
    gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes
-DNPY_MINGW_USE_CUST
OM_MSVCR -D__MSVCRT_VERSION__=0x0900 -Inumpy\core\src\private
-Inumpy\core\src -
Inumpy\core -Inumpy\core\src\npymath -Inumpy\core\src\multiarray
-Inumpy\core\sr
c\umath -Inumpy\core\src\npysort -IC:\Anaconda\include -IC:\Anaconda\PC -c
_conf
igtest.c -o _configtest.o
    removing: _configtest.c _configtest.o
    C compiler: gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes

    compile options: '-DNPY_MINGW_USE_CUSTOM_MSVCR
-D__MSVCRT_VERSION__=0x0900 -
Inumpy\core\src\private -Inumpy\core\src -Inumpy\core
-Inumpy\core\src\npymath -
Inumpy\core\src\multiarray -Inumpy\core\src\umath -Inumpy\core\src\npysort
-IC:\
Anaconda\include -IC:\Anaconda\PC -c'
    gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes
-DNPY_MINGW_USE_CUST
OM_MSVCR -D__MSVCRT_VERSION__=0x0900 -Inumpy\core\src\private
-Inumpy\core\src -
Inumpy\core -Inumpy\core\src\npymath -Inumpy\core\src\multiarray
-Inumpy\core\sr
c\umath -Inumpy\core\src\npysort -IC:\Anaconda\include -IC:\Anaconda\PC -c
_conf
igtest.c -o _configtest.o
    removing: _configtest.c _configtest.o
    C compiler: gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes

    compile options: '-DNPY_MINGW_USE_CUSTOM_MSVCR
-D__MSVCRT_VERSION__=0x0900 -
Inumpy\core\src\private -Inumpy\core\src -Inumpy\core
-Inumpy\core\src\npymath -
Inumpy\core\src\multiarray -Inumpy\core\src\umath -Inumpy\core\src\npysort
-IC:\
Anaconda\include -IC:\Anaconda\PC -c'
    gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes
-DNPY_MINGW_USE_CUST
OM_MSVCR -D__MSVCRT_VERSION__=0x0900 -Inumpy\core\src\private
-Inumpy\core\src -
Inumpy\core -Inumpy\core\src\npymath -Inumpy\core\src\multiarray
-Inumpy\core\sr
c\umath -Inumpy\core\src\npysort -IC:\Anaconda\include -IC:\Anaconda\PC -c
_conf
igtest.c -o _configtest.o
    removing: _configtest.c _configtest.o
    C compiler: gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes

    compile options: '-DNPY_MINGW_USE_CUSTOM_MSVCR
-D__MSVCRT_VERSION__=0x0900 -
Inumpy\core\src\private -Inumpy\core\src -Inumpy\core
-Inumpy\core\src\npymath -
Inumpy\core\src\multiarray -Inumpy\core\src\umath -Inumpy\core\src\npysort
-IC:\
Anaconda\include -IC:\Anaconda\PC -c'
    gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes
-DNPY_MINGW_USE_CUST
OM_MSVCR -D__MSVCRT_VERSION__=0x0900 -Inumpy\core\src\private
-Inumpy\core\src -
Inumpy\core -Inumpy\core\src\npymath -Inumpy\core\src\multiarray
-Inumpy\core\sr
c\umath -Inumpy\core\src\npysort -IC:\Anaconda\include -IC:\Anaconda\PC -c
_conf
igtest.c -o _configtest.o
    gcc -g _configtest.o -lmsvcr90 -o _configtest.exe
    success!
    removing: _configtest.exe.manifest _configtest.c _configtest.o
_configtest.e
xe
    C compiler: gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes

    compile options: '-DNPY_MINGW_USE_CUSTOM_MSVCR
-D__MSVCRT_VERSION__=0x0900 -
Inumpy\core\src\private -Inumpy\core\src -Inumpy\core
-Inumpy\core\src\npymath -
Inumpy\core\src\multiarray -Inumpy\core\src\umath -Inumpy\core\src\npysort
-IC:\
Anaconda\include -IC:\Anaconda\PC -c'
    gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes
-DNPY_MINGW_USE_CUST
OM_MSVCR -D__MSVCRT_VERSION__=0x0900 -Inumpy\core\src\private
-Inumpy\core\src -
Inumpy\core -Inumpy\core\src\npymath -Inumpy\core\src\multiarray
-Inumpy\core\sr
c\umath -Inumpy\core\src\npysort -IC:\Anaconda\include -IC:\Anaconda\PC -c
_conf
igtest.c -o _configtest.o
    gcc -g _configtest.o -lmsvcr90 -o _configtest.exe
    success!
    removing: _configtest.exe.manifest _configtest.c _configtest.o
_configtest.e
xe
    C compiler: gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes

    compile options: '-DNPY_MINGW_USE_CUSTOM_MSVCR
-D__MSVCRT_VERSION__=0x0900 -
Inumpy\core\src\private -Inumpy\core\src -Inumpy\core
-Inumpy\core\src\npymath -
Inumpy\core\src\multiarray -Inumpy\core\src\umath -Inumpy\core\src\npysort
-IC:\
Anaconda\include -IC:\Anaconda\PC -c'
    gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes
-DNPY_MINGW_USE_CUST
OM_MSVCR -D__MSVCRT_VERSION__=0x0900 -Inumpy\core\src\private
-Inumpy\core\src -
Inumpy\core -Inumpy\core\src\npymath -Inumpy\core\src\multiarray
-Inumpy\core\sr
c\umath -Inumpy\core\src\npysort -IC:\Anaconda\include -IC:\Anaconda\PC -c
_conf
igtest.c -o _configtest.o
    gcc -g _configtest.o -lmsvcr90 -o _configtest.exe
    success!
    removing: _configtest.exe.manifest _configtest.c _configtest.o
_configtest.e
xe
    BUILD_ARCHITECTURE: 'AMD64', os.name='nt', sys.platform='win32'
    C compiler: gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes

    compile options: '-DNPY_MINGW_USE_CUSTOM_MSVCR
-D__MSVCRT_VERSION__=0x0900 -
Inumpy\core\src\private -Inumpy\core\src -Inumpy\core
-Inumpy\core\src\npymath -
Inumpy\core\src\multiarray -Inumpy\core\src\umath -Inumpy\core\src\npysort
-IC:\
Anaconda\include -IC:\Anaconda\PC -c'
    gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes
-DNPY_MINGW_USE_CUST
OM_MSVCR -D__MSVCRT_VERSION__=0x0900 -Inumpy\core\src\private
-Inumpy\core\src -
Inumpy\core -Inumpy\core\src\npymath -Inumpy\core\src\multiarray
-Inumpy\core\sr
c\umath -Inumpy\core\src\npysort -IC:\Anaconda\include -IC:\Anaconda\PC -c
_conf
igtest.c -o _configtest.o
    _configtest.c:2:41: error: expected ';', ',' or ')' before 'a'
    failure.
    removing: _configtest.c _configtest.o
    C compiler: gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes

    compile options: '-DNPY_MINGW_USE_CUSTOM_MSVCR
-D__MSVCRT_VERSION__=0x0900 -
Inumpy\core\src\private -Inumpy\core\src -Inumpy\core
-Inumpy\core\src\npymath -
Inumpy\core\src\multiarray -Inumpy\core\src\umath -Inumpy\core\src\npysort
-IC:\
Anaconda\include -IC:\Anaconda\PC -c'
    gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes
-DNPY_MINGW_USE_CUST
OM_MSVCR -D__MSVCRT_VERSION__=0x0900 -Inumpy\core\src\private
-Inumpy\core\src -
Inumpy\core -Inumpy\core\src\npymath -Inumpy\core\src\multiarray
-Inumpy\core\sr
c\umath -Inumpy\core\src\npysort -IC:\Anaconda\include -IC:\Anaconda\PC -c
_conf
igtest.c -o _configtest.o
    success!
    removing: _configtest.c _configtest.o
    C compiler: gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes

    compile options: '-DNPY_MINGW_USE_CUSTOM_MSVCR
-D__MSVCRT_VERSION__=0x0900 -
Inumpy\core\src\private -Inumpy\core\src -Inumpy\core
-Inumpy\core\src\npymath -
Inumpy\core\src\multiarray -Inumpy\core\src\umath -Inumpy\core\src\npysort
-IC:\
Anaconda\include -IC:\Anaconda\PC -c'
    gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes
-DNPY_MINGW_USE_CUST
OM_MSVCR -D__MSVCRT_VERSION__=0x0900 -Inumpy\core\src\private
-Inumpy\core\src -
Inumpy\core -Inumpy\core\src\npymath -Inumpy\core\src\multiarray
-Inumpy\core\sr
c\umath -Inumpy\core\src\npysort -IC:\Anaconda\include -IC:\Anaconda\PC -c
_conf
igtest.c -o _configtest.o
    success!
    removing: _configtest.c _configtest.o
    C compiler: gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes

    compile options: '-DNPY_MINGW_USE_CUSTOM_MSVCR
-D__MSVCRT_VERSION__=0x0900 -
Inumpy\core\src\private -Inumpy\core\src -Inumpy\core
-Inumpy\core\src\npymath -
Inumpy\core\src\multiarray -Inumpy\core\src\umath -Inumpy\core\src\npysort
-IC:\
Anaconda\include -IC:\Anaconda\PC -c'
    gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes
-DNPY_MINGW_USE_CUST
OM_MSVCR -D__MSVCRT_VERSION__=0x0900 -Inumpy\core\src\private
-Inumpy\core\src -
Inumpy\core -Inumpy\core\src\npymath -Inumpy\core\src\multiarray
-Inumpy\core\sr
c\umath -Inumpy\core\src\npysort -IC:\Anaconda\include -IC:\Anaconda\PC -c
_conf
igtest.c -o _configtest.o
    _configtest.c: In function 'main':
    _configtest.c:7:12: error: 'Py_UNICODE_WIDE' undeclared (first use in
this f
unction)
    _configtest.c:7:12: note: each undeclared identifier is reported only
once f
or each function it appears in
    failure.
    removing: _configtest.c _configtest.o
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File
"c:\users\sander\appdata\local\temp\pip-build-ygtavk\numpy\setup.py",
 line 263, in <module>
        setup_package()
      File
"c:\users\sander\appdata\local\temp\pip-build-ygtavk\numpy\setup.py",
 line 255, in setup_package
        setup(**metadata)
      File
"c:\users\sander\appdata\local\temp\pip-build-ygtavk\numpy\numpy\dist
utils\core.py", line 169, in setup
        return old_setup(**new_attr)
      File "C:\Anaconda\lib\distutils\core.py", line 151, in setup
        dist.run_commands()
      File "C:\Anaconda\lib\distutils\dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "C:\Anaconda\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File
"c:\users\sander\appdata\local\temp\pip-build-ygtavk\numpy\numpy\dist
utils\command\install.py", line 62, in run
        r = self.setuptools_run()
      File
"c:\users\sander\appdata\local\temp\pip-build-ygtavk\numpy\numpy\dist
utils\command\install.py", line 36, in setuptools_run
        return distutils_install.run(self)
      File "C:\Anaconda\lib\distutils\command\install.py", line 563, in run
        self.run_command('build')
      File "C:\Anaconda\lib\distutils\cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "C:\Anaconda\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File
"c:\users\sander\appdata\local\temp\pip-build-ygtavk\numpy\numpy\dist
utils\command\build.py", line 47, in run
        old_build.run(self)
      File "C:\Anaconda\lib\distutils\command\build.py", line 127, in run
        self.run_command(cmd_name)
      File "C:\Anaconda\lib\distutils\cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "C:\Anaconda\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File
"c:\users\sander\appdata\local\temp\pip-build-ygtavk\numpy\numpy\dist
utils\command\build_src.py", line 153, in run
        self.build_sources()
      File
"c:\users\sander\appdata\local\temp\pip-build-ygtavk\numpy\numpy\dist
utils\command\build_src.py", line 170, in build_sources
        self.build_extension_sources(ext)
      File
"c:\users\sander\appdata\local\temp\pip-build-ygtavk\numpy\numpy\dist
utils\command\build_src.py", line 329, in build_extension_sources
        sources = self.generate_sources(sources, ext)
      File
"c:\users\sander\appdata\local\temp\pip-build-ygtavk\numpy\numpy\dist
utils\command\build_src.py", line 386, in generate_sources
        source = func(extension, build_dir)
      File "numpy\core\setup.py", line 455, in generate_config_h
        rep = check_long_double_representation(config_cmd)
      File "numpy\core\setup_common.py", line 191, in
check_long_double_represen
tation
        cmd.compiler.compile_options.remove("/GL")
    AttributeError: Mingw32CCompiler instance has no attribute
'compile_options'


    ----------------------------------------
  Rolling back uninstall of numpy
Command "C:\Anaconda\python.exe -u -c "import setuptools,
tokenize;__file__='c:\
\users\\sander\\appdata\\local\\temp\\pip-build-ygtavk\\numpy\\setup.py';exec(co
mpile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n',
'\n'), __
file__, 'exec'))" install --record
c:\users\sander\appdata\local\temp\pip-ez3b8n
-record\install-record.txt --single-version-externally-managed --compile"
failed
 with error code 1 in
c:\users\sander\appdata\local\temp\pip-build-ygtavk\numpy

C:\Users\Sander>

*****************************************************************************************

which version of Theano I do need?

I have
theano.__version__
'0.7.0'


thanks
Sander

**Comment by dnouri** [comment]
> Perhaps it's time for a new pypi release?

:+1:

**Comment by Sandy4321** [comment]
Pls help understand which version of Theano is needed to work with current
Lasagne

**Comment by Sandy4321** [comment]
pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git
from
http://www.deeplearning.net/software/theano/install.html#bleeding-edge-install-instructions
helped to run 
import lasagne
without errors 
thanks for help

**Comment by f0k** [comment]
Closing because your first installation issue is resolved, and you opened another issue for the second one. Duly noted that we should focus on getting 0.2 ready.
