### ISSUE TITLE
Does call set_all_params_value several time can slow down computation ?

### ISSUE THREAD

**Issue by jrabary** [Lasagne/Lasagne#612]
Dear all,

I don't know whethere  here is a good place to ask this kind of question but I can't find a user mailing list for lasagne. 
I'm using lasage to train a triplet network. One important thing to consider is the selection of the triplet example. To speed up training, I have two process (with python multiprocessing) one for training and one for hard negative mining. After each training step I send the current network params values `get_all_params_value` to the triplet generator process. I load it from there with `set_all_params_value`.
I notice that if I do this get-set params very often, then the triplet generation process get slow down. 
Does this talk to someone ?

**Comment by f0k** [comment]
> but I can't find a user mailing list for lasagne.

Let us know if there's anything to make it easier to find. It's mentioned in the [README on the front page](//github.com/Lasagne/Lasagne), in the "Please review the [guidelines for contributing](https://github.com/Lasagne/Lasagne/blob/master/CONTRIBUTING.md) to this repository." link shown when opening an issue, and [the first hit on google](https://www.google.at/search?q=lasagne+mailing+list) (granted, "the first hit" is probably not universal at all).

> I notice that if I do this get-set params very often, then the triplet generation process get slow down.

Getting and setting the parameters should always take the same time, and not affect the network either. How do you send the weights? Can you check if there's a memory leak somewhere, i.e., does the memory usage go up over time (this will only affect your process when memory gets scarce, though)? If you don't send the parameters, does the triplet generation process also slow down after a while?

**Comment by jrabary** [comment]
After deep investigation, I think that my problem has nothing to do with the repeated call to set get.
By the way in my case, I send the parameters using multiprocess.Queue object. It uses pickle to serialize them. 
I close this issue because it's not a problem related to lasagne. 
Thank you.
