### ISSUE TITLE
No module named nonlinearities

### ISSUE THREAD

**Issue by m-decoster** [Lasagne/Lasagne#624]
**Operating System**: OS X El Capitan 10.11.1

I have installed Theano and Lasagne as per the instructions in the `README.md` file, but I keep getting the same error when trying to run the example also in that file:

```
Traceback (most recent call last):
  File "example.py", line 3, in <module>
    import lasagne
  File "/private/tmp/lasagne.py", line 10, in <module>
    from lasagne.nonlinearities import leaky_rectify, softmax
ImportError: No module named nonlinearities
```

I have tried reinstalling Lasagne and Theano, but I keep getting this error.

**Comment by f0k** [comment]
As you see, `import lasagne` tries to import the module from `/private/tmp/lasagne.py`, which is not actually the module you have installed. You will need to move `/private/tmp/lasagne.py` outside of your PYTHONPATH so it doesn't shadow the actual Lasagne module.

**Comment by dbankman** [comment]
**Operating System: Ubuntu 14.04**

I have a similar error:

`Traceback (most recent call last):`
`    File "mnist.py", line 33, in <module>`
`        import lasagne`
`    File "/home/dbankman/.local/lib/python2.7/site-packages/lasagne/__init__.py", line 22, in <module>`
`        from . import nonlinearities`
`ImportError: cannot import name nonlinearities`

This error only appears when I set `device=gpu`. 

I've installed the "bleeding edge versions" of Theano and Lasagne:
`pip install --upgrade https://github.com/Theano/Theano/archive/master.zip --user`
`pip install --upgrade https://github.com/Lasagne/Lasagne/archive/master.zip --user`

**Comment by dbankman** [comment]
I found that running
`theano-cache clear`
fixes the problem. Does anyone know exactly what that does?

**Comment by f0k** [comment]
> Does anyone know exactly what that does?

It deletes your current `~/.theano/compiledir-...` which caches compiled modules generated by Theano when compiling a function or when activating GPU support. When you update your CUDA version or graphics driver, it may happen that the GPU support module cannot be imported any longer as it links to earlier versions of system libraries, thus `import theano` fails, thus `from . import nonlinearities` fails, thus `import lasagne` fails. Forcing a recompile by deleting the theano cache is the easiest solution then.

**Comment by Jonbean** [comment]
@dbankman I have the similar problem and `theano-cache clear` doesn't work either. 

Here's my installation result:

`pip install https://github.com/Lasagne/Lasagne/archive/master.zip
Collecting https://github.com/Lasagne/Lasagne/archive/master.zip
  Downloading https://github.com/Lasagne/Lasagne/archive/master.zip (203kB)
    100% |████████████████████████████████| 204kB 1.3MB/s 
Requirement already satisfied (use --upgrade to upgrade): numpy in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from Lasagne==0.2.dev1)
Installing collected packages: Lasagne
  Running setup.py install for Lasagne ... done
Successfully installed Lasagne-0.2.dev1`

Here's the error:

`
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-7-950fc8a00ce6> in <module>()
----> 1 import lasagne

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lasagne/__init__.py in <module>()
     22 
     23 
---> 24 from . import nonlinearities
     25 from . import init
     26 from . import layers

ImportError: cannot import name nonlinearities`

**Comment by benanne** [comment]
What happens when you run `import theano`?

If possible, could you repost this question on our mailing list, so we can continue the discussion there? https://groups.google.com/forum/#!forum/lasagne-users
Our issue queue is not intended to be used for support. Thanks for your understanding and cooperation!

**Comment by silverlining21** [comment]
@dankolbman 
`theano-cache clear`
 I found it works for me only once, I need to re-run this cmd for each single time. that's not convenient at all.

**Comment by maltanar** [comment]
Not sure if it's a viable workaround, but changing the order of module imports solved this problem for me:

import lasagne 
import theano

**Comment by Euniceu** [comment]
File "C:\Anaconda\lib\site-packages\lasagne\__init__.py", line 17, in <module>
    from . import nonlinearities

ImportError: cannot import name nonlinearities

**Comment by f0k** [comment]
@Euniceu: What happens when you run `python -c "import theano"`?

**Comment by Euniceu** [comment]
@f0k nothing happend. I think I intalled theano corrected.

**Comment by f0k** [comment]
Yes, if nothing happens, theano was imported successfully. Does your `C:\Anaconda\lib\site-packages\lasagne` look complete, i.e., does it contain a `nonlinearities.py`? When you run `python -c "import lasagne"`, do you get [the stack trace posted before](https://github.com/Lasagne/Lasagne/issues/624#issuecomment-191494011)? What happens if you run `python -c "import lasagne.nonlinearities"`?

**Comment by JWilkenIxto** [comment]
hello, I have the same problem.
I tried everything, what was recommended here, but nothing solved my problem.
The lasagne folder contains nonlinearity.py
Here is my code and error:
![image](https://user-images.githubusercontent.com/29146232/28582817-1d9455be-7167-11e7-974b-0d9659173fa0.png)

**Comment by sashavor** [comment]
Has there been any progress in finding a solution to this? I have the same error...

**Comment by f0k** [comment]
@sashavor: There are different errors resulting in that message, and therefore different solutions. What's your setup? How did you install Lasagne? What path are you when trying to import it, and what path has Lasagne been installed to? Is there any other `lasagne.py` on your python path that shadows the installed module?
