### ISSUE TITLE
Make FlattenLayer support `None` in input shape

### ISSUE THREAD

**Issue by benanne** [Lasagne/Lasagne#625]
Currently, `FlattenLayer` does not work if any of the axes that are flattened have a shape of `None`. So this does not work:

```
l = lasagne.layers.InputLayer((None, None, None))
l = lasagne.layers.FlattenLayer(l)
```

Instead, users get an unhelpful error message because Lasagne attempts to compute the output shape nevertheless: 

```
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'
```

(see https://groups.google.com/forum/#!topic/lasagne-users/0fa-GRH8wwo )

The shape computation is here: https://github.com/Lasagne/Lasagne/blob/master/lasagne/layers/shape.py#L46-L49

I think we can easily adapt this to simply return `None` for the flattened dimension of any of the constituent dimensions from the input shape have size `None`.

Any takers? :) If nobody wants to I can probably do a PR this weekend. Shouldn't be too much work, but I don't have much time to spare at the moment.

**Comment by chuzui** [comment]
It looks simple. Maybe I can give a try.
