### ISSUE TITLE
Question regarding RNNLayer

### ISSUE THREAD

**Issue by ramalhoruben** [Lasagne/Lasagne#632]
Is it possible, with the current implementation of the RNNLayer, to implement a recurrent net which feeds on the results of conv layers? Something like the architecture used in this paper:

http://arxiv.org/pdf/1412.5567v2.pdf

The illustration in the paper portraits very clearly what I pretend. If it is indeed possible, how can I accomplish it? Conv layers don't seem to accept input masks.. and my signals doesn't haver a fixed length.

**Comment by skaae** [comment]
Yes. You just need to dim shuffle a bit. Can you move the question to the
mailinglist?
. This page is for bugs etc.
Den 05/03/2016 17.00 skrev "r.ramalho" <notifications@github.com>:

**Comment by ramalhoruben** [comment]
I will, thank you.
