### ISSUE TITLE
Dropout performance

### ISSUE THREAD

**Issue by f0k** [Lasagne/Lasagne#64]
Looking at [the dropout code](https://github.com/benanne/nntools/blob/2840cbc657ff341ef2f1654c1a5916d0fbe3931e/nntools/layers/base.py#L414-428), I see two potential performance problems:

``` python
return input * utils.floatX(_srng.binomial(input.shape, p=retain_prob, dtype='int32'))
```
1. If you follow the implementation, the binomial is computed in 'floatX', then casted to 'int32' (inside `binomial()`) and then back to 'floatX'. It should be better to set the dtype to `theano.config.floatX` right away, or was there a reason?
2. The size is symbolic (`input.shape`) rather than explicit (`self.input_layer.get_output_shape()`). This way `MRG_RandomStreams` cannot determine the number of streams to use and falls back to a default value. Is there a reason against using the explicit shape? Does `DropoutLayer` have to support shapes different from the compile time shape? Should we support this via an extra optional `input_shape` argument in `get_output_for`, similar to the convolutional layers, or maybe via a flag in the constructor (`use_runtime_shape=True`, `fixed_shape=False` or something)?

**Comment by dnouri** [comment]
For the record (search engines).  For those like me who (wrongly) set a fixed batch size in the input layer, but were passing batches with variable size into the network, this change in `DropoutLayer` may trigger an error like:

```
ValueError: GpuElemwise. Input dimension mis-match. Input 1 (indices start at 0) has shape[0] == 128, but the output's size on that axis is <SOME_NUMBER>.
```

The right thing to do is to set the batch size to `None` when specifying the `shape` of your input layers; this is what's referred to in the [previous comment] (https://github.com/benanne/Lasagne/issues/64#issuecomment-68097383).

@benanne I tested both `layers.Conv2DCCLayer` and `layers.cuda_convnet.Conv2DCCLayer`, and both seem to be okay with a variable batch size indicated by `None`.

**Comment by benanne** [comment]
@dnouri do you mean `layers.Conv2DLayer`? Because those two are the same now :) The cuda-convnet wrappers don't require any shape info so I'm sure they're fine. The regular `Conv2DLayer` might or might not be (it shouldn't be too hard to fix that anyway). We'll need to add tests for this use case because it seems easy to forget about it.

**Comment by dnouri** [comment]
@benanne Yes, I meant `layers.Conv2DLayer`; it just works. Haven't tried with dnn_conv or GpuCorrMM yet; these are the defaults in newer versions of Theano.
