### ISSUE TITLE
Make get_params optionally return expressions?

### ISSUE THREAD

**Issue by wielandbrendel** [Lasagne/Lasagne#641]
While implementing a form of [BinaryConnect](https://github.com/MatthieuCourbariaux/BinaryConnect) I noticed that get_params returns only the shared variables, but not expressions. That makes perfect sense e.g. for low-rank dense layers (where W = UV is a Theano expression with U and V as shared variables). I now have the opposite use case: I'd like to register an expression as a parameter of which I later want to compute the gradient, so I want get_param to return that expression instead of the shared variables contained. In principle that is easy to implement: one could add a keyword "only_shared=True" in get_params and modify the return statement. 

If you like the idea I can open a pull request.

[Further info on use case]: My use case is as follows: I have a parameter that is binary (e.g. 0 or 1), but I'd still like to use SGD to optimize that parameter. To this end I follow BinaryConnect and define a new real-valued hidden variable *p* with support *[0,1]* (through clipping). The binary parameter is then implemented as a simple Bernoulli process with probability *p*. The parameter *p* is then updated in the direction of the gradient with respect to the binary parameter (so e.g. if the binary parameter b was 1, and the is positive with respect to this parameter, then p is increased).

**Comment by f0k** [comment]
In https://github.com/Lasagne/Lasagne/issues/11#issuecomment-134951719, we figured that we'd only add this if there's a use case. Now that you've got a use case, yes, you're very welcome to send a PR! It's basically just about calling or not calling `collect_shared_vars()` in `Layer.get_params()`. The crucial parts are: Finding a good name for the new keyword argument, and documenting it well. Parameter expressions are something that many users won't use, so we should make sure they're not confused by this. Note that most of the `get_params` and `get_all_params` docstring assumes that we always return a list of shared variables, so the text needs several changes.

About the keyword name, I'd suggest something like `unwrap_shared` (or just `unwrap`?) -- your suggestion of `only_shared` sounds as if it would skip parameter expressions completely!

**Comment by wielandbrendel** [comment]
@fok I like the keyword 'unwrap_shared' and have made the necessary modifications (see PR). I also changed the docstrings accordingly (hope I didn't miss anything...).
