### ISSUE TITLE
Check that Layer.output_shape is not symbolic

### ISSUE THREAD

**Issue by f0k** [Lasagne/Lasagne#645]
Users creating custom layers may inadvertently have `get_output_shape_for()` return a (partly) symbolic shape (e.g., https://groups.google.com/forum/#!topic/lasagne-users/uEPYSSk6sRI). The `Layer.output_shape` property could check that it returns a valid shape, i.e., a tuple that only contains integers, or numpy integers, or `None`. If not, it could display a helpful error message.

**Comment by benanne** [comment]
This is an excellent idea, it seems to be a common mistake. It's a small addition that won't get in anyone's way and will improve usability a little bit. I'm all for it :)
