### ISSUE TITLE
DOCS: "[Math Processing Error]"

### ISSUE THREAD

**Issue by JackKelly** [Lasagne/Lasagne#649]
I'm a huge fan of Lasagne: thank you to everyone involved!

Maths does not appear to be rendering correctly in the docs.  Specifically, red text saying "[Math Processing Error]" appears in place of the rendered maths.  For example, these documentation pages show the issue:

* [lasagne.layers.BatchNormLayer](http://lasagne.readthedocs.org/en/latest/modules/layers/normalization.html#lasagne.layers.BatchNormLayer)
* [lasagne.objectives.categorical_crossentropy](http://lasagne.readthedocs.org/en/latest/modules/objectives.html#lasagne.objectives.categorical_crossentropy)

**Comment by skaae** [comment]
Thats odd. I can't see any rendering errors using either FF or safari? Maybe its a browser issue?

**Comment by JackKelly** [comment]
Hmm, you're right: it is a browser issue!

Using Google Chrome Version 49.0.2623.110 (64-bit) on Ubuntu Linux 15.10, this is what I see:

![image](https://cloud.githubusercontent.com/assets/460756/14105492/c29b72c2-f5a3-11e5-8f79-7cf58314314f.png)

But using FF 45.0, I see this:

![image](https://cloud.githubusercontent.com/assets/460756/14105533/159d0f26-f5a4-11e5-8565-1ddd2dc4edbf.png)

**Comment by JackKelly** [comment]
Hmm... doing a force-refresh on Chrome appears to fix the issue... how odd...

![image](https://cloud.githubusercontent.com/assets/460756/14105567/49bb9da4-f5a4-11e5-83d2-cd298a90f3c2.png)

**Comment by JackKelly** [comment]
(thanks for the very quick reply, BTW - and sorry for bothering you... seems this issue has gone away now... not entirely sure what went wrong!)
