### ISSUE TITLE
Denselayer for DBLSTM

### ISSUE THREAD

**Issue by zzw922cn** [Lasagne/Lasagne#655]
Now I want to construct a Deep Bidirectional LSTM network,at the bottom of my network,I want to use Dense Layer,but I can't implement this ,because I find I only can use recurrent layer for the bottom.How to solve my problem?Thank you!

**Comment by f0k** [comment]
Closing because this is a usage question. Please re-post on our mailing list (https://groups.google.com/forum/#!forum/lasagne-users) if the problem is still unsolved.
