### ISSUE TITLE
adding train accuracy

### ISSUE THREAD

**Issue by rayset** [Lasagne/Lasagne#662]
I'm trying the mnist example, but I really don't get how could I add the train accuracy.

It only comes with the validation accuracy but I think for beginners it would be great if it could include this other accuracy too.

Any idea on how to implement it?

**Comment by f0k** [comment]
`val_fn` already shows how to compute the validation accuracy. Just go backwards from `err, acc = val_fn(inputs, targets)` and change any occurrence of `train_fn` to match the corresponding occurrence of `val_fn`. Also go through the introductory material in the tutorial (http://lasagne.readthedocs.org/en/latest/user/tutorial.html#before-we-start) so you understand every single line of the MNIST example, afterwards it will be easy!

In future, please post such questions on the [mailing list](https://groups.google.com/forum/#!forum/lasagne-users), as indicated in the [guidelines for contributing](/Lasagne/Lasagne/blob/master/CONTRIBUTING.md) linked above the "New Issue" form. Thanks!
