### ISSUE TITLE
MergeLayer fails in python 3 when input layers have shapes containing None

### ISSUE THREAD

**Issue by aitkenap** [Lasagne/Lasagne#674]
The function `autocrop_array_shapes` (lasagne/layers/merge.py) raises a `TypeError` in python 3 when any of the `input_shapes` have any elements of type `NoneType`.

Sample code:

```
from lasagne.layers.merge import autocrop_array_shapes

# Works for python 2 and 3
shape_no_crop = autocrop_array_shapes([(None, 2, 3, 4), (5, 6, 7, 8)], cropping=None)
print("Shape with no cropping:")
print(shape_no_crop)

# Works for python 2, fails for python 3
shape_crop = autocrop_array_shapes([(None, 2, 3, 4), (5, 6, 7, 8)], cropping=["center"]*4)
print("Shape with cropping:")
print(shape_crop)
```

python2.7 output:

```
Shape with no cropping:
[(None, 2, 3, 4), (5, 6, 7, 8)]
Shape with cropping:
[(None, 2, 3, 4), (None, 2, 3, 4)]
```

python3.4 output/stack trace:

```
Shape with no cropping:
[(None, 2, 3, 4), (5, 6, 7, 8)]
Traceback (most recent call last):
  File "/home/magicpony/Lasagne/examples/merge_layer_bug.py", line 12, in <module>
    shape_crop = autocrop_array_shapes([(None, 2, 3, 4), (5, 6, 7, 8)], cropping=["center"]*4)
  File "/home/magicpony/Lasagne/lasagne/layers/merge.py", line 236, in autocrop_array_shapes
    result.append([min(sh)] * len(sh))
TypeError: unorderable types: int() < NoneType()
```

I am using:
 - Python 2.7/3.4
 - Lasagne Master (d1d7843a346c8182df26b1d83cf43b6b7d4ba78b)
 - Theano 0.8.0

This seems to be caused by the changes between python 2 and 3 in comparing objects of different types. In python 2, `int() < None` evaluates to `False`. In python 3 this raises a `TypeError: unorderable types` (same goes for `None < None`).

It seems to me that the behaviour of `autocrop_array_shapes` in python 2 is expected.
(i.e. if the shape for a particular axis is `None` for any of the inputs, `None` should be returned for the shape after cropping).

To set some context within a more practical use case, here is an example that behaves as expected in python 2 but raises the exception in python 3 (using a `MergeLayer` with an `InputLayer` for which `shape=(None, 4, None, None)`.

```
import numpy
import theano
import theano.tensor as T
from lasagne.layers import InputLayer, Conv2DLayer, get_output
from lasagne.layers.merge import ElemwiseSumLayer

inputTensor1 = T.tensor4("input1")
inputTensor2 = T.tensor4("input2")

imgSize = 20
inputLayer0 = InputLayer(shape=(None, 4, None, None), name="inputLayer1")
inputLayer1 = InputLayer(shape=(None, 4, None, None), name="inputLayer2")

inputData0 = numpy.ones((10, 4, imgSize, imgSize))
inputData1 = numpy.ones((10, 4, imgSize + 2, imgSize -2))

# Merge layer followed by conv layer:
net =  ElemwiseSumLayer([inputLayer0, inputLayer1], cropping=["lower"] * 4)
net = Conv2DLayer(net, num_filters=4, filter_size=3)

inputs = [inputTensor1, inputTensor2]
output = get_output(net, inputs={inputLayer0: inputs[0], inputLayer1: inputs[1]})
predictFunction = theano.function(inputs, output)

outputData = predictFunction(inputData0, inputData1)
print("Shape of output data:")
print(outputData.shape)

print("Expected shape:")
print(10, 4, 18, 16)
```

I think this can be fixed so that it works in both python 2 and 3 by replacing line 236 of lasagne/layers/merge.py (in `autocrop_array_shapes` ):
```
result.append([min(sh)] * len(sh))
```
with:
```
min_sh = None if any(x is None for x in sh) else min(sh)
result.append([min_sh] * len(sh))
```
If this is the desired behaviour, I'm happy to add some tests and submit a PR.

**Comment by f0k** [comment]
Thanks a lot for your finding and the detailed report!

> If this is the desired behaviour, I'm happy to add some tests and submit a PR.

This would be highly appreciated. A single additional test case for `autocrop_array_shapes` along the lines of your first example would be enough, and your code fix looks good! Let me know if you need any help (http://lasagne.readthedocs.io/en/latest/user/development.html#how-to-contribute gives some hints on how to install things to be able to run the tests locally).

**Comment by aitkenap** [comment]
Great, thanks. I'll try to find some time this week.
