### ISSUE TITLE
i want to use 2D convolutional net to deal  some textual input. and i need 3 different filter size.for example ,the input sentence matrix is 30x300 . filter1 size= 2x300,filter2 size = 3x300,filter3 size = 4*300. what should i do?

### ISSUE THREAD

**Issue by 450586509** [Lasagne/Lasagne#675]
by the way , i think this function can not deal with different filter_size. 
An integer or a 2-element tuple specifying the size of the filters.
lasagne.layers.Conv2DLayer(network,num_filters=32,filter_size(5,5),nonlinearity=lasagne.nonlinearities.rectify,W = lasagne.init.GlorotUniform())

**Comment by f0k** [comment]
> what should i do?

You'd create three Conv2DLayers and concatenate them afterwards:
```python
a = Conv2DLayer(network, 32, (2, 300), pad='same')
b = Conv2DLayer(network, 32, (3, 300), pad='same')
c = Conv2DLayer(network, 32, (4, 300), pad='same')
network = ConcatLayer([a, b, c], axis=1)
```

In future, please post such questions on our mailing list instead, as indicated in the yellow link above the issue submission form. The issue tracker is meant for bug reports and feature discussions, not for support. Thanks!
