### ISSUE TITLE
MissingGxx , g++ not available Error

### ISSUE THREAD

**Issue by ahmed-18** [Lasagne/Lasagne#684]
I've been trying to deploy my Python Flask App that uses Conv nets using Lasagne on local IIS. When I try to load a pickled Neural Network , I get following Errors

1. Unable to Create compiledir. I solved this by changing compiledir path in configdefaults.py and giving read/write rights to IIS on that directory. Now compiledir gets created and I get a different type of error given below.
2. Now I'm getting MissingGXX error "g++ not available! We can't compile c code.". G++ is there in my PythonFolder\Scripts and I've added this path to my environmental variable PATH.

> I just Want to know that what causes this error while g++ is already there and added to PATH? Is it because Theano can't find g++ and it's all about path issues or it has something to do with compiledir lock

PS: I can run the code from my Winpython console and everything works fine. I've seen the contents of %PATH% , %PYTHONPATH% and %HOME% from my Win python console and replicated the same on my deployed IIS web App.

Here's the header of the stack trace :

(MissingGXX('The following error happened while compiling the node', Shape_i{0}(input.input), '\n', "g++ not available! We can't compile c code.", '[Shape_i{0}(input.input)]'), , (

**Comment by f0k** [comment]
This is a problem related to Theano, not a Lasagne issue. We're willing to help, but please let's keep this discussion on the mailing list (at [your existing post](https://groups.google.com/forum/#!topic/lasagne-users/XbueQOw8YTE)). The Lasagne issue tracker is meant for bug reports and feature discussions regarding Lasagne only. Thank you!
