### ISSUE TITLE
in LSTM, i want to use Xt and the out put of time T-1 as input of time T ,how to write the layer?

### ISSUE THREAD

**Issue by coderLong** [Lasagne/Lasagne#688]

**Comment by f0k** [comment]
This is currently not easily possible, see https://groups.google.com/d/msg/lasagne-users/p4rGKqnKAtY/ckDGX2CTDQAJ. In future, please post such questions on our mailing list, the issue tracker is meant for bug reports and feature discussions only. Thank you!
