### ISSUE TITLE
Casscade of CNN

### ISSUE THREAD

**Issue by gogolgrind** [Lasagne/Lasagne#691]
Hello to everyone!. For now I am work on some object detection. My goal is implement this structure:
![casscade](https://lh3.googleusercontent.com/-9ebTuinMRJ8/VxAs6rLm5DI/AAAAAAAAAGw/7Kfl4ljvul8c5-rHUBY91o2GYsEojJBlwCLcB/s1600/ccnn.JPG)
It is from following article: [click](http://www.cv-foundation.org/openaccess/content_cvpr_2015/papers/Li_A_Convolutional_Neural_2015_CVPR_paper.pdf)
I don't understand, how to connect full connected layers of 12-net and 24-net.
Can you get me some advices what should I do?
Am I right, that to do this connection I need create other definition of CNN? I mean, If have two separate trained models (e.g. 12-net and 24-net) it is impossible  connect them, isn't it?

**Comment by f0k** [comment]
Already answered on our mailing list (which is the correct place for such questions): https://groups.google.com/d/topic/lasagne-users/mUF4dYDpId8/discussion
