### ISSUE TITLE
Conv2DLayer memory problem

### ISSUE THREAD

**Issue by btpeter** [Lasagne/Lasagne#700]
Hello there, I am stuck in CNN for few days.
Here is my network:

```
def build_cnn(input_var=None):
	# Input
	input_var = T.cast(input_var.reshape((-1, 1, 200, 4)),"float32")
	network = lasagne.layers.InputLayer(shape=(None,1,200,4),input_var=input_var)
	# Convolutional One
	network = Conv2DLayer(
			network,
			num_filters=conv_one,
			filter_size=(conv_win,1),
			nonlinearity=lasagne.nonlinearities.rectify,
			W=lasagne.init.GlorotUniform())

	network = MaxPool2DLayer(network, pool_size=(pool_win,1), stride=pool_win)
	# Full Connection
	network = lasagne.layers.DenseLayer(
			network,
			num_units=full,
			nonlinearity=lasagne.nonlinearities.rectify)
	# Output
	network = lasagne.layers.DenseLayer(
			network,
			num_units=1,
			nonlinearity=lasagne.nonlinearities.sigmoid)
	return network
```

My dataset is about 600M, when i use **num_filters=10 or 20** ,it worked.
But when i use **num_filters=50**,it would use more 10g RAM and finally core dumped.
Is that NORMAL?
Please let me know if I am making some mistakes and suggest me the solution.
I Would really appreciate the help. Thx.

**Comment by f0k** [comment]
If you're running on CPU, by default it will use the gemm-based convolution from Caffe, which copy-expands the input such that the convolution becomes a single dot product with the reshaped kernel tensor. This expansion requires a nontrivial amount of extra memory. If you happen to pass your complete dataset through the network at once, it may well exceed your available memory. Try to pass it in smaller chunks (like 64 examples each). Theano also offers a different convolution implementation, but this is slower (pass `THEANO_FLAGS=optimizer_excluding=conv_gemm` if you want to try this).

In the future, please post such questions to our mailing list, the issue tracker is meant for bug reports and feature discussions only. Thank you!
