### ISSUE TITLE
How to dealocate network from gpu memory?

### ISSUE THREAD

**Issue by eduardo4jesus** [Lasagne/Lasagne#705]
This [theano-topic](https://groups.google.com/forum/#!topic/theano-users/E0zgD1PxC3U) shows how to free the gpu memory allocated by a shared variable.

Given a Lasagne network, for instance the MLP in the MNIST example, I need to free the gpu memory it allocated. But I can't figured out how. I already tried deleting it and then call `gc.collect` but it doesn't work.

How could I de-reference all the shared variables at once?

Thanks.

**Comment by f0k** [comment]
> How could I de-reference all the shared variables at once?

Deleting all references to the network and any expressions derived from it (including update dictionaries and compiled functions), then calling `gc.collect` should free the memory. Are you sure the shared variables are the culprit?

**Comment by eduardo4jesus** [comment]
I am doing some tests with the [MNIST](https://github.com/Lasagne/Lasagne/blob/master/examples/mnist.py) in order to understand how to deallocate the network memory. This is the first test I could think about:

I changed the number of units from 800 to 32000 so the allocated memory is more expressive when watching the GPU Memory Usage with `nvidia-smi -l 1`. Then, using `pudb3` for debugging, I put breakpoints in the lines 106 and 112, so I can observe the exactly moment when the GPU memory increases from 92MiB to 189MiB.

Then, still inside the `pudb3`, in the command line with the thread still stopped, I execute:
```
del l_hid1
l_hid1 = None
import gc
gc.collect()
```
`gc.collect()` returned 375. But the GPU Usage Memory for my process stayed in 189MiB.

**Comment by f0k** [comment]
> `gc.collect()` returned 375. But the GPU Usage Memory for my process stayed in 189MiB.

Can you write a short test script exhibiting this behaviour? I.e., not a fully-fledged MNIST training script, just a minimal example? This will make it easier to determine what's going on.

**Comment by eduardo4jesus** [comment]
Thank you for asking me this. I made a short test as you asked, then I realized that the memory was actually being freed only by unreferencing the network despite having `allow_gc=false` in `.theanorc`. No need to even explicitly calling `del` or `gc.collect()`.

Also, I realized that `pudb3` was tricking me the whole time. Let's say I have this code snippet:
```
33 def main():                           
34     input_var = T.tensor4('inputs')   
35                                       
36     nets = []                         
37     for i in range(3):                
38         network = build_mlp(input_var)
39         nets.append(network)         
40         print('break here')           
41                                       
42     print('break here as well')       
43                                       
44                                       
45 if __name__ == '__main__':            
46     main()                            
47     print('last break')               
```
When I had a breakpoint at line 42. Though I assigned `nets = None` and deleted it, the debugger was, somehow, still holding references to those structures. After leaving the `main` function and break again on `line 47`, the GPU memory came back to 'normal'. I tested it again without doing anything and realized that, as said earlier, nothing needs to be done.

Thanks again.
