### ISSUE TITLE
Check for floatX != float64 on importing dnn

### ISSUE THREAD

**Issue by f0k** [Lasagne/Lasagne#706]
As reported on [lasagne-users](https://groups.google.com/d/topic/lasagne-users/u2enSHC81w0/discussion), using a cuDNN layer when `theano.config.floatX=float64` leads to error messages that are difficult to interpret, because the shared variables for the parameters are created as float64 variables and then tried to be cast as CUDA arrays inside the convolution Ops.

We may want to at least issue a clear warning when importing lasagne.layers.dnn and floatX=float64 (same for the cuda-convnet and corrmm layers).

**Comment by benanne** [comment]
Interesting. I'm not sure I fully understand what's going on though, isn't Theano supposed to complain instead of trying to forcefully cast these? Or is this our mistake?

**Comment by f0k** [comment]
Well, it does complain when the expression is built (concretely, [in this line](https://github.com/Theano/Theano/blob/rel-0.8.2/theano/sandbox/cuda/dnn.py#L419)):
```
TypeError: CudaNdarrayType only supports dtype float32 for now. Tried using dtype float64 for variable None 
```
It's just that Theano's complaint is not very user-friendly, because it relates to trying to convert the input expression to the `Conv2DDNNLayer` (which has a name of `None`) to a `CudaNdarray`. And if floatX=float64, there's hardly any way to have the input expression remain float32, users would have to create all variables and parameters manually.
There is a way, though, and also it's possible somebody makes a case distinction in their code to not use `Conv2DDNNLayer` when floatX=float64, so I'd make it a warning, not an error. Nothing bad happens when you merely *import* the `dnn` module.

The alternative would be to throw an exception in `get_output_for()` of all cuDNN-based layers, when we can check whether the input and/or weights are double precision.

**Comment by benanne** [comment]
Alright, warning sounds good to me. I'd be fine with the alternative as well, I think.

**Comment by f0k** [comment]
@ReyhaneAskari: Now that Lasagne uses the new backend when available, I think the warning should be thrown at the import, when we find that the old backend is used and floatX=float64 -- or what exactly happens when trying to use these layers under the new backend with float64?

**Comment by nouiz** [comment]
float64 should work in the new back-end. But it isn't much tested. So maybe
some cudnn kernel will fail as they don't always support it but we don't
make special handling of this to prevent that.

But float64 is slow on many GPUs. So I think a warning is still a good idea.

**Comment by f0k** [comment]
> But float64 is slow on many GPUs. So I think a warning is still a good idea.

Okay, then I'd suggest to add a warning in the three GPU layer modules when we made it past the GPU check and find that floatX = float64. This will only reach users which use `layers.dnn` or `layers.cuda_convnet` or `layers.corrmm`, which we actually don't want to encourage at all, but still it would have helped at least the poor soul mentioned in the top post. And it's super easy to implement (even with a test).
