### ISSUE TITLE
DilatedConv2DLayer: dilation or dilation-1

### ISSUE THREAD

**Issue by justinsalamon** [Lasagne/Lasagne#707]
In the DilatedConv2DLayer docstring, for the `dilation` parameter [it says](https://github.com/Lasagne/Lasagne/blob/master/lasagne/layers/conv.py#L812-L814): 
```
An integer or a 2-element tuple specifying the dilation factor of the filters, 
i.e., the number of zeros inserted between filter elements
```
Which implies that a dilation factor of e.g. 1 would insert 1 zero between every pair of filter elements. However, the note at the bottom [says](https://github.com/Lasagne/Lasagne/blob/master/lasagne/layers/conv.py#L868-L874):
```
The dilated convolution is implemented as the backward pass of a
convolution wrt. weights, passing the filters as the output gradient.
It can be thought of as dilating the filters (by adding ``dilation - 1``
zeros between adjacent filter elements) and cross-correlating them with the
input. See [1]_ for more background.
```
Which implies that a dilation factor of 1 would result in no zeros being added between filter elements.

Looking at the code I think the latter is what actually happens (?), but it would be helpful if this were clarified in the docstring for the dilation parameter.

**Comment by f0k** [comment]
Hey Justin, thanks for your report! The first description was wrong indeed, good catch. I've submitted a fix. See you in August!
