### ISSUE TITLE
Add `shared_axes` argument to DropoutLayer

### ISSUE THREAD

**Issue by f0k** [Lasagne/Lasagne#710]
As discussed in #701, adding a `shared_axes` argument to `DropoutLayer` would allow several additional use cases for dropout:
* shared_axes=(): standard dropout
* shared_axes=(0): batch-wise dropout (use the same dropout mask across axis 0)
* shared_axes=(2,3): drop full feature maps (use the same dropout mask across axes 2 and 3)
* shared_axes=(1,2): drop full frequency bands of spectrograms (use the same dropout mask across axes 1 and 2)

In addition, we could have a `spatial_dropout()` shortcut (possibly coordinate the naming with whatever we decide for #626).

**Comment by benanne** [comment]
I like it. Adding a shortcut for what is probably going to be the most common use case sounds like a great idea as well.

**Comment by f0k** [comment]
> possibly coordinate the naming with whatever we decide for #626

Let's revive this pesky naming discussion. I'd like to coordinate naming for the following four things:
1. Drop full channels (feature maps) -- called spatial dropout [elsewhere](https://github.com/torch/nn/blob/master/doc/simple.md#nn.SpatialDropout)
2. Drop full pixels
3. Softmax across channels, i.e., per pixel -- called spatial softmax [elsewhere](https://github.com/torch/nn/blob/master/doc/transfer.md#spatialsoftmax)
4. Softmax across pixels, i.e., per channel -- called spatial softmax [elsewhere](http://arxiv.org/abs/1509.06113)

*spatial* is a little ambiguous. It tells that it will expect the input to have spatial dimensions and treat them differently, but it doesn't tell in what way.

What about ChannelDropout, PixelDropout, PixelwiseSoftmax, ChannelwiseSoftmax (in that order)?

Close alternatives: PixelwiseDropout does not make clear whether it drops pixels, or has the same dropout mask applied to each pixel. PixelSoftmax does not make clear whether it applies a softmax per pixel, or computes distributions over pixels.

Flaw: While "spatial" can refer to 1D, 2D and 3D (unless in Torch, where it's used for 2D, and volumetric for 3D), "pixel" is pretty much tied to 2D. I wouldn't want to distinguish dimensionalities, though. "location" would be a substitute for "pixel".

**Comment by benanne** [comment]
If we do PixelDropout we should probably also do PixelSoftmax though (and not PixelwiseSoftmax). That said, I'm not sure if I'm sold on 'pixel' because as you said it only really works in 2D.

Couldn't we just be opinionated and go with "Spatial" and "Channelwise"? SpatialSoftmax would then be consistent with the Torch usage (which I think is a stronger argument than its use in a paper). We could add a note to the documentation that explains the difference.

**Comment by f0k** [comment]
> If we do PixelDropout we should probably also do PixelSoftmax though (and not PixelwiseSoftmax).

But PixelSoftmax is ambiguous. I think we can't adopt the same naming scheme for dropout and softmax.

> Couldn't we just be opinionated and go with "Spatial" and "Channelwise"?

So we'd have SpatialDropout, ChannelwiseDropout, ChannelwiseSoftmax and SpatialSoftmax for the four cases above, in this order? I think ChannelwiseDropout sounds like referring to the first case, not the second.

> SpatialSoftmax would then be consistent with the Torch usage (which I think is a stronger argument than its use in a paper).

Yes, I just wanted to point out that it's still ambiguous. I'm all for having a spatial_softmax and spatial_dropout shortcut, but I'd like to make them aliases to something inambiguous.

What about `spatial_dropout = dropout_channels`, `dropout_locations`, `spatial_softmax = softmax_per_location`, `softmax_per_channel`, in this order? I think this is inambiguous. (We could even add `softmax_over_channels = softmax_per_location` aliases and vice versa.)

I'll do the dropout implementation first; the softmax implementation needs some thought, as it may be better to move this into Theano.

**Comment by benanne** [comment]
> What about spatial_dropout = dropout_channels, dropout_locations, spatial_softmax = softmax_per_location, softmax_per_channel, in this order? I think this is inambiguous. (We could even add softmax_over_channels = softmax_per_location aliases and vice versa.)

That sounds great, those are indeed completely unambiguous.
