### ISSUE TITLE
TransposedConv2DLayer: output_size argument

### ISSUE THREAD

**Issue by f0k** [Lasagne/Lasagne#711]
The `TransposedConv2DLayer` currently produces an output of the minimum size that could have produced its input in a forward convolution. Sometimes that's not what you want: For a encoder/decoder architecture, you'll want each transposed convolution in the decoder to recreate the input shape of the corresponding forward convolution in the encoder. For example, convolving a 32x32 input with 3x3 filters, stride 2x2 and "same" padding will produce a 16x16 output, but applying the corresponding transposed convolution will produce a 31x31 output only (because a 31x31 input would have resulted in a 16x16 output as well).

To solve this, as agreed in #610, we should add an optional `output_size` argument to the `TransposedConv2DLayer` constructor that allows to override the inferred minimum output size.

**Comment by dhaneshr** [comment]
Hi,

What is the current status of this issue ?

**Comment by f0k** [comment]
Nobody has picked it up yet, you're very welcome to send us a PR! Let us know if you need any guidance.
