### ISSUE TITLE
How to get the gradient( dL/dw) of the first hiden layer during training?

### ISSUE THREAD

**Issue by zzd1992** [Lasagne/Lasagne#712]

**Comment by f0k** [comment]
Just add it as an additional output of your `train_fn` function:
```
train_fn = theano.function([input_var, target_var],
                           [loss, theano.grad(loss, wrt=layer1.W)],
                           updates=updates)
```
This assumes `layer1` is the first hidden layer. If you didn't keep it around when building the network, you can get it as `lasagne.layers.get_all_layers(network)[1]` (`[0]` would be the input layer, so `[1]` is the first layer processing the input).

In future, please post such questions on our mailing list, this issue tracker is meant to be reserved for bug reports and feature discussions. Thank you!
