### ISSUE TITLE
How to set 'target_values' when use LSTMLayer and I want to use all timesteps' output 

### ISSUE THREAD

**Issue by wu-hanqing** [Lasagne/Lasagne#713]
I have read the [example](http://lasagne.readthedocs.io/en/latest/modules/layers/recurrent.html#examples) of how to get all timesteps' output, but I didn't know how to set the corresponding target_values, I thought it should be a matrix, but I got a exception: TypeError: matrix required for argument: coding_dist.
Can you give some complete examples? Thanks!

**Comment by f0k** [comment]
Just call `your_output_layer.output_shape` and see what dimensionality it has. For binary cross-entropy, the dimensions should match. For categorical cross-entropy, both predictions and targets must be a matrix, or predictions must be a matrix and targets must be an integer vector ([as documented](http://lasagne.readthedocs.io/en/latest/modules/objectives.html#lasagne.objectives.categorical_crossentropy)). Possibly you will need to reshape the output of your LSTM from `(batchsize, seq_len, num_out)` to `(batchsize*seq_len, num_out)`, with a `ReshapeLayer(..., (-1, [-1]))`, *before* applying a softmax nonlinearity.

In future, please post such questions on our mailing list, this issue tracker is meant to be reserved for bug reports and feature discussions. Thank you!
