### ISSUE TITLE
How to learn the leakiness parameter of leaky relu (leaky_rectify)

### ISSUE THREAD

**Issue by c0tzelepis** [Lasagne/Lasagne#714]
Let's assume that I want to use as the activation function of a convolutional layer, the leaky relu. Do I need to set the leakiness to a constant value? For instance, taken from an example (found here: http://lasagne.readthedocs.io/en/latest/modules/nonlinearities.html), we can define the leaky relu with a fixed leakiness parameter equal to 0.1 as follows:

```
from lasagne.nonlinearities import LeakyRectify
custom_rectify = LeakyRectify(0.1)
l1 = DenseLayer(l_in, num_units=200, nonlinearity=custom_rectify)
```

What really concerns me if how I could use the leakiness parameter as an extra parameter of the network that could be learned during training. Is this possible?

Thank you very much for your help.

**Comment by f0k** [comment]
Yes, a leaky rectifier with learnable leakiness is called a Parametric ReLU (PReLU) in literature, and available as [`lasagne.layers.ParametricRectifierLayer`](http://lasagne.readthedocs.io/en/latest/modules/layers/special.html#lasagne.layers.ParametricRectifierLayer). It's not in `lasagne.nonlinearities` because nonlinearities in Lasagne are supposed to be fixed functions, they do not have an API to register trainable parameters. To use the parametric rectifier, just place it after the layer you want the nonlinearity to be applied to, and set that layer's nonlinearity to `None` or `lasagne.nonlinearities.identity` (that's the same):
```python
from lasagne.layers import ParametricRectifierLayer as Prelu
layer = InputLayer(...)
layer = Prelu(DenseLayer(layer, num_units=..., nonlinearity=None))
```

**Comment by c0tzelepis** [comment]
@f0k 
Thank you very much for your prompt answer. Just another question, if you may. Can I define myself a new parametric activation function with an extra learnable parameter? Just like the leaky relu. I have a closed form for the activation function, as well as a closed form for its first derivatives with to the new parameter (and wrt to the filter weights, biases). Is there any way of doing that? Thank you very much for you help.

**Comment by f0k** [comment]
Sure, just have a look at the source code: https://github.com/Lasagne/Lasagne/blob/9805a16/lasagne/layers/special.py#L923-L999
You can probably ignore the part about the `axes` argument in the constructor and the `dimshuffle` in `get_output_for()`, but this gives you the basic structure: Subclass `lasagne.layers.Layer`, implement `__init__()` to register any learnable parameters via `self.add_param()`, and override `get_output_for()` with your closed form of the activation function. If your layer changes the shape of the output to be different than the input shape, also implement `get_output_shape_for()`. You don't need the closed form of the first derivative anywhere, Theano will derive it automatically.

**Comment by c0tzelepis** [comment]
@f0k thank you very much again for your invaluable help. I will try to act as you suggest, but I would to ask another question. Please let me know in advance if this is ok. It's not my intention to spam the repo, neither to bother you. I just think that some people may benefit by this.

Any activation function is applied in a pixel-wise fashion to the output of a convolutional layer. That is, say that we have an activation function; for the sake of simplicity let it be relu: f(x)=max(0,x). Then, x is value of a pixel that is the result of the application of a filter with parameters (w,b) to a patch of the input, say y,  i.e., x = w^Ty+b. For my own activation function, besides the value of x (which I get automatically by a previous layer), I also need the norm of the filter, i.e., ||w||. Is there any way of getting this value from the previous layer before I apply an activation function?

**Comment by f0k** [comment]
> Is there any way of getting this value from the previous layer before I apply an activation function?

Sure, in your implementation of `get_output_for()`, you can just access `self.input_layer.W` if you want. Also see [`lasagne.utils.compute_norms`](http://lasagne.readthedocs.io/en/latest/modules/utils.html#lasagne.utils.compute_norms), this may be handy.

> Please let me know in advance if this is ok. It's not my intention to spam the repo, neither to bother you.

Actually, usage questions should better be posted at our mailing list: https://groups.google.com/d/forum/lasagne-users
Let's continue there if you have any more questions!

**Comment by c0tzelepis** [comment]
@f0k thank you very much once again. Your help is really much appreciated! I will follow your advises so far and I will continue in the list if I have any trouble (well, I will certainly join the list very soon). 
Cheers :)

**Comment by c0tzelepis** [comment]
@f0k thank you very much once again. Your help is really much appreciated! I will follow your advises so far and I will continue in the list if I have any trouble (well, I will certainly join the list very soon). 
Cheers :)

Edit: I already started a topic in the list; if you have some time, would be nice if you could take a look. Thanks a lot!
