### ISSUE TITLE
More flexible DenseLayer

### ISSUE THREAD

**Issue by f0k** [Lasagne/Lasagne#719]
A common use case for a dense layer is to stack it on top of a recurrent layer to compute a prediction at every time step. Since the recurrent layer output is of shape `(batchsize, seq_len, feats)`, this requires three layers: A `ReshapeLayer(..., (-1, feats))`, the `DenseLayer(..., num_units)`, and possibly another `ReshapeLayer(..., (batchsize, seq_len, num_units))`. The latter requires either the `batchsize` or `seq_len` to be known at compile time, or obtained as symbolic variables.

The operation inside the `DenseLayer` is quite simple: It consists of `T.flatten()` followed by `T.dot()`.
Now `T.dot(x, y)` already supports arbitrary dimensionality for `x`, performing the dot product over the last axis only. The only reason we cannot directly use it on the output of a recurrent layer is that it flattens the input to be a matrix, in this case of shape `(batchsize, seq_len * feats)`.

We could make the `DenseLayer` much more flexible simply by allowing to specify the number of axes to be flattened (or to be kept). I propose to add a keyword argument with the following semantics:
* If it's a positive integer, this gives the number of axes not to be flattened. E.g., setting it to `1` (the default) means to keep the first axis and flatten the remaining ones. Put differently, it gives the index of the axis all following ones are to be collapsed under.
* If it's a negative integer, it also gives the index of the axis all following ones are to be collapsed under, counted from the end as is customary in Python for negative indices. E.g., setting it to `-2` means to flatten the last two axes, and `-1` means to only flatten the last axis, which does nothing.
* If it's zero, we throw an error because we think this is never intended and based on a misunderstanding? Otherwise, this would flatten all the input into a single vector, losing the batch dimension on the way.

I'm not too sure about the name of the keyword argument, though. It could be `keep_axes`, or `distribute_over` (as the dot product is distributed over the given number of axes).

Alternatively, we could also have a full-blown `shared_axes` argument listing the axes to distribute the dot product over, but this would involve moving all the others to the end before the dot product and restoring the order afterwards (e.g., a `(3,4,5,6)` tensor with `shared_axes=(0,-1)` would have a `(20,num_units)` weight matrix and produce a `(3,num_units,6)` output) -- maybe that's too much flexibility.

**Comment by benanne** [comment]
This could be a nice addition indeed. I also think `shared_axes` would be overkill -- that use case is better served by using `ReshapeLayer`s and `DimshuffleLayer`s imo, or even custom `Layer` subclasses.

I think "the number of axes not to be flattened" is the wrong way to think about it, because everything gets flattened into a matrix, we're just influencing which of the original axes form part of the rows of this matrix, and which form part of the columns. This is very different from e.g. `FlattenLayer`'s `outdim` argument, which directly controls how many trailing axes get flattened (and the number of dimensions in the output depends on this, whereas in this case it would always be 2). So to avoid confusion we should probably choose the language carefully.

As for the name, I think I prefer something with `distribute`, or maybe something else altogether, but `keep_axes` is not clear enough.

**Comment by f0k** [comment]
> I think "the number of axes not to be flattened" is the wrong way to think about it, because everything gets flattened into a matrix

No, I'm actually suggesting to *not* flatten it into a matrix. With `keep_axes=2`, it would flatten a tensor of `(2,3,4,5)` into a tensor of `(2,3,20)`, and then `T.dot()` against a weight matrix of `(20,30)` would result in a `(2,3,30)` output. There's no need to turn it into a `(6,20)` matrix for that:
```
>>> import numpy as np
>>> import theano
>>> import theano.tensor as T
>>> a = T.dtensor3()
>>> b = T.dmatrix()
>>> T.dot(a, b).eval({a: np.random.randn(2,3,20), b: np.random.randn(20,30)}).shape
(2, 3, 30)
```
This would allow to stack a `DenseLayer(..., num_units=..., keep_axes=-1)` directly on top of a recurrent layer and get results in a `(batchsize, seq_len, num_units)` tensor. Incidentally, Keras has a separate layer class for this use case (the `TimeDistributedDense` class).

> This is very different from e.g. FlattenLayer's `outdim` argument, which directly controls how many trailing axes get flattened

I'd rather say the `outdim` argument does this *indirectly*. It *directly* gives the number of output dimensions. Anyway, thinking along this line, we could also give the `DenseLayer` an argument telling how many trailing axes to involve in the dot product. Then, semantics would be as follows:
* Positive integer: Give the number of trailing axes to collapse.
* Negative integer: Give the (negated) number of leading axes to keep.
* Zero: Either error out or collapse input to a vector.

The default would be `-1`. Semantics would be exactly inverse to what I proposed before, but maybe this would make naming easier?

> As for the name, I think I prefer something with `distribute`, or maybe something else altogether, but `keep_axes` is not clear enough.

Hooray, a name discussion! :)

**Comment by benanne** [comment]
Alright, I guess I misunderstood. I'm not sure which of these two options for the argument semantics makes the most sense, I'll have to think about it.

**Comment by f0k** [comment]
> I'll have to think about it.

Me too, otherwise I'd have proposed a convincing name right away! :) I think it doesn't really matter which of these two options we choose, as they allow exactly the same use cases with exactly the same effort. It's just a question of what gives us a better name for the keyword argument.

**Comment by f0k** [comment]
Maybe:
```
over_axes: int
    Number of leading axes to distribute the dot product over.
    These axes will be kept in the output tensor, remaining axes
    will be collapsed and multiplied against the weight matrix.
    A negative number gives the (negated) number of trailing
    axes to involve in the dot product.
```
If we ever wanted to, this would be extensible to allow an iterable, although it would be a bit confusing that `3` would not be identical to `(3,)` but to `(0,1,2)` then.
