### ISSUE TITLE
 ConcatLayer causes mismatch error for different last dimension  

### ISSUE THREAD

**Issue by MorLong** [Lasagne/Lasagne#723]
```
a =  InputLayer(shape=(2,3))

b =  InputLayer(shape=(2,4))

c =  InputLayer(shape=(2,3)) 

```

 ConcatLayer causes mismatch error for different last dimension  :
`lasagne.layers.ConcatLayer ([a,b],axis= -1).output_shape ->  :
`
"ValueError: Mismatch: input shapes must be the same except in the concatenation axis"

it is ok for same last dimensions:
`lasagne.layers.ConcatLayer ([a,c],axis= -1).output_shape  ->:  (2, 6 )
`

the discussion could be found on[ mailing list ](https://groups.google.com/d/msg/lasagne-users/zAJMj8aJP6o/Y1ZCTivgBAAJ)

**Comment by benanne** [comment]
Thanks for the report :)
