### ISSUE TITLE
Error in LSTMLayer comment

### ISSUE THREAD

**Issue by erfannoury** [Lasagne/Lasagne#724]
Hello everyone!

I was reading through the code for the LSTM layer (and trying to implement LN-LSTM) that I came across this line in the code comments [recurrent.py#L990](https://github.com/Lasagne/Lasagne/blob/master/lasagne/layers/recurrent.py#L990).
Shouldn't at each call to scan, `input_n` be of size `(n_batch, 4*num_units)`. I know it is a minor issue, but just for the sake of correctness.

**Comment by f0k** [comment]
Yes, you're right. Also it shouldn't be "each call to scan", but "each call to step". (Probably "each call" is a bit misleading, too, I guess it will only be called once to build the graph for the loop.)

Do you want to send a PR? Can you check if the GRULayer needs this as well?

**Comment by erfannoury** [comment]
Yeah, for sure. I'll check and then send a PR.
