### ISSUE TITLE
Citing

### ISSUE THREAD

**Issue by craffel** [Lasagne/Lasagne#73]
[Github repos can have DOIs](https://guides.github.com/activities/citable-code/) but only after a release has been made.  We should do this once we have a release because we want people to cite this.

**Comment by craffel** [comment]
My first paper which uses `lasagne` was accepted, so I'd love to have a DOI before the camera-ready version is due.

**Comment by f0k** [comment]
From my crystal ball, this would be July 17th?

**Comment by craffel** [comment]
[Indeed](https://github.com/craffel/midi-dataset-ismir)... will I be seeing you there this year?

**Comment by moscow25** [comment]
Congrats! Hopefully, first of many to come...

**Comment by f0k** [comment]
Congratulations, and yes! We also have papers that could cite Lasagne if we finish the release in time.

**Comment by benanne** [comment]
There really isn't that much left to do. Unfortunately I'm not able to coordinate the remaining work at the moment, so I'm sort of hoping it'll just get done :p

**Comment by f0k** [comment]
I guess I'll be able to cover that, I'm just busy with another project at least for this week.

**Comment by craffel** [comment]
Bump.

**Comment by f0k** [comment]
> Bump.

You're welcome to help :) I've still got to work on my paper, but we can try to get Lasagne released on Friday. There are a few outstanding issues, though (such as #311 which will change the API). On the other hand, if we don't release it on time, can't we still cite it just by name and URL?

**Comment by craffel** [comment]
> You're welcome to help :)

I'd be happy to, although I don't feel super qualified to comment on the conv part of the library, and I don't have much to add to naming/API conventions at this point.

> On the other hand, if we don't release it on time, can't we still cite it just by name and URL?

Sort of, but then citations will get split across citing the URL and citing the release/DOI when it's available.  When there's no release/DOI available for code, I usually just put a footnote (what I'm currently doing for lasagne).

**Comment by f0k** [comment]
> I've still got to work on my paper, but we can try to get Lasagne released on Friday.

Sorry, that turns out to be impossible. I was occupied with running some additional experiments and will be occupied with writing for some time. On the positive side, we can schedule to include #294 for the first release now. Let's still aim to release 0.1 in July!

**Comment by dimatura** [comment]
Unfortunately I don't have the bandwidth/codebase familiarity to help with the release, but I still have a week left for my camera ready!

**Comment by f0k** [comment]
> I still have a week left for my camera ready!

July 28th?

**Comment by ebenolson** [comment]
Is there an up-to-date list of what needs to be done somewhere?

If it's not possible by then, maybe a 0.0.9pre release just to get a DOI?

**Comment by benanne** [comment]
I'd be okay with that. We can't keep postponing this indefinitely, we're starting to miss out on rather a lot of citations :p

**Comment by f0k** [comment]
Just remembered an email from yesterday... another camera-ready deadline has been moved to July 28th (probably the one that also interests @craffel?). Who's in for releasing it on Sunday?

**Comment by craffel** [comment]
Haha we could try.  I think I used up the space I had reserved for a lasagne cite in my paper though.

**Comment by benanne** [comment]
`\baselinestretch` to the rescue :D

**Comment by dimatura** [comment]
Hi it's actually July 30, so different conference ;)

**Comment by f0k** [comment]
I'm occupied until the evening... will be tough to finish the release today, but July 28 could still be doable.

**Comment by MartinThoma** [comment]
I guess this is how Lasagne should be cited:

```tex
@misc{sander_dieleman_2015_27878,
  author       = {Sander Dieleman and
                  Jan Schlüter and
                  Colin Raffel and
                  Eben Olson and
                  Søren Kaae Sønderby and
                  Daniel Nouri and
                  Daniel Maturana and
                  Martin Thoma and
                  Eric Battenberg and
                  Jack Kelly and
                  Jeffrey De Fauw and
                  Michael Heilman and
                  diogo149 and
                  Brian McFee and
                  Hendrik Weideman and
                  takacsg84 and
                  peterderivaz and
                  Jon and
                  instagibbs and
                  Dr. Kashif Rasul and
                  CongLiu and
                  Britefury and
                  Jonas Degrave},
  title        = {Lasagne: First release.},
  month        = aug,
  year         = 2015,
  doi          = {10.5281/zenodo.27878},
  url          = {http://dx.doi.org/10.5281/zenodo.27878}
}
```

See https://zenodo.org/record/27878/export/hx#.VfmAv3U4bK4

**Comment by f0k** [comment]
> I guess this is how Lasagne should be cited:

Yes, although you may either want to shorten the author list with an `et al.` somewhere or replace the unresolved user names by the corresponding real names listed in the [release description](https://github.com/Lasagne/Lasagne/releases/tag/v0.1). It's a bit unfortunate that we can't influence this (those users would need to reveal their real names directly to github, I guess).

> This should probably be included in the docs.

It's the DOI button on top of the README, but yes, not everybody will know to look for that. We should give that explicitly, both in the README and on the documentation front page (we wanted to change that one anyway).

**Comment by craffel** [comment]
> It's the DOI button on top of the README, but yes, not everybody will know to look for that. We should give that explicitly, both in the README and on the documentation front page (we wanted to change that one anyway).

Bumping this, I it would be great to be more up-front about how to cite Lasagne now that more people are using Lasagne in research papers.  People are citing Laagne in various ways, like [this](https://scholar.google.com/scholar?q=%22github.com%2Flasagne%2Flasagne%22&btnG=&hl=en&as_sdt=0%2C34) or [this](https://scholar.google.com/scholar?q=%22lasagne%3A+first+release%22&btnG=&hl=en&as_sdt=0%2C34) which accounts for about 56 papers, and Google has only attributed 7 of those to the [non-corrupt record for our Zenodo DOI](https://scholar.google.com/scholar?cites=17500558986719745348&as_sdt=5,34&sciodt=0,34&hl=en).

(Sorry to pop up out of nowhere to bump this, I just noticed it a minute ago on Google Scholar.  Going back to writing my thesis now.  See you next month :) )

**Comment by luster** [comment]
Bump. Finishing my Master's thesis in audio denoising, would also like to cite in the paper

**Comment by f0k** [comment]
> would also like to cite in the paper

I use this one (as provided by Zenodo, but replacing the unresolved github user names):
```
@misc{lasagne,
  author       = {Sander Dieleman and
                  Jan Schlüter and
                  Colin Raffel and
                  Eben Olson and
                  Søren Kaae Sønderby and
                  Daniel Nouri and
                  Daniel Maturana and
                  Martin Thoma and
                  Eric Battenberg and
                  Jack Kelly and
                  Jeffrey De Fauw and
                  Michael Heilman and
                  Diogo Moitinho de Almeida and
                  Brian McFee and
                  Hendrik Weideman and
                  Gábor Takács and
                  Peter de Rivaz and
                  Jon Crall and
                  Gregory Sanders and
                  Kashif Rasul and
                  Cong Liu and
                  Geoffrey French and
                  Jonas Degrave},
  title        = {Lasagne: First release.},
  month        = aug,
  year         = 2015,
  doi          = {10.5281/zenodo.27878},
  url          = {http://dx.doi.org/10.5281/zenodo.27878}
}
```
If this is too long, you can replace any number of trailing authors with `others` (`... and ... and ... and others`) to make BibTeX render it as `et al.`.

We could add this `.bib` file directly to the repository or as part of the documentation, but then the next Zenodo release would include the old `.bib` file. Hmm. Doesn't work.

For Theano, citations can be found at: http://deeplearning.net/software/theano/citation.html

**Comment by f0k** [comment]
> Can you add the finalized citation to the github readme or the rtd?

Thanks for bumping this again! To work around the chicken-and-egg problem that a BibTeX entry directly in the README would never match the Zenodo ID of the release, I've put the BibTeX entry in the wiki so we can refer to it from the README (PR pending).
