### ISSUE TITLE
LSTM layer fails when number of units = 1

### ISSUE THREAD

**Issue by kroman93** [Lasagne/Lasagne#730]
Before submitting your issue, please check these hints!
- **If you have a usage question**, please please post on [our mailing list](https://groups.google.com/forum/#!forum/lasagne-users) instead of creating an issue.
  Make sure to check the [Lasagne documentation](http://lasagne.readthedocs.org/en/latest/) and the [Theano documentation](http://deeplearning.net/software/theano/) first!
  You can search the mailing list as well to see if your question has come up before.
- **If you suspect you have found a bug**, please first try [updating to the bleeding-edge versions of Theano and Lasagne](http://lasagne.readthedocs.io/en/latest/user/installation.html#bleeding-edge-version). It may have been fixed already.
  If you are not sure whether the problem lies within your code, Theano, or Lasagne, first post on [our mailing list](https://groups.google.com/forum/#!forum/lasagne-users).
  In any case, try to provide a minimal code example that reproduces the bug, this will greatly speed up the process of tracking down the problem.
- **If you have a feature request or idea**, please include a clear description of the use case(s) it would enable, referencing research papers if applicable, and indicate whether you would be willing to implement the feature yourself.
  We are happy to discuss your suggestion, help refining it, and decide upfront whether it would fit the main library or our [Lasagne/Recipes](https://github.com/Lasagne/Recipes).

**Comment by kroman93** [comment]
Comes up with this error: TypeError: Cannot convert Type TensorType(float32, 3D) (of Variable Subtensor{:int64:}.0) into Type TensorType(float32, (False, False, True)). You can try to manually convert Subtensor{:int64:}.0 into a TensorType(float32, (False, False, True)).

**Comment by f0k** [comment]
This seems to be a long-standing Theano bug. Can you please follow the hints (you weren't meant to re-post them) and provide a minimal working example, i.e., a short Python script that we can copy/paste and run to expose the error? I'll try to minimize it further to report it to the Theano developers then. Thank you!

**Comment by nouiz** [comment]
Do you have the full stack trace?

**Comment by f0k** [comment]
Just quickly tried to recreate it.
```python
import theano
import theano.tensor as T
import lasagne
x = T.tensor4('x')
network = lasagne.layers.InputLayer((10,20,30,40), input_var=x)
network = lasagne.layers.LSTMLayer(network, num_units=1)
theano.grad(None, wrt=x, known_grads={lasagne.layers.get_output(network): T.tensor4('y')})
```
Gives:
```
ValueError: ('You cannot drop a non-broadcastable dimension.', ((False, False, False, False), (1, 0, 2)))
```
The stack trace is very long. It ends with:
```
/raid/user/jan/install/Theano-git/theano/gradient.pyc in access_term_cache(node)
    963             inputs = node.inputs
    964 
--> 965             output_grads = [access_grad_cache(var) for var in node.outputs]
    966 
    967             # list of bools indicating if each output is connected to the cost

/raid/user/jan/install/Theano-git/theano/gradient.pyc in access_grad_cache(var)
   1269                     for idx in node_to_idx[node]:
   1270 
-> 1271                         term = access_term_cache(node)[idx]
   1272 
   1273                         if not isinstance(term, gof.Variable):

/raid/user/jan/install/Theano-git/theano/gradient.pyc in access_term_cache(node)
   1103                                 str(g_shape))
   1104 
-> 1105                 input_grads = node.op.grad(inputs, new_output_grads)
   1106 
   1107                 if input_grads is None:

/raid/user/jan/install/Theano-git/theano/tensor/elemwise.py in grad(self, inp, grads)
    421             return [inp[0].zeros_like(dtype=theano.config.floatX)]
    422         else:
--> 423             return [DimShuffle(gz.type.broadcastable, grad_order)(
    424                 Elemwise(scalar.identity)(gz))]
    425 

/raid/user/jan/install/Theano-git/theano/tensor/elemwise.py in __init__(self, input_broadcastable, new_order, inplace)
    175                     raise ValueError(
    176                         "You cannot drop a non-broadcastable dimension.",
--> 177                         (input_broadcastable, new_order))
    178 
    179         # this is the list of the original dimensions that we keep
```
Before there is a long chain of the first two calls shown above.

Part of the problem could be that `lasagne.layers.get_output(network).broadcastable` is `(False, False, False)`, although it should be `True` in the last dimension. Setting the gradient tensor to be broadcastable on axis 2 doesn't help anything.

If we add another layer on top, we get down do the reported problem:
```python
network = lasagne.layers.DenseLayer(network, num_units=1)
theano.grad(None, wrt=x, known_grads={lasagne.layers.get_output(network2): T.matrix('y')})
```
This gives:
```
TypeError: Cannot convert Type TensorType(float32, 3D) (of Variable Subtensor{:int64:}.0) into Type TensorType(float32, (False, False, True)). You can try to manually convert Subtensor{:int64:}.0 into a TensorType(float32, (False, False, True)).
```
With the traceback ending in:
```
/raid/user/jan/install/Theano-git/theano/gradient.pyc in access_term_cache(node)
   1103                                 str(g_shape))
   1104 
-> 1105                 input_grads = node.op.grad(inputs, new_output_grads)
   1106 
   1107                 if input_grads is None:

/raid/user/jan/install/Theano-git/theano/scan_module/scan_op.pyc in grad(self, inputs, dC_douts)
   2522 
   2523         local_op = Scan(inner_gfn_ins, inner_gfn_outs, info)
-> 2524         outputs = local_op(*outer_inputs)
   2525         if type(outputs) not in (list, tuple):
   2526             outputs = [outputs]

/raid/user/jan/install/Theano-git/theano/gof/op.py in __call__(self, *inputs, **kwargs)
    600         """
    601         return_list = kwargs.pop('return_list', False)
--> 602         node = self.make_node(*inputs, **kwargs)
    603 
    604         if config.compute_test_value != 'off':

/raid/user/jan/install/Theano-git/theano/scan_module/scan_op.pyc in make_node(self, *inputs)
    429         for inner_seq, outer_seq in zip(self.inner_seqs(self.inputs),
    430                                         self.outer_seqs(inputs)):
--> 431             new_inputs.append(format(outer_seq, as_var=inner_seq))
    432 
    433         argoffset += len(self.outer_seqs(inputs))

/raid/user/jan/install/Theano-git/theano/scan_module/scan_op.pyc in format(var, as_var)
    421                     broadcastable=(tuple(var.broadcastable[:1]) +
    422                                    tuple(as_var.broadcastable)))
--> 423                 rval = tmp.filter_variable(rval)
    424             return rval
    425 

/raid/user/jan/install/Theano-git/theano/tensor/type.pyc in filter_variable(self, other, allow_convert)
    232             dict(othertype=other.type,
    233                  other=other,
--> 234                  self=self))
    235 
    236     def value_validity_msg(self, a):
```
This time, the network output has the correct broadcast pattern of `(False, True)`. But again, it doesn't change anything if I use `T.addbroadcast(T.matrix('y'), 1)` for the output gradient.

**Comment by githubnemo** [comment]
Is there any news on this? Is this fixed? I could not find a corresponding issue on the Theano issue tracker.

**Comment by f0k** [comment]
> Is there any news on this? Is this fixed?

It doesn't seem so. The following still triggers the error for me:
```python
import theano
import theano.tensor as T
import lasagne
x = T.tensor3('x')
network = lasagne.layers.InputLayer((10,20,30), input_var=x)
network = lasagne.layers.LSTMLayer(network, num_units=1)
network = lasagne.layers.DenseLayer(network, num_units=1)
theano.grad(None, wrt=x, known_grads={lasagne.layers.get_output(network): T.matrix('y')})
```

> I could not find a corresponding issue on the Theano issue tracker.

Right. Let's file one: https://github.com/Theano/Theano/issues/5224
(If you want to help, you can try reducing this to a Theano-only example, to make it a little easier for the Theano developers.)

**Comment by nouiz** [comment]
We are working on this. The problem is that the optimization
local_greedy_distributor don't apply when the broadcast pattern isn't
(False, False). Not sure exactly why yet, someone is still working on this.

**Comment by nouiz** [comment]
Sorry, I mixed the issue. My previous comment was for  gh-765, not this one.

**Comment by f0k** [comment]
> Sorry, I mixed the issue.

I noticed that :) Good to hear you're making progress on that other issue!
