### ISSUE TITLE
squared_error: Warn if comparing column vector against row vector

### ISSUE THREAD

**Issue by f0k** [Lasagne/Lasagne#755]
At least one user got trapped by setting target_var to a vector for a regression task, and then passing it to lasagne.objectives.squared_error along with the network predictions for a network of a single output unit: https://groups.google.com/forum/#!topic/lasagne-users/DsSY1cHCC2M

Due to #715, Theano knows that the network predictions are a column vector (a matrix with broadcast pattern (False, True)), so it will happily broadcast the network predictions and the targets into a square matrix of (batchsize, batchsize) and compute the squared differences between every prediction and every target (as opposed to computing the squared differences between corresponding predictions and targets only). The mean of the loss is still a scalar, so training will appear to work, but not learn anything.

We should catch this case and warn the user to use a column vector for the squared error targets.

**Comment by f0k** [comment]
> We should catch this case and warn the user to use a column vector for the squared error targets.

Maybe it's even better to just support this case, and turn a 1D target vector into a column vector if needed. This closes the trap and also circumvents the log sigmoid stabilization not being applied for binary classification (if we encourage users to use a target vector for single outputs). PR in #770.

**Comment by jingriver** [comment]
2016年11月20日星期日，Jan Schlüter <notifications@github.com> 写道：
