### ISSUE TITLE
dropout layer failed to prevent upcasting

### ISSUE THREAD

**Issue by guoxuesong** [Lasagne/Lasagne#757]
in layers/noise.py:

> # Using theano constant to prevent upcasting
> one = T.constant(1) 
> retain_prob = one - self.p

Actually, 'one' beomes a int16 and 'retain_prob' becomes float32 even if self.p is a float16 .
It should be like this:

> one = T.constant(1.0) 

Same is in updates.py

It's time to consider supporting float16 now.

**Comment by f0k** [comment]
Good spot! There were no tests for float16, but yes, it would be good to take care of that. Do you want to file a PR including tests for float16? For guidance, please see http://lasagne.readthedocs.io/en/latest/user/development.html#how-to-contribute. If you don't have the time, let us know and we'll take care of it ourselves.

**Comment by guoxuesong** [comment]
Looks not as easy as document said.
$ py.test
usage: py.test [options] [file_or_dir] [file_or_dir] [...]
py.test: error: unrecognized arguments: --cov=lasagne --cov-report=term-missing --pep8
  inifile: /home/work/Lasagne/setup.cfg
  rootdir: /home/work/Lasagne

**Comment by f0k** [comment]
> Looks not as easy as document said.

Did you follow this part?
> To be able to run the tests and build the documentation locally, install additional requirements with: pip install -r requirements-dev.txt (adding --user if you want to install to your home directory instead).

> If you use the bleeding-edge version of Theano, then instead of running that command, just use pip install to manually install all dependencies listed in requirements-dev.txt with their correct versions; otherwise it will attempt to downgrade Theano to the known good version in requirements.txt.

Specifically, [`requirements-dev.txt`](https://github.com/Lasagne/Lasagne/blob/master/requirements-dev.txt) includes pytest-cov and pytest-pep8. Let me know if you need further advice.

**Comment by nouiz** [comment]
I think this is better. In case self.p is an int at some point. But in
practice, the proposed change will probably work.

one = T.constant(1.0, dtype=self.p.dtype)

**Comment by f0k** [comment]
> one = T.constant(1.0, dtype=self.p.dtype)

This doesn't work because `self.p` can be a Python float. We could use `input.dtype`, though.

However, this has been resolved upstream in Theano by using int8 instead of int16:
```
>>> T.constant(1).dtype
'int8'
>>> (T.scalar('x', dtype='float16') - T.constant(1)).dtype
'float16'
```
We'd just need to update the requirements.txt accordingly. This change was in Theano/Theano@1661f0bc (Oct 12). Or, if we want to stay compatible with Theano on PyPI, we can explicitly specify `dtype='int8'` ourselves.

**Comment by guoxuesong** [comment]
> a PR including tests for float16
sorry, have no time to work at this

**Comment by Sentient07** [comment]
I presume that we have to explicitly specify the `dtype` wherever possible. I will make the necessary changes to the `Dropout`.

**Comment by Sentient07** [comment]
I tried to recreate the problem, but realised it might be something to do with the flags? I tried to recreate the problem reported using THEANO_FLAGS `floatX=float32` and `floatX=float16`. In both the cases the output seems to be what the `floatX` flag value is. Which to me seems to be the desired output. I verified this with pdb at different steps and `retain_prob` is same as `floatX` value.

<img width="750" alt="screenshot at jul 30 16-12-04" src="https://user-images.githubusercontent.com/6195312/28752627-de232250-7541-11e7-974d-19e87dd43ee1.png">

**Comment by guoxuesong** [comment]
@Sentient07 looks like theano did something, one.eval().dtype is int8 now. It had been int16, when I open this issue.

**Comment by Sentient07** [comment]
Since `Theano` made a release post @f0k 's last comment, I think the PyPi would have been updated and we don't need to change the code. A test might be needed still? Not sure, as there are no / less chances that constants would be `int16` anymore

**Comment by f0k** [comment]
> looks like theano did something, one.eval().dtype is int8 now.

Yes, I mentioned this: https://github.com/Lasagne/Lasagne/issues/757#issuecomment-261808904

> Since Theano made a release

It's not in Theano 0.8.2, though, the plan was to have 0.2 compatible to 0.8.2. I'd still suggest to explicitly add dtype `int8` to all `one = T.constant(1)` in the code.

> A test might be needed still?

Yes, to be sure it doesn't break in future.
