### ISSUE TITLE
squared_error return float32 for float16

### ISSUE THREAD

**Issue by guoxuesong** [Lasagne/Lasagne#758]
in lasagne/objectives.py

> return (a - b)**2

I would like change it to:

> return (a - b)**theano.tensor.constant(2.0)

**Comment by f0k** [comment]
The only advantage of `**2` was that it works with numpy arrays, but that's not documented or used anywhere. Can you change it to `T.square(a - b)`? This way we get a slightly smaller graph. On compilation, `**2` is optimized to `square` anyway.

**Comment by guoxuesong** [comment]
> add a test for float16 staying float16
sorry, have no time to work on this.
