### ISSUE TITLE
Convert InputLayer input_shape to tuple if needed

### ISSUE THREAD

**Issue by f0k** [Lasagne/Lasagne#763]
At least one user got trapped when passing a shape list instead of a shape tuple to the `InputLayer` constructor: https://github.com/Lasagne/Lasagne/commit/bc963cd12b2b7b51d81225c50077521d40aee75c#commitcomment-19594546
Many `get_output_shape_for()` implementations do not rely on the shape being a tuple, but if they do, it is hard to understand where the problem originated.
We should probably just unconditionally convert the shape to a tuple in the `InputLayer` constructor.

**Comment by benanne** [comment]
Good call. I think this type of error might become more common now that TensorFlow is encouraging everyone to specify shapes as lists instead...
