### ISSUE TITLE
sklearn.base.clone causes the network to print twice during training

### ISSUE THREAD

**Issue by ibeckermayer** [Lasagne/Lasagne#764]
I am using Daniel's facial key-point recognition tutorial as a template for a personal project, and I'm just at the point of training my model but am running into a puzzling error. As in the [tutorial](https://github.com/dnouri/kfkd-tutorial/blob/master/kfkd.py#L407), I am training multiple specialist models using a for loop:

``` python
def fit_specialists(fname_pretrain = None):
    # Fit specialist models running on the GPU
    a = 1
    for setting in SPECIALIST_SETTINGS:
        # Load the appropriate specialist data
        cols = setting['columns']
        flip_indices = setting['flip_indices']
        X,y = load2d(cols=cols,flip_inds=flip_indices)

        # Create the model
        model = clone(net)
        model.output_num_units = y.shape[1]
        model.max_epochs = 1 # !!! int(4e6 / y.shape[0])
        if 'kwargs' in setting:
            # an option 'kwargs' in the settings list may be used to
            # set any other parameter of the net:
            vars(model).update(setting['kwargs'])

        if 'fname_pretrain' in setting:
            fname_pretrain = setting['fname_pretrain']

        if fname_pretrain is not None:
            model.load_params_from(fname_pretrain)

        print("Training model for columns {} for {} epochs".format(
            cols, model.max_epochs))
        print "model.fit about to start"
        model.fit(X, y)
        print "model.fit stopped"
        train_loss = np.array([i["train_loss"] for i in simple_net.train_history_])
        valid_loss = np.array([i["valid_loss"] for i in simple_net.train_history_])
        plt.plot(train_loss, linewidth=3, label="train")
        plt.plot(valid_loss, linewidth=3, label="valid")
        plt.grid()
        plt.legend()
        tit = "Model " + num2str(a) + " Loss"
        plt.title(tit)
        plt.xlabel("epoch")
        plt.ylabel("loss")
        plt.yscale("log")
        chart_name = "Model" + num2str(a) + "Loss.png"
        plt.savefig(chart_name)
        name = str(a)+'_params.pkl'
        model.save_params_to(name)
        a = a+1
```

My network is defined as follows:

``` python
net = NeuralNet(
    layers=[
        ('input', layers.InputLayer),
        ('conv1', Conv2DLayer),
        ('pool1', MaxPool2DLayer),
        ('dropout1', layers.DropoutLayer),
        ('conv2', Conv2DLayer),
        ('pool2', MaxPool2DLayer),
        ('dropout2', layers.DropoutLayer),
        ('conv3', Conv2DLayer),
        ('pool3', MaxPool2DLayer),
        ('dropout3', layers.DropoutLayer),
        ('hidden4', layers.DenseLayer),
        ('dropout4', layers.DropoutLayer),
        ('hidden5', layers.DenseLayer),
        ('output', layers.DenseLayer),
        ],
    input_shape=(None, 1, 288, 288),
    conv1_num_filters=32, conv1_filter_size=(3, 3), pool1_pool_size=(2, 2),
    dropout1_p=0.1,
    conv2_num_filters=64, conv2_filter_size=(2, 2), pool2_pool_size=(2, 2),
    dropout2_p=0.2,
    conv3_num_filters=128, conv3_filter_size=(2, 2), pool3_pool_size=(2, 2),
    dropout3_p=0.3,
    hidden4_num_units=1000,
    dropout4_p=0.5,
    hidden5_num_units=1000,
    output_num_units=30, output_nonlinearity=None,

    update_learning_rate=theano.shared(float32(0.03)),
    update_momentum=theano.shared(float32(0.9)),

    regression=True,
    on_epoch_finished=[
    AdjustVariable('update_learning_rate', start=0.03, stop=0.0001),
    AdjustVariable('update_momentum', start=0.9, stop=0.999),
    EarlyStopping(patience=200),
    ],
    max_epochs=3000,
    verbose=1,
    )
```

The problem is specifically due to the part where I use sklearn.base.clone to clone a pre defined network architecture. Ever since I've implemented this, with verbosity set to one, my console prints the following when running:

``` terminal
# Neural Network with 157849478 learnable parameters

## Layer information

  #  name      size
---  --------  ----------
  0  input     1x288x288
  1  conv1     32x286x286
  2  pool1     32x143x143
  3  dropout1  32x143x143
  4  conv2     64x142x142
  5  pool2     64x71x71
  6  dropout2  64x71x71
  7  conv3     128x70x70
  8  pool3     128x35x35
  9  dropout3  128x35x35
 10  hidden4   1000
 11  dropout4  1000
 12  hidden5   1000
 13  output    6

# Neural Network with 157849478 learnable parameters

## Layer information

  #  name      size
---  --------  ----------
  0  input     1x288x288
  1  conv1     32x286x286
  2  pool1     32x143x143
  3  dropout1  32x143x143
  4  conv2     64x142x142
  5  pool2     64x71x71
  6  dropout2  64x71x71
  7  conv3     128x70x70
  8  pool3     128x35x35
  9  dropout3  128x35x35
 10  hidden4   1000
 11  dropout4  1000
 12  hidden5   1000
 13  output    6
```

No, that's not a mistake, the model prints out twice. Additionally, the epoch table is printed twice in a similar manner. Interestingly, its not printing the pre defined net, and the new net, since the output for both are 6 (meaning they both have been updated by the fit_specialists() function). Additionally, I've found that if I define the net with 

``` python
net = NeuralNet(
...
verbose = 0
...)
```

and try to update it on the cloned net

``` python
...
model = clone(net)
model.verbose = 1
...
```

nothing prints out.

If this is just a strange bug with the printing, that would be interesting to fix for aesthetics but ultimately doesn't matter to me. What I'm interested in is whether this is training 2 models simultaneously, since I'll be training using AWS and double training would cost me quite a bit of money.

**Comment by ibeckermayer** [comment]
I've experimented further, and found an additional problem. Although I'm still not 100% as to whether I am training 2 networks at once, I made the network much smaller so I could run tests on my CPU, and found that the training times are roughly similar when training 
```python
model = clone(net)
model.fit(X,y)
```
vs
```python
net.fit(X,y)
```
suggesting that I'm only training one net.

The only real difference is the strange tendency to double print everything when training the cloned net. Still interested to hear if this is a known bug with printing, or if I should somehow clone the network in a different manner.

**Comment by f0k** [comment]
> or if I should somehow clone the network in a different manner.

Possibly yes. If Daniel suggests to use `sklearn.base.clone`, he may have written the `NeuralNet` class to be compatible with this, but I don't know. You may try to use `copy.deepcopy`, or just rebuild the model instead of cloning it (if you put your model creation into a function like `build_model()`, it's easy to just call it multiple times to get multiple models).

**Comment by ibeckermayer** [comment]
Ok, thanks for the suggestions

**Comment by f0k** [comment]
Closing. Let's use [your mailing list post](https://groups.google.com/forum/#!topic/lasagne-users/JltG-abNTVQ) for further discussions, as it's not a Lasagne issue, but a usage question (for a third-party library even).
