### ISSUE TITLE
Warning/error for invalid/unused input dictionary keys in get_output()

### ISSUE THREAD

**Issue by f0k** [Lasagne/Lasagne#773]
At least two users [got](https://groups.google.com/forum/#!topic/lasagne-users/txSQ33FYwLc) [trapped](https://groups.google.com/d/msg/lasagne-users/xJO1NQGyUW4/rgkTIvc1BwAJ) when using `lasagne.layers.get_output` with an `inputs` dictionary that had Theano variables or strings as keys instead of Layer instances. We may want to throw an error for keys that are not Layer instances, or warn about unused keys (the former is much simpler).

**Comment by benanne** [comment]
The former is a good idea, yes. The latter could get rather complicated, I think, and I'm not sure if it should be solved at this level.

This design pattern of using dictionary inputs (and keyword arguments, e.g. `dropout` and `trainable`) gives us a lot of flexibility, but it also results in silent errors in some cases. This seems to be a problem with Python more generally though, not just with Lasagne. I don't think we can revert this choice as Lasagne relies on it quite heavily, but it would be nice if there was a clean solution for some of these issues that doesn't make the code a lot more complicated, and applies to all the situations where we've used this (layer kwargs, parameter tags, input dicts, ...).

**Comment by ReyhaneAskari** [comment]
I will be working on this issue next week.
