### ISSUE TITLE
Speeding up training on images of different sizes

### ISSUE THREAD

**Issue by fusionlove** [Lasagne/Lasagne#780]
Hello,

I'm training on a natural scene dataset whose images are different sizes. I'm using several convolutional layers followed by a layers.dnn.SpatialPoolingDNNLayer to standardise the sizes before the fully-connected layers.

As far as I can see, this means I have to fit the network one image at a time, since storing images as a batch means they would all have to be the same size. Is this assumption correct?

Unfortunately, running batches this way slows down fitting by a factor of about 50 - which is not surprising, since we're running the images one by one.

Can you think of a way to speed this up - or is this issue better approached in Theano?

Thanks,
Fintan

**Comment by f0k** [comment]
> As far as I can see, this means I have to fit the network one image at a time, since storing images as a batch means they would all have to be the same size. Is this assumption correct?

Basically yes. It's the same problem you get when processing a batch of differently-sized temporal sequences with an RNN. A common solution in that case is to zero-pad the sequences to have the same size and ensure the zero-padded data does not participate in computing the loss.

> Can you think of a way to speed this up - or is this issue better approached in Theano?

One way would be propagating all images in parallel until they passed the pooling layer, then concatenating the data into a batch. However, this requires Theano to use different streams, which is only supported by the new backend. The code would probably look something like this:
```python
inputs = ...  # a list of input variables for your batch
network1 = ...  # the part up to and including the spatial pyramid pooling
network2 = ...  # the remaining part, connected to network1
intermediate = T.concatenate([lasagne.layers.get_output(network1, T.shape_padleft(inp, 1), deterministic=False) for inp in inputs], axis=0)  # not sure whether you'd need to do anything to ensure it uses different streams
final = lasagne.layers.get_output(network2, {network1: intermediate}, deterministic=False)
```

Alternatively, you can borrow the zero-padding technique from RNNs. You'd have to zero-pad everything to the same size, then crop the images before the pyramid pooling layer and pass them through pooling one by one (you may also be able to write a custom pyramid pooling layer that does this via `scan`). This would at least give you full parallelization of the convolutions, at the cost of some wasted computation on the padded data.

Hope this helps! In future, please post such requests on our mailing list instead: https://groups.google.com/forum/#!forum/lasagne-users
We'd like to reserve the issue tracker for bug reports and feature discussions. Thank you!
