### ISSUE TITLE
Does lasagne.layers.get_all_params() need some modification?

### ISSUE THREAD

**Issue by skrish13** [Lasagne/Lasagne#783]
Right now, lasage.layers.get_all_params() gives a list of all parameters of an individual or list of layers. It works great for almost all cases. But for example, if we work with a network like Faster RCNN or any type of network which basically has a shared convolutional layers initially and branch out (into two) to have multiple FCs (in this case) or any different network. 

So in this case, I only have one FCs in each branch, so I just do a get_all_params(fc1) + [fc2.W,fc.b] to get all the parameters. If the branched out networks are bigger, this obviously would be tougher

Edit 1 - I should have used layer.get_params() instead of writing it's parameters in a list. 

- One way to tackle is just use get_all_params() at all ends of branches (if i may call that) and just **keep unique elements** in the list. Although this seems logically correct, when I print the list of all params I just get W,b,W,b etc so leaving this up to users would be a bad idea? / info on **how to implement** this could be discussed in the thread.
- Other way is to create a new function which will **return params of only the layers between** the shared convs and the end fcs (branches), so basically a subtraction between the lists of fc2 and conv_last (letting this be the last conv layer). Instead of the user manually generating the list of all layers contained in that, what I was thinking was an **automatic** subtraction given two layers and their corresponding parameters **using this function** itself (Referring to the coding convention followed in [this](https://hastebin.com/sovikewiwi.py) manner, where a layer represents everything below it too)

Attached a screenshot to better explain what I've tried to say.

![screenshot from 2016-12-21 01 29 40](https://cloud.githubusercontent.com/assets/10350518/21365813/0af991e8-c71d-11e6-8eb4-4207c1deec2d.png)

**Comment by skrish13** [comment]
I just realized we can achieve the 2nd point mentioned in my issue quite easily. The 2nd point was to return the parameters of only the branches (layers between end of a branch and last shared layer). This can be done by using one of the get_all_layers() parameters, **treat_as_input**. 

So it'd be something like this,
```
def get_all_params(layer, unwrap_shared=True, treat_as_input=None, **tags):

    layers = get_all_layers(layer,treat_as_input)
    params = chain.from_iterable(l.get_params(unwrap_shared=unwrap_shared, **tags) for l in layers)
    return utils.unique(params)
```

Do you think it'll be useful if we do this? Can I make this change and add a PR? 
I'd love to have more discussion, @f0k , in general, on using Lasagne for networks similar to the one mentioned in the issue, as well as this fix.

**Comment by benanne** [comment]
I'm not sure if I fully understand, but it isn't this use case already covered by passing a list of output layers to `get_all_params()`? You can just do `get_all_params([fc1, fc2, net3])` and it should do the correct thing.

**Comment by skrish13** [comment]
Yes, I didn't realize that'd do it. Thanks a lot. (I kinda assumed the user has to manually eliminate the common parameters of shared layers).  Here's an example testing it, in case anyone needs it.

![screenshot - 122116 - 17 00 14](https://cloud.githubusercontent.com/assets/10350518/21387749/29f2a7c4-c79f-11e6-8757-2e118e3b9157.png)

**Comment by skrish13** [comment]
One last thing, don't you think adding the **treat_as_input** parameter to get_all_params() will be **useful**? (and also very simple to implement) As we can get parameters of certain layers **automatically**. 
Else, the user has to use get_all_layers() with the treat_as_input=[] and pass that list of layers to get_all_params()

**Comment by f0k** [comment]
> Else, the user has to use get_all_layers() with the treat_as_input=[] and pass that list of layers to get_all_params()

This will not do what you want -- get_all_params() will traverse the layer graph again. You'd need to collect the parameters yourself then (`list(itertools.chain.from_iterable(l.get_params(trainable=True) for l in layers))`).

I think adding `treat_as_input` to `get_all_params()` may complicate the API too much. Wouldn't we need to add it to `count_params()`, `get_all_param_values()` and `set_all_param_values()` then? As long as this doesn't become a very common use case, I think it's fine to leave parameter collection for custom layer lists up to the user.

What's your use case for `get_all_params(layers, treat_as_input=...)`?

**Comment by skrish13** [comment]
> I think adding treat_as_input to get_all_params() may complicate the API too much. Wouldn't we need to add it to count_params(), get_all_param_values() and set_all_param_values() then?

Yes, that is true indeed.

> What's your use case for get_all_params(layers, treat_as_input=...)?

Basically networks like the one which I've shown in the figure above, for example, Faster-RCNN. So let's assume that there are a set of layers between the last shared layer and the output layer of one of the branches.  So to get all the parameters only for that branch or any similar use-case in general. Hmm, I realize this is indeed not a common use case, so yes you're right to leave it up to the users.

> This will not do what you want -- get_all_params() will traverse the layer graph again

Oh okay, now I understand the difference between passing list of layers as input to get_all_params() and using train_as_input=[] inside instead.

Thanks a lot!
