### ISSUE TITLE
Adding Gradient Noise for improving training

### ISSUE THREAD

**Issue by tmanh** [Lasagne/Lasagne#790]
Hello!

Recently, a low-overhead technique and easy-to-implement of adding gradient noise while updating weights in network was proposed in [here](https://arxiv.org/pdf/1511.06807v1.pdf). It provided great results for improving training (even with poor initialization).

Unfortunately, I have not found it in Lasagne.

Waiting for your replies.

**Comment by rafaelvalle** [comment]
Below is an implementation of adding noise to the gradient based on Adding
Gradient Noise Improves Learning for Very Deep Networks. Adding gradient
noise can also improve curriculum learning!

Starter code is based on Jan Schlueter's code for Saiency Maps and Guided
Backpropagation
https://github.com/Lasagne/Recipes/blob/master/examples/Saliency Maps
and Guided
Backpropagation.ipynb

class ModifiedBackprop(object):
    def __init__(self, nonlinearity, epoch, prev_seq_err):
        self.nonlinearity = nonlinearity
        self.epoch = epoch
        self.prev_seq_err = prev_seq_err
        self.rnd_normal = None
        self.ops = {}  # memoizes an OpFromGraph instance per tensor type

    def __call__(self, x):
        # OpFromGraph is oblique to Theano optimizations, so we need to move
        # things to GPU ourselves if needed.
        if theano.sandbox.cuda.cuda_enabled:
            maybe_to_gpu = theano.sandbox.cuda.as_cuda_ndarray_variable
        else:
            maybe_to_gpu = lambda x: x
        # We move the input to GPU if needed.
        x = maybe_to_gpu(x)
        # We note the tensor type of the input variable to the nonlinearity
        # (mainly dimensionality and dtype); we need to create a fitting Op.
        tensor_type = x.type
        # If we did not create a suitable Op yet, this is the time to do so.
        if tensor_type not in self.ops:
            # For the graph, we create an input variable of the correct
type:
            inp = tensor_type()
            # We pass it through the nonlinearity (and move to GPU if
needed).
            outp = maybe_to_gpu(self.nonlinearity(inp))
            # Then we fix the forward expression...
            op = theano.OpFromGraph([inp], [outp])
            # ...and replace the gradient with our own (defined in a
subclass).
            op.grad = self.grad
            # Finally, we memoize the new Op
            self.ops[tensor_type] = op
        # And apply the memoized Op to the input we got.
        return self.ops[tensor_type](x)


class GuidedBackProp(ModifiedBackprop):
    def grad(self, inputs, out_grads):
        (inp, ) = inputs
        (grd, ) = out_grads
        dtype = inp.dtype
        if self.rnd_normal is None:
            srng = RandomStreams(seed=234)
            rnd_normal = srng.normal(T.shape(grd))
        prev_seq_err = 1.
        noise_param = T.sqrt(T.pow(1+self.epoch, -0.55) * prev_seq_err)
        noise_scale = 0.0
        noise = rnd_normal * noise_param * noise_scale
        return (grd.astype(dtype) + noise, )


epoch_shared = theano.shared(1)
prev_seq_err_shared = theano.shared(1)


Substitute your linearities with

    GuidedBackProp(lasagne.nonlinearities.sigmoid, epoch_shared,
prev_seq_err_shared)

HTH

**Comment by tmanh** [comment]
Thank you for quick reply, but there's seem no easy way to add gradient noise without reimplementation a new method for updating gradient.

**Comment by rafaelvalle** [comment]
I don't understand you: the method **grad** in the class **GuidedBackProp** is a new method for updating the gradient...

**Comment by f0k** [comment]
@rafaelvalle: Did you try to reproduce any of the experiments in the "Adding Gradient Noise" paper? Might serve as a nice Lasagne Recipe. Otherwise, thanks for posting the code here, it should be easy to find with a search engine.

**Comment by rafaelvalle** [comment]
It depends on how long it takes to train their network for MNIST: "it has 20 hidden layers, with each layer containing 50 hidden units. We use the ReLU activation function". I have one Titan X :-)
