### ISSUE TITLE
Borrowing updates.py

### ISSUE THREAD

**Issue by twiecki** [Lasagne/Lasagne#796]
Are you guys OK if we copy the excellent optimizer implementations you have in `updates.py` for `pymc3`? Licenses should be compatible (using Apache v2). Any special header you want us to include?

**Comment by f0k** [comment]
> Are you guys OK if we copy the excellent optimizer implementations you have in `updates.py` for `pymc3`?

Sure, just stick to the license: https://github.com/Lasagne/Lasagne/blob/master/LICENSE

> Any special header you want us to include?

Just the license itself. Note that it says "The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.", and I'd consider that a substantial portion. You can add a comment at the beginning of the file saying where you got this from, and that it's governed by the following license, which you'd include afterwards. An additional note on the origin in the module docstring would be good as well, without all the license text.

**Comment by twiecki** [comment]
Thanks!

https://github.com/pymc-devs/pymc3/blob/eceec902dec6a3076f59f6b7cb8cc47e72a8ff9c/pymc3/variational/updates.py
