### ISSUE TITLE
-- Lasagne / Theano crash on new custom layer

### ISSUE THREAD

**Issue by jc-Rosichini** [Lasagne/Lasagne#798]
Hi,

I'm experiencing a crash when using a simple lasagne custom layer as defined below.

**(1) my config:**
Windows 10
Python Anaconda 3.5
Theano 0.9.0beta1dev
Lasagne 0.2dev1

**(2) the custom layer code**
```python
class FoldpixelLayer_div2_pack(Layer):
    def __init__(self, incoming, W=init.Normal(0.25), **kwargs):
        super(FoldpixelLayer_div2_pack, self).__init__(incoming, **kwargs)
        self.num_inputs = self.input_shape[1]
        self.W = self.add_param(W, (self.num_inputs, 4), name='W')
    
    def get_output_shape_for(self, input_shape):
        kin = input_shape[1]        # nb input  features planes
        self.kout= kin              # nb output features planes
        return (input_shape[0], self.kout, int(input_shape[2]/2), int(input_shape[3]/2))

    def get_output_for(self, input, deterministic=False, **kwargs):
        out = T.zeros((input.shape[0], self.output_shape[1], self.output_shape[2], self.output_shape[3]), dtype=T.config.floatX)
        for quad in range (self.num_inputs):
            p1 = input[:,quad,0::2,0::2] * self.W[quad,0]
            p2 = input[:,quad,0::2,1::2] * self.W[quad,1]
            p3 = input[:,quad,1::2,0::2] * self.W[quad,2]
            p4 = input[:,quad,1::2,1::2] * self.W[quad,3]
            ps=  p1 + p2 + p3 + p4
            out = T.set_subtensor(out[:,quad,:,:], ps)
        return out      
 ```

**(3) symptoms:**
The code compiles ok both in cpu and/or gpu modes
Then it crashes python at execution with no further warnings... :(

I'm surely missing something!
Thanks for your help

**Comment by f0k** [comment]
> Then it crashes python at execution with no further warnings... :(

This should never happen. Can you post a minimal script using your layer that crashes Python? I.e., something that has the necessary imports, instantiates the layer, creates a Theano expression, compiles a function and feeds some test data, so we can just download and run it? Thank you!

**Comment by jc-Rosichini** [comment]
Will do asap!

**Comment by jc-Rosichini** [comment]
Here is a 7zip file with toytest: https://we.tl/ZPNB9bfkxA
[toytest.zip](https://github.com/Lasagne/Lasagne/files/775265/toytest.zip)

Apparently :

(1) using toytest.py the bug doesn't reiterate when compiled using gpu mode BUT another issue raises with the new cuda0 (libgpuarray) mode
Is that a Theano compile bug?

(2) the initial bug (ie python crashing without additional notice) is still manifesting on my complete code when the custom layer module is added to the network

**Comment by ebenolson** [comment]
This ran ok for me on cpu and cuda0. 

I notice you're using windows though, are you sure you've installed theano and libgpuarray properly? I think  it can be tricky getting the compilers set up right..

**Comment by jc-Rosichini** [comment]
Thanks Eben,
You may be right, I'll go again in the process of compiling libgpuarray (although all the related tests and pygpu are ok) and try once more.

**Comment by nouiz** [comment]
We should do the RC tomorrow. Then someone from continuum will do new conda
package of Theano. Using those will be strongly suggested.

**Comment by jc-Rosichini** [comment]
Hi,
I think I got a semi explanation

**Symptoms:**
(1) Some config lead to a never ending compilation/optimization phase (the same happens using old and new backend)
(2) In some cases this even materializes with a python crash

**Toy bugcode:**
see toytest.py file
[toytest.txt](https://github.com/Lasagne/Lasagne/files/785063/toytest.txt)


**Tentative explanation:**

(1) When the compile phase never ends, from time to time a message pops up such as :
____Lasagne_bug>python toytest.py
_......
Using gpu device 0: GeForce GTX 980M (CNMeM is enabled with initial size: 81.5% of memory, cuDNN 5105)
ERROR (theano.gof.opt): EquilibriumOptimizer max'ed out by 'cut_gpua_constant_transfers'. You can safely raise the current threshold of 8.000000 with the theano flag 'optdb.max_use_ratio'.
ERROR (theano.gof.opt): EquilibriumOptimizer max'ed out by 'cut_gpua_constant_transfers'. You can safely raise the current threshold of 8.000000 with the theano flag 'optdb.max_use_ratio'._
....._
I think that this is related to creating a large amount of theano compute nodes, due to the 'for loop' in:
`
def get_output_for(self, input, deterministic=False, **kwargs):
      out = T.zeros((input.shape[0], self.output_shape[1], self.output_shape[2], self.output_shape[3]), dtype=T.config.floatX)

      for quad in range (self.num_inputs):
            p1 = input[:,quad,0::2,0::2] * self.W[quad,0]
            p2 = input[:,quad,0::2,1::2] * self.W[quad,1]
            p3 = input[:,quad,1::2,0::2] * self.W[quad,2]
            p4 = input[:,quad,1::2,1::2] * self.W[quad,3]
            ps=  p1 + p2 + p3 + p4
           out = T.set_subtensor(out[:,quad,:,:], ps)
       return out`
ie the more features planes as inputs the worse it is!

(2) In some cases if the module is included in a larger (non toy) networks, python merely crashes with no further indication....

**Remedy:**
- I have no clue of how to prevent the crash...
- Is there a smart way to avoid the 'for loop' (use of theano scan, vectorization, ...) that can be recommended ? Thanks for some hints

**Comment by jc-Rosichini** [comment]
Just tried this modified code... it compiles straight away in a matter of seconds  ;-)
`  
def get_output_for(self, input, deterministic=False, **kwargs):
        
        i0 = input[:,:,0::2,0::2]
        i1 = input[:,:,0::2,1::2]
        i2 = input[:,:,1::2,0::2]
        i3 = input[:,:,1::2,1::2]
        
        new_shape = (i0.shape[0],i0.shape[1],i0.shape[2]*i0.shape[3])
        res_i0 = i0.reshape(new_shape)
        res_i1 = i1.reshape(new_shape)
        res_i2 = i2.reshape(new_shape)
        res_i3 = i3.reshape(new_shape)
               
        wones  = T.ones((new_shape[1],new_shape[2]))
        w0     = T.dot(self.W[:,0], wones)
        w1     = T.dot(self.W[:,1], wones)
        w2     = T.dot(self.W[:,2], wones)
        w3     = T.dot(self.W[:,3], wones)
    
        res_out = res_i0*w0 + res_i1*w1 + res_i2*w2 + res_i3*w3
        
        out = res_out.reshape((input.shape[0],self.output_shape[1],self.output_shape[2],self.output_shape[3]))
        return out  `

**Comment by f0k** [comment]
Good you solved it! Just glancing over the code, instead of multiplying with `T.ones` you should be able to just use `dimshuffle` to insert broadcastable dimensions. And looking again, isn't this just a 2x2 convolution with stride 2? Closing this because it's not a Lasagne issue, but feel free to continue the discussion.

**Comment by jc-Rosichini** [comment]
Hi Jan,

Thanks for your note.
Actually what I'm trying to do is to avoid a maxpool 2 by replacing it with
a 'learned pool'' which combines 4 neighbours in each *intra* input feature
plane to generate output  feature planes
1/4 of the size.

btw. wrt convolution are even filter sizes allowed ?

2017-02-22 2:06 GMT+01:00 Jan Schlüter <notifications@github.com>:

**Comment by f0k** [comment]
> Actually what I'm trying to do is to avoid a maxpool 2 by replacing it with a 'learned pool'' which combines 4 neighbours in each *intra* input feature plane to generate output feature planes 1/4 of the size.

I see. If you want the same 'learned pool' for each feature map, you can reshape the input to (batchsize `*` channels, 1, ..., ...), apply a 2x2 convolution of stride 2 and reshape back to (batchsize, channels, ..., ...). If you want a separate 'learned pool' per feature map and process each feature map separately, you'd need grouped convolution (with num_groups==input_channels==output_channels), which is still not available in Theano. You may want to add it if your initial experiments seem fruitful :)

**Comment by jc-Rosichini** [comment]
That's the point: each feature map is expected to be processed separately with 4 associated learnt weights

**Comment by f0k** [comment]
> That's the point: each feature map is expected to be processed separately with 4 associated learnt weights

All right, then there's no easy way to improve over what you currently have. If you need better performance, you could look into adding grouped convolution to Theano. That'd be cool to have for a number of use cases. I posted some pointers regarding the implementation on the lasagne mailing list: https://groups.google.com/d/msg/lasagne-users/DlvHKRiFjjs/cbdaPLxVCgAJ
