### ISSUE TITLE
Weird : Bad optimization error... relax the tolerance by setting tensor.cmp_sloppy=1 ???

### ISSUE THREAD

**Issue by jc-Rosichini** [Lasagne/Lasagne#802]
Hi,
Weird behaviour of the following toy test.
The same program stops running randomly at different steps issuing : (see zip source and dump)
`
E:\FC_JC_theano_HE1_fin_feb19>python toy_test_1.py
Run
@ 0     loss 79947.078125
@ 1     loss 79877.8515625
@ 2     loss 79827.6953125
@ 3     loss 79785.7421875
@ 4     loss 79748.5390625
@ 5     loss 79714.4765625
@ 6     loss 79682.640625
@ 7     loss 79652.5234375
@ 8     loss 79623.6875
@ 9     loss 79595.9140625
@ 10    loss 79568.984375
@ 11    loss 79542.7734375
@ 12    loss 79517.1484375
@ 13    loss 79492.03125
@ 14    loss 79467.3359375
@ 15    loss 79443.03125
@ 16    loss 79419.03125
Traceback (most recent call last):
  File "toy_test_1.py", line 65, in <module>
    lossv = fn(dummy_inval,dummy_target)
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\compile\function_module.py", line 884, in __call__
    self.fn() if output_subset is None else\
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\compile\debugmode.py", line 2305, in deco
    return f()
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\compile\debugmode.py", line 2230, in f
    r_vals)
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\compile\debugmode.py", line 1078, in _find_bad_optimizations0
    new_graph=new_graph_str)
theano.compile.debugmode.BadOptimization: BadOptimization Error
  Variable: id 1433134195936 CorrMM_gradWeights{half, (1, 1), (1, 1)}.0
  Op CorrMM_gradWeights{half, (1, 1), (1, 1)}(Assert{msg='AbstractConv_gradWeights shape mismatch: shape of image does not match given imshp.'}.0, Elemwise{add,no_inplace}.0, Subtensor{int64}.0, Subtensor{int64}.0)
  Value Type: <class 'numpy.ndarray'>
  Old Value shape, dtype, strides: (3, 3, 1, 1) float32 (4, 12, 4, 4)

  Old Value:  [[[[ -9249.30371094]]
`
dump files: 
[dump1.txt](https://github.com/Lasagne/Lasagne/files/786043/dump1.txt)
[dump2.txt](https://github.com/Lasagne/Lasagne/files/786044/dump2.txt)

**(1) my config:**
Windows 10
Python Anaconda 3.5
Theano 0.9.0beta1dev
Lasagne 0.2dev1

**(2) the code**

[toy_test_1.txt](https://github.com/Lasagne/Lasagne/files/786042/toy_test_1.txt)

**Comment by jc-Rosichini** [comment]
lowering the value of learning rate makes it work.... from time to time...

**Comment by nouiz** [comment]
There is an issue on Theano about a shape big in Theano on Windows. Can you
look it up? Maybe they are related.

Le dim. 19 févr. 2017 13:16, jc-Rosichini <notifications@github.com> a
écrit :

**Comment by jc-Rosichini** [comment]
Are you referring to #5582 ?

**Comment by nouiz** [comment]
The PR was merged. Update Theano to the dev version as CMD try again.

Le lun. 20 févr. 2017 18:07, jc-Rosichini <notifications@github.com> a
écrit :

**Comment by f0k** [comment]
This doesn't seem to have anything to do with shapes, it's just that the DebugMode seems to be too strict for Conv2d. Looking at the actual values, the difference between the AbstractConv2d and CorrMM are on the order of 0.0015%.
@jc-Rosichini, I think you can safely ignore this and disable the DebugMode again, or only use it together with `tensor.cmp_sloppy=1`, as suggested in the error message. You wouldn't want to use the DebugMode for actual experiments anyway.
