### ISSUE TITLE
ValueError: shape must be a tuple of int and/or [int]

### ISSUE THREAD

**Issue by dankorg** [Lasagne/Lasagne#803]
when i run the following training cnn code:
https://github.com/MTG/DeepConvSep/blob/master/examples/dsd100/trainCNN.py

I get this error:

I 2017-02-22 04:00:18 trainer:433 Maximum: 0.634328
I 2017-02-22 04:00:18 trainer:434 Mean: 0.003356
I 2017-02-22 04:00:18 trainer:435 Standard dev: 0.013143
I 2017-02-22 04:00:18 trainer:163 Building Autoencoder
Traceback (most recent call last):
File "C:\Python27\lib\runpy.py", line 162, in run_module_as_main
"main", fname, loader, pkg_name)
File "C:\Python27\lib\runpy.py", line 72, in run_code
exec code in run_globals
File "C:\DeepConvSep\examples\dsd100\trainCNN.py", line 444, in
train_errs=train_auto(train=ld1,fun=build_ca,transform=tt,outdir=db+'output/
'+model+"/",testdir=db+'Mixtures/',model=db+"models/"+"model"+model+".pkl",num
epochs=nepochs,scale_factor=scale_factor)
File "C:\DeepConvSep\examples\dsd100\trainCNN.py", line 173, in train_auto
network2 = fun(input_var=input_var2,batch_size=train.batch_size,time_context
=train.time_context,feat_size=train.input_size)
File "C:\DeepConvSep\examples\dsd100\trainCNN.py", line 105, in build_ca
l_reshape1 = lasagne.layers.ReshapeLayer(l_fc11,(batch_size,l_conv2.output_s
hape[1],l_conv2.output_shape[2], l_conv2.output_shape[3]))
File "C:\Python27\lib\site-packages\lasagne\layers\shape.py", line 121, in i
nit
raise ValueError("shape must be a tuple of int and/or [int]")
ValueError: shape must be a tuple of int and/or [int]

so what do I do here?
thanks!

**Comment by f0k** [comment]
Answered on the mailing list: https://groups.google.com/forum/#!topic/lasagne-users/cpVh3Nd4RJA
In the future, please post such questions on the mailing list. The issue tracker is meant for bug reports and feature discussions only. Thank you!
