### ISSUE TITLE
since theano 0.9 support multi-gpu, does lasagne now support multi-gpu, especially for model parallelism?

### ISSUE THREAD

**Issue by yyht** [Lasagne/Lasagne#805]

**Comment by rafaelvalle** [comment]
https://github.com/Lasagne/Lasagne/issues/676
Please post such questions in the lasagne users forum.

**Comment by f0k** [comment]
Thank you @rafaelvalle. @yyht, this has been answered in #676. Closing!

**Comment by justheuristic** [comment]
Here's one way you could do multi-gpus with contexts: https://github.com/Theano/Theano/issues/6122
