### ISSUE TITLE
How about a learning rate of theano.shared type

### ISSUE THREAD

**Issue by guoxuesong** [Lasagne/Lasagne#810]
I run into a 100 layers model, that need 90 minutes to compile and load. I just want to switch learning rate from 2e-3 to 2e-4.

adamax only accept a learning rate of float type, I tried to feed it a theano.shared one so that I can change the value of the shared to change the learning rate. It not works, and complained as follow:

> TypeError: ('An update must have the same type as the original shared variable (shared_var=W, shared_var.type=CudaNdarrayType(float32, (False, False, True, True)), update_val=Elemwise{sub,no_inplace}.0, update_val.type=TensorType(float64, (False, False, True, True))).', 'If the difference is related to the broadcast pattern, you can call the tensor.unbroadcast(var, axis_to_unbroadcast[, ...]) function to remove broadcastable dimensions.')

**Comment by ebenolson** [comment]
You need to make sure the dtype of your shared variable is `float32` to avoid upcasting. For example

    lr = theano.shared(np.float32(1e-3))

**Comment by guoxuesong** [comment]
@ebenolson thanks very much. 

Maybe, we should update the document.

**Comment by f0k** [comment]
> Maybe, we should update the document.

Any suggestion? Which documentation did you read before and after the error occurred, just to know where to put it? Note that it's not mandatory to use `float32`, but it has to match the dtype of the shared variables, which use `theano.config.floatX` by default. You can use `lasagne.utils.floatX` to convert a scalar or array to that dtype. We could include this as an example in the `lasagne.updates` module docstring, but would you have read that?

**Comment by guoxuesong** [comment]
document of adamax:

> learning_rate : float

I think change to `float or shared variables` would be enough. My mistake is after I try and enconter a error, I thought 'oh, Lasagne not support this', so I did not check myself problem carefully.

**Comment by f0k** [comment]
> document of adamax:

Looking at the documentation, adam and adamax are the only ones that say "float", all the others say "float or symbolic scalar". Let's update this: #813
