### ISSUE TITLE
clang error in mac, will this code run in mac?

### ISSUE THREAD

**Issue by hidayat21** [Lasagne/Lasagne#824]
clang: error: unknown argument: '-sha'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: no such file or directory: '+cx16'
clang: error: no such file or directory: '+xsave'
clang: error: no such file or directory: '+bmi2'
clang: error: language not recognized: 'savec'
clang: error: no such file or directory: '+fsgsbase'
clang: error: no such file or directory: '+avx'
clang: error: no such file or directory: '+popcnt'
clang: error: no such file or directory: '+fma'
clang: error: no such file or directory: '+bmi'
clang: error: no such file or directory: '+aes'
clang: error: no such file or directory: '+rdrnd'
clang: error: language not recognized: 'saves'
clang: error: no such file or directory: '+sse4.1'
clang: error: no such file or directory: '+sse4.2'
clang: error: no such file or directory: '+avx2'
clang: error: no such file or directory: '+sse'
clang: error: no such file or directory: '+lzcnt'

**Comment by f0k** [comment]
First of all, please try installing the bleeding-edge versions of Theano and Lasagne:
```
pip install --upgrade --no-deps http://github.com/Theano/Theano/archive/master.zip
pip install --upgrade --no-deps http://github.com/Lasagne/Lasagne/archive/master.zip
```
Did you try to run on GPU or on CPU?

(Note that this is actually a Theano issue, not a Lasagne issue, but we can continue here for now.)

**Comment by BLCKPSTV** [comment]
How do I install these bleeding-edge versions with anaconda?

**Comment by f0k** [comment]
> How do I install these bleeding-edge versions with anaconda?

After some cursory web search I think you'd use `pip` as well. `conda install` does not support installing from source, but `pip` is included in anaconda.

**Comment by samuela** [comment]
I can reproduce on a clean virtualenv.

macOS 10.13.1
Python 2.7.14

Running 
```
pip install -r https://raw.githubusercontent.com/Lasagne/Lasagne/v0.1/requirements.txt
```
seems to install a version of theano that just doesn't work. The relevant Theano issue appears to be https://github.com/Theano/Theano/issues/4296. Running the usual Lasagne install process

```
pip install -r https://raw.githubusercontent.com/Lasagne/Lasagne/v0.1/requirements.txt
pip install Lasagne==0.1
```
and then manually doing
```
pip install Theano==0.8.1
```
fixed the issue for me.

**Comment by f0k** [comment]
Thank you for the report. I will bump `requirements.txt` to 0.8.2 as intended for Lasagne 0.2 anyway.
