### ISSUE TITLE
OS crashes (GPU crash) after running a program which imports lasagne.

### ISSUE THREAD

**Issue by laimonassutkus** [Lasagne/Lasagne#831]
**Program, that i am trying to run:**
`import lasagne`
`print("Hello World!")`

**Issue**: 
After running a program above screen flashes and turns dark. The only thing i can see is my mouse pointer. 

**Installations:**
_CUDNN_ - cudnn64-5
_CUDA_ - version 8
_cl.exe_ - by visual studio 14.0
_OS_ - windows 8.1
Lasagne - 0.1 - installation through pip
Theano - 0.9.0 - installation through pip
GPU - single Nvidia GTX 760M
SciPy, NumPy and other packages - installed through "Unofficial Windows Binaries for Python Extension Packages"

What else should i provide ?

**Comment by laimonassutkus** [comment]
Install lasagne 0.2.dev1

**Comment by f0k** [comment]
Crazy. Not sure why a more recent Lasagne version should make a difference -- I would have suggested to update the graphics driver, or maybe to update Theano to the version from git. Anyway, glad you could sove it.
