### ISSUE TITLE
any ways to output the intermediate variable of a layer?

### ISSUE THREAD

**Issue by kingwenChen** [Lasagne/Lasagne#835]
It is difficult for lasagne to see some intermediate variable's values of a layer when debuging or analyzing.
Something like theano.printing.Print() or theano.function() can do it by the theano.
While using the upper method means i need to change the source code of a encapsulated layer, it is not a god ideal.
So I think the Layer could add a method or init like config in which are variable's name.
then just offering the variable's name to see some variable's values.

are there any ways to output the intermediate variable of a layer?

**Comment by f0k** [comment]
> are there any ways to output the intermediate variable of a layer?

Only the ways offered by Theano, but there's no need to change the source code of a layer for that. If you want to see an intermediate output in addition to the output at the end of a network, just compile a function for that:
```python
output, intermediate = lasagne.layers.get_output([network, network.input_layer.input_layer.input_layer], deterministic=True)
pred_fn = theano.function([input_var], [output, intermediate])
```
Alternatively, for debugging, the test value system may come handy:
http://deeplearning.net/software/theano/tutorial/debug_faq.html#using-test-values
When you activate it (`THEANO_FLAGS=compute_test_value=warn`), you can assign a test value to the input variable: `input_var.tag.test_value = np.random.randn(*input_shape)`, and then obtain the outputs of all layers at once: `outputs = lasagne.layers.get_output(lasagne.layers.get_all_layers(network))`. Every expression in that list will now have a `tag.test_value` you can inspect to see what's going on in the network.
When using test values, you can also start a `pdb` prompt right before calling `get_output` and then step through the code to investigate what's happening inside each `get_output_for()` method of a layer.

Hope this helps! I don't see how we could extend Lasagne for this, so I'm closing this issue. Feel free to continue the discussion here.
