### ISSUE TITLE
Checking cuda for theano errors.. 

### ISSUE THREAD

**Issue by BLCKPSTV** [Lasagne/Lasagne#839]
I'm receiving following errors when checking if CUDA works on my conda theano build. 

```
THEANO_FLAGS=device=gpu python -c "import theano; print(theano.sandbox.cuda.device_properties(0))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/quintendewilde/anaconda/envs/py27/lib/python2.7/site-packages/theano/__init__.py", line 67, in <module>
    from theano.configdefaults import config
  File "/Users/quintendewilde/anaconda/envs/py27/lib/python2.7/site-packages/theano/configdefaults.py", line 119, in <module>
    in_c_key=False)
  File "/Users/quintendewilde/anaconda/envs/py27/lib/python2.7/site-packages/theano/configparser.py", line 285, in AddConfigVar
    configparam.__get__(root, type(root), delete_key=True)
  File "/Users/quintendewilde/anaconda/envs/py27/lib/python2.7/site-packages/theano/configparser.py", line 333, in __get__
    self.__set__(cls, val_str)
  File "/Users/quintendewilde/anaconda/envs/py27/lib/python2.7/site-packages/theano/configparser.py", line 344, in __set__
    self.val = self.filter(val)
  File "/Users/quintendewilde/anaconda/envs/py27/lib/python2.7/site-packages/theano/configdefaults.py", line 98, in filter
    'You are tring to use the old GPU back-end. '
ValueError: You are tring to use the old GPU back-end. It was removed from Theano. Use device=cuda* now. See for more information.
(py27) iMacvanQuinten:AI_Writer quintendewilde$ python -c "from theano.sandbox.cuda.dnn import dnn_available as d; print(d() or d.msg)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named cuda.dnn

```

bash_profile = 

```
#Tensorflow requirements

export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/cuda/lib64:/usr/local/cuda/$
export CUDA_HOME=/usr/local/cuda
export PATH="/usr/local/cuda/bin:$PATH"

#Anaconda
export PATH="/Users/quintendewilde/anaconda/bin:$PATH"

```

**Comment by nouiz** [comment]
You use the old Theano GPU back-end. Switch to the new one.

https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29


Theano last release 0.9, still support the old back-end, but not the dev
version.

**Comment by BLCKPSTV** [comment]
Hmm, did that and now I get all clang errors which is way above my current knowledge to fix.. 
`
Exception: Compilation failed (return status=1): clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-tbm'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-fma4'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-prfchw'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-pcommit'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-clwb'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-pku'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-smap'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-rdseed'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-sse4a'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-clflushopt'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-mwaitx'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-prefetchwt1'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-sgx'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-sha'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: no such file or directory: '+sse2'. clang: error: no such file or directory: '+cx16'. clang: error: no such file or directory: '+bmi2'. clang: error: language not recognized: 'savec'. clang: error: no such file or directory: '+fsgsbase'. clang: error: no such file or directory: '+popcnt'. clang: error: no such file or directory: '+aes'. clang: error: language not recognized: 'saves'. clang: error: no such file or directory: '+mmx'. clang: error: language not recognized: 'op'. clang: error: no such file or directory: '+hle'. clang: error: no such file or directory: '+xsave'. clang: error: no such file or directory: '+invpcid'. clang: error: no such file or directory: '+avx'. clang: error: no such file or directory: '+rtm'. clang: error: no such file or directory: '+fma'. clang: error: no such file or directory: '+bmi'. clang: error: no such file or directory: '+rdrnd'. clang: error: no such file or directory: '+sse4.1'. clang: error: no such file or directory: '+sse4.2'. clang: error: no such file or directory: '+avx2'. clang: error: no such file or directory: '+sse'. clang: error: no such file or directory: '+lzcnt'. clang: error: no such file or directory: '+pclmul'. clang: error: no such file or directory: '+f16c'. clang: error: no such file or directory: '+ssse3'. clang: error: no such file or directory: '+cmov'. clang: error: no such file or directory: '+movbe'. clang: error: no such file or directory: '+xsaveopt'. clang: error: no such file or directory: '+sse3'. 
`

**Comment by f0k** [comment]
This error was also mentioned in https://github.com/Theano/Theano/issues/4306. Can you upgrade Theano to the bleeding-edge version (`pip install --upgrade --no-deps http://github.com/Theano/Theano/archive/master.zip`)?

**Comment by BLCKPSTV** [comment]
I've installed it thru pip. Though running same ipython script it still generates the error. 

I've uninstalled 'conda uninstall theano'  theano. 

How do I link the new installed bleeding edge version in conda? 

Thanks for allowing further discussion/help for this breaking my head this few days from this!

**Comment by f0k** [comment]
> How do I link the new installed bleeding edge version in conda?

What happens if you install it with pip using the command I gave above? What does `python -c 'import theano; print theano.__version__'` produce?

**Comment by BLCKPSTV** [comment]
0.10.0dev1.dev-RELEASE

I've stumbled upon a new error with this answer
`
See [here](https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29)`

But this installation bring me back with a conda install of 9.0 and the libgpuarray and there I get lost installation wise with there explanation: 

1. where do I use device=cuda instead of gpu (pythonscript? terminal?)
2. the four if's below the first line, also were do I find these? I've checked my code and none of them have this in it.
3. grep gave me no result or better it kept searching for a long time and didn't give me anything so I ctrl/c it.
4. all below from what I mentioned above don't get what or where to this.
```
Use device=cuda or cuda0, ... instead of gpu.
If you use: conv3d2d, dnn_conv3d, use the new 3d abstract conv: theano.tensor.nnet.conv3d()
If you use: dnn_conv2d: use the 2d abstract conv: theano.tensor.nnet.conv2d()
If you use: dnn_pool: use the new 3d pooling interface. (It wasn't useful for 2d pooling): theano.tensor.signal.pool.pool_{2d,3d}
If you use: dnn_batch_normalization_train() or dnn_batch_normalization_test(), use theano.tensor.nnet.bn.batch_normalization_{train,test} instead.
grep for "import theano.sandbox.cuda" in your files.
If you find such import, they will need to be converted. In many cases, you can stop using a gpu interface and use the CPU interface. This will make your code work with CPU and both GPU back-end.
Now all convolution are available on the CPU
Now all pooling are available the CPU
If others, check in the CPU interface, otherwise, you can probably change theano.sandbox.cuda to theano.gpuarray
Check that it still train and have the same speed (we don't expect problems, but it is better to be safe!)
The new Theano backend uses config.gpuarray.preallocate for GPU memory allocation. It is purposeless for the old backend(CUDA backend).
Likewise, CUDA backend uses config.lib.cnmem for GPU memory allocation.

```

**Comment by f0k** [comment]
> 0.10.0dev1.dev-RELEASE

This means the new version installed fine.

> But this installation bring me back with a conda install of 9.0 and the libgpuarray and there I get lost installation wise with there explanation

I thought you already successfully switched to the new GPU backend (https://github.com/Lasagne/Lasagne/issues/839#issuecomment-306241527). In any case, you can also install the bleeding-edge version of Theano to use the new backend, you don't need to downgrade to 0.9 again. Possibly also install the bleeding-edge version of libgpuarray.

> where do I use device=cuda instead of gpu (pythonscript? terminal?)

Wherever you had `device=gpu` before. Either in `THEANOFLAGS=device=cuda`, or in your `.theanorc`. It's not so common to set the device in the Python script, usually you want to let the user decide on the device.

> the four if's below the first line, also were do I find these? I've checked my code and none of them have this in it.

That's why they say "if" :) If your code doesn't have these, you don't need to change anything.

**Comment by BLCKPSTV** [comment]
I did indeed already switched 0.9 with conda. I'm looking to see if I can bring bleeding libgpuarray in it.
And now I grep .theanorc to find this file and adjust it. Or is THEANOFLAGS=device=cuda something I should put in my terminal.. I don't see how to comprehend this is working, should I educate myself on how flags work? Thanks ahead!

**Comment by f0k** [comment]
> And now I grep .theanorc to find this file and adjust it. Or is THEANO_FLAGS=device=cuda something I should put in my terminal.

In your very first post in this thread, you had it in your terminal. If this is too cumbersome, you can add it to your .theanorc file which is read whenever you import theano. This is explained on http://deeplearning.net/software/theano/library/config.html, although sadly it doesn't say where to put the .theanorc file. I think you can get the location with `python -c 'import os; print os.path.expanduser("~/.theanorc")`.

**Comment by Sangramsingkayte** [comment]
/Users/sangramsing/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "train.py", line 53, in <module>
    import gantts
  File "/Users/sangramsing/Documents/gantts/gantts/__init__.py", line 6, in <module>
    from gantts import models
  File "/Users/sangramsing/Documents/gantts/gantts/models.py", line 5, in <module>
    import cuda_functional
  File "/Users/sangramsing/Documents/gantts/cuda_functional.py", line 10, in <module>
    from cupy.cuda import function
ModuleNotFoundError: No module named 'cupy.cuda'

**Comment by f0k** [comment]
@Sangramsingkayte: Sorry, it seems you're in the wrong project here. `gantts` uses PyTorch and `sru`, which in turn uses `cupy`. Make sure you install all requirements.

**Comment by Sangramsingkayte** [comment]
yes, I install all requirements. but now run the system
