### ISSUE TITLE
Custom layer which takes two layers as inputs

### ISSUE THREAD

**Issue by srikarym** [Lasagne/Lasagne#859]
I'm trying to implement a custom layer which takes two layers as inputs. I used the MergeLayer subclass but I'm unable to get the output by lasagne.layers.get_output(). Code is given below 

` 
    class Custom_Layer(lasagne.layers.MergeLayer):

        def __init__(self,f1,f2,b11,b21,b12,b22, **kwargs):
            super(Custom_Layer, self).__init__(incomings = [f1,f2], **kwargs)
            self.b11 = b11
            self.b21 = b21
            self.b12 = b12
            self.b22 = b22

        def get_output_shape_for(self, input_shapes):
            return input_shapes

        def get_output_for(self, inputs, **kwargs):

            f1,f2 = inputs
            
             *********Some operations on f1 and f2 *********

            return output
`
l1_final = Custom_Layer(l_conv1,l_conv2,0,0,0,0)
out = lasagne.layers.get_output(l1_final)

Can someone tell me the mistake in my code? The error which is being shown is -  

<ipython-input-153-c9bc284d07b7> in <module>()
----> 1 out =  lasagne.layers.get_output(l1_final)

/home/ram/.local/lib/python2.7/site-packages/lasagne/layers/helper.pyc in get_output(layer_or_layers, inputs, **kwargs)
    189                                  "mapping this layer to an input expression."
    190                                  % layer)
--> 191             all_outputs[layer] = layer.get_output_for(layer_inputs, **kwargs)
    192             try:
    193                 names, _, _, defaults = getargspec(layer.get_output_for)

<ipython-input-150-098dfc0af6fd> in get_output_for(self, inputs, **kwargs)
     17         print feature2
     18 
---> 19         sub11 = lasagne.layers.ElemwiseMergeLayer([feature1,feature2],T.sub,cropping=None)
     20         sub11_biased = BiasLayer(sub11,b=lasagne.init.Constant(self.b11), shared_axes=(0,1,2,3))
     21         sub11_rect = lasagne.layers.NonlinearityLayer(sub11_biased, nonlinearity=lasagne.nonlinearities.rectify)

/home/ram/.local/lib/python2.7/site-packages/lasagne/layers/merge.pyc in __init__(self, incomings, merge_function, cropping, **kwargs)
    323 
    324     def __init__(self, incomings, merge_function, cropping=None, **kwargs):
--> 325         super(ElemwiseMergeLayer, self).__init__(incomings, **kwargs)
    326         self.merge_function = merge_function
    327         self.cropping = cropping

/home/ram/.local/lib/python2.7/site-packages/lasagne/layers/base.pyc in __init__(self, incomings, name)
    257         self.input_shapes = [incoming if isinstance(incoming, tuple)
    258                              else incoming.output_shape
--> 259                              for incoming in incomings]
    260         self.input_layers = [None if isinstance(incoming, tuple)
    261                              else incoming

AttributeError: 'TensorVariable' object has no attribute 'output_shape'

**Comment by Sentient07** [comment]
The way you typically pass a `Layer` that is inherits `MergeLayer` is passing the incoming layers as a list. From the code that you shared, you don't seem to do that. Refer, [link](https://github.com/Lasagne/Lasagne/blob/master/lasagne/layers/base.py#L251-L252).

**Comment by srikarym** [comment]
I tried that approach as well but I got the same error. 

`class Custom_Layer(lasagne.layers.MergeLayer):

    def __init__(self,incomings,b11,b21,b12,b22, **kwargs):
        super(Custom_Layer, self).__init__(incomings, **kwargs)
        self.b11 = b11
        self.b21 = b21
        self.b12 = b12
        self.b22 = b22

    def get_output_shape_for(self, input_shapes):
        return input_shapes

    def get_output_for(self, inputs, **kwargs):

        f1,f2 = inputs
        
         *********Some operations on f1 and f2 *********

        return output
`
l1_final = Custom_Layer([l_conv1,l_conv2],0,0,0,0)
 out = lasagne.layers.get_output(l1_final)

'TensorVariable' object has no attribute 'output_shape'

**Comment by Sentient07** [comment]
Oh, I guess you are passing a Theano Variable instead of Lasagne Layer. Can
you do an assert in the beginning of constructor to check the object type?

**Comment by f0k** [comment]
> The way you typically pass a `Layer` that is inherits `MergeLayer` is passing the incoming layers as a list.

But if you specifically want a layer that supports two inputs, it's reasonable to do it they way you had in the first post.

> `---> 19 sub11 = lasagne.layers.ElemwiseMergeLayer([feature1,feature2],T.sub,cropping=None)`

The error is not in your layer, but in the ElemwiseMergeLayer you showed. `feature1` and `feature2` must be Lasagne layers, not Theano variables. You may need to wrap them in `InputLayer`s.

For the future, please post such questions on our mailing list: https://groups.google.com/forum/#!forum/lasagne-users
The issue tracker is meant for bug reports and feature discussions only. Thank you! (I'm closing this because it's not an issue with Lasagne, but feel free to continue the discussion here.)

**Comment by srikarym** [comment]
The inputs which I'm giving to the custom layer are in fact lasagne layers . Is there any other error in my code?

**Comment by f0k** [comment]
> The inputs which I'm giving to the custom layer are in fact lasagne layers .

But we're talking about the inputs to the `ElemwiseMergeLayer`, not your custom layer. That's what's highlighted in the stack trace. Hmm, reading the code again, are you actually creating layers in your `get_output_for()` method? This method gets Theano expressions and is supposed to return a Theano expression. It usually won't use Lasagne layers, but Theano operations.
