### ISSUE TITLE
docker image cannot run examples/mnist.py

### ISSUE THREAD

**Issue by guoxuesong** [Lasagne/Lasagne#864]
Traceback (most recent call last):
  File "mnist.py", line 22, in <module>
    import theano
  File "/usr/local/lib/python2.7/dist-packages/theano/__init__.py", line 102, in <module>
    from theano.scan_module import (scan, map, reduce, foldl, foldr, clone,
  File "/usr/local/lib/python2.7/dist-packages/theano/scan_module/__init__.py", line 41, in <module>
    from theano.scan_module import scan_opt
  File "/usr/local/lib/python2.7/dist-packages/theano/scan_module/scan_opt.py", line 71, in <module>
    from theano.scan_module import scan_op
  File "/usr/local/lib/python2.7/dist-packages/theano/scan_module/scan_op.py", line 58, in <module>
    from six import iteritems, integer_types, raise_from
ImportError: cannot import name raise_from

I would like to build a new docker image for Lasagne if need.

**Comment by f0k** [comment]
@Kaixhin, are the docker images still being updated regularly? Is it possible they got broken? Maybe bleeding-edge Theano requires a more recent `six` version.

**Comment by Kaixhin** [comment]
The Docker images are getting updated, but it looks like `six` is indeed the problem. The build logs from the latest Theano (CUDA 8.0) build can be found [here](https://hub.docker.com/r/kaixhin/cuda-theano/builds/b8whnsbpslrpsuqemscqsaa/). In particular, I added the following to the Dockerfile:

```
RUN pip install --upgrade pip
RUN pip install --upgrade six
```

But they don't do anything - do you know how to make sure `six` (and `pip`) actually get updated?
 System-wide installation is a better solution within a Docker container. Relevant part of log:

```
Step 10/12 : RUN pip install --upgrade six

 ---> Running in aa9a4440c35c

Downloading/unpacking six from https://pypi.python.org/packages/c8/0a/b6723e1bc4c516cb687841499455a8505b44607ab535be01091c0f24f079/six-1.10.0-py2.py3-none-any.whl#md5=3ab558cf5d4f7a72611d59a81a315dc8

  Downloading six-1.10.0-py2.py3-none-any.whl

Installing collected packages: six
  Found existing installation: six 1.5.2

    Not uninstalling six at /usr/lib/python2.7/dist-packages, owned by OS

Successfully installed six
Cleaning up...
```

**Comment by f0k** [comment]
> But they don't do anything

Are you sure? It seems `Not uninstalling six` just means it didn't mess with the `python-six` package installed at `/usr/lib`, but it should still have installed an updated `six` at `/usr/local/lib`: https://stackoverflow.com/questions/34286492/ubuntu-upgrading-python-packages-installed-by-os

So I would assume your addition fixed the problem! Does the `mnist.py` example still fail?

**Comment by Kaixhin** [comment]
I added this fix on [April 30th](https://github.com/Kaixhin/dockerfiles/commit/7137947928a9cbe9d6e6406191aba8f71565c598), and the Theano Dockerfiles haven't been updated since then (and the Lasagne Dockerfiles haven't been modified for even longer, as they mainly depend on Theano). There have been a few Lasagne builds [in the last month](https://hub.docker.com/r/kaixhin/cuda-lasagne/builds/), so this has either been unreported or is because of some other recent change.

**Comment by Kaixhin** [comment]
My bad - the `theano` one hasn't been updated in a while. Will build a new one now!

**Comment by f0k** [comment]
Cool, thanks for stepping in so quickly! Thank you for the report, @guoxuesong!
