### ISSUE TITLE
Better error message when importing cuda_convnet

### ISSUE THREAD

**Issue by f0k** [Lasagne/Lasagne#866]
When importing `lasagne.layers.cuda_convnet` under Theano 0.10, it will blindly try to import theano.sandbox.cuda and Theano will throw a nasty error message about switching to the new GPU backend, even if the user actually uses the new backend.
`lasagne/layers/cuda_convnet.py` should first check if the new GPU backend is in use and give a better error message in this case (along the lines of "cuda_convnet is not supported under Theano's new GPU backend. Please either use the ordinary convolutional and pooling layers (they are usually faster), or downgrade Theano to version 0.9 and use its old GPU backend.").
This would have helped at least one user who had a `from lasagne.layers.cuda_convnet import Conv2DCCLayer` in his code for some reason: https://groups.google.com/forum/#!topic/lasagne-users/qgoa9BBamDA

**Comment by ReyhaneAskari** [comment]
I am going to work on this ticket. @f0k @lamblin

**Comment by Sentient07** [comment]
Hi @ReyhaneAskari . @f0k assigned a few issues to me that blocks the next Lasagne release and this happens to be one. I have addressed the rest and this one is remaining . Are you still on this? If not, can I proceed with this?

**Comment by ReyhaneAskari** [comment]
Sorry, I was on vacation during part of August. I will work on it in this week.

**Comment by Sentient07** [comment]
No problem then! Thanks for the update :)
