### ISSUE TITLE
Announcement: You can training lasagne model in DIGITS now.

### ISSUE THREAD

**Issue by guoxuesong** [Lasagne/Lasagne#874]
I'm happy to announce that I have made some modifies to DIGITS to support training lasagne model.

You need install [deepstacks.lasagne](https://github.com/guoxuesong/deepstacks) and [a modified version of DIGITS ](https://github.com/guoxuesong/DIGITS). You still need to install caffe, because DIGITS need it.

Please download mnist dataset following [DIGITS's GettingStarted document](https://github.com/NVIDIA/DIGITS/blob/master/docs/GettingStarted.md). When creating model, select Deepstacks.lasagne instead of caffe. Click 'customize' of LeNet, and paste the following code:

```
# Example for using raw lasagne:

import deepstacks
import lasagne
from deepstacks.framework.main import *
import deepstacks.framework.using_lmdb
from deepstacks.macros import *
from deepstacks.framework.macros import *
def build_network(inputs):
    network = inputs['image']
    if 'mean' in inputs:
        network=lasagne.layers.ElemwiseMergeLayer((network,inputs['mean']),T.sub)
    network = lasagne.layers.Conv2DLayer(
            network, num_filters=20, filter_size=(5, 5),
            nonlinearity=lasagne.nonlinearities.rectify,
            W=lasagne.init.GlorotUniform())
    network = lasagne.layers.MaxPool2DLayer(network, pool_size=(2, 2))
    network = lasagne.layers.Conv2DLayer(
            network, num_filters=50, filter_size=(5, 5),
            nonlinearity=lasagne.nonlinearities.rectify,
            W=lasagne.init.GlorotUniform())
    network = lasagne.layers.MaxPool2DLayer(network, pool_size=(2, 2))
    network = lasagne.layers.DenseLayer(
            lasagne.layers.dropout(network, p=.5),
            num_units=500,
            nonlinearity=lasagne.nonlinearities.rectify)
    network = lasagne.layers.DenseLayer(
            lasagne.layers.dropout(network, p=.5),
            num_units=10,
            nonlinearity=lasagne.nonlinearities.softmax)

    res, stacks, paramlayers, errors, watchpoints=deepstacks.lasagne.build_network(network,(
        (classify,'target'),
        ),inputs)
    return res,stacks,paramlayers+[network],errors,watchpoints
```

'Show visualizations and statistics' and 'Classify Many' feature are not supported yet.

Enjoy it.

**Comment by nouiz** [comment]
This is interresting.

I suggest you to email theano-dev and theano-user about that to let more
people know it.

Personally, I think having a link to that in lasagne doc could be
interresting too, but I'm not managing it.

I added this link to this page in Theano:
https://github.com/Theano/Theano/wiki/Related-projects

**Comment by f0k** [comment]
I added this to the Lasagne wiki as well:
https://github.com/Lasagne/Lasagne/wiki/3rd-party-extensions-and-code

Will close the issue because it's not an issue we need to take care of.

**Comment by guoxuesong** [comment]
'Show visualizations and statistics' works now @f0k @nouiz

**Comment by guoxuesong** [comment]
Use this [digits.sh](https://github.com/guoxuesong/deepstacks/blob/master/digits.sh) to start training in DIGITS from command line.

usage: digits.sh [-u USERNAME] network.py DATASET BATCHSIZE

for exmaple: ~/deepstacks/digits.sh -u myusername mynetwork.py 20170825-163329-a5a4 8

Feel free to copy and edit it for your own
 
Every time you run digits.sh on mynetwork.py  the training will continue using saved weight from last training. Delete mynetwork-model* if you want start from begining. Log file in DIGITS is linked to mynetwork.log for easy access.
