### ISSUE TITLE
Strange behaviour of MergeLayer with Multiple InputLayers 

### ISSUE THREAD

**Issue by massimilianocomin** [Lasagne/Lasagne#875]
Hello,

I'm currently trying to implement a simple Neural Net in Lasagne which has two InputLayers that process separately the data with two LSTM followed by DenseLayers. The net then takes the elementwise sum of the two branches.

I have a very weird shape mismatch error, please see the minimal code below that reproduces the error.

The two LSTM branches should be able to handle variable size inputs, and separately they do. But when I provide the net with two inputs of different shapes it throws me a shape mismatch : but the two inputs are NEVER processed together !!

So I believe there is a bug somewhere. The shape mismatch comes from the MergeLayer, as if it was fed with the inputs directly.

```
# Initialization
x = T.vector('x')
y = T.vector('y')
x = x.reshape((1,x.size,1))
y = y.reshape((1,y.size,1))

# I want the net to evaluate these expressions as well
xx = T.pow(x,2)
yy = T.pow(y,2)


# Build net
net_one = L.InputLayer((1,None,1),x)

net_one = L.RecurrentLayer(net_one,7, only_return_final=True)

net_one = L.DenseLayer(net_one, 1, nonlinearity=None, b=None, num_leading_axes=0)

print(L.get_output_shape(net_one))



net_two = L.InputLayer((1,None,1),y)

net_two = L.RecurrentLayer(net_two,7, only_return_final=True)

net_two = L.DenseLayer(net_two, 1, nonlinearity=None, b=None, num_leading_axes=0)

print(L.get_output_shape(net_two))



net = L.ElemwiseSumLayer((net_one,net_two))

print(L.get_output_shape(net))



# Input layers
inp1, inp2 = net.input_layers


# The two outcomes of the NN 
out1 = L.get_output(net)
out2 = L.get_output(net, {inp1:xx,inp2:yy})

# Loss over the normal and transformed expressions
dicriminator_loss = out1.sum() - out2.sum()

# Build graph
params = L.get_all_params(net)
updates = lasagne.updates.adam(dicriminator_loss, params)

f = theano.function([x,y], dicriminator_loss, updates=updates)


# Test

data1 = np.arange(10).reshape((1,10,1)).astype('float32')

data2 = np.arange(22).reshape((1,22,1)).astype('float32')

# This is OK
print(f(data1,data1))

# ValueError !!
print(f(data1,data2))
```

**Comment by vvmurthy** [comment]
Just for some context:

The reason for the `ValueError` is how the inputs to `net` are retrieved. When you call `inp1, inp2 = net.input_layers` , you will actually get the DenseLayers as `inp1` and `inp2`, because `Layer.input_layer` is defined as the preceding layer, not the actual `InputLayer` for the network.

Because the DenseLayers are considered the input, when the line `out2 = L.get_output(net, {inp1:xx,inp2:yy})` is run, my understanding is that `xx` and `yy` are effectively treated as outputs from the DenseLayer into the ElemwiseSumLayer, hence the `ValueError`.

The quickest fix is to make `net_one` and `net_two` into dictionary objects, so that we can later retrieve their inputs directly. E.G. 
```
net_one = {}
net_one['in'] = L.InputLayer((1, None, 1), x)
net_one['rl'] = L.RecurrentLayer(net_one['in'], 7, only_return_final=True)
net_one['dl'] = L.DenseLayer(net_one['rl'], 1, nonlinearity=None, b=None, num_leading_axes=0)

net_two = {}
net_two['in'] = L.InputLayer((1, None, 1),y)
net_two['rl'] = L.RecurrentLayer(net_two['in'], 7, only_return_final=True)
net_two['dl'] = L.DenseLayer(net_two['rl'], 1, nonlinearity=None, b=None, num_leading_axes=0)

net = L.ElemwiseSumLayer((net_one['dl'], net_two['dl']))
print(L.get_output_shape(net))

# Input layers
inp1 = net_one['in']
inp2 = net_two['in']
```

Hope this helps.

**Comment by f0k** [comment]
Thanks for the quick reply @vvmurthy! You nailed the problem. Closing this!
