### ISSUE TITLE
Objectives as Layers - any thoughts?

### ISSUE THREAD

**Issue by botev** [Lasagne/Lasagne#879]
Hi, so I want just to get some feedback on the idea of making the objectives rather than pure Python functions to be layers. I currently have the use case of this (and we have done it internally with a fork) for KFAC/KFRA where there is a "backprop" going on which requires that the objective is an actual object. Outside of that, I would argue that Lasagne currently composes functors with the Layer interface and there is no reason why the objectives can not be functors rather than functions themselves. 

My aim for this is more of to see opinions on this.

**Comment by ebenolson** [comment]
Objectives used to be their own class (not a subclass of `Layer` though I think). There is historical discussion of this in #15, #173, #286

**Comment by guoxuesong** [comment]
I'm using lasagne layer to compose objectives now, for exmaple: ElemwiseMergeLayer((xlayer,ylayer), lasagne.objectives.squared_error).

The reasons:

1) I use multi targets, and wish the objective code be near to the code of corresponding output layer.

2) I use layer-substitute, and wish this works not only on layers but also on objectives. If objective is not layer, I need two different replace method.

3) Even not compose objective as layer, I cannot avoid composing some objective-like values. Calculate these values using ElemwiseMergeLayer is fast and happy.

But I donnot think we should add some extra code to lasagne, instead, in my opinon, lasagne.objectives could be removed. And I agree that keep them is good for new users.

**Comment by botev** [comment]
@guoxuesong My motivation is similar to yours and I do want the objectives to be functors rather than functions. However, I don't see why this is a problem:
```
class MeanErrorLayer(L.Layer):
   # ... Implementation


def mean_error_func(a, b)
    l = MeanErrorLayer((None, None), (None, None))
    return l.get_output_for(a, b)
```
This way you both have an object and expose the underlying object. Even further, I'm not sure if you can't make the `get_output_for` static and just directly write `mean_error_func=MeanErrorLayer.get_output_for` or some other sugar.

**Comment by guoxuesong** [comment]
@botev You only need to do this when your output and target has different shape, otherwise you can always use ElemwiseMergeLayer.

I think lasagne should provide some mergelayer that not require all the inputs have the same shape, maybe take a extra arg ''output_shape'.

**Comment by botev** [comment]
Ah, maybe you are right on that use case that in general, you might not need anything more. Nevertheless, for the Kronecker-Factored stuff, I actually do need different objectives or to have layers representing distributions. But yes maybe this is not a general problem for users.

**Comment by f0k** [comment]
Whatever the use case, we probably cannot change the current objectives to be layers without breaking compatibility. We could add an `ObjectiveLayer` that takes a layer, a target expression and an objective function. But that could also be accomplished by an `ElemwiseMergeLayer` or by an `ExpressionLayer` along with `functools.partial`.

> I think lasagne should provide some mergelayer that not require all the inputs have the same shape

I think what's missing for your case would be an `ExpressionLayer` that accepts multiple input layers. This will be easier after #678 (currently it would require a second `ExpressionMergeLayer` class).

Will close this issue as I think we don't need objectives as layers at least for now; but please feel free to continue the discussion!
