### ISSUE TITLE
AttributeError:'module' object has no attribute 'dnn'

### ISSUE THREAD

**Issue by jenish08** [Lasagne/Lasagne#883]
# load our serialized model from disk

print("[INFO] loading model...")
net = cv2.dnn.readNetFromCaffe(args["prototxt"], args["model"])

error: 
AttributeError:'module' object has no attribute 'dnn'

**Comment by hitman996** [comment]
Hi Jenish08,  I am having the similar problem. Did you figure out any solution to this problem?

**Comment by f0k** [comment]
Since Theano 0.10, the old GPU backend in `theano.sandbox.cuda.dnn` does not exist any longer. You will either need to downgrade Theano to 0.9, or upgrade Lasagne to the current bleeding-edge version.

**Comment by palakthakur15** [comment]
Hey, I too have encountered a similar problem. how did you solve it?

**Comment by gemfield** [comment]
Make sure your python_opencv version >= 3.3

**Comment by palakthakur15** [comment]
> Make sure your python_opencv version >= 3.3

Yes, I realized that the opencv version I was using was 3.1, after updating the version it worked. Thanks.

**Comment by f0k** [comment]
Oh, so this is an issue about OpenCV, not about Lasagne. You're in the wrong repository here, but if it helps people searching for this error, you're welcome.

**Comment by alaspuresujay** [comment]
@palakthakur15 hey how you upgrade the version

**Comment by f0k** [comment]
> hey how you upgrade the version

Depends on the Python distribution you use. `pip install opencv-python-headless` may be an option.

Pay attention to what the traceback says, though. In the original post in this thread, somebody tried to access `cv2.dnn`, where `cv2` is the OpenCV module, and upgrading OpenCV was the solution. You will get the exact same error message if you try to access `theano.sandbox.cuda.dnn`, or any other non-existing or non-imported `.dnn` module, which will require a different solution.
