### ISSUE TITLE
Where is the GlobalMaxPool2D??

### ISSUE THREAD

**Issue by IstrateRoxana** [Lasagne/Lasagne#903]
I see that there is only one GlobalMaxPooling, and it performs on 1D input volumes, how can i use a GlobalMaxPool2D with the current library?

**Comment by f0k** [comment]
[`lasagne.layers.GlobalPoolLayer`](http://lasagne.readthedocs.io/en/latest/modules/layers/pool.html#lasagne.layers.GlobalPoolLayer) pools across all spatial dimensions. There is no separate 1D, 2D, 3D version. It performs global average pooling by default, but you can pass `T.max` as the pooling function to have global max pooling.
