### ISSUE TITLE
How to save layer l_out as lasagne layer to network in json or h5 format to be imported from Matlab 

### ISSUE THREAD

**Issue by acharya1981** [Lasagne/Lasagne#904]
How can I save theano lasagne network as json network, 

So that I can import it from Matlab.

**Comment by f0k** [comment]
You can get all the weight values with `lasagne.layers.get_all_param_values()`, and write them to a HDF5 file using `h5py`. Something like:
```python
with h5py.File('params.h5', 'w') as f:
    for i, p in enumerate(lasagne.layers.get_all_param_values(l_out)):
        f['param%d' % i] = p
```
