### ISSUE TITLE
AttributeError: 'Conv2DLayer' object has no attribute 'num_groups'

### ISSUE THREAD

**Issue by enniyasubbu** [Lasagne/Lasagne#910]
Theano - v1.0.1
Lasagne - v0.2.dev1

I am testing the following:
[https://github.com/kahst/AcousticEventDetection#testing]

Command:
`python AED_test.py --filenames 'dataset/schreien_scream.wav' --modelname 'AED_Example_Run_model.pkl' --overlap 4 --results 5 --confidence 0.01`

Seems like a Lasagne issue.

```
HANDLING IMPORTS...
Using cuDNN version 7103 on context None
Mapped name None to device cuda: GeForce GT 650M (0000:01:00.0)
...DONE!
IMPORTING MODEL... DONE!
Traceback (most recent call last):
  File "AED_test.py", line 159, in <module>
    TEST_NET = getPredictionFuntion(NET)
  File "AED_test.py", line 71, in getPredictionFuntion
    net_output = l.get_output(net, deterministic=True)
  File "/home/enniya/miniconda2/lib/python2.7/site-packages/lasagne/layers/helper.py", line 197, in get_output
    all_outputs[layer] = layer.get_output_for(layer_inputs, **kwargs)
  File "/home/enniya/miniconda2/lib/python2.7/site-packages/lasagne/layers/conv.py", line 352, in get_output_for
    conved = self.convolve(input, **kwargs)
  File "/home/enniya/miniconda2/lib/python2.7/site-packages/lasagne/layers/conv.py", line 643, in convolve
    if self.num_groups > 1:  # pragma: no cover
AttributeError: 'Conv2DLayer' object has no attribute 'num_groups'
```

**Comment by nouiz** [comment]
Try the dev version of lasable. I could help you.

**Comment by f0k** [comment]
Did you create the pickled model yourself or was it done with an earlier version of Lasagne? If the latter, you may need to downgrade Lasagne to commit 8978b1d or earlier (i.e., before grouped convolutions were added):
```bash
pip install git+git://github.com/Lasagne/Lasagne@8978b1d
```
Lasagne models are not designed to be pickled between versions; the usual recommendation is to only export/import the weights using `lasagne.layers.get_all_param_values()` and rebuild the model for testing using the same code used for training.
