### ISSUE TITLE
updates.py

### ISSUE THREAD

**Issue by jiangnanhugo** [Lasagne/Lasagne#915]
my bad. Sorry.

**Comment by ebenolson** [comment]
Hi Jiang, it might be helpful for you to read through [the Theano tutorial](http://deeplearning.net/software/theano/tutorial/).

**Comment by jiangnanhugo** [comment]
1. the code is quote from `updates.py` file

2. the equation for calculate is
$$\begin{aligned}
m_t&=\beta m_{t-1}+ g_t\\
param_t &=param_{t-1} - lr * m_t
\end{aligned}$$
