### ISSUE TITLE
Hi！ There are some problems about creating a new layer!

### ISSUE THREAD

**Issue by wqz960** [Lasagne/Lasagne#916]
I try to create a layer derived from MergeLayer . But I don't know how to check it, can you provide me a demo to check whether my new layer is not what I want.

**Comment by f0k** [comment]
> But I don't know how to check it, can you provide me a demo to check whether my new layer is not what I want.

Not sure what you mean. If you just want to try interactively what your layer produces, you would compile a function that just performs a forward pass through your layer:
```
input1 = InputLayer(input_shape1)
input2 = InputLayer(input_shape2)
layer = MyMergeLayer((input1, input2))
fn = theano.function([input1.input_var, input2.input_var], lasagne.layers.get_output(layer))
```
Now you can pass data to `fn` and check what's happening.

In a similar way, you can also write tests that pass well-defined data to `fn` and compare the results to expected outputs.
